#!/usr/bin/env python3
"""mkpcsastro.py - write pcsastro.ps2: pcs from the desktop, Astro Blast off
the card, recoloured, a bumper added, the World changed, and played.

The session software/pcs/video/run-astro.sh records:

  1  the desktop: the Pinball icon selected, then opened - `pcs` with a bare
     CR, the editor (pcs.md 8)
  2  DISK: Astro Blast (DEMO1, `demo1.pbt`) picked off the catalogue's first
     row and LOADed, and the panel QUIT
  3  the brush, light blue off the picker, and the two flippers at the bottom
     painted - ⭐ a library part's colour is its ART's (pcsedit.paint)
  4  the hand, and a round bumper (BMP1, the pop bumper Astro Blast already
     has three of) out of the bin into the open space right of the island
  5  the brush, yellow, and the new bumper painted
  6  WORLD: GRAVITY dragged to 5, and QUIT
  7  PLAY for about sixteen seconds: the button held through the ball's
     landing on the plunger, which launches it, then both flippers, `q` back to
     the editor, `q` to the desktop, and `q` to end it (the recording
     stops at the shell's DONE)

⚠ ONE POINTER THROUGH BOTH PROGRAMS.  `desk` puts it at (320, 240) with one
PutGC and pcs reads the same absolute position (pcsin.inc's Pt.AcX/Pt.AcY),
so the script keeps one origin and never re-origins at the hand-over.
⚠ Timed from DESK-READY.  The launch is measured by run-v3desk.sh's `pin`
leg: the second click at 12 s, pcs's screen up ~26 s after the gate - so
pcs's first gesture is at 42 s.

    python3 software/pcs/bench/scripts/mkpcsastro.py > .../pcsastro.ps2
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.dirname(HERE))
import mkpcs            # noqa: E402
import pcsparts         # noqa: E402
import pcsworld         # noqa: E402

PARTS = pcsparts.parts()
BOXES = mkpcs.bin_boxes()
NAMES = [p.name for p in PARTS]

TOOL = {'hand': (560, 14), 'brush': (560, 116), 'play': (560, 162),
        'world': (564, 218), 'disk': (564, 276)}
PICK = (432, 360)
LIGHTBLUE, YELLOW = (0, 7), (9, 4)          # pcspal.PICK's 0x60CCF2, 0xF4EA0E
# the DISK panel (pcsdisk.py): the catalogue's first row, LOAD and QUIT
DK_ROW0, DK_LOAD, DK_QUIT = (400, 64), (362, 308), (494, 308)
# Astro Blast's two bottom flippers, objects 11 and 12: world (52..70) and
# (72..90) by 162..177, both hit solid by SELECTPOLY
FLIPPERS = ((58, 170), (84, 170))
BUMPER = ('BMP1', 96, 96)                   # its corner, in world units
# ⭐ THE BUTTON IS DOWN BEFORE THE BALL LANDS AND STAYS DOWN PAST IT.  The ball
# starts at the top of the lane and falls onto the plunger ~220 frames later
# at gravity 5 (pcsobj.py), and LAUNCHHIT fires only on that contact with the
# button held; a press while it is still falling does nothing, and one after
# it has landed catches it bouncing and throws it short of the GATE.  Held
# through the landing, the model launches it past the gate every time.
# ⚠ Seconds, so it depends on the play loop's rate: ~30 frames a second with
# only the ball moving (2026-09-24).
LAUNCH_HOLD = 10.5

out = []
t = 0.0
pos = [320, 240]


def line(s):
    """⛔ `at` IS ABSOLUTE AND `+` IS NOT, so the clock follows both."""
    global t
    if s.startswith('+'):
        t += float(s.split()[0][1:])
    out.append(s)


def at(when, s):
    global t
    t = when
    line('at %-8.3f %s' % (t, s))


def glide(x1, y1, secs=0.7, steps=10):
    """The pointer moved as a hand moves it, from wherever it is."""
    x0, y0 = pos
    for i in range(1, steps + 1):
        line('+%-8.3f move to %d %d' % (secs / steps, x0 + (x1 - x0) * i // steps,
                                        y0 + (y1 - y0) * i // steps))
    pos[:] = [x1, y1]


def click(x, y, pause=1.5):
    at(t + pause, 'move to %d %d' % tuple(pos))
    glide(x, y)
    line('+0.300    click left')


def drag(x0, y0, x1, y1, pause=1.5, secs=1.2):
    at(t + pause, 'move to %d %d' % tuple(pos))
    glide(x0, y0)
    line('+0.300    down left')
    glide(x1, y1, secs, 14)
    line('+0.300    up left')


def pick(cell):
    click(PICK[0] + 8 * cell[0] + 4, PICK[1] + 8 * cell[1] + 4)


def from_bin(name, tx, ty):
    """Template `name` out of the bin, its corner onto world (tx, ty) -
    mkpcsbuild.py's arithmetic: the part keeps the offset it was grabbed at."""
    i = NAMES.index(name)
    bx, by, bw, bh = BOXES[i]
    cx, cy = 2 * (bx + bw // 2), 2 * (by + bh // 2)
    p = PARTS[i]
    drag(cx, cy, 2 * (tx - min(p.x) + cx // 2), 2 * (ty - min(p.y) + cy // 2),
         secs=1.6)
    return p


def main():
    line('# pcsastro.ps2 - pcs from the desktop icon, Astro Blast loaded,')
    line('# recoloured, a bumper added, gravity 5, and played for 15 s.')
    line('# GENERATED by mkpcsastro.py - edit that, not this.')
    line('origin 320 240')
    line('gap 120')
    line('')
    line('# 1  the Pinball icon: select, then open')
    at(2.0, 'move to 320 240')
    glide(600, 410, 1.0)
    line('+0.300    click left')
    at(12.0, 'move to 600 410')
    line('+0.300    click left')
    at(13.0, 'move to 600 410')
    glide(500, 300)

    line('# 2  DISK, Astro Blast off the first row, LOAD, QUIT')
    at(42.0, 'move to 500 300')
    click(*TOOL['disk'], pause=0.0)
    click(*DK_ROW0, pause=2.5)
    click(*DK_LOAD, pause=1.5)
    click(*DK_QUIT, pause=5.0)

    line('# 3  the brush, light blue, and both flippers')
    click(*TOOL['brush'], pause=3.0)
    pick(LIGHTBLUE)
    for wx, wy in FLIPPERS:
        click(2 * wx, 2 * wy, pause=2.0)

    line('# 4  the hand, and a round bumper out of the bin')
    click(*TOOL['hand'], pause=3.0)
    name, bx, by = BUMPER
    p = from_bin(name, bx, by)
    w, h = max(p.x) - min(p.x), max(p.y) - min(p.y)

    line('# 5  the brush, yellow, and the new bumper')
    click(*TOOL['brush'], pause=2.5)
    pick(YELLOW)
    click(2 * (bx + w // 2), 2 * (by + h // 2), pause=2.0)

    line('# 6  WORLD: GRAVITY to 5, QUIT')
    click(*TOOL['world'], pause=3.0)
    gx, gy = pcsworld.TRACKS[0][0] + pcsworld.TW // 2, pcsworld.TRACKS[0][1]
    lvl = lambda n: gy + 4 + pcsworld.ST * n + pcsworld.KH // 2   # noqa: E731
    assert pcsworld.level(0, lvl(5)) == 5
    drag(gx, lvl(4), gx, lvl(5), pause=3.0, secs=0.8)
    click(pcsworld.QX + pcsworld.QW // 2, pcsworld.QY + pcsworld.QH // 2,
          pause=2.5)

    line('# 7  PLAY: the plunger pulled and the button held until the ball')
    line('#    has landed on it, then the flippers')
    click(*TOOL['hand'], pause=3.0)
    click(*TOOL['play'], pause=1.5)
    at(t + 0.3, 'move to %d %d' % tuple(pos))
    glide(300, 476, 0.4)                  # the whole pull: pdl0 saturates at 382
    line('+0.100    down left')
    line('+%.3f   up left' % LAUNCH_HOLD)
    for k in range(8):
        b = ('right', 'left')[k % 2]
        at(t + 0.5, 'down %s' % b)
        line('+0.250    up %s' % b)
    at(t + 1.0, 'type "q"')              # the game back to the editor
    at(t + 6.0, 'type "q"')              # and pcs back to the desktop
    at(t + 20.0, 'key tap q')            # and the desktop ends: DONE
    print('\n'.join(out))


if __name__ == '__main__':
    main()
