#!/usr/bin/env python3
"""Write level2/arm6309/modules/coarmfont3.asm - CP437, 256 glyphs, 8x8.

video3's character mode puts the colour in the ATTR byte, not in the glyph,
so the font is baked ONCE as 1bpp and there are no inverse glyphs: the whole
256-code page is real characters.  That is what makes CP437 ANSI art possible
at all (hardware/video3/docs/demo-report.md 2).

The glyphs come from software/tools/show.py's font(8), which reads the
host's console font and draws the shade and half-block cells itself - those
are what ANSI art is mostly made of and the console font lacks some.
"""
import sys, pathlib
sys.path.insert(0, str(pathlib.Path(__file__).resolve().parents[2] / "tools"))
import show

CP437_NAMES = {0x00: "NUL", 0x20: "space", 0xB0: "light shade", 0xB1: "medium shade",
               0xB2: "dark shade", 0xDB: "full block", 0xC9: "box dr", 0xBB: "box dl",
               0xC8: "box ur", 0xBC: "box ul", 0xCD: "box h", 0xBA: "box v"}

def main(out):
    f = show.font(8)
    L = ["* coarmfont3.asm - CP437 as 256 8x8 glyphs, 8 row bytes each, MSB",
         "* leftmost.  GENERATED by arm6309 software/toolbox/tools/mkcp437.py;",
         "* do not edit.  video3's character mode takes the colour from ATTR, so",
         "* a glyph is 1bpp and every one of the 256 codes is a real character -",
         "* there is no inverse half, which is what lets ANSI art use the box and",
         "* shade cells at $B0-$DF.",
         "",
         "ArmFont3"]
    for code in range(256):
        row = ",".join("$%02X" % b for b in f[code])
        note = CP437_NAMES.get(code, "")
        L.append("                    fcb       %s   $%02X %s" % (row, code, note))
    L.append("")
    pathlib.Path(out).write_text("\n".join(L))
    print("ok    %s: 256 glyphs, %d bytes of font" % (out, 256 * 8))

if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "coarmfont3.asm")
