#!/usr/bin/env python3
"""Write demo_tb.sv: software/archive/demo/bench/replay_tb.sv with an instruction trace.

    mkdemotb.py ../../bench/replay_tb.sv OUT/demo_tb.sv

Generated rather than copied so the bench it checks against is always the
current replay_tb. The additions are cpu_tb.sv's boundary and write lines,
written to +itrace= for the cycles below +itracemax=.
"""
import sys

src = open(sys.argv[1]).read()
head = '''// GENERATED by hardware/cpu/sim/test/mkdemotb.py from bench/replay_tb.sv - do not edit.
// replay_tb with cpu_tb.sv's instruction trace added, so demo_run.c --itrace can
// be compared with the Verilog instruction by instruction on the demo's code.
// Cycle 0 is the first CPUSTATE_FETCH_I1 after reset.
'''
if src.count('module replay_tb;') != 1:
    sys.exit("FAIL  mkdemotb.py: replay_tb.sv no longer declares 'module replay_tb;' once")
src = src.replace('module replay_tb;', 'module demo_tb;')
probe = '''  // ---- the instruction trace (added by mkdemotb.py) ---------------------
  string itrace_path;
  int ifd = 0;
  longint icyc = 0, itracemax = 64'h7FFFFFFFFFFFFFFF;
  bit istarted = 0;
  always @(negedge E) begin
    if (!istarted && cpu.cpucore.CpuState == 7'd4) istarted = 1;
    if (istarted && ifd != 0) begin
      if (icyc < itracemax) begin
        if (cpu.cpucore.CpuState == 7'd4)
          $fwrite(ifd, "%0d %04x %02x %02x %04x %04x %04x %04x %02x %02x\\n", icyc,
                  cpu.cpucore.pc, cpu.cpucore.a, cpu.cpucore.b, cpu.cpucore.x, cpu.cpucore.y,
                  cpu.cpucore.u, cpu.cpucore.s, cpu.cpucore.dp, cpu.cpucore.cc);
        if (!rnw) $fwrite(ifd, "%0d W %04x %02x\\n", icyc, addr, dout);
      end
      icyc++;
    end
  end
  initial begin
    if ($value$plusargs("itrace=%s", itrace_path)) ifd = $fopen(itrace_path, "w");
    void'($value$plusargs("itracemax=%d", itracemax));
  end
  final if (ifd != 0) $fclose(ifd);
endmodule
'''
i = src.rindex('endmodule')
open(sys.argv[2], 'w').write(head + src[:i] + probe + src[i + len('endmodule'):])
