#!/usr/bin/env python3
"""Write bench/vramrate.asm -- the VRAM store-rate bench.

    python3 software/archive/demo/bench/mkvramrate.py software/archive/demo/bench/vramrate.asm

The unrolled blocks are hundreds of literal instructions, so the .asm is
generated and THIS is the file to edit.  docs/video-copyrect.md 6 is what the
bench answers and what its numbers mean.
"""
import sys

CHUNK_F  = 96               # MUST divide CALLSZ *and* be divisible by every
                            # form's bytes-per-iteration: an unrolled block has
                            # no early exit, so a partial chunk over- or
                            # under-runs and the bookkeeping never notices.
                            # 96 = 2*48 = 1*96 = 6*16, and 8160 = 85*96.
CHECKSZ  = 960              # the self-check's transfer: 10 chunks
CALLSZ   = 8160             # bytes per streamer call: 85 chunks
NBYTES   = CALLSZ * 16      # 130,560 bytes a phase
REPS     = NBYTES // CALLSZ
assert all(CHUNK_F % k == 0 for k in (1, 2, 6)), 'chunk must divide every stride'
assert CALLSZ % CHUNK_F == 0 and CHECKSZ % CHUNK_F == 0
CHUNK_S  = 24               # vidcore.asm's VcChunk

def rep(lines, n):
    return "".join("        " + l + "\n" for _ in range(n) for l in lines)

def fast(name, inner, per_iter, dp, reload_, note):
    """A streamer with Strm's per-chunk bookkeeping and an unrolled body."""
    n = CHUNK_F // per_iter
    rl = "".join("        " + l + "\n" for l in reload_)
    return f"""
* --- {name}: {note}
{name}    pshs    cc,dp
        lda     #${dp:02X}
        tfr     a,dp
{name}h   orcc    #IRQMASK
        lda     PtrGen
        cmpa    PtrSeen
        beq     {name}g
{name}g   ldd     SCnt
        cmpd    #{CHUNK_F}
        bls     {name}1
        ldd     #{CHUNK_F}
{name}1   pshs    d
{rl}{rep(inner, n)}        ldd     ,s
        addd    PtrN
        std     PtrN
        ldd     SCnt
        subd    ,s++
        std     SCnt
        beq     {name}e
        lda     ,s
        bita    #IRQMASK
        lbne    {name}h
        andcc   #$EF
        lbra    {name}h
{name}e   puls    cc,dp,pc
"""

def phase(marker, setup, call, note):
    t = marker.lower()
    return f"""
* --- ${marker}: {note}
p{t}     lda     #${marker}
        lbsr    mark
        lbsr    setwp
{"".join("        " + l + chr(10) for l in setup)}        lda     #{REPS}
        sta     total
p{t}l    ldd     #{CALLSZ}
        std     SCnt
{"".join("        " + l + chr(10) for l in call)}        dec     total
        bne     p{t}l
        rts
"""

o = []
w = o.append
w(f"""*******************************************************************************
* vramrate.asm -- how fast can a 6809 put bytes into VRAM on this card?
*
*   sh software/archive/demo/bench/run-vramrate.sh
*
* GENERATED by bench/mkvramrate.py -- the unrolled blocks are hundreds of
* literal instructions.  EDIT THE GENERATOR, not this file.
*
* software/nitros9/docs/nitros9-hardware-improvements.md quotes VidCore at "~10 us a byte in
* masked chunks", and EVERY H-item's cost is denominated in it.  This measures
* that loop and its alternatives on the same machine, the same card and the
* same masking discipline (nitros9-av-plan.md 3.4: /IRQ open between chunks),
* so the only variable is how the inner loop is written.
*
* Each phase moves {NBYTES:,} bytes and brackets itself with a write to the
* progress port ($FF2F), which machine.c timestamps; tools/vramrate.py
* subtracts and divides.  Phases 1, 3 and 5 are vidcore.asm's Strm verbatim.
*
*   $A1 PUT  VDATA  Strm, chunk {CHUNK_S}        $A5 GET  VDATA  Strm, chunk {CHUNK_S}
*   $A2 PUT  VDATA  unrolled, DP, chunk {CHUNK_F}  $A6 GET  VDATA  unrolled, DP, chunk {CHUNK_F}
*   $A3 FILL VDATA  Strm, chunk {CHUNK_S}        $A7 FILL WINDOW STD <dp, two bytes an instruction
*   $A4 FILL VDATA  unrolled, DP, chunk {CHUNK_F}  $A8 PUT  WINDOW PULU + STD/STX/STY <dp
*   $A0 the timed phases end (the self-check runs after it)
*   $AF done
*******************************************************************************

MAPHI   EQU     $FF90
MAPLO   EQU     $FFA0
SIMPORT EQU     $FF2F
VBASE   EQU     $FF60
VCTRL   EQU     $FF60
WFG     EQU     $FF66
WBG     EQU     $FF67
WPTR0   EQU     $FF68
WPTR1   EQU     $FF69
WPTR2   EQU     $FF6A
WADV    EQU     $FF74
VDATA   EQU     $FF75
O_VDATA EQU     VDATA-VBASE     $15 -- vidcore.asm addresses it as VR.VDATA,u

VRAMWIN EQU     $2000           logical block 1: an 8 KB window on the ring
VRDP    EQU     $20             DP that puts direct addressing in that window
SRCBUF  EQU     $4000           16 KB of SIMM: the source and the sink
IRQMASK EQU     $10

SCnt    EQU     $C000           vidcore.asm's VG.SCnt and friends
SFill   EQU     $C002
SByte   EQU     $C003
PtrN    EQU     $C004
PtrGen  EQU     $C006
PtrSeen EQU     $C007
Base    EQU     $C008
total   EQU     $C00A
fillw   EQU     $C00C
cmph    EQU     $C00E           the compare's outer count -- RAM, not ROM

        ORG     $8000
        FCC     "6309"
        JMP     start

        SETDP   $FF
start   orcc    #$50
        lds     #$E000
        lda     #$FF
        tfr     a,dp

* --- block 1 is the VRAM window (boot.asm section 2: physical A20:A19 = 01)
        clr     MAPHI+1
        lda     #$40
        sta     MAPLO+1

* --- the card: display off, WMODE 00 direct, no IRQ.  Nothing is displayed,
*     so no phase depends on what the frame shows.
        clr     VCTRL
        clr     WADV
        clr     WFG
        clr     WBG
        ldd     #VBASE
        std     Base
        clr     PtrGen
        clr     PtrSeen
        ldd     #$5A5A
        std     fillw

* --- a source pattern, so a wrong loop is visible as well as slow
        ldx     #SRCBUF
        clrb
srcfl   stb     ,x+
        incb
        cmpx    #SRCBUF+16384
        bne     srcfl
        lbra    run

setwp   clr     WPTR0
        clr     WPTR1
        clr     WPTR2
        rts

mark    sta     SIMPORT
        rts

* --- Strm: vidcore.asm's chunked streamer, verbatim except that the statics
*     are absolute.  VcWait can never fire here: nothing else touches WPTR.
*     SFill 0 = put (X -> VDATA), 1 = fill (SByte), 2 = get (VDATA -> X)
Strm    pshs    cc,u
        ldu     Base
sch     orcc    #IRQMASK
        lda     PtrGen
        cmpa    PtrSeen
        beq     sgo
sgo     ldd     SCnt
        cmpd    #{CHUNK_S}
        bls     sc1
        ldb     #{CHUNK_S}
sc1     pshs    b
        lda     SFill
        beq     sp
        cmpa    #2
        bne     sf
sg      lda     O_VDATA,u
        sta     ,x+
        decb
        bne     sg
        bra     scd
sp      lda     ,x+
        sta     O_VDATA,u
        decb
        bne     sp
        bra     scd
sf      lda     SByte
sfl     sta     O_VDATA,u
        decb
        bne     sfl
scd     clra
        ldb     ,s
        addd    PtrN
        std     PtrN
        clra
        puls    b
        pshs    d
        ldd     SCnt
        subd    ,s++
        std     SCnt
        beq     send
        lda     ,s
        bita    #IRQMASK
        bne     sch
        andcc   #$EF
        bra     sch
send    puls    cc,u,pc
""")

# ---- the unrolled streamers -------------------------------------------------
w(fast("fput", ["ldd     ,x++", "sta     <$75", "stb     <$75"], 2, 0xFF, [],
       "PUT through +$15 VDATA, direct-page stores, two bytes an iteration."
       "\n*     LDD ,X++ 8 + STA <dp 4 + STB <dp 4 = 8 cycles a byte"))
w(fast("ffil", ["sta     <$75"], 1, 0xFF, ["lda     SByte"],
       "FILL through +$15 VDATA.  STA <dp 4 = 4 cycles a byte"))
w(fast("fget", ["lda     <$75", "ldb     <$75", "std     ,x++"], 2, 0xFF, [],
       "GET through +$15 VDATA.  LDA 4 + LDB 4 + STD ,X++ 8 = 8 cycles a byte"))
w(fast("wfil", ["std     <$00"], 2, 0x20, ["ldd     fillw"],
       "FILL through the VRAM WINDOW.  graphics.md 11: every address in the"
       "\n*     block is the port, so a 16-bit store carries TWO bytes."
       "\n*     STD <dp 5 = 2.5 cycles a byte"))
w(fast("wput", ["pulu    a,b,x,y", "std     <$00", "stx     <$00", "sty     <$00"], 6, 0x20, [],
       "PUT through the VRAM WINDOW.  PULU fetches six bytes in 11 cycles and"
       "\n*     three 16-bit stores retire them, in order: 26/6 = 4.33 a byte"))

# ---- the phases -------------------------------------------------------------
w(phase("A1", ["clr     SFill"], ["ldx     #SRCBUF", "lbsr    Strm"],
        "PUT, vidcore.asm's Strm -- the number every H-item is quoted in"))
w(phase("A2", [], ["ldx     #SRCBUF", "lbsr    fput"], "PUT, unrolled, VDATA"))
w(phase("A3", ["lda     #1", "sta     SFill", "lda     #$5A", "sta     SByte"],
        ["lbsr    Strm"], "FILL, Strm"))
w(phase("A4", [], ["lbsr    ffil"], "FILL, unrolled, VDATA"))
w(phase("A5", ["lda     #2", "sta     SFill"], ["ldx     #SRCBUF", "lbsr    Strm"],
        "GET, Strm"))
w(phase("A6", [], ["ldx     #SRCBUF", "lbsr    fget"], "GET, unrolled, VDATA"))
w(phase("A7", [], ["lbsr    wfil"], "FILL through the VRAM window"))
w(phase("A8", [], ["ldu     #SRCBUF", "lbsr    wput"], "PUT through the VRAM window"))


w("""
*------------------------------------------------------------------ the check
* A loop that is fast and wrong is worth nothing, and the GET phases overwrite
* the source, so correctness is asserted here rather than inferred from a dump.
* Each PUT form fills ring row 0 (wstep wraps within 1024 bytes) and vidcore's
* own Strm GET reads it back.  $AE = every form agreed, $EE = one did not.
CMPBUF  EQU     $6000

* mkpat - B = seed; CHECKSZ bytes of seed, seed+1, ...  A different seed per
* form, so a form that writes short fails against the previous form's bytes
* instead of matching them.
mkpat   ldx     #SRCBUF
mkpl    stb     ,x+
        incb
        cmpx    #SRCBUF+960
        bne     mkpl
        rts

* rdback - WPTR := 0, then Strm GET 1024 bytes into CMPBUF, and compare
rdback  lbsr    setwp
        lda     #2
        sta     SFill
        ldd     #960
        std     SCnt
        ldx     #CMPBUF
        lbsr    Strm
        ldx     #SRCBUF
        ldy     #CMPBUF
        ldd     #960
        std     cmph
cmpl    lda     ,x+
        cmpa    ,y+
        bne     cmpbad
        ldd     cmph
        subd    #1
        std     cmph
        bne     cmpl
        andcc   #$FE            carry clear: they agree
        rts
cmpbad  orcc    #$01
        rts

verify
* --- Strm, vidcore verbatim
        clrb
        lbsr    mkpat
        lbsr    setwp
        clr     SFill
        ldd     #960
        std     SCnt
        ldx     #SRCBUF
        lbsr    Strm
        lbsr    rdback
        bcs     vbad
        lda     #$AB
        lbsr    mark

* --- the unrolled VDATA form
        ldb     #$55
        lbsr    mkpat
        lbsr    setwp
        ldd     #960
        std     SCnt
        ldx     #SRCBUF
        lbsr    fput
        lbsr    rdback
        bcs     vbad
        lda     #$AC
        lbsr    mark

* --- PULU + three 16-bit stores, through the window
        ldb     #$AA
        lbsr    mkpat
        lbsr    setwp
        ldd     #960
        std     SCnt
        ldu     #SRCBUF
        lbsr    wput
        lbsr    rdback
        bcs     vbad

        lda     #$AE
        lbsr    mark
        rts
vbad    lda     #$EE
        lbsr    mark
        rts
""")
w("""
run     lbsr    pa1
        lbsr    pa2
        lbsr    pa3
        lbsr    pa4
        lbsr    pa5
        lbsr    pa6
        lbsr    pa7
        lbsr    pa8
        lda     #$A0            the last phase ends HERE, not at $AF
        lbsr    mark
        lbsr    verify
        lda     #$AF
        lbsr    mark
done    bra     done

        END
""")
open(sys.argv[1], "w").write("".join(o))
print("wrote", sys.argv[1])
