// GENERATED by hardware/gal/verilog/emit.ts from the term lists in
// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module aseq (
    input  wire RESET,
    input  wire S2,
    input  wire S1,
    input  wire S0,
    input  wire ACOUT,
    input  wire NEQL,
    input  wire NEQH,
    input  wire DMAEN0,
    input  wire CTRL7,
    input  wire DMAEN1,
    input  wire DMAEN2,
    input  wire DMAEN3,
    input  wire CTRL6,
    input  wire SEL,
    input  wire E,
    input  wire A0,
    input  wire A1,
    input  wire A2,
    input  wire A3,
    input  wire RW,
    input  wire D0,
    input  wire D1,
    input  wire D2,
    input  wire D3,
    input  wire D4,
    input  wire D5,
    input  wire SLOTCLK,
    output wire QCHAN,
    output wire QTMR,
    output wire RUN,
    output wire WORKSLOT,
    output wire T0,
    output wire T1,
    output wire T2,
    output wire T3,
    output wire LAST,
    output wire RSTANY,
    output wire DUEANY,
    output wire START,
    output wire BUSY,
    output wire ENDNOW,
    output wire CHAIN1,
    output wire WT0,
    output wire WT1,
    output wire WT2,
    output wire WC0,
    output wire WC1,
    output wire RPICK0,
    output wire RPICK1,
    output wire RPICK2,
    output wire RPICK3,
    output wire DPICK0,
    output wire DPICK1,
    output wire DPICK2,
    output wire DPICK3,
    output wire DUE0,
    output wire DUE1,
    output wire DUE2,
    output wire DUE3,
    output wire CLR0,
    output wire CLR1,
    output wire CLR2,
    output wire CLR3,
    output wire TDUE,
    output wire TACK,
    output wire TQ,
    output wire TARM,
    output wire DMAQ0,
    output wire DMAQ1,
    output wire DMAQ2,
    output wire DMAQ3,
    output wire RST0,
    output wire RST1,
    output wire RST2,
    output wire RST3,
    output wire RCLR0,
    output wire RCLR1,
    output wire RCLR2,
    output wire RCLR3,
    output wire HSY1,
    output wire HSY2,
    output wire HSTB,
    output wire HA0,
    output wire HA1,
    output wire HA2,
    output wire HA3,
    output wire HRW,
    output wire HDUE,
    output wire HACK,
    output wire ISADATA,
    output wire ISAIDX,
    output wire ISSDATA,
    output wire ISSPTR,
    output wire ISTIMER,
    output wire AIDXLD,
    output wire AINC,
    output wire AIDX0,
    output wire AIDX1,
    output wire AIDX2,
    output wire AIDX3,
    output wire AIDX4,
    output wire AIDX5,
    output wire HW0,
    output wire HW1,
    output wire HW2,
    output wire HL0,
    output wire HL1,
    output wire HRO,
    output wire HSTAGE,
    output wire HCOMMIT,
    output wire GBL,
    output wire SFA5,
    output wire SFOE,
    output wire SFA4,
    output wire SFA3,
    output wire SFA0,
    output wire SFA1,
    output wire SFA2,
    output wire SFWE0,
    output wire SFWE1,
    output wire SFWE2,
    output wire ALATCK,
    output wire BLATCK,
    output wire BLATOE,
    output wire ONESOE,
    output wire CNTOE,
    output wire ACIN,
    output wire SUMOE,
    output wire SROE,
    output wire SRWE,
    output wire SBOE,
    output wire SDHCAP,
    output wire SDHOE,
    output wire SDQ0,
    output wire SDQ1,
    output wire SDQ2,
    inout  wire SDH0,
    inout  wire SDH1,
    inout  wire SDH2,
    output wire PWCK,
    output wire PWOE,
    output wire PFCK,
    output wire PFLANE,
    output wire PWBUSY,
    output wire PFVALID,
    output wire CVBUSY,
    output wire CVB,
    output wire CVOEA,
    output wire WROTE0,
    output wire WROTE1,
    output wire WROTE2,
    output wire WROTE3,
    output wire CVCSS,
    output wire CVCSV,
    output wire CVLD0,
    output wire CVLD1,
    output wire CVLD2,
    output wire CVLD3,
    output wire CVC0,
    output wire CVC1,
    output wire CVC2,
    output wire VDIRTY,
    output wire VACK,
    output wire FIRE0,
    output wire FIRE1,
    output wire FIRE2,
    output wire FIRE3,
    output wire FIRE4,
    output wire FIRE5,
    output wire NOFIRE,
    output wire SETA,
    output wire SETB,
    output wire SETC,
    output wire SDH0_OE,
    output wire SDH1_OE,
    output wire SDH2_OE
);

  reg  r_T0;
  reg  r_T1;
  reg  r_T2;
  reg  r_T3;
  reg  r_BUSY;
  reg  r_WT0;
  reg  r_WT1;
  reg  r_WT2;
  reg  r_WC0;
  reg  r_WC1;
  reg  r_DUE0;
  reg  r_DUE1;
  reg  r_DUE2;
  reg  r_DUE3;
  reg  r_TDUE;
  reg  r_TQ;
  reg  r_DMAQ0;
  reg  r_DMAQ1;
  reg  r_DMAQ2;
  reg  r_DMAQ3;
  reg  r_RST0;
  reg  r_RST1;
  reg  r_RST2;
  reg  r_RST3;
  reg  r_HSY1;
  reg  r_HSY2;
  reg  r_HA0;
  reg  r_HA1;
  reg  r_HA2;
  reg  r_HA3;
  reg  r_HRW;
  reg  r_HDUE;
  reg  r_AIDX0;
  reg  r_AIDX1;
  reg  r_AIDX2;
  reg  r_AIDX3;
  reg  r_AIDX4;
  reg  r_AIDX5;
  reg  r_HW0;
  reg  r_HW1;
  reg  r_HW2;
  reg  r_HL0;
  reg  r_HL1;
  reg  r_HRO;
  reg  r_HSTAGE;
  reg  r_HCOMMIT;
  reg  r_SDQ0;
  reg  r_SDQ1;
  reg  r_SDQ2;
  reg  r_PWBUSY;
  reg  r_PFVALID;
  reg  r_WROTE0;
  reg  r_WROTE1;
  reg  r_WROTE2;
  reg  r_WROTE3;
  reg  r_VDIRTY;

  assign T0 = r_T0;
  assign T1 = r_T1;
  assign T2 = r_T2;
  assign T3 = r_T3;
  assign BUSY = r_BUSY;
  assign WT0 = r_WT0;
  assign WT1 = r_WT1;
  assign WT2 = r_WT2;
  assign WC0 = r_WC0;
  assign WC1 = r_WC1;
  assign DUE0 = r_DUE0;
  assign DUE1 = r_DUE1;
  assign DUE2 = r_DUE2;
  assign DUE3 = r_DUE3;
  assign TDUE = r_TDUE;
  assign TQ = r_TQ;
  assign DMAQ0 = r_DMAQ0;
  assign DMAQ1 = r_DMAQ1;
  assign DMAQ2 = r_DMAQ2;
  assign DMAQ3 = r_DMAQ3;
  assign RST0 = r_RST0;
  assign RST1 = r_RST1;
  assign RST2 = r_RST2;
  assign RST3 = r_RST3;
  assign HSY1 = r_HSY1;
  assign HSY2 = r_HSY2;
  assign HA0 = r_HA0;
  assign HA1 = r_HA1;
  assign HA2 = r_HA2;
  assign HA3 = r_HA3;
  assign HRW = r_HRW;
  assign HDUE = r_HDUE;
  assign AIDX0 = r_AIDX0;
  assign AIDX1 = r_AIDX1;
  assign AIDX2 = r_AIDX2;
  assign AIDX3 = r_AIDX3;
  assign AIDX4 = r_AIDX4;
  assign AIDX5 = r_AIDX5;
  assign HW0 = r_HW0;
  assign HW1 = r_HW1;
  assign HW2 = r_HW2;
  assign HL0 = r_HL0;
  assign HL1 = r_HL1;
  assign HRO = r_HRO;
  assign HSTAGE = r_HSTAGE;
  assign HCOMMIT = r_HCOMMIT;
  assign SDQ0 = r_SDQ0;
  assign SDQ1 = r_SDQ1;
  assign SDQ2 = r_SDQ2;
  assign PWBUSY = r_PWBUSY;
  assign PFVALID = r_PFVALID;
  assign WROTE0 = r_WROTE0;
  assign WROTE1 = r_WROTE1;
  assign WROTE2 = r_WROTE2;
  assign WROTE3 = r_WROTE3;
  assign VDIRTY = r_VDIRTY;

  // buried
  assign QCHAN =
         (~S2);
  // buried
  assign QTMR =
         (S2 & ~S1 & ~S0);
  // buried - a work slot with a sequence in it
  assign RUN =
         (WORKSLOT & BUSY);
  // buried - slots 5, 6 and 7 - 3.1's host service and deferred work, together
  assign WORKSLOT =
         (S2 & S1)
         | (S2 & S0);
  // buried - the final step of the sequence in progress
  assign LAST =
         (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & T1 & T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & ~WT1 & WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & T3)
         | (RUN & WT0 & ~WT1 & WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & T1 & T2 & ~T3);
  // buried
  assign RSTANY =
         (RST0)
         | (RST1)
         | (RST2)
         | (RST3);
  // buried
  assign DUEANY =
         (DUE0)
         | (DUE1)
         | (DUE2)
         | (DUE3);
  // buried
  assign START =
         (WORKSLOT & ~BUSY & RSTANY)
         | (WORKSLOT & ~BUSY & TDUE)
         | (WORKSLOT & ~BUSY & DUEANY)
         | (WORKSLOT & ~BUSY & HDUE)
         | (WORKSLOT & ~BUSY & VDIRTY);
  // buried - W1 ended on a buffer end, so W2 follows without releasing the engine
  assign ENDNOW =
         (RUN & ~WT2 & ~WT1 & ~WT0 & ~T0 & T1 & T2 & ~T3 & ~ACOUT);
  // buried - W6 finished its reload, so W1 follows without releasing the engine
  assign CHAIN1 =
         (RUN & ~WT0 & WT1 & ~WT2 & T0 & T1 & T2 & ~T3);
  // buried
  assign RPICK0 =
         (START & RSTANY & RST0);
  // buried
  assign RPICK1 =
         (START & RSTANY & ~RST0 & RST1);
  // buried
  assign RPICK2 =
         (START & RSTANY & ~RST0 & ~RST1 & RST2);
  // buried
  assign RPICK3 =
         (START & RSTANY & ~RST0 & ~RST1 & ~RST2 & RST3);
  // buried
  assign DPICK0 =
         (START & ~RSTANY & ~TDUE & DUE0);
  // buried
  assign DPICK1 =
         (START & ~RSTANY & ~TDUE & ~DUE0 & DUE1);
  // buried
  assign DPICK2 =
         (START & ~RSTANY & ~TDUE & ~DUE0 & ~DUE1 & DUE2);
  // buried
  assign DPICK3 =
         (START & ~RSTANY & ~TDUE & ~DUE0 & ~DUE1 & ~DUE2 & DUE3);
  // buried
  assign CLR0 =
         (DPICK0);
  // buried
  assign CLR1 =
         (DPICK1);
  // buried
  assign CLR2 =
         (DPICK2);
  // buried
  assign CLR3 =
         (DPICK3);
  // buried
  assign TACK =
         (START & ~RSTANY & TDUE);
  // buried
  assign TARM =
         (CTRL6 & ~TQ);
  // buried
  assign RCLR0 =
         (RPICK0);
  // buried
  assign RCLR1 =
         (RPICK1);
  // buried
  assign RCLR2 =
         (RPICK2);
  // buried
  assign RCLR3 =
         (RPICK3);
  // buried - 9.4.4: one slot wide, on the leading edge of a synchronised access
  assign HSTB =
         (HSY1 & ~HSY2);
  // buried - 9.2: the host's access is retired when its sequence ENDS
  assign HACK =
         (RUN & WT2 & ~WT1 & ~WT0 & LAST);
  // buried
  assign ISADATA =
         (~HA3 & ~HA2 & ~HA1 & HA0);
  // buried
  assign ISAIDX =
         (~HA3 & ~HA2 & ~HA1 & ~HA0);
  // buried
  assign ISSDATA =
         (HA3 & ~HA2 & ~HA1 & HA0);
  // buried
  assign ISSPTR =
         (~HA3 & HA2 & HA1 & ~HA0)
         | (~HA3 & HA2 & HA1 & HA0)
         | (HA3 & ~HA2 & ~HA1 & ~HA0);
  // buried
  assign ISTIMER =
         (HA3 & ~HA2 & HA1 & HA0)
         | (HA3 & HA2 & ~HA1 & ~HA0);
  // buried
  assign AIDXLD =
         (HSTB & ~A3 & ~A2 & ~A1 & ~A0 & ~RW);
  // buried - 9.2: ADATA post-increments
  assign AINC =
         (RUN & WT2 & ~WT1 & ~WT0 & LAST & ISADATA);
  // buried - this access is one of the six words at $20
  assign GBL =
         (QTMR)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & ~T2 & ~T3 & HSTAGE);
  // EXTERNAL
  assign SFA5 =
         (GBL);
  // EXTERNAL
  assign SFOE =
         (QCHAN)
         | (QTMR)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & T3)
         | (RUN & WT0 & ~WT1 & WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & ~T1 & ~T2 & ~T3 & HCOMMIT & ~HRW)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & T1 & ~T2 & ~T3 & ISSDATA)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & ~T1 & T2 & ~T3);
  // EXTERNAL
  assign SFA4 =
         (QCHAN & S1)
         | (RUN & ~GBL & ~WT2 & WC1)
         | (RUN & ~GBL & WT2 & ~WT0 & AIDX5)
         | (RUN & WT0 & ~WT1 & WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & WT2 & ~T0 & ~T1 & T2 & ~T3);
  // EXTERNAL
  assign SFA3 =
         (QCHAN & S0)
         | (RUN & ~GBL & ~WT2 & WC0)
         | (RUN & ~GBL & WT2 & ~WT0 & AIDX4)
         | (RUN & WT0 & ~WT1 & WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & WT2 & T0 & T1 & ~T2 & ~T3);
  // EXTERNAL
  assign SFA0 =
         (QTMR)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & T1 & T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & ~T2 & ~T3 & HSTAGE)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & ~T2 & ~T3 & ~HSTAGE & HW0)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & ~T1 & T2 & ~T3 & HW0)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & T1 & ~T2 & ~T3 & HW0);
  // EXTERNAL
  assign SFA1 =
         (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & ~T2 & ~T3 & ~HSTAGE & HW1)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & ~T1 & T2 & ~T3 & HW1)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & T1 & ~T2 & ~T3 & HW1);
  // EXTERNAL
  assign SFA2 =
         (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & T1 & T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & ~T2 & ~T3 & HSTAGE)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & ~T2 & ~T3 & ~HSTAGE & HW2)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & ~T1 & T2 & ~T3 & HW2)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & T1 & ~T2 & ~T3 & HW2);
  // EXTERNAL
  assign SFWE0 =
         (RUN & ~WT0 & ~WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & T1 & T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & T1 & T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & ~T2 & ~T3 & ~HRW & ~HRO & ~ISAIDX & ~ISSDATA & ~HL0 & ~HL1)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & T1 & ~T2 & ~T3 & HCOMMIT & ~HRW)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & T2 & ~T3 & ISSDATA);
  // EXTERNAL
  assign SFWE1 =
         (RUN & ~WT0 & ~WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & T1 & T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & T1 & T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & ~T2 & ~T3 & ~HRW & ~HRO & ~ISAIDX & ~ISSDATA & HL0 & ~HL1)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & T1 & ~T2 & ~T3 & HCOMMIT & ~HRW)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & T2 & ~T3 & ISSDATA);
  // EXTERNAL
  assign SFWE2 =
         (RUN & ~WT0 & ~WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & T1 & T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & ~T2 & ~T3 & ~HRW & ~HRO & ~ISAIDX & ~ISSDATA & ~HL0 & HL1)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & T1 & ~T2 & ~T3 & HCOMMIT & ~HRW & HW1)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & T2 & ~T3 & ISSDATA);
  // EXTERNAL
  assign ALATCK =
         (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3 & ~SLOTCLK)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3 & ~SLOTCLK)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3 & ~SLOTCLK)
         | (RUN & WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3 & ~SLOTCLK)
         | (RUN & WT0 & ~WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3 & ~SLOTCLK)
         | (RUN & WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3 & ~SLOTCLK)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3 & ~SLOTCLK)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3 & ~SLOTCLK)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & T3 & ~SLOTCLK)
         | (RUN & ~WT0 & WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3 & ~SLOTCLK)
         | (RUN & ~WT0 & WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3 & ~SLOTCLK)
         | (RUN & ~WT0 & WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3 & ~SLOTCLK)
         | (RUN & ~WT0 & WT1 & ~WT2 & ~T0 & T1 & T2 & ~T3 & ~SLOTCLK)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & ~T1 & ~T2 & ~T3 & HCOMMIT & ~HRW & ~SLOTCLK)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & T1 & ~T2 & ~T3 & ISSDATA & ~SLOTCLK);
  // EXTERNAL
  assign BLATCK =
         (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3 & ~SLOTCLK)
         | (RUN & WT0 & ~WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3 & ~SLOTCLK)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3 & ~SLOTCLK)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3 & ~SLOTCLK)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3 & ~SLOTCLK)
         | (RUN & WT0 & WT1 & ~WT2 & ~T0 & T1 & T2 & ~T3 & ~SLOTCLK)
         | (RUN & ~WT0 & WT1 & ~WT2 & ~T0 & T1 & ~T2 & ~T3 & ~SLOTCLK);
  // EXTERNAL
  assign BLATOE =
         (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3);
  // EXTERNAL - B = $FFFF, so A - 1 is A + $FFFF and the card has no inverter
  assign ONESOE =
         (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & T1 & T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3);
  // EXTERNAL
  assign CNTOE =
         (RUN & ~WT0 & WT1 & ~WT2 & ~T0 & T1 & T2 & ~T3);
  // EXTERNAL
  assign ACIN =
         (RUN & ~WT0 & ~WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & T2 & ~T3 & ISSDATA);
  // EXTERNAL
  assign SUMOE =
         (RUN & ~WT0 & ~WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & T1 & T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & T1 & T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & T1 & ~T2 & ~T3 & HCOMMIT & ~HRW)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & T2 & ~T3 & ISSDATA);
  // EXTERNAL
  assign SROE =
         (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & T1 & ~T2 & ~T3 & ISSDATA & HRW);
  // EXTERNAL
  assign SRWE =
         (RUN & WT2 & ~WT1 & ~WT0 & T0 & T1 & ~T2 & ~T3 & ISSDATA & ~HRW);
  // EXTERNAL - the fetched byte drives the PEND lane while word 0 is written
  assign SBOE =
         (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3);
  // buried
  assign SDHCAP =
         (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & ~T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & ~T1 & ~T2 & ~T3 & HCOMMIT & ~HRW)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & T1 & ~T2 & ~T3 & ISSDATA);
  // buried
  assign SDHOE =
         (RUN & ~WT0 & ~WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & T1 & T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & ~WT0 & WT1 & ~WT2 & T0 & ~T1 & T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & T1 & ~T2 & ~T3 & HCOMMIT & ~HRW)
         | (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & T2 & ~T3 & ISSDATA);
  // EXTERNAL, bidirectional
  assign SDH0 = ((SDHOE)) ?
         (~ACIN & ~ONESOE & ~BLATOE & SDQ0)
         | (ACIN & SDQ0 & ~ACOUT)
         | (ACIN & ~SDQ0 & ACOUT)
         | (ONESOE & SDQ0 & ACOUT)
         | (ONESOE & ~SDQ0 & ~ACOUT)
         | (BLATOE & ACOUT) : 1'bz;
  // EXTERNAL, bidirectional
  assign SDH1 = ((SDHOE)) ?
         (~ACIN & ~ONESOE & ~BLATOE & SDQ1)
         | (ACIN & SDQ1 & ~ACOUT)
         | (ACIN & SDQ1 & ~SDQ0)
         | (ACIN & ~SDQ1 & ACOUT & SDQ0)
         | (ONESOE & SDQ1 & ACOUT)
         | (ONESOE & SDQ1 & SDQ0)
         | (ONESOE & ~SDQ1 & ~ACOUT & ~SDQ0) : 1'bz;
  // EXTERNAL, bidirectional
  assign SDH2 = ((SDHOE)) ?
         (~ACIN & ~ONESOE & ~BLATOE & SDQ2)
         | (ACIN & SDQ2 & ~ACOUT)
         | (ACIN & SDQ2 & ~SDQ0)
         | (ACIN & SDQ2 & ~SDQ1)
         | (ACIN & ~SDQ2 & ACOUT & SDQ1 & SDQ0)
         | (ONESOE & SDQ2 & ACOUT)
         | (ONESOE & SDQ2 & SDQ0)
         | (ONESOE & SDQ2 & SDQ1)
         | (ONESOE & ~SDQ2 & ~ACOUT & ~SDQ1 & ~SDQ0) : 1'bz;
  // EXTERNAL - the posted-write latch takes the host's byte on the synchronised edge
  assign PWCK =
         (HSTB & ~RW & ~SLOTCLK);
  // EXTERNAL
  assign PWOE =
         (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & ~T2 & ~T3 & ~HRW & ~ISAIDX & ~ISSDATA)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & T1 & ~T2 & ~T3 & ISSDATA & ~HRW);
  // EXTERNAL
  assign PFCK =
         (RUN & WT2 & ~WT1 & ~WT0 & T0 & ~T1 & T2 & ~T3)
         | (RUN & WT2 & ~WT1 & ~WT0 & T0 & T1 & ~T2 & ~T3 & ISSDATA & HRW);
  // EXTERNAL - 9.3: which byte lane the host's index names
  assign PFLANE =
         (HL0);
  // buried
  assign CVBUSY =
         (RUN & WT2 & ~WT1 & WT0);
  // buried - W5's second half: port registers 3 and 2, DAC B
  assign CVB =
         (RUN & WT0 & ~WT1 & WT2 & T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & WT2 & ~T0 & ~T1 & T2 & ~T3)
         | (RUN & WT0 & ~WT1 & WT2 & T0 & ~T1 & T2 & ~T3);
  // EXTERNAL
  assign CVOEA =
         (~QCHAN & ~CVBUSY)
         | (CVBUSY & ~CVB);
  // buried - 6.2: the two sample packages, in the half-frame after the hit
  assign CVCSS =
         (~QCHAN & ~CVBUSY & WROTE0)
         | (~QCHAN & ~CVBUSY & WROTE1)
         | (QCHAN & ~CVBUSY & WROTE2)
         | (QCHAN & ~CVBUSY & WROTE3);
  // buried
  assign CVCSV =
         (RUN & WT0 & ~WT1 & WT2 & ~T0 & T1 & ~T2 & ~T3)
         | (RUN & WT0 & ~WT1 & WT2 & T0 & ~T1 & T2 & ~T3);
  // buried
  assign CVLD0 =
         (QCHAN & ~CVBUSY & ~S0 & ~S1)
         | (RUN & WT0 & ~WT1 & WT2 & ~T0 & ~T1 & ~T2 & ~T3);
  // buried
  assign CVLD1 =
         (QCHAN & ~CVBUSY & S0 & ~S1)
         | (RUN & WT0 & ~WT1 & WT2 & T0 & ~T1 & ~T2 & ~T3);
  // buried
  assign CVLD2 =
         (QCHAN & ~CVBUSY & ~S0 & S1)
         | (RUN & WT0 & ~WT1 & WT2 & ~T0 & ~T1 & T2 & ~T3);
  // buried
  assign CVLD3 =
         (QCHAN & ~CVBUSY & S0 & S1)
         | (RUN & WT0 & ~WT1 & WT2 & T0 & T1 & ~T2 & ~T3);
  // EXTERNAL
  assign CVC0 =
         (CVLD0)
         | (CVLD2)
         | (CVCSS);
  // EXTERNAL
  assign CVC1 =
         (CVLD1)
         | (CVLD2)
         | (CVCSV);
  // EXTERNAL
  assign CVC2 =
         (CVLD3)
         | (CVCSS)
         | (CVCSV);
  // buried
  assign VACK =
         (START & ~RSTANY & ~TDUE & ~DUEANY & ~HDUE);
  // buried - this channel's buffer ran out - 1 requirement 7
  assign FIRE0 =
         (ENDNOW & ~WC0 & ~WC1);
  // buried - this channel's buffer ran out - 1 requirement 7
  assign FIRE1 =
         (ENDNOW & WC0 & ~WC1);
  // buried - this channel's buffer ran out - 1 requirement 7
  assign FIRE2 =
         (ENDNOW & ~WC0 & WC1);
  // buried - this channel's buffer ran out - 1 requirement 7
  assign FIRE3 =
         (ENDNOW & WC0 & WC1);
  // buried
  assign FIRE4 =
         (RUN & WT0 & WT1 & ~WT2 & T0 & ~T1 & ~T2 & T3);
  // buried - 8.1 bit 5: a posted write arrived while the previous had not retired
  assign FIRE5 =
         (HSTB & ~RW & PWBUSY);
  // buried
  assign NOFIRE =
         (~FIRE0 & ~FIRE1 & ~FIRE2 & ~FIRE3 & ~FIRE4 & ~FIRE5);
  // EXTERNAL
  assign SETA =
         (FIRE1)
         | (FIRE3)
         | (FIRE5)
         | (NOFIRE);
  // EXTERNAL
  assign SETB =
         (FIRE2)
         | (FIRE3)
         | (NOFIRE);
  // EXTERNAL
  assign SETC =
         (FIRE4)
         | (FIRE5)
         | (NOFIRE);

  // SDH0 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SDH0_OE =
         (SDHOE);
  // SDH1 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SDH1_OE =
         (SDHOE);
  // SDH2 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SDH2_OE =
         (SDHOE);

  always @(posedge SLOTCLK) begin
      r_T0 <=
         (RUN & ~LAST & ~T0)
         | (~RUN & T0);
      r_T1 <=
         (RUN & ~LAST & T1 & ~T0)
         | (RUN & ~LAST & ~T1 & T0)
         | (~RUN & T1);
      r_T2 <=
         (RUN & ~LAST & T2 & ~T0)
         | (RUN & ~LAST & T2 & ~T1)
         | (RUN & ~LAST & ~T2 & T0 & T1)
         | (~RUN & T2);
      r_T3 <=
         (RUN & ~LAST & T3 & ~T0)
         | (RUN & ~LAST & T3 & ~T1)
         | (RUN & ~LAST & T3 & ~T2)
         | (RUN & ~LAST & ~T3 & T0 & T1 & T2)
         | (~RUN & T3);
      r_BUSY <=
         (START)
         | (BUSY & ~LAST)
         | (ENDNOW)
         | (CHAIN1);
      r_WT0 <=
         (ENDNOW)
         | (START & ~RSTANY & TDUE)
         | (START & ~RSTANY & ~TDUE & ~DUEANY & ~HDUE)
         | (WT0 & ~START & ~ENDNOW);
      r_WT1 <=
         (START & RSTANY)
         | (START & ~RSTANY & TDUE)
         | (WT1 & ~START & ~ENDNOW & ~CHAIN1);
      r_WT2 <=
         (START & ~RSTANY & ~TDUE & ~DUEANY & HDUE)
         | (START & ~RSTANY & ~TDUE & ~DUEANY & ~HDUE)
         | (WT2 & ~START & ~ENDNOW);
      r_WC0 <=
         (RPICK1)
         | (RPICK3)
         | (DPICK1)
         | (DPICK3)
         | (WC0 & ~START);
      r_WC1 <=
         (RPICK2)
         | (RPICK3)
         | (DPICK2)
         | (DPICK3)
         | (WC1 & ~START);
      r_DUE0 <=
         (QCHAN & ~S1 & ~S0 & ~NEQL & ~NEQH & DMAEN0 & CTRL7)
         | (DUE0 & ~CLR0);
      r_DUE1 <=
         (QCHAN & ~S1 & S0 & ~NEQL & ~NEQH & DMAEN1 & CTRL7)
         | (DUE1 & ~CLR1);
      r_DUE2 <=
         (QCHAN & S1 & ~S0 & ~NEQL & ~NEQH & DMAEN2 & CTRL7)
         | (DUE2 & ~CLR2);
      r_DUE3 <=
         (QCHAN & S1 & S0 & ~NEQL & ~NEQH & DMAEN3 & CTRL7)
         | (DUE3 & ~CLR3);
      r_TDUE <=
         (QTMR & ~NEQL & ~NEQH & CTRL6)
         | (TARM)
         | (TDUE & ~TACK);
      r_TQ <=
         (CTRL6);
      r_DMAQ0 <=
         (DMAEN0);
      r_DMAQ1 <=
         (DMAEN1);
      r_DMAQ2 <=
         (DMAEN2);
      r_DMAQ3 <=
         (DMAEN3);
      r_RST0 <=
         (DMAEN0 & ~DMAQ0)
         | (RST0 & ~RCLR0);
      r_RST1 <=
         (DMAEN1 & ~DMAQ1)
         | (RST1 & ~RCLR1);
      r_RST2 <=
         (DMAEN2 & ~DMAQ2)
         | (RST2 & ~RCLR2);
      r_RST3 <=
         (DMAEN3 & ~DMAQ3)
         | (RST3 & ~RCLR3);
      r_HSY1 <=
         (SEL & E);
      r_HSY2 <=
         (HSY1);
      r_HA0 <=
         (HSTB & A0)
         | (HA0 & ~HSTB);
      r_HA1 <=
         (HSTB & A1)
         | (HA1 & ~HSTB);
      r_HA2 <=
         (HSTB & A2)
         | (HA2 & ~HSTB);
      r_HA3 <=
         (HSTB & A3)
         | (HA3 & ~HSTB);
      r_HRW <=
         (HSTB & RW)
         | (HRW & ~HSTB);
      r_HDUE <=
         (HSTB)
         | (HDUE & ~HACK);
      r_AIDX0 <=
         (AIDXLD & D0)
         | (~AIDXLD & AINC & ~AIDX0)
         | (~AIDXLD & ~AINC & AIDX0);
      r_AIDX1 <=
         (AIDXLD & D1)
         | (~AIDXLD & AINC & AIDX1 & ~AIDX0)
         | (~AIDXLD & AINC & ~AIDX1 & AIDX0)
         | (~AIDXLD & ~AINC & AIDX1);
      r_AIDX2 <=
         (AIDXLD & D2)
         | (~AIDXLD & AINC & AIDX2 & ~AIDX0)
         | (~AIDXLD & AINC & AIDX2 & ~AIDX1)
         | (~AIDXLD & AINC & ~AIDX2 & AIDX0 & AIDX1)
         | (~AIDXLD & ~AINC & AIDX2);
      r_AIDX3 <=
         (AIDXLD & D3)
         | (~AIDXLD & AINC & AIDX3 & ~AIDX0)
         | (~AIDXLD & AINC & AIDX3 & ~AIDX1)
         | (~AIDXLD & AINC & AIDX3 & ~AIDX2)
         | (~AIDXLD & AINC & ~AIDX3 & AIDX0 & AIDX1 & AIDX2)
         | (~AIDXLD & ~AINC & AIDX3);
      r_AIDX4 <=
         (AIDXLD & D4)
         | (~AIDXLD & AINC & AIDX4 & ~AIDX0)
         | (~AIDXLD & AINC & AIDX4 & ~AIDX1)
         | (~AIDXLD & AINC & AIDX4 & ~AIDX2)
         | (~AIDXLD & AINC & AIDX4 & ~AIDX3)
         | (~AIDXLD & AINC & ~AIDX4 & AIDX0 & AIDX1 & AIDX2 & AIDX3)
         | (~AIDXLD & ~AINC & AIDX4);
      r_AIDX5 <=
         (AIDXLD & D5)
         | (~AIDXLD & AINC & AIDX5 & ~AIDX0)
         | (~AIDXLD & AINC & AIDX5 & ~AIDX1)
         | (~AIDXLD & AINC & AIDX5 & ~AIDX2)
         | (~AIDXLD & AINC & AIDX5 & ~AIDX3)
         | (~AIDXLD & AINC & AIDX5 & ~AIDX4)
         | (~AIDXLD & AINC & ~AIDX5 & AIDX0 & AIDX1 & AIDX2 & AIDX3 & AIDX4)
         | (~AIDXLD & ~AINC & AIDX5);
      r_HW0 <=
         (~AIDX0 & ~AIDX1 & ~AIDX2 & ~AIDX3)
         | (AIDX0 & ~AIDX1 & ~AIDX2 & ~AIDX3)
         | (~AIDX0 & AIDX1 & ~AIDX2 & ~AIDX3)
         | (AIDX0 & AIDX1 & ~AIDX2 & ~AIDX3)
         | (~AIDX0 & ~AIDX1 & AIDX2 & ~AIDX3)
         | (~AIDX0 & AIDX1 & ~AIDX2 & AIDX3)
         | (~AIDX0 & AIDX1 & AIDX2 & AIDX3)
         | (AIDX0 & AIDX1 & AIDX2 & AIDX3);
      r_HW1 <=
         (~AIDX0 & ~AIDX1 & ~AIDX2 & ~AIDX3)
         | (AIDX0 & ~AIDX1 & ~AIDX2 & ~AIDX3)
         | (~AIDX0 & AIDX1 & ~AIDX2 & ~AIDX3)
         | (AIDX0 & AIDX1 & AIDX2 & ~AIDX3)
         | (~AIDX0 & ~AIDX1 & ~AIDX2 & AIDX3)
         | (AIDX0 & ~AIDX1 & ~AIDX2 & AIDX3)
         | (~AIDX0 & AIDX1 & ~AIDX2 & AIDX3)
         | (AIDX0 & AIDX1 & ~AIDX2 & AIDX3)
         | (~AIDX0 & ~AIDX1 & AIDX2 & AIDX3)
         | (AIDX0 & ~AIDX1 & AIDX2 & AIDX3);
      r_HW2 <=
         (AIDX0 & AIDX1 & ~AIDX2 & ~AIDX3)
         | (~AIDX0 & ~AIDX1 & AIDX2 & ~AIDX3)
         | (AIDX0 & ~AIDX1 & AIDX2 & ~AIDX3)
         | (~AIDX0 & AIDX1 & AIDX2 & ~AIDX3)
         | (AIDX0 & AIDX1 & AIDX2 & ~AIDX3)
         | (~AIDX0 & ~AIDX1 & ~AIDX2 & AIDX3)
         | (AIDX0 & ~AIDX1 & ~AIDX2 & AIDX3)
         | (~AIDX0 & AIDX1 & ~AIDX2 & AIDX3);
      r_HL0 <=
         (AIDX0 & ~AIDX1 & ~AIDX2 & ~AIDX3)
         | (AIDX0 & AIDX1 & ~AIDX2 & ~AIDX3)
         | (AIDX0 & ~AIDX1 & AIDX2 & ~AIDX3)
         | (AIDX0 & ~AIDX1 & ~AIDX2 & AIDX3)
         | (~AIDX0 & ~AIDX1 & AIDX2 & AIDX3)
         | (~AIDX0 & AIDX1 & AIDX2 & AIDX3);
      r_HL1 <=
         (~AIDX0 & ~AIDX1 & ~AIDX2 & ~AIDX3)
         | (AIDX0 & AIDX1 & AIDX2 & ~AIDX3)
         | (~AIDX0 & AIDX1 & ~AIDX2 & AIDX3)
         | (AIDX0 & AIDX1 & ~AIDX2 & AIDX3);
      r_HRO <=
         (AIDX0 & AIDX1 & ~AIDX2 & AIDX3)
         | (~AIDX0 & ~AIDX1 & AIDX2 & AIDX3)
         | (AIDX0 & ~AIDX1 & AIDX2 & AIDX3)
         | (~AIDX0 & AIDX1 & AIDX2 & AIDX3)
         | (AIDX0 & AIDX1 & AIDX2 & AIDX3);
      r_HSTAGE <=
         (~AIDX0 & ~AIDX1 & ~AIDX2 & ~AIDX3)
         | (AIDX0 & ~AIDX1 & ~AIDX2 & ~AIDX3)
         | (~AIDX0 & AIDX1 & ~AIDX2 & ~AIDX3)
         | (AIDX0 & AIDX1 & ~AIDX2 & ~AIDX3)
         | (~AIDX0 & ~AIDX1 & AIDX2 & ~AIDX3)
         | (AIDX0 & ~AIDX1 & AIDX2 & ~AIDX3)
         | (~AIDX0 & AIDX1 & AIDX2 & ~AIDX3);
      r_HCOMMIT <=
         (~AIDX0 & AIDX1 & ~AIDX2 & ~AIDX3)
         | (~AIDX0 & ~AIDX1 & AIDX2 & ~AIDX3)
         | (~AIDX0 & AIDX1 & AIDX2 & ~AIDX3);
      r_SDQ0 <=
         (SDHCAP & SDH0)
         | (SDQ0 & ~SDHCAP);
      r_SDQ1 <=
         (SDHCAP & SDH1)
         | (SDQ1 & ~SDHCAP);
      r_SDQ2 <=
         (SDHCAP & SDH2)
         | (SDQ2 & ~SDHCAP);
      r_PWBUSY <=
         (HSTB & ~RW)
         | (PWBUSY & ~HACK);
      r_PFVALID <=
         (PFCK)
         | (PFVALID & ~AIDXLD & ~AINC);
      r_WROTE0 <=
         (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3 & ~WC0 & ~WC1)
         | (WROTE0 & ~S2)
         | (WROTE0 & ~S1)
         | (WROTE0 & ~S0);
      r_WROTE1 <=
         (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3 & WC0 & ~WC1)
         | (WROTE1 & ~S2)
         | (WROTE1 & ~S1)
         | (WROTE1 & ~S0);
      r_WROTE2 <=
         (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3 & ~WC0 & WC1)
         | (WROTE2 & ~QCHAN)
         | (WROTE2 & ~S1)
         | (WROTE2 & ~S0);
      r_WROTE3 <=
         (RUN & ~WT0 & ~WT1 & ~WT2 & ~T0 & ~T1 & T2 & ~T3 & WC0 & WC1)
         | (WROTE3 & ~QCHAN)
         | (WROTE3 & ~S1)
         | (WROTE3 & ~S0);
      r_VDIRTY <=
         (RUN & WT2 & ~WT1 & ~WT0 & ~T0 & ~T1 & ~T2 & ~T3 & ~HRW & ~HRO & ~ISAIDX & ~ISSDATA & ~AIDX3 & AIDX2 & AIDX1 & AIDX0)
         | (VDIRTY & ~VACK);
  end

endmodule
`default_nettype wire
