// GENERATED by hardware/gal/verilog/emit.ts from the term lists in
// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module audio (
    input  wire SLOTCLK,
    input  wire RESET,
    input  wire A0,
    input  wire A1,
    input  wire A2,
    input  wire A3,
    input  wire RW,
    input  wire E,
    input  wire SETC,
    input  wire SETB,
    input  wire SETA,
    input  wire PFCK,
    input  wire PFLANE,
    input  wire CNTOE,
    input  wire IOSEL,
    input  wire A6,
    input  wire A5,
    input  wire A4,
    input  wire PWBUSY,
    input  wire PFVALID,
    output wire S0,
    output wire S1,
    output wire S2,
    output wire S3,
    output wire OEB,
    output wire CCLK,
    output wire WDMACON,
    output wire WINTENA,
    output wire WINTREQ,
    output wire WCTRL,
    output wire RINTREQ,
    output wire RASTAT,
    output wire DMAEN0,
    output wire DMAEN1,
    output wire DMAEN2,
    output wire DMAEN3,
    output wire P0,
    output wire P1,
    output wire P2,
    output wire ENA0,
    output wire ENA1,
    output wire ENA2,
    output wire ENA3,
    output wire ENA4,
    output wire ENA5,
    output wire PEND0,
    output wire PEND1,
    output wire PEND2,
    output wire PEND3,
    output wire PEND4,
    output wire PEND5,
    output wire REQ0,
    output wire REQ1,
    output wire REQ2,
    output wire REQ3,
    output wire REQ4,
    output wire REQ5,
    output wire FIRQ,
    output wire CTRL0,
    output wire CTRL1,
    output wire CTRL2,
    output wire CTRL3,
    output wire CTRL4,
    output wire CTRL5,
    output wire CTRL6,
    output wire CTRL7,
    output wire SET0,
    output wire SET1,
    output wire SET2,
    output wire SET3,
    output wire SET4,
    output wire SET5,
    output wire CT0,
    output wire CT1,
    output wire CT2,
    output wire CT3,
    output wire CT4,
    output wire CT5,
    output wire CT6,
    output wire CT7,
    output wire CT8,
    output wire CT9,
    output wire CT10,
    output wire CT11,
    output wire CT12,
    output wire CT13,
    output wire CT14,
    output wire CT15,
    output wire NEQL,
    output wire NEQH,
    output wire TC0,
    output wire TC1,
    output wire TC2,
    output wire TC3,
    output wire TC4,
    output wire TC5,
    output wire TC6,
    output wire TC7,
    output wire TC8,
    output wire TC9,
    output wire TC10,
    output wire TC11,
    output wire TC12,
    output wire TC13,
    output wire TC14,
    output wire TC15,
    output wire TLOAD,
    output wire TFIRE,
    output wire PF0,
    output wire PF1,
    output wire PF2,
    output wire PF3,
    output wire PF4,
    output wire PF5,
    output wire PF6,
    output wire PF7,
    inout  wire SD0,
    inout  wire SD1,
    inout  wire SD2,
    inout  wire SD3,
    inout  wire SD4,
    inout  wire SD5,
    inout  wire SD6,
    inout  wire SD7,
    inout  wire SD8,
    inout  wire SD9,
    inout  wire SD10,
    inout  wire SD11,
    inout  wire SD12,
    inout  wire SD13,
    inout  wire SD14,
    inout  wire SD15,
    output wire SYNCR1,
    output wire SYNCR2,
    output wire MERGE,
    output wire FIRQANY,
    output wire SEL,
    output wire HRD,
    output wire RPF,
    inout  wire D0,
    inout  wire D1,
    inout  wire D2,
    inout  wire D3,
    inout  wire D4,
    inout  wire D5,
    inout  wire D6,
    inout  wire D7,
    output wire FIRQ_OE,
    output wire SD0_OE,
    output wire SD1_OE,
    output wire SD2_OE,
    output wire SD3_OE,
    output wire SD4_OE,
    output wire SD5_OE,
    output wire SD6_OE,
    output wire SD7_OE,
    output wire SD8_OE,
    output wire SD9_OE,
    output wire SD10_OE,
    output wire SD11_OE,
    output wire SD12_OE,
    output wire SD13_OE,
    output wire SD14_OE,
    output wire SD15_OE,
    output wire D0_OE,
    output wire D1_OE,
    output wire D2_OE,
    output wire D3_OE,
    output wire D4_OE,
    output wire D5_OE,
    output wire D6_OE,
    output wire D7_OE
);

  reg  r_S0;
  reg  r_S1;
  reg  r_S2;
  reg  r_S3;
  reg  r_OEB;
  reg  r_DMAEN0;
  reg  r_DMAEN1;
  reg  r_DMAEN2;
  reg  r_DMAEN3;
  reg  r_P0;
  reg  r_P1;
  reg  r_P2;
  reg  r_ENA0;
  reg  r_ENA1;
  reg  r_ENA2;
  reg  r_ENA3;
  reg  r_ENA4;
  reg  r_ENA5;
  reg  r_PEND0;
  reg  r_PEND1;
  reg  r_PEND2;
  reg  r_PEND3;
  reg  r_PEND4;
  reg  r_PEND5;
  reg  r_REQ0;
  reg  r_REQ1;
  reg  r_REQ2;
  reg  r_REQ3;
  reg  r_REQ4;
  reg  r_REQ5;
  reg  r_CTRL0;
  reg  r_CTRL1;
  reg  r_CTRL2;
  reg  r_CTRL3;
  reg  r_CTRL4;
  reg  r_CTRL5;
  reg  r_CTRL6;
  reg  r_CTRL7;
  reg  r_CT0;
  reg  r_CT1;
  reg  r_CT2;
  reg  r_CT3;
  reg  r_CT4;
  reg  r_CT5;
  reg  r_CT6;
  reg  r_CT7;
  reg  r_CT8;
  reg  r_CT9;
  reg  r_CT10;
  reg  r_CT11;
  reg  r_CT12;
  reg  r_CT13;
  reg  r_CT14;
  reg  r_CT15;
  reg  r_TC0;
  reg  r_TC1;
  reg  r_TC2;
  reg  r_TC3;
  reg  r_TC4;
  reg  r_TC5;
  reg  r_TC6;
  reg  r_TC7;
  reg  r_TC8;
  reg  r_TC9;
  reg  r_TC10;
  reg  r_TC11;
  reg  r_TC12;
  reg  r_TC13;
  reg  r_TC14;
  reg  r_TC15;
  reg  r_TLOAD;
  reg  r_TFIRE;
  reg  r_PF0;
  reg  r_PF1;
  reg  r_PF2;
  reg  r_PF3;
  reg  r_PF4;
  reg  r_PF5;
  reg  r_PF6;
  reg  r_PF7;
  reg  r_SYNCR1;
  reg  r_SYNCR2;

  assign S0 = r_S0;
  assign S1 = r_S1;
  assign S2 = r_S2;
  assign S3 = r_S3;
  assign OEB = r_OEB;
  assign DMAEN0 = r_DMAEN0;
  assign DMAEN1 = r_DMAEN1;
  assign DMAEN2 = r_DMAEN2;
  assign DMAEN3 = r_DMAEN3;
  assign P0 = r_P0;
  assign P1 = r_P1;
  assign P2 = r_P2;
  assign ENA0 = r_ENA0;
  assign ENA1 = r_ENA1;
  assign ENA2 = r_ENA2;
  assign ENA3 = r_ENA3;
  assign ENA4 = r_ENA4;
  assign ENA5 = r_ENA5;
  assign PEND0 = r_PEND0;
  assign PEND1 = r_PEND1;
  assign PEND2 = r_PEND2;
  assign PEND3 = r_PEND3;
  assign PEND4 = r_PEND4;
  assign PEND5 = r_PEND5;
  assign REQ0 = r_REQ0;
  assign REQ1 = r_REQ1;
  assign REQ2 = r_REQ2;
  assign REQ3 = r_REQ3;
  assign REQ4 = r_REQ4;
  assign REQ5 = r_REQ5;
  assign CTRL0 = r_CTRL0;
  assign CTRL1 = r_CTRL1;
  assign CTRL2 = r_CTRL2;
  assign CTRL3 = r_CTRL3;
  assign CTRL4 = r_CTRL4;
  assign CTRL5 = r_CTRL5;
  assign CTRL6 = r_CTRL6;
  assign CTRL7 = r_CTRL7;
  assign CT0 = r_CT0;
  assign CT1 = r_CT1;
  assign CT2 = r_CT2;
  assign CT3 = r_CT3;
  assign CT4 = r_CT4;
  assign CT5 = r_CT5;
  assign CT6 = r_CT6;
  assign CT7 = r_CT7;
  assign CT8 = r_CT8;
  assign CT9 = r_CT9;
  assign CT10 = r_CT10;
  assign CT11 = r_CT11;
  assign CT12 = r_CT12;
  assign CT13 = r_CT13;
  assign CT14 = r_CT14;
  assign CT15 = r_CT15;
  assign TC0 = r_TC0;
  assign TC1 = r_TC1;
  assign TC2 = r_TC2;
  assign TC3 = r_TC3;
  assign TC4 = r_TC4;
  assign TC5 = r_TC5;
  assign TC6 = r_TC6;
  assign TC7 = r_TC7;
  assign TC8 = r_TC8;
  assign TC9 = r_TC9;
  assign TC10 = r_TC10;
  assign TC11 = r_TC11;
  assign TC12 = r_TC12;
  assign TC13 = r_TC13;
  assign TC14 = r_TC14;
  assign TC15 = r_TC15;
  assign TLOAD = r_TLOAD;
  assign TFIRE = r_TFIRE;
  assign PF0 = r_PF0;
  assign PF1 = r_PF1;
  assign PF2 = r_PF2;
  assign PF3 = r_PF3;
  assign PF4 = r_PF4;
  assign PF5 = r_PF5;
  assign PF6 = r_PF6;
  assign PF7 = r_PF7;
  assign SYNCR1 = r_SYNCR1;
  assign SYNCR2 = r_SYNCR2;

  // EXTERNAL
  assign CCLK =
         (S2 & S1 & S0);
  // buried
  assign WDMACON =
         (SEL & ~A3 & ~A2 & A1 & ~A0 & ~RW);
  // buried
  assign WINTENA =
         (SEL & ~A3 & ~A2 & A1 & A0 & ~RW);
  // buried
  assign WINTREQ =
         (SEL & ~A3 & A2 & ~A1 & ~A0 & ~RW);
  // buried
  assign WCTRL =
         (SEL & ~A3 & A2 & ~A1 & A0 & ~RW);
  // buried
  assign RINTREQ =
         (SEL & ~A3 & A2 & ~A1 & ~A0 & RW);
  // buried
  assign RASTAT =
         (SEL & A3 & ~A2 & A1 & ~A0 & RW);
  // EXTERNAL
  assign FIRQ =
         1'b0;
  // buried
  assign SET0 =
         (~SETC & ~SETB & ~SETA);
  // buried
  assign SET1 =
         (~SETC & ~SETB & SETA);
  // buried
  assign SET2 =
         (~SETC & SETB & ~SETA);
  // buried
  assign SET3 =
         (~SETC & SETB & SETA);
  // buried
  assign SET4 =
         (SETC & ~SETB & ~SETA)
         | (TFIRE);
  // buried
  assign SET5 =
         (SETC & ~SETB & SETA);
  // EXTERNAL - 4.2: some bit of NEXT[7:0] differs from the count
  assign NEQL =
         (SD0 & ~CT0)
         | (~SD0 & CT0)
         | (SD1 & ~CT1)
         | (~SD1 & CT1)
         | (SD2 & ~CT2)
         | (~SD2 & CT2)
         | (SD3 & ~CT3)
         | (~SD3 & CT3)
         | (SD4 & ~CT4)
         | (~SD4 & CT4)
         | (SD5 & ~CT5)
         | (~SD5 & CT5)
         | (SD6 & ~CT6)
         | (~SD6 & CT6)
         | (SD7 & ~CT7)
         | (~SD7 & CT7);
  // EXTERNAL - 4.2: some bit of NEXT[15:8] differs from the count
  assign NEQH =
         (SD8 & ~CT8)
         | (~SD8 & CT8)
         | (SD9 & ~CT9)
         | (~SD9 & CT9)
         | (SD10 & ~CT10)
         | (~SD10 & CT10)
         | (SD11 & ~CT11)
         | (~SD11 & CT11)
         | (SD12 & ~CT12)
         | (~SD12 & CT12)
         | (SD13 & ~CT13)
         | (~SD13 & CT13)
         | (SD14 & ~CT14)
         | (~SD14 & CT14)
         | (SD15 & ~CT15)
         | (~SD15 & CT15);
  // EXTERNAL, bidirectional
  assign SD0 = ((CNTOE)) ?
         (CT0) : 1'bz;
  // EXTERNAL, bidirectional
  assign SD1 = ((CNTOE)) ?
         (CT1) : 1'bz;
  // EXTERNAL, bidirectional
  assign SD2 = ((CNTOE)) ?
         (CT2) : 1'bz;
  // EXTERNAL, bidirectional
  assign SD3 = ((CNTOE)) ?
         (CT3) : 1'bz;
  // EXTERNAL, bidirectional
  assign SD4 = ((CNTOE)) ?
         (CT4) : 1'bz;
  // EXTERNAL, bidirectional
  assign SD5 = ((CNTOE)) ?
         (CT5) : 1'bz;
  // EXTERNAL, bidirectional
  assign SD6 = ((CNTOE)) ?
         (CT6) : 1'bz;
  // EXTERNAL, bidirectional
  assign SD7 = ((CNTOE)) ?
         (CT7) : 1'bz;
  // EXTERNAL, bidirectional
  assign SD8 = ((CNTOE)) ?
         (CT8) : 1'bz;
  // EXTERNAL, bidirectional
  assign SD9 = ((CNTOE)) ?
         (CT9) : 1'bz;
  // EXTERNAL, bidirectional
  assign SD10 = ((CNTOE)) ?
         (CT10) : 1'bz;
  // EXTERNAL, bidirectional
  assign SD11 = ((CNTOE)) ?
         (CT11) : 1'bz;
  // EXTERNAL, bidirectional
  assign SD12 = ((CNTOE)) ?
         (CT12) : 1'bz;
  // EXTERNAL, bidirectional
  assign SD13 = ((CNTOE)) ?
         (CT13) : 1'bz;
  // EXTERNAL, bidirectional
  assign SD14 = ((CNTOE)) ?
         (CT14) : 1'bz;
  // EXTERNAL, bidirectional
  assign SD15 = ((CNTOE)) ?
         (CT15) : 1'bz;
  // buried - 9.4.5: every colour clock EXCEPT while a host read is in flight
  assign MERGE =
         (CCLK & ~SYNCR2 & ~SYNCR1);
  // buried
  assign FIRQANY =
         (REQ0 & ENA0)
         | (REQ1 & ENA1)
         | (REQ2 & ENA2)
         | (REQ3 & ENA3)
         | (REQ4 & ENA4)
         | (REQ5 & ENA5);
  // EXTERNAL - 9.1: $FF40-$FF4F out of the 128-byte geographic window - SEVEN bits
  assign SEL =
         (IOSEL & A6 & ~A5 & ~A4);
  // buried - a host read this part answers: AINTREQ, ASTAT or ADATA/SDATA, inside E
  assign HRD =
         (RINTREQ & E)
         | (RASTAT & E)
         | (RPF & E);
  // buried
  assign RPF =
         (SEL & RW & ~A3 & ~A2 & ~A1 & A0)
         | (SEL & RW & A3 & ~A2 & ~A1 & A0);
  // EXTERNAL, bidirectional
  assign D0 = ((HRD)) ?
         (RINTREQ & REQ0)
         | (RASTAT & DMAEN0)
         | (RPF & PF0) : 1'bz;
  // EXTERNAL, bidirectional
  assign D1 = ((HRD)) ?
         (RINTREQ & REQ1)
         | (RASTAT & DMAEN1)
         | (RPF & PF1) : 1'bz;
  // EXTERNAL, bidirectional
  assign D2 = ((HRD)) ?
         (RINTREQ & REQ2)
         | (RASTAT & DMAEN2)
         | (RPF & PF2) : 1'bz;
  // EXTERNAL, bidirectional
  assign D3 = ((HRD)) ?
         (RINTREQ & REQ3)
         | (RASTAT & DMAEN3)
         | (RPF & PF3) : 1'bz;
  // EXTERNAL, bidirectional
  assign D4 = ((HRD)) ?
         (RINTREQ & REQ4)
         | (RASTAT & CTRL6)
         | (RPF & PF4) : 1'bz;
  // EXTERNAL, bidirectional
  assign D5 = ((HRD)) ?
         (RINTREQ & REQ5)
         | (RPF & PF5) : 1'bz;
  // EXTERNAL, bidirectional
  assign D6 = ((HRD)) ?
         (RASTAT & PWBUSY)
         | (RPF & PF6) : 1'bz;
  // EXTERNAL, bidirectional
  assign D7 = ((HRD)) ?
         (RASTAT & PFVALID)
         | (RPF & PF7) : 1'bz;

  // FIRQ is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FIRQ_OE =
         (FIRQANY);
  // SD0 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD0_OE =
         (CNTOE);
  // SD1 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD1_OE =
         (CNTOE);
  // SD2 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD2_OE =
         (CNTOE);
  // SD3 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD3_OE =
         (CNTOE);
  // SD4 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD4_OE =
         (CNTOE);
  // SD5 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD5_OE =
         (CNTOE);
  // SD6 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD6_OE =
         (CNTOE);
  // SD7 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD7_OE =
         (CNTOE);
  // SD8 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD8_OE =
         (CNTOE);
  // SD9 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD9_OE =
         (CNTOE);
  // SD10 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD10_OE =
         (CNTOE);
  // SD11 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD11_OE =
         (CNTOE);
  // SD12 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD12_OE =
         (CNTOE);
  // SD13 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD13_OE =
         (CNTOE);
  // SD14 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD14_OE =
         (CNTOE);
  // SD15 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD15_OE =
         (CNTOE);
  // D0 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign D0_OE =
         (HRD);
  // D1 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign D1_OE =
         (HRD);
  // D2 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign D2_OE =
         (HRD);
  // D3 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign D3_OE =
         (HRD);
  // D4 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign D4_OE =
         (HRD);
  // D5 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign D5_OE =
         (HRD);
  // D6 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign D6_OE =
         (HRD);
  // D7 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign D7_OE =
         (HRD);

  wire AR_ = (RESET);
  always @(posedge SLOTCLK or posedge AR_) begin
    if (AR_) begin
      r_S0 <= 1'b0;
      r_S1 <= 1'b0;
      r_S2 <= 1'b0;
      r_S3 <= 1'b0;
      r_OEB <= 1'b0;
      r_DMAEN0 <= 1'b0;
      r_DMAEN1 <= 1'b0;
      r_DMAEN2 <= 1'b0;
      r_DMAEN3 <= 1'b0;
      r_P0 <= 1'b0;
      r_P1 <= 1'b0;
      r_P2 <= 1'b0;
      r_ENA0 <= 1'b0;
      r_ENA1 <= 1'b0;
      r_ENA2 <= 1'b0;
      r_ENA3 <= 1'b0;
      r_ENA4 <= 1'b0;
      r_ENA5 <= 1'b0;
      r_PEND0 <= 1'b0;
      r_PEND1 <= 1'b0;
      r_PEND2 <= 1'b0;
      r_PEND3 <= 1'b0;
      r_PEND4 <= 1'b0;
      r_PEND5 <= 1'b0;
      r_REQ0 <= 1'b0;
      r_REQ1 <= 1'b0;
      r_REQ2 <= 1'b0;
      r_REQ3 <= 1'b0;
      r_REQ4 <= 1'b0;
      r_REQ5 <= 1'b0;
      r_CTRL0 <= 1'b0;
      r_CTRL1 <= 1'b0;
      r_CTRL2 <= 1'b0;
      r_CTRL3 <= 1'b0;
      r_CTRL4 <= 1'b0;
      r_CTRL5 <= 1'b0;
      r_CTRL6 <= 1'b0;
      r_CTRL7 <= 1'b0;
      r_CT0 <= 1'b0;
      r_CT1 <= 1'b0;
      r_CT2 <= 1'b0;
      r_CT3 <= 1'b0;
      r_CT4 <= 1'b0;
      r_CT5 <= 1'b0;
      r_CT6 <= 1'b0;
      r_CT7 <= 1'b0;
      r_CT8 <= 1'b0;
      r_CT9 <= 1'b0;
      r_CT10 <= 1'b0;
      r_CT11 <= 1'b0;
      r_CT12 <= 1'b0;
      r_CT13 <= 1'b0;
      r_CT14 <= 1'b0;
      r_CT15 <= 1'b0;
      r_TC0 <= 1'b0;
      r_TC1 <= 1'b0;
      r_TC2 <= 1'b0;
      r_TC3 <= 1'b0;
      r_TC4 <= 1'b0;
      r_TC5 <= 1'b0;
      r_TC6 <= 1'b0;
      r_TC7 <= 1'b0;
      r_TC8 <= 1'b0;
      r_TC9 <= 1'b0;
      r_TC10 <= 1'b0;
      r_TC11 <= 1'b0;
      r_TC12 <= 1'b0;
      r_TC13 <= 1'b0;
      r_TC14 <= 1'b0;
      r_TC15 <= 1'b0;
      r_TLOAD <= 1'b0;
      r_TFIRE <= 1'b0;
      r_PF0 <= 1'b0;
      r_PF1 <= 1'b0;
      r_PF2 <= 1'b0;
      r_PF3 <= 1'b0;
      r_PF4 <= 1'b0;
      r_PF5 <= 1'b0;
      r_PF6 <= 1'b0;
      r_PF7 <= 1'b0;
      r_SYNCR1 <= 1'b0;
      r_SYNCR2 <= 1'b0;
    end else begin
      r_S0 <=
         (~S0);
      r_S1 <=
         (S1 & ~S0)
         | (~S1 & S0);
      r_S2 <=
         (S2 & ~S0)
         | (S2 & ~S1)
         | (~S2 & S0 & S1);
      r_S3 <=
         (S3 & ~S0)
         | (S3 & ~S1)
         | (S3 & ~S2)
         | (~S3 & S0 & S1 & S2);
      r_OEB <=
         (S3 & ~S0)
         | (S3 & ~S1)
         | (S3 & ~S2)
         | (~S3 & S0 & S1 & S2);
      r_DMAEN0 <=
         (WDMACON & D7 & D0)
         | (DMAEN0 & ~WDMACON)
         | (DMAEN0 & D7)
         | (DMAEN0 & ~D0);
      r_DMAEN1 <=
         (WDMACON & D7 & D1)
         | (DMAEN1 & ~WDMACON)
         | (DMAEN1 & D7)
         | (DMAEN1 & ~D1);
      r_DMAEN2 <=
         (WDMACON & D7 & D2)
         | (DMAEN2 & ~WDMACON)
         | (DMAEN2 & D7)
         | (DMAEN2 & ~D2);
      r_DMAEN3 <=
         (WDMACON & D7 & D3)
         | (DMAEN3 & ~WDMACON)
         | (DMAEN3 & D7)
         | (DMAEN3 & ~D3);
      r_P0 <=
         (CCLK & ~P2 & ~P0)
         | (~CCLK & P0);
      r_P1 <=
         (CCLK & ~P2 & P1 & ~P0)
         | (CCLK & ~P2 & ~P1 & P0)
         | (~CCLK & P1);
      r_P2 <=
         (CCLK & ~P2 & P0 & P1)
         | (~CCLK & P2);
      r_ENA0 <=
         (WINTENA & D7 & D0)
         | (ENA0 & ~WINTENA)
         | (ENA0 & D7)
         | (ENA0 & ~D0);
      r_ENA1 <=
         (WINTENA & D7 & D1)
         | (ENA1 & ~WINTENA)
         | (ENA1 & D7)
         | (ENA1 & ~D1);
      r_ENA2 <=
         (WINTENA & D7 & D2)
         | (ENA2 & ~WINTENA)
         | (ENA2 & D7)
         | (ENA2 & ~D2);
      r_ENA3 <=
         (WINTENA & D7 & D3)
         | (ENA3 & ~WINTENA)
         | (ENA3 & D7)
         | (ENA3 & ~D3);
      r_ENA4 <=
         (WINTENA & D7 & D4)
         | (ENA4 & ~WINTENA)
         | (ENA4 & D7)
         | (ENA4 & ~D4);
      r_ENA5 <=
         (WINTENA & D7 & D5)
         | (ENA5 & ~WINTENA)
         | (ENA5 & D7)
         | (ENA5 & ~D5);
      r_PEND0 <=
         (SET0)
         | (PEND0 & ~MERGE);
      r_PEND1 <=
         (SET1)
         | (PEND1 & ~MERGE);
      r_PEND2 <=
         (SET2)
         | (PEND2 & ~MERGE);
      r_PEND3 <=
         (SET3)
         | (PEND3 & ~MERGE);
      r_PEND4 <=
         (SET4)
         | (PEND4 & ~MERGE);
      r_PEND5 <=
         (SET5)
         | (PEND5 & ~MERGE);
      r_REQ0 <=
         (WINTREQ & D7 & D0)
         | (PEND0 & MERGE)
         | (REQ0 & ~WINTREQ)
         | (REQ0 & D7)
         | (REQ0 & ~D0);
      r_REQ1 <=
         (WINTREQ & D7 & D1)
         | (PEND1 & MERGE)
         | (REQ1 & ~WINTREQ)
         | (REQ1 & D7)
         | (REQ1 & ~D1);
      r_REQ2 <=
         (WINTREQ & D7 & D2)
         | (PEND2 & MERGE)
         | (REQ2 & ~WINTREQ)
         | (REQ2 & D7)
         | (REQ2 & ~D2);
      r_REQ3 <=
         (WINTREQ & D7 & D3)
         | (PEND3 & MERGE)
         | (REQ3 & ~WINTREQ)
         | (REQ3 & D7)
         | (REQ3 & ~D3);
      r_REQ4 <=
         (WINTREQ & D7 & D4)
         | (PEND4 & MERGE)
         | (REQ4 & ~WINTREQ)
         | (REQ4 & D7)
         | (REQ4 & ~D4);
      r_REQ5 <=
         (WINTREQ & D7 & D5)
         | (PEND5 & MERGE)
         | (REQ5 & ~WINTREQ)
         | (REQ5 & D7)
         | (REQ5 & ~D5);
      r_CTRL0 <=
         (WCTRL & D0)
         | (CTRL0 & ~WCTRL);
      r_CTRL1 <=
         (WCTRL & D1)
         | (CTRL1 & ~WCTRL);
      r_CTRL2 <=
         (WCTRL & D2)
         | (CTRL2 & ~WCTRL);
      r_CTRL3 <=
         (WCTRL & D3)
         | (CTRL3 & ~WCTRL);
      r_CTRL4 <=
         (WCTRL & D4)
         | (CTRL4 & ~WCTRL);
      r_CTRL5 <=
         (WCTRL & D5)
         | (CTRL5 & ~WCTRL);
      r_CTRL6 <=
         (WCTRL & D6)
         | (CTRL6 & ~WCTRL);
      r_CTRL7 <=
         (WCTRL & D7)
         | (CTRL7 & ~WCTRL);
      r_CT0 <=
         (CCLK & ~CT0)
         | (~CCLK & CT0);
      r_CT1 <=
         (CCLK & CT1 & ~CT0)
         | (CCLK & ~CT1 & CT0)
         | (~CCLK & CT1);
      r_CT2 <=
         (CCLK & CT2 & ~CT0)
         | (CCLK & CT2 & ~CT1)
         | (CCLK & ~CT2 & CT0 & CT1)
         | (~CCLK & CT2);
      r_CT3 <=
         (CCLK & CT3 & ~CT0)
         | (CCLK & CT3 & ~CT1)
         | (CCLK & CT3 & ~CT2)
         | (CCLK & ~CT3 & CT0 & CT1 & CT2)
         | (~CCLK & CT3);
      r_CT4 <=
         (CCLK & CT4 & ~CT0)
         | (CCLK & CT4 & ~CT1)
         | (CCLK & CT4 & ~CT2)
         | (CCLK & CT4 & ~CT3)
         | (CCLK & ~CT4 & CT0 & CT1 & CT2 & CT3)
         | (~CCLK & CT4);
      r_CT5 <=
         (CCLK & CT5 & ~CT0)
         | (CCLK & CT5 & ~CT1)
         | (CCLK & CT5 & ~CT2)
         | (CCLK & CT5 & ~CT3)
         | (CCLK & CT5 & ~CT4)
         | (CCLK & ~CT5 & CT0 & CT1 & CT2 & CT3 & CT4)
         | (~CCLK & CT5);
      r_CT6 <=
         (CCLK & CT6 & ~CT0)
         | (CCLK & CT6 & ~CT1)
         | (CCLK & CT6 & ~CT2)
         | (CCLK & CT6 & ~CT3)
         | (CCLK & CT6 & ~CT4)
         | (CCLK & CT6 & ~CT5)
         | (CCLK & ~CT6 & CT0 & CT1 & CT2 & CT3 & CT4 & CT5)
         | (~CCLK & CT6);
      r_CT7 <=
         (CCLK & CT7 & ~CT0)
         | (CCLK & CT7 & ~CT1)
         | (CCLK & CT7 & ~CT2)
         | (CCLK & CT7 & ~CT3)
         | (CCLK & CT7 & ~CT4)
         | (CCLK & CT7 & ~CT5)
         | (CCLK & CT7 & ~CT6)
         | (CCLK & ~CT7 & CT0 & CT1 & CT2 & CT3 & CT4 & CT5 & CT6)
         | (~CCLK & CT7);
      r_CT8 <=
         (CCLK & CT8 & ~CT0)
         | (CCLK & CT8 & ~CT1)
         | (CCLK & CT8 & ~CT2)
         | (CCLK & CT8 & ~CT3)
         | (CCLK & CT8 & ~CT4)
         | (CCLK & CT8 & ~CT5)
         | (CCLK & CT8 & ~CT6)
         | (CCLK & CT8 & ~CT7)
         | (CCLK & ~CT8 & CT0 & CT1 & CT2 & CT3 & CT4 & CT5 & CT6 & CT7)
         | (~CCLK & CT8);
      r_CT9 <=
         (CCLK & CT9 & ~CT0)
         | (CCLK & CT9 & ~CT1)
         | (CCLK & CT9 & ~CT2)
         | (CCLK & CT9 & ~CT3)
         | (CCLK & CT9 & ~CT4)
         | (CCLK & CT9 & ~CT5)
         | (CCLK & CT9 & ~CT6)
         | (CCLK & CT9 & ~CT7)
         | (CCLK & CT9 & ~CT8)
         | (CCLK & ~CT9 & CT0 & CT1 & CT2 & CT3 & CT4 & CT5 & CT6 & CT7 & CT8)
         | (~CCLK & CT9);
      r_CT10 <=
         (CCLK & CT10 & ~CT0)
         | (CCLK & CT10 & ~CT1)
         | (CCLK & CT10 & ~CT2)
         | (CCLK & CT10 & ~CT3)
         | (CCLK & CT10 & ~CT4)
         | (CCLK & CT10 & ~CT5)
         | (CCLK & CT10 & ~CT6)
         | (CCLK & CT10 & ~CT7)
         | (CCLK & CT10 & ~CT8)
         | (CCLK & CT10 & ~CT9)
         | (CCLK & ~CT10 & CT0 & CT1 & CT2 & CT3 & CT4 & CT5 & CT6 & CT7 & CT8 & CT9)
         | (~CCLK & CT10);
      r_CT11 <=
         (CCLK & CT11 & ~CT0)
         | (CCLK & CT11 & ~CT1)
         | (CCLK & CT11 & ~CT2)
         | (CCLK & CT11 & ~CT3)
         | (CCLK & CT11 & ~CT4)
         | (CCLK & CT11 & ~CT5)
         | (CCLK & CT11 & ~CT6)
         | (CCLK & CT11 & ~CT7)
         | (CCLK & CT11 & ~CT8)
         | (CCLK & CT11 & ~CT9)
         | (CCLK & CT11 & ~CT10)
         | (CCLK & ~CT11 & CT0 & CT1 & CT2 & CT3 & CT4 & CT5 & CT6 & CT7 & CT8 & CT9 & CT10)
         | (~CCLK & CT11);
      r_CT12 <=
         (CCLK & CT12 & ~CT0)
         | (CCLK & CT12 & ~CT1)
         | (CCLK & CT12 & ~CT2)
         | (CCLK & CT12 & ~CT3)
         | (CCLK & CT12 & ~CT4)
         | (CCLK & CT12 & ~CT5)
         | (CCLK & CT12 & ~CT6)
         | (CCLK & CT12 & ~CT7)
         | (CCLK & CT12 & ~CT8)
         | (CCLK & CT12 & ~CT9)
         | (CCLK & CT12 & ~CT10)
         | (CCLK & CT12 & ~CT11)
         | (CCLK & ~CT12 & CT0 & CT1 & CT2 & CT3 & CT4 & CT5 & CT6 & CT7 & CT8 & CT9 & CT10 & CT11)
         | (~CCLK & CT12);
      r_CT13 <=
         (CCLK & CT13 & ~CT0)
         | (CCLK & CT13 & ~CT1)
         | (CCLK & CT13 & ~CT2)
         | (CCLK & CT13 & ~CT3)
         | (CCLK & CT13 & ~CT4)
         | (CCLK & CT13 & ~CT5)
         | (CCLK & CT13 & ~CT6)
         | (CCLK & CT13 & ~CT7)
         | (CCLK & CT13 & ~CT8)
         | (CCLK & CT13 & ~CT9)
         | (CCLK & CT13 & ~CT10)
         | (CCLK & CT13 & ~CT11)
         | (CCLK & CT13 & ~CT12)
         | (CCLK & ~CT13 & CT0 & CT1 & CT2 & CT3 & CT4 & CT5 & CT6 & CT7 & CT8 & CT9 & CT10 & CT11 & CT12)
         | (~CCLK & CT13);
      r_CT14 <=
         (CCLK & CT14 & ~CT0)
         | (CCLK & CT14 & ~CT1)
         | (CCLK & CT14 & ~CT2)
         | (CCLK & CT14 & ~CT3)
         | (CCLK & CT14 & ~CT4)
         | (CCLK & CT14 & ~CT5)
         | (CCLK & CT14 & ~CT6)
         | (CCLK & CT14 & ~CT7)
         | (CCLK & CT14 & ~CT8)
         | (CCLK & CT14 & ~CT9)
         | (CCLK & CT14 & ~CT10)
         | (CCLK & CT14 & ~CT11)
         | (CCLK & CT14 & ~CT12)
         | (CCLK & CT14 & ~CT13)
         | (CCLK & ~CT14 & CT0 & CT1 & CT2 & CT3 & CT4 & CT5 & CT6 & CT7 & CT8 & CT9 & CT10 & CT11 & CT12 & CT13)
         | (~CCLK & CT14);
      r_CT15 <=
         (CCLK & CT15 & ~CT0)
         | (CCLK & CT15 & ~CT1)
         | (CCLK & CT15 & ~CT2)
         | (CCLK & CT15 & ~CT3)
         | (CCLK & CT15 & ~CT4)
         | (CCLK & CT15 & ~CT5)
         | (CCLK & CT15 & ~CT6)
         | (CCLK & CT15 & ~CT7)
         | (CCLK & CT15 & ~CT8)
         | (CCLK & CT15 & ~CT9)
         | (CCLK & CT15 & ~CT10)
         | (CCLK & CT15 & ~CT11)
         | (CCLK & CT15 & ~CT12)
         | (CCLK & CT15 & ~CT13)
         | (CCLK & CT15 & ~CT14)
         | (CCLK & ~CT15 & CT0 & CT1 & CT2 & CT3 & CT4 & CT5 & CT6 & CT7 & CT8 & CT9 & CT10 & CT11 & CT12 & CT13 & CT14)
         | (~CCLK & CT15);
      r_TC0 <=
         (TLOAD & ~SD0)
         | (~TLOAD & CCLK & P2 & CTRL6 & ~TC0)
         | (~TLOAD & ~CCLK & TC0)
         | (~TLOAD & ~P2 & TC0)
         | (~TLOAD & ~CTRL6 & TC0);
      r_TC1 <=
         (TLOAD & ~SD1)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC1 & ~TC0)
         | (~TLOAD & CCLK & P2 & CTRL6 & ~TC1 & TC0)
         | (~TLOAD & ~CCLK & TC1)
         | (~TLOAD & ~P2 & TC1)
         | (~TLOAD & ~CTRL6 & TC1);
      r_TC2 <=
         (TLOAD & ~SD2)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC2 & ~TC0)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC2 & ~TC1)
         | (~TLOAD & CCLK & P2 & CTRL6 & ~TC2 & TC0 & TC1)
         | (~TLOAD & ~CCLK & TC2)
         | (~TLOAD & ~P2 & TC2)
         | (~TLOAD & ~CTRL6 & TC2);
      r_TC3 <=
         (TLOAD & ~SD3)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC3 & ~TC0)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC3 & ~TC1)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC3 & ~TC2)
         | (~TLOAD & CCLK & P2 & CTRL6 & ~TC3 & TC0 & TC1 & TC2)
         | (~TLOAD & ~CCLK & TC3)
         | (~TLOAD & ~P2 & TC3)
         | (~TLOAD & ~CTRL6 & TC3);
      r_TC4 <=
         (TLOAD & ~SD4)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC4 & ~TC0)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC4 & ~TC1)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC4 & ~TC2)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC4 & ~TC3)
         | (~TLOAD & CCLK & P2 & CTRL6 & ~TC4 & TC0 & TC1 & TC2 & TC3)
         | (~TLOAD & ~CCLK & TC4)
         | (~TLOAD & ~P2 & TC4)
         | (~TLOAD & ~CTRL6 & TC4);
      r_TC5 <=
         (TLOAD & ~SD5)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC5 & ~TC0)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC5 & ~TC1)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC5 & ~TC2)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC5 & ~TC3)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC5 & ~TC4)
         | (~TLOAD & CCLK & P2 & CTRL6 & ~TC5 & TC0 & TC1 & TC2 & TC3 & TC4)
         | (~TLOAD & ~CCLK & TC5)
         | (~TLOAD & ~P2 & TC5)
         | (~TLOAD & ~CTRL6 & TC5);
      r_TC6 <=
         (TLOAD & ~SD6)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC6 & ~TC0)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC6 & ~TC1)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC6 & ~TC2)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC6 & ~TC3)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC6 & ~TC4)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC6 & ~TC5)
         | (~TLOAD & CCLK & P2 & CTRL6 & ~TC6 & TC0 & TC1 & TC2 & TC3 & TC4 & TC5)
         | (~TLOAD & ~CCLK & TC6)
         | (~TLOAD & ~P2 & TC6)
         | (~TLOAD & ~CTRL6 & TC6);
      r_TC7 <=
         (TLOAD & ~SD7)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC7 & ~TC0)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC7 & ~TC1)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC7 & ~TC2)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC7 & ~TC3)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC7 & ~TC4)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC7 & ~TC5)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC7 & ~TC6)
         | (~TLOAD & CCLK & P2 & CTRL6 & ~TC7 & TC0 & TC1 & TC2 & TC3 & TC4 & TC5 & TC6)
         | (~TLOAD & ~CCLK & TC7)
         | (~TLOAD & ~P2 & TC7)
         | (~TLOAD & ~CTRL6 & TC7);
      r_TC8 <=
         (TLOAD & ~SD8)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC8 & ~TC0)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC8 & ~TC1)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC8 & ~TC2)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC8 & ~TC3)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC8 & ~TC4)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC8 & ~TC5)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC8 & ~TC6)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC8 & ~TC7)
         | (~TLOAD & CCLK & P2 & CTRL6 & ~TC8 & TC0 & TC1 & TC2 & TC3 & TC4 & TC5 & TC6 & TC7)
         | (~TLOAD & ~CCLK & TC8)
         | (~TLOAD & ~P2 & TC8)
         | (~TLOAD & ~CTRL6 & TC8);
      r_TC9 <=
         (TLOAD & ~SD9)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC9 & ~TC0)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC9 & ~TC1)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC9 & ~TC2)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC9 & ~TC3)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC9 & ~TC4)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC9 & ~TC5)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC9 & ~TC6)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC9 & ~TC7)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC9 & ~TC8)
         | (~TLOAD & CCLK & P2 & CTRL6 & ~TC9 & TC0 & TC1 & TC2 & TC3 & TC4 & TC5 & TC6 & TC7 & TC8)
         | (~TLOAD & ~CCLK & TC9)
         | (~TLOAD & ~P2 & TC9)
         | (~TLOAD & ~CTRL6 & TC9);
      r_TC10 <=
         (TLOAD & ~SD10)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC10 & ~TC0)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC10 & ~TC1)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC10 & ~TC2)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC10 & ~TC3)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC10 & ~TC4)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC10 & ~TC5)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC10 & ~TC6)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC10 & ~TC7)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC10 & ~TC8)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC10 & ~TC9)
         | (~TLOAD & CCLK & P2 & CTRL6 & ~TC10 & TC0 & TC1 & TC2 & TC3 & TC4 & TC5 & TC6 & TC7 & TC8 & TC9)
         | (~TLOAD & ~CCLK & TC10)
         | (~TLOAD & ~P2 & TC10)
         | (~TLOAD & ~CTRL6 & TC10);
      r_TC11 <=
         (TLOAD & ~SD11)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC11 & ~TC0)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC11 & ~TC1)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC11 & ~TC2)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC11 & ~TC3)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC11 & ~TC4)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC11 & ~TC5)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC11 & ~TC6)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC11 & ~TC7)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC11 & ~TC8)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC11 & ~TC9)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC11 & ~TC10)
         | (~TLOAD & CCLK & P2 & CTRL6 & ~TC11 & TC0 & TC1 & TC2 & TC3 & TC4 & TC5 & TC6 & TC7 & TC8 & TC9 & TC10)
         | (~TLOAD & ~CCLK & TC11)
         | (~TLOAD & ~P2 & TC11)
         | (~TLOAD & ~CTRL6 & TC11);
      r_TC12 <=
         (TLOAD & ~SD12)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC12 & ~TC0)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC12 & ~TC1)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC12 & ~TC2)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC12 & ~TC3)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC12 & ~TC4)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC12 & ~TC5)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC12 & ~TC6)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC12 & ~TC7)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC12 & ~TC8)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC12 & ~TC9)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC12 & ~TC10)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC12 & ~TC11)
         | (~TLOAD & CCLK & P2 & CTRL6 & ~TC12 & TC0 & TC1 & TC2 & TC3 & TC4 & TC5 & TC6 & TC7 & TC8 & TC9 & TC10 & TC11)
         | (~TLOAD & ~CCLK & TC12)
         | (~TLOAD & ~P2 & TC12)
         | (~TLOAD & ~CTRL6 & TC12);
      r_TC13 <=
         (TLOAD & ~SD13)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC13 & ~TC0)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC13 & ~TC1)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC13 & ~TC2)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC13 & ~TC3)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC13 & ~TC4)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC13 & ~TC5)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC13 & ~TC6)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC13 & ~TC7)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC13 & ~TC8)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC13 & ~TC9)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC13 & ~TC10)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC13 & ~TC11)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC13 & ~TC12)
         | (~TLOAD & CCLK & P2 & CTRL6 & ~TC13 & TC0 & TC1 & TC2 & TC3 & TC4 & TC5 & TC6 & TC7 & TC8 & TC9 & TC10 & TC11 & TC12)
         | (~TLOAD & ~CCLK & TC13)
         | (~TLOAD & ~P2 & TC13)
         | (~TLOAD & ~CTRL6 & TC13);
      r_TC14 <=
         (TLOAD & ~SD14)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC14 & ~TC0)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC14 & ~TC1)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC14 & ~TC2)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC14 & ~TC3)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC14 & ~TC4)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC14 & ~TC5)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC14 & ~TC6)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC14 & ~TC7)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC14 & ~TC8)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC14 & ~TC9)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC14 & ~TC10)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC14 & ~TC11)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC14 & ~TC12)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC14 & ~TC13)
         | (~TLOAD & CCLK & P2 & CTRL6 & ~TC14 & TC0 & TC1 & TC2 & TC3 & TC4 & TC5 & TC6 & TC7 & TC8 & TC9 & TC10 & TC11 & TC12 & TC13)
         | (~TLOAD & ~CCLK & TC14)
         | (~TLOAD & ~P2 & TC14)
         | (~TLOAD & ~CTRL6 & TC14);
      r_TC15 <=
         (TLOAD & ~SD15)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC15 & ~TC0)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC15 & ~TC1)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC15 & ~TC2)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC15 & ~TC3)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC15 & ~TC4)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC15 & ~TC5)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC15 & ~TC6)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC15 & ~TC7)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC15 & ~TC8)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC15 & ~TC9)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC15 & ~TC10)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC15 & ~TC11)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC15 & ~TC12)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC15 & ~TC13)
         | (~TLOAD & CCLK & P2 & CTRL6 & TC15 & ~TC14)
         | (~TLOAD & CCLK & P2 & CTRL6 & ~TC15 & TC0 & TC1 & TC2 & TC3 & TC4 & TC5 & TC6 & TC7 & TC8 & TC9 & TC10 & TC11 & TC12 & TC13 & TC14)
         | (~TLOAD & ~CCLK & TC15)
         | (~TLOAD & ~P2 & TC15)
         | (~TLOAD & ~CTRL6 & TC15);
      r_TLOAD <=
         (~S2 & S1 & S0 & ~CTRL6)
         | (~S2 & S1 & S0 & TC0 & TC1 & TC2 & TC3 & TC4 & TC5 & TC6 & TC7 & TC8 & TC9 & TC10 & TC11 & TC12 & TC13 & TC14 & TC15);
      r_TFIRE <=
         (~S2 & S1 & S0 & CTRL6 & TC0 & TC1 & TC2 & TC3 & TC4 & TC5 & TC6 & TC7 & TC8 & TC9 & TC10 & TC11 & TC12 & TC13 & TC14 & TC15);
      r_PF0 <=
         (PFCK & ~PFLANE & SD0)
         | (PFCK & PFLANE & SD8)
         | (PF0 & ~PFCK);
      r_PF1 <=
         (PFCK & ~PFLANE & SD1)
         | (PFCK & PFLANE & SD9)
         | (PF1 & ~PFCK);
      r_PF2 <=
         (PFCK & ~PFLANE & SD2)
         | (PFCK & PFLANE & SD10)
         | (PF2 & ~PFCK);
      r_PF3 <=
         (PFCK & ~PFLANE & SD3)
         | (PFCK & PFLANE & SD11)
         | (PF3 & ~PFCK);
      r_PF4 <=
         (PFCK & ~PFLANE & SD4)
         | (PFCK & PFLANE & SD12)
         | (PF4 & ~PFCK);
      r_PF5 <=
         (PFCK & ~PFLANE & SD5)
         | (PFCK & PFLANE & SD13)
         | (PF5 & ~PFCK);
      r_PF6 <=
         (PFCK & ~PFLANE & SD6)
         | (PFCK & PFLANE & SD14)
         | (PF6 & ~PFCK);
      r_PF7 <=
         (PFCK & ~PFLANE & SD7)
         | (PFCK & PFLANE & SD15)
         | (PF7 & ~PFCK);
      r_SYNCR1 <=
         (RINTREQ);
      r_SYNCR2 <=
         (SYNCR1);
    end
  end

endmodule
`default_nettype wire
