// GENERATED by hardware/gal/verilog/emit.ts from the term lists in
// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module audio (
    input  wire SLOTCLK,
    input  wire RESET,
    input  wire SEL,
    input  wire A0,
    input  wire A1,
    input  wire A2,
    input  wire A3,
    input  wire RW,
    input  wire E,
    input  wire D0,
    input  wire D1,
    input  wire D2,
    input  wire D3,
    input  wire D7,
    input  wire D4,
    input  wire D5,
    input  wire SET0,
    input  wire SET1,
    input  wire SET2,
    input  wire SET3,
    input  wire SET4,
    input  wire SET5,
    input  wire D6,
    output wire S0,
    output wire S1,
    output wire S2,
    output wire CCLK,
    output wire CHANSLOT,
    output wire TMRSLOT,
    output wire HOSTSLOT,
    output wire DEFSLOT,
    output wire DEFREQ,
    output wire DEFACK,
    output wire WAIDX,
    output wire WDMACON,
    output wire WINTENA,
    output wire WINTREQ,
    output wire WCTRL,
    output wire RINTREQ,
    output wire RASTAT,
    output wire SFCE,
    output wire SRCE,
    output wire HOSTREQ,
    output wire DMAEN0,
    output wire DMAEN1,
    output wire DMAEN2,
    output wire DMAEN3,
    output wire P0,
    output wire P1,
    output wire P2,
    output wire CIACLK,
    output wire ENA0,
    output wire ENA1,
    output wire ENA2,
    output wire ENA3,
    output wire ENA4,
    output wire ENA5,
    output wire PEND0,
    output wire PEND1,
    output wire PEND2,
    output wire PEND3,
    output wire PEND4,
    output wire PEND5,
    output wire REQ0,
    output wire REQ1,
    output wire REQ2,
    output wire REQ3,
    output wire REQ4,
    output wire REQ5,
    output wire FIRQ,
    output wire CTRL0,
    output wire CTRL1,
    output wire CTRL2,
    output wire CTRL3,
    output wire CTRL4,
    output wire CTRL5,
    output wire CTRL6,
    output wire CTRL7,
    output wire SYNCH1,
    output wire SYNCH2,
    output wire SYNCR1,
    output wire SYNCR2,
    output wire SYNCS1,
    output wire SYNCS2,
    output wire MERGE,
    output wire FIRQANY,
    output wire NEWREQ,
    output wire FIRQ_OE
);

  reg  r_S0;
  reg  r_S1;
  reg  r_S2;
  reg  r_DEFREQ;
  reg  r_DMAEN0;
  reg  r_DMAEN1;
  reg  r_DMAEN2;
  reg  r_DMAEN3;
  reg  r_P0;
  reg  r_P1;
  reg  r_P2;
  reg  r_ENA0;
  reg  r_ENA1;
  reg  r_ENA2;
  reg  r_ENA3;
  reg  r_ENA4;
  reg  r_ENA5;
  reg  r_PEND0;
  reg  r_PEND1;
  reg  r_PEND2;
  reg  r_PEND3;
  reg  r_PEND4;
  reg  r_PEND5;
  reg  r_REQ0;
  reg  r_REQ1;
  reg  r_REQ2;
  reg  r_REQ3;
  reg  r_REQ4;
  reg  r_REQ5;
  reg  r_CTRL0;
  reg  r_CTRL1;
  reg  r_CTRL2;
  reg  r_CTRL3;
  reg  r_CTRL4;
  reg  r_CTRL5;
  reg  r_CTRL6;
  reg  r_CTRL7;
  reg  r_SYNCH1;
  reg  r_SYNCH2;
  reg  r_SYNCR1;
  reg  r_SYNCR2;
  reg  r_SYNCS1;
  reg  r_SYNCS2;

  assign S0 = r_S0;
  assign S1 = r_S1;
  assign S2 = r_S2;
  assign DEFREQ = r_DEFREQ;
  assign DMAEN0 = r_DMAEN0;
  assign DMAEN1 = r_DMAEN1;
  assign DMAEN2 = r_DMAEN2;
  assign DMAEN3 = r_DMAEN3;
  assign P0 = r_P0;
  assign P1 = r_P1;
  assign P2 = r_P2;
  assign ENA0 = r_ENA0;
  assign ENA1 = r_ENA1;
  assign ENA2 = r_ENA2;
  assign ENA3 = r_ENA3;
  assign ENA4 = r_ENA4;
  assign ENA5 = r_ENA5;
  assign PEND0 = r_PEND0;
  assign PEND1 = r_PEND1;
  assign PEND2 = r_PEND2;
  assign PEND3 = r_PEND3;
  assign PEND4 = r_PEND4;
  assign PEND5 = r_PEND5;
  assign REQ0 = r_REQ0;
  assign REQ1 = r_REQ1;
  assign REQ2 = r_REQ2;
  assign REQ3 = r_REQ3;
  assign REQ4 = r_REQ4;
  assign REQ5 = r_REQ5;
  assign CTRL0 = r_CTRL0;
  assign CTRL1 = r_CTRL1;
  assign CTRL2 = r_CTRL2;
  assign CTRL3 = r_CTRL3;
  assign CTRL4 = r_CTRL4;
  assign CTRL5 = r_CTRL5;
  assign CTRL6 = r_CTRL6;
  assign CTRL7 = r_CTRL7;
  assign SYNCH1 = r_SYNCH1;
  assign SYNCH2 = r_SYNCH2;
  assign SYNCR1 = r_SYNCR1;
  assign SYNCR2 = r_SYNCR2;
  assign SYNCS1 = r_SYNCS1;
  assign SYNCS2 = r_SYNCS2;

  // EXTERNAL
  assign CCLK =
         (S2 & S1 & S0);
  // EXTERNAL
  assign CHANSLOT =
         (~S2);
  // EXTERNAL
  assign TMRSLOT =
         (S2 & ~S1 & ~S0);
  // EXTERNAL
  assign HOSTSLOT =
         (S2 & ~S1 & S0);
  // EXTERNAL
  assign DEFSLOT =
         (S2 & S1);
  // buried
  assign DEFACK =
         (DEFREQ & S2 & S1);
  // buried
  assign WAIDX =
         (SEL & ~A3 & ~A2 & ~A1 & ~A0 & ~RW);
  // buried
  assign WDMACON =
         (SEL & ~A3 & ~A2 & A1 & ~A0 & ~RW);
  // buried
  assign WINTENA =
         (SEL & ~A3 & ~A2 & A1 & A0 & ~RW);
  // buried
  assign WINTREQ =
         (SEL & ~A3 & A2 & ~A1 & ~A0 & ~RW);
  // buried
  assign WCTRL =
         (SEL & ~A3 & A2 & ~A1 & A0 & ~RW);
  // buried
  assign RINTREQ =
         (SEL & ~A3 & A2 & ~A1 & ~A0 & RW);
  // EXTERNAL
  assign RASTAT =
         (SEL & A3 & ~A2 & A1 & ~A0 & RW);
  // EXTERNAL
  assign SFCE =
         (SEL & ~A3 & ~A2 & ~A1 & A0);
  // EXTERNAL
  assign SRCE =
         (SEL & A3 & ~A2 & ~A1 & A0);
  // buried
  assign HOSTREQ =
         (SEL & E);
  // EXTERNAL
  assign CIACLK =
         (CCLK & P2);
  // EXTERNAL
  assign FIRQ =
         1'b0;
  // buried - 9.4.5: every colour clock EXCEPT while a host read is in flight
  assign MERGE =
         (CCLK & ~SYNCR2 & ~SYNCR1);
  // buried
  assign FIRQANY =
         (REQ0 & ENA0)
         | (REQ1 & ENA1)
         | (REQ2 & ENA2)
         | (REQ3 & ENA3)
         | (REQ4 & ENA4)
         | (REQ5 & ENA5);
  // buried
  assign NEWREQ =
         (SYNCH2 & ~SYNCH1);

  // FIRQ is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FIRQ_OE =
         (FIRQANY);

  wire AR_ = (RESET);
  always @(posedge SLOTCLK or posedge AR_) begin
    if (AR_) begin
      r_S0 <= 1'b0;
      r_S1 <= 1'b0;
      r_S2 <= 1'b0;
      r_DEFREQ <= 1'b0;
      r_DMAEN0 <= 1'b0;
      r_DMAEN1 <= 1'b0;
      r_DMAEN2 <= 1'b0;
      r_DMAEN3 <= 1'b0;
      r_P0 <= 1'b0;
      r_P1 <= 1'b0;
      r_P2 <= 1'b0;
      r_ENA0 <= 1'b0;
      r_ENA1 <= 1'b0;
      r_ENA2 <= 1'b0;
      r_ENA3 <= 1'b0;
      r_ENA4 <= 1'b0;
      r_ENA5 <= 1'b0;
      r_PEND0 <= 1'b0;
      r_PEND1 <= 1'b0;
      r_PEND2 <= 1'b0;
      r_PEND3 <= 1'b0;
      r_PEND4 <= 1'b0;
      r_PEND5 <= 1'b0;
      r_REQ0 <= 1'b0;
      r_REQ1 <= 1'b0;
      r_REQ2 <= 1'b0;
      r_REQ3 <= 1'b0;
      r_REQ4 <= 1'b0;
      r_REQ5 <= 1'b0;
      r_CTRL0 <= 1'b0;
      r_CTRL1 <= 1'b0;
      r_CTRL2 <= 1'b0;
      r_CTRL3 <= 1'b0;
      r_CTRL4 <= 1'b0;
      r_CTRL5 <= 1'b0;
      r_CTRL6 <= 1'b0;
      r_CTRL7 <= 1'b0;
      r_SYNCH1 <= 1'b0;
      r_SYNCH2 <= 1'b0;
      r_SYNCR1 <= 1'b0;
      r_SYNCR2 <= 1'b0;
      r_SYNCS1 <= 1'b0;
      r_SYNCS2 <= 1'b0;
    end else begin
      r_S0 <=
         (~S0);
      r_S1 <=
         (S1 & ~S0)
         | (~S1 & S0);
      r_S2 <=
         (S2 & ~S0)
         | (S2 & ~S1)
         | (~S2 & S0 & S1);
      r_DEFREQ <=
         (NEWREQ)
         | (DEFREQ & ~DEFACK);
      r_DMAEN0 <=
         (WDMACON & D7 & D0)
         | (DMAEN0 & ~WDMACON)
         | (DMAEN0 & D7)
         | (DMAEN0 & ~D0);
      r_DMAEN1 <=
         (WDMACON & D7 & D1)
         | (DMAEN1 & ~WDMACON)
         | (DMAEN1 & D7)
         | (DMAEN1 & ~D1);
      r_DMAEN2 <=
         (WDMACON & D7 & D2)
         | (DMAEN2 & ~WDMACON)
         | (DMAEN2 & D7)
         | (DMAEN2 & ~D2);
      r_DMAEN3 <=
         (WDMACON & D7 & D3)
         | (DMAEN3 & ~WDMACON)
         | (DMAEN3 & D7)
         | (DMAEN3 & ~D3);
      r_P0 <=
         (CCLK & ~P2 & ~P0)
         | (~CCLK & P0);
      r_P1 <=
         (CCLK & ~P2 & P1 & ~P0)
         | (CCLK & ~P2 & ~P1 & P0)
         | (~CCLK & P1);
      r_P2 <=
         (CCLK & ~P2 & P0 & P1)
         | (~CCLK & P2);
      r_ENA0 <=
         (WINTENA & D7 & D0)
         | (ENA0 & ~WINTENA)
         | (ENA0 & D7)
         | (ENA0 & ~D0);
      r_ENA1 <=
         (WINTENA & D7 & D1)
         | (ENA1 & ~WINTENA)
         | (ENA1 & D7)
         | (ENA1 & ~D1);
      r_ENA2 <=
         (WINTENA & D7 & D2)
         | (ENA2 & ~WINTENA)
         | (ENA2 & D7)
         | (ENA2 & ~D2);
      r_ENA3 <=
         (WINTENA & D7 & D3)
         | (ENA3 & ~WINTENA)
         | (ENA3 & D7)
         | (ENA3 & ~D3);
      r_ENA4 <=
         (WINTENA & D7 & D4)
         | (ENA4 & ~WINTENA)
         | (ENA4 & D7)
         | (ENA4 & ~D4);
      r_ENA5 <=
         (WINTENA & D7 & D5)
         | (ENA5 & ~WINTENA)
         | (ENA5 & D7)
         | (ENA5 & ~D5);
      r_PEND0 <=
         (SET0)
         | (PEND0 & ~MERGE);
      r_PEND1 <=
         (SET1)
         | (PEND1 & ~MERGE);
      r_PEND2 <=
         (SET2)
         | (PEND2 & ~MERGE);
      r_PEND3 <=
         (SET3)
         | (PEND3 & ~MERGE);
      r_PEND4 <=
         (SET4)
         | (PEND4 & ~MERGE);
      r_PEND5 <=
         (SET5)
         | (PEND5 & ~MERGE);
      r_REQ0 <=
         (WINTREQ & D7 & D0)
         | (PEND0 & MERGE)
         | (REQ0 & ~WINTREQ)
         | (REQ0 & D7)
         | (REQ0 & ~D0);
      r_REQ1 <=
         (WINTREQ & D7 & D1)
         | (PEND1 & MERGE)
         | (REQ1 & ~WINTREQ)
         | (REQ1 & D7)
         | (REQ1 & ~D1);
      r_REQ2 <=
         (WINTREQ & D7 & D2)
         | (PEND2 & MERGE)
         | (REQ2 & ~WINTREQ)
         | (REQ2 & D7)
         | (REQ2 & ~D2);
      r_REQ3 <=
         (WINTREQ & D7 & D3)
         | (PEND3 & MERGE)
         | (REQ3 & ~WINTREQ)
         | (REQ3 & D7)
         | (REQ3 & ~D3);
      r_REQ4 <=
         (WINTREQ & D7 & D4)
         | (PEND4 & MERGE)
         | (REQ4 & ~WINTREQ)
         | (REQ4 & D7)
         | (REQ4 & ~D4);
      r_REQ5 <=
         (WINTREQ & D7 & D5)
         | (PEND5 & MERGE)
         | (REQ5 & ~WINTREQ)
         | (REQ5 & D7)
         | (REQ5 & ~D5);
      r_CTRL0 <=
         (WCTRL & D0)
         | (CTRL0 & ~WCTRL);
      r_CTRL1 <=
         (WCTRL & D1)
         | (CTRL1 & ~WCTRL);
      r_CTRL2 <=
         (WCTRL & D2)
         | (CTRL2 & ~WCTRL);
      r_CTRL3 <=
         (WCTRL & D3)
         | (CTRL3 & ~WCTRL);
      r_CTRL4 <=
         (WCTRL & D4)
         | (CTRL4 & ~WCTRL);
      r_CTRL5 <=
         (WCTRL & D5)
         | (CTRL5 & ~WCTRL);
      r_CTRL6 <=
         (WCTRL & D6)
         | (CTRL6 & ~WCTRL);
      r_CTRL7 <=
         (WCTRL & D7)
         | (CTRL7 & ~WCTRL);
      r_SYNCH1 <=
         (HOSTREQ);
      r_SYNCH2 <=
         (SYNCH1);
      r_SYNCR1 <=
         (RINTREQ);
      r_SYNCR2 <=
         (SYNCR1);
      r_SYNCS1 <=
         (SFCE);
      r_SYNCS2 <=
         (SYNCS1);
    end
  end

endmodule
`default_nettype wire
