/* Verilog from the same term lists the fitter compiles.
 *
 * hardware/gal/ already has two independent implementations of every live GAL -
 * our fuse map and Atmel's - and jedec/cupl.check.ts sweeps them against each
 * other. What neither can do is RUN the card: a fuse map is a truth table, and
 * "does a whole frame come out right" is a question about hundreds of thousands
 * of clock edges through a hundred registers on two packages.
 *
 * That is what a simulator is for, and the one rule is the same rule cupl.ts
 * states: ONE ORIGIN. Retyping the equations as Verilog would make a third
 * source that nothing compares against the first two, which is the exact
 * failure mode that put two errors in the 22V10 fuse map on 2026-09-07. So the
 * Verilog is generated from Merged/Design, like the CUPL is.
 *
 * WHAT THIS MODELS AND WHAT IT DOES NOT. It models the LOGIC: the sum of
 * products each macrocell forms, the register, the one asynchronous reset. It
 * does not model propagation delay, the switch matrix, product-term cascading
 * or the fitter's placement - those are fit1508.exe's business and cpld/*.fit
 * is where they are recorded. A signal here is its ASSERTED sense throughout,
 * the same convention assemble.ts uses for terms: a pin declared active-low is
 * inverted at the pin and not in the equation.
 */

import type { Cell, Design } from "../jedec/assemble"
import type { Merged } from "../jedec/cupl"

const expr = (terms: string[]): string => {
  if (terms.length === 0) return "1'b0"
  return terms
    .map((t) => t.split("&").map((l) => {
      const s = l.trim()
      return s.startsWith("!") ? `~${s.slice(1).trim()}` : s
    }).join(" & "))
    .map((t) => `(${t})`)
    .join("\n         | ")
}

export interface VerilogSpec {
  name: string
  clock?: string
  /** the asynchronous reset expression, asserted-high */
  ar?: string
  inputs: { name: string; activeLow?: boolean }[]
  cells: Cell[]
  /** signals that leave the part; the rest are buried but still emitted as
   *  ports, because a testbench that cannot see a buried counter cannot say
   *  anything useful about a raster. They are marked in the comment. */
  external: Set<string>
}

export const fromMerged = (m: Merged): VerilogSpec => ({
  name: m.name, clock: m.clock, ar: m.ar,
  inputs: m.inputs, cells: m.cells, external: m.external,
})

/** A standalone GAL22V10 design, for rfa - the card's one remaining GAL. */
export const fromDesign = (d: Design): VerilogSpec => {
  const produced = new Set(d.cells.map((c) => c.name))
  return {
    name: d.name, clock: d.clockPin ? "CLK" : undefined, ar: d.ar,
    inputs: d.inputs.filter((i) => !produced.has(i.name)),
    cells: d.cells,
    external: new Set(d.cells.map((c) => c.name)),
  }
}

export const toVerilog = (s: VerilogSpec): string => {
  const out: string[] = []
  const inputNames = new Set(s.inputs.map((i) => i.name))
  const ports: string[] = []
  if (s.clock && !inputNames.has(s.clock)) ports.push(`input  wire ${s.clock}`)
  for (const i of s.inputs) ports.push(`input  wire ${i.name}`)
  for (const c of s.cells) ports.push(`output wire ${c.name}`)
  for (const c of s.cells) if (c.oe) ports.push(`output wire ${c.name}_OE`)

  out.push(`// GENERATED by hardware/gal/verilog/emit.ts from the term lists in`)
  out.push(`// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.`)
  out.push(`//`)
  out.push(`// Every cell is a port, buried ones included, so a testbench can watch the`)
  out.push(`// counters. The ones that really leave the package are marked EXTERNAL.`)
  out.push(`\`default_nettype none`)
  out.push("")
  out.push(`module ${s.name} (`)
  out.push(ports.map((p) => `    ${p}`).join(",\n"))
  out.push(`);`)
  out.push("")

  const regs = s.cells.filter((c) => c.registered)
  const comb = s.cells.filter((c) => !c.registered)

  for (const c of regs) out.push(`  reg  r_${c.name};`)
  out.push("")
  for (const c of regs) out.push(`  assign ${c.name} = r_${c.name};`)
  out.push("")

  for (const c of comb) {
    const tag = s.external.has(c.name) ? "EXTERNAL" : "buried"
    out.push(`  // ${tag}${c.why ? ` - ${c.why}` : ""}`)
    out.push(`  assign ${c.name} =`)
    out.push(`         ${expr(c.terms)};`)
  }
  out.push("")
  for (const c of s.cells) {
    if (!c.oe) continue
    out.push(`  // ${c.name} is open drain: the data is a constant and the`)
    out.push(`  // condition rides on the output enable (graphics.md 12.1).`)
    out.push(`  assign ${c.name}_OE =`)
    out.push(`         ${expr([c.oe])};`)
  }
  out.push("")

  if (regs.length) {
    const ar = s.ar ? expr([s.ar]) : null
    if (ar) out.push(`  wire AR_ = ${ar};`)
    out.push(`  always @(posedge ${s.clock ?? "CLK"}${ar ? " or posedge AR_" : ""}) begin`)
    if (ar) {
      out.push(`    if (AR_) begin`)
      for (const c of regs) out.push(`      r_${c.name} <= 1'b0;`)
      out.push(`    end else begin`)
    }
    for (const c of regs) {
      out.push(`      r_${c.name} <=`)
      out.push(`         ${expr(c.terms)};`)
    }
    if (ar) out.push(`    end`)
    out.push(`  end`)
  }
  out.push("")
  out.push(`endmodule`)
  out.push(`\`default_nettype wire`)
  return out.join("\n") + "\n"
}
