// A MODULE PLAYS ON THE CARD, AND THE CONVERTERS ARE RECORDED.
//
//   sh gal/verilog/run-modplay.sh /tmp/arm6309-mod/00_notes.mod
//
// THE DEVICE UNDER TEST IS audio_card.v AND NOTHING ELSE: U1 (audio.v) and U2
// (aseq.v), generated by emit.ts from the same Cell term lists jedec/cupl.ts
// compiles for fit1508.exe, plus the board between them - the state file, the
// sample RAM, the free-running counter, the adder chain and the four AD7528.
// Every byte reaches it through the host port at $FF40-$FF4F, over a 6809 bus
// cycle, exactly as the 6309 will send it. There is no C model of the card in
// this simulation, and nothing here reads one.
//
// ⚠ WHAT IS NOT UNDER TEST, STATED PLAINLY, because the difference is the whole
// value of the run:
//
//   * THE REPLAYER. Which register gets which byte on which tick is software -
//     audio/docs/modplayer.md §5's tick engine - and it arrives here as a
//     recorded trace from audio/refplayer, which is the reference the 6309 port
//     is contracted to reproduce byte for byte. A replayer bug would make the
//     card play the wrong notes correctly; the control below is what separates
//     the two.
//   * THE ANALOGUE STAGE. Resistors, one I/V amplifier per side and the A500's
//     4.4 kHz pole have no RTL. This testbench records what the CONVERTERS are
//     given - four sample codes and four volume codes, whenever they change -
//     and audio/tools/dacwav renders that through audio/refplayer/render.c,
//     which is a model of the card's analogue chain and is not card.c.
//
// ⭐ AND THE TEMPO COMES FROM THE CARD. The trace is timestamped by TICK, not
// by time, and the tick is the card's own §8.2 timer: this waits for /FIRQ and
// then plays the next tick's writes. So the card's divide-by-5 CIA clock, its
// TIMER reload and its interrupt path are in the loop, and a module that plays
// at the wrong tempo says so.
//
// A comment line here must never begin with the simulator's own name.

module modplay_tb;

  // 28.37516 MHz: eight slots per 3.546895 MHz colour clock (audio.md §3.1).
  logic SLOTCLK = 0;
  always #1 SLOTCLK <= ~SLOTCLK;

  logic RESET = 1, RW = 1, E = 0, IOSEL = 0;
  logic [6:0] A = 7'h00;
  wire  [7:0] HD;
  logic [7:0] hostD = 8'h00;
  logic       hostDrv = 1'b0;
  assign HD = hostDrv ? hostD : 8'hzz;

  wire FIRQ_OE;
  wire [15:0] COUNT;
  wire [7:0] DACSAMP0,DACSAMP1,DACSAMP2,DACSAMP3;
  wire [7:0] DACVOL0,DACVOL1,DACVOL2,DACVOL3;

  audio_card card (.*);

  int fails = 0, claims = 0;
  task automatic ok(input bit good, input string claim);
    claims++;
    if (good) $display("ok    %s", claim);
    else begin fails++; $display("FAIL  %s", claim); end
  endtask

  /* ---- the host port, as a 6809E cycle -------------------------------- *
   * audio.md §9.4: the port is asynchronous to the card and the address is
   * the whole seven bits the geographic window leaves it. Same shape as
   * audio_tb's, with one difference that matters here - the busy handshake is
   * polled over the BUS through ASTAT, not peeked at inside the part, because
   * a host that cannot see b6 is exactly the host §9.2 says loses writes. */
  logic [7:0] rdval;

  task automatic idle();
    IOSEL = 0; RW = 1; hostDrv = 0; A = 7'h00;
  endtask

  task automatic rdraw(input int addr);
    @(negedge SLOTCLK); IOSEL = 1; A = addr[6:0]; RW = 1;
    repeat (3) @(negedge SLOTCLK);
    E = 1;
    repeat (4) @(negedge SLOTCLK);
    rdval = HD;
    repeat (3) @(negedge SLOTCLK);
    E = 0; @(negedge SLOTCLK); idle();
    repeat (8) @(negedge SLOTCLK);
  endtask

  int pw_wait_max = 0;
  bit pw_stuck = 0;
  // ⚠ BOUNDED. CLAUDE.md's fifth trap: an unbounded wait here would hang the
  // run rather than fail it if ASTAT b6 ever stuck high.
  task automatic pwwait();
    int w;
    w = 0;
    forever begin
      rdraw(7'h4A);                       // ASTAT
      if (!rdval[6]) break;               // b6 = posted-write busy (§9.2)
      w++;
      if (w > 512) begin pw_stuck = 1; break; end
    end
    if (w > pw_wait_max) pw_wait_max = w;
  endtask

  task automatic wr(input int off, input logic [7:0] v);
    pwwait();
    @(negedge SLOTCLK); IOSEL = 1; A = 7'h40 | off[3:0]; RW = 0;
    hostD = v; hostDrv = 1;
    repeat (3) @(negedge SLOTCLK);
    E = 1;
    repeat (7) @(negedge SLOTCLK);
    E = 0; @(negedge SLOTCLK); idle();
    repeat (8) @(negedge SLOTCLK);
  endtask

  /* ---- the converters, recorded on change ------------------------------ *
   * The card's output is a zero-order hold at each channel's own rate - a few
   * kHz to 28 kHz - inside a 3.55 MHz colour clock, so writing a row per
   * colour clock would be four hundred times more file than information. What
   * is written is the instant a converter code changes, and the renderer holds
   * it: which is not a compression of the signal, it IS the signal (§6.2). */
  int      dacfd;
  longint  cc;                       // colour clocks since RESET released
  logic [7:0] ls0, ls1, ls2, ls3, lv0, lv1, lv2, lv3;
  bit      first_row = 1;
  int      dac_rows = 0;

  /* ⭐ +voldbg: what the state file holds against what the converter got.
   * The card's own VOL byte for channel n is SF[n*8+6][23:16] (aseq.micro.ts:
   * SFA = {0, ch[1:0], w[2:0]}), so this is the two ends of 6.1's volume path
   * printed side by side. Added while chasing 16 item 40. */
  int voldbg = 0;
  initial void'($value$plusargs("voldbg=%d", voldbg));

  task automatic dac_emit();
    if (voldbg > 0 && dac_rows < voldbg)
      $display("      vol cc=%0d  DACVOL=%3d %3d %3d %3d   file=%3d %3d %3d %3d",
               cc, DACVOL0, DACVOL1, DACVOL2, DACVOL3,
               card.SF[6][23:16], card.SF[14][23:16],
               card.SF[22][23:16], card.SF[30][23:16]);
    if (dacfd != 0)
      $fwrite(dacfd, "%0d %0d %0d %0d %0d %0d %0d %0d %0d\n", cc,
              DACSAMP0, DACSAMP1, DACSAMP2, DACSAMP3,
              DACVOL0, DACVOL1, DACVOL2, DACVOL3);
    dac_rows++;
    ls0 = DACSAMP0; ls1 = DACSAMP1; ls2 = DACSAMP2; ls3 = DACSAMP3;
    lv0 = DACVOL0;  lv1 = DACVOL1;  lv2 = DACVOL2;  lv3 = DACVOL3;
  endtask

  // One colour clock is eight slots. COUNT is the free-running colour-clock
  // counter on the card itself, so this counts what the card counts.
  logic [15:0] prev_count;
  bit          counting = 0;
  always @(posedge SLOTCLK) if (counting) begin
    if (COUNT !== prev_count) begin
      cc++;
      prev_count = COUNT;
    end
    if (first_row
        || DACSAMP0 !== ls0 || DACSAMP1 !== ls1
        || DACSAMP2 !== ls2 || DACSAMP3 !== ls3
        || DACVOL0  !== lv0 || DACVOL1  !== lv1
        || DACVOL2  !== lv2 || DACVOL3  !== lv3) begin
      dac_emit();
      first_row = 0;
    end
  end

  /* ---- +cvdbg=N: the bus at the instant a port register is clocked ------
   * 16 item 41. The state file holds the right VOL and the converter gets a
   * sample byte, so the question is what SD[23:16] carries at the load - which
   * is one $display and not an argument. */
  int cvdbg = 0, cvdbg_n = 0;
  initial void'($value$plusargs("cvdbg=%d", cvdbg));
  // +cvwin=N: every slot in the 3 colour clocks starting at N, CVC code or not.
  int cvwin = -1;
  initial void'($value$plusargs("cvwin=%d", cvwin));
  always @(negedge SLOTCLK)
    if (cvwin >= 0 && cc >= cvwin && cc < cvwin + 3)
      $display("      SLOT cc=%0d S=%b%b%b code=%0d SD=%02h SFOE=%b SFA=%02h CVR0=%02h dv0=%02h CVOEA=%b CVBUSY=%b QCHAN=%b WT=%b%b%b",
               cc, card.S2, card.S1, card.S0,
               {card.CVC2, card.CVC1, card.CVC0}, card.SD[23:16],
               card.SFOE, card.SFA, card.CVR0, DACVOL0, card.CVOEA,
               card.u2.CVBUSY, card.u2.QCHAN,
               card.u2.WT2, card.u2.WT1, card.u2.WT0);

  always @(negedge SLOTCLK)
    if (cvdbg > 0 && cvdbg_n < cvdbg
        && {card.CVC2, card.CVC1, card.CVC0} != 3'd0) begin
      cvdbg_n++;
      $display("      cv cc=%0d code=%0d SD=%02h SFOE=%b SBOE=%b SFA=%02h file6=%02h CVR0=%02h dv0=%02h CVOEA=%b CVBUSY=%b QCHAN=%b WT=%b%b%b",
               cc, {card.CVC2, card.CVC1, card.CVC0}, card.SD[23:16],
               card.SFOE, card.SBOE, card.SFA,
               card.SF[6][23:16], card.CVR0, DACVOL0, card.CVOEA,
               card.u2.CVBUSY, card.u2.QCHAN,
               card.u2.WT2, card.u2.WT1, card.u2.WT0);
    end

  /* ---- 6.1's volume path, end to end ----------------------------------- *
   *
   * ⛔ THE CLAIM THAT WAS MISSING, and it is why 16 item 41 survived. audio_tb
   * asserts `sfh(6) == $40` - "VOL is one byte and goes straight through" -
   * which is a claim about the STATE FILE, and the state file was right the
   * whole time. Nothing had ever compared the converter's own pins against the
   * file's contents, so a volume path that delivered a SAMPLE byte to the
   * volume DAC read as forty-three green claims.
   *
   * Sampled every 4096 colour clocks, and only where the file's byte has not
   * changed since the previous sample - W5's latency is three colour clocks
   * and a replayer writes VOL about 200 times a second, so a settled
   * comparison is the honest one and a live one would just measure the
   * handshake. */
  int vol_checks = 0, vol_bad = 0;
  int vol_bad_ch = -1;
  logic [7:0] prev_file [0:3];
  longint     next_vol_check = 4096;
  always @(posedge SLOTCLK) if (counting && cc >= next_vol_check) begin
    logic [7:0] f [0:3];
    next_vol_check = cc + 4096;
    f[0] = card.SF[6][23:16];  f[1] = card.SF[14][23:16];
    f[2] = card.SF[22][23:16]; f[3] = card.SF[30][23:16];
    for (int n = 0; n < 4; n++) begin
      logic [7:0] got;
      got = (n == 0) ? DACVOL0 : (n == 1) ? DACVOL1 : (n == 2) ? DACVOL2 : DACVOL3;
      if (f[n] === prev_file[n]) begin
        vol_checks++;
        if (got !== f[n]) begin
          vol_bad++;
          if (vol_bad_ch < 0) vol_bad_ch = n;
        end
      end
      prev_file[n] = f[n];
    end
  end

  /* ---- the trace ------------------------------------------------------- */
  // audio/refplayer's format: "%06lu %-7s %02X" - tick, register name, byte.
  function automatic int reg_of(input string name);
    case (name)
      "AIDX":    reg_of = 0;
      "ADATA":   reg_of = 1;
      "ADMACON": reg_of = 2;
      "AINTENA": reg_of = 3;
      "AINTREQ": reg_of = 4;
      "ACTRL":   reg_of = 5;
      "SPTR2":   reg_of = 6;
      "SPTR1":   reg_of = 7;
      "SPTR0":   reg_of = 8;
      "SDATA":   reg_of = 9;
      "ASTAT":   reg_of = 10;
      "TIMER1":  reg_of = 11;
      "TIMER0":  reg_of = 12;
      default:   reg_of = -1;
    endcase
  endfunction

  int      trfd, srfd;
  string   sram_path, trace_path, dac_path;
  int      run_cc;
  int      tick_now, tick_line, n, v, got;
  string   rname;
  int      writes_played = 0, ticks_played = 0, unknown_regs = 0;
  int      firq_timeouts = 0;
  logic [7:0] byte_v;

  // Wait for the card's own tick interrupt. BOUNDED: a tempo timer that never
  // fires must fail this run, not stall it.
  task automatic wait_firq(input int limit_cc);
    longint deadline;
    deadline = cc + limit_cc;
    while (!FIRQ_OE && cc < deadline) @(posedge SLOTCLK);
    if (!FIRQ_OE) firq_timeouts++;
  endtask

  initial begin
    if (!$value$plusargs("sram=%s", sram_path))  sram_path  = "";
    if (!$value$plusargs("trace=%s", trace_path)) trace_path = "";
    if (!$value$plusargs("dac=%s", dac_path))    dac_path   = "";
    if (!$value$plusargs("cc=%d", run_cc))       run_cc     = 3546895;   // one second

    trfd = $fopen(trace_path, "r");
    ok(trfd != 0, $sformatf("the register trace opens (%s)", trace_path));
    // ⚠ Not a ternary. This simulator mis-generates `cond ? 0 : $fopen(p,"w")`
    // - it emits `std::string{""} , std::string{"w"}` as one argument and the
    // C++ will not compile. An if is a workaround, not a preference.
    dacfd = 0;
    if (dac_path != "") dacfd = $fopen(dac_path, "w");
    ok(dac_path == "" || dacfd != 0, "the converter log opens");

    repeat (8) @(posedge SLOTCLK);
    RESET = 0;
    repeat (64) @(posedge SLOTCLK);
    cc = 0; prev_count = COUNT; counting = 1;

    // ---- 1. the samples, through SPTR/SDATA -----------------------------
    // audio.md §9.2: a 19-bit pointer with post-increment on the data port.
    // This is the upload the 6309 does with TFM, one store per byte.
    srfd = $fopen(sram_path, "r");
    ok(srfd != 0, $sformatf("the sample image opens (%s)", sram_path));
    wr(6, 8'h00); wr(7, 8'h00); wr(8, 8'h00);      // SPTR := 0
    n = 0;
    while ($fscanf(srfd, "%h", v) == 1) begin
      wr(9, v[7:0]);
      n++;
    end
    $fclose(srfd);
    ok(n > 0, $sformatf("%0d sample bytes uploaded through the host port", n));
    ok(!pw_stuck, "ASTAT b6 always cleared - no host write was ever refused (§9.2)");

    /* Every uploaded byte is in the sample RAM, compared against the file the
     * loader wrote - so "the upload happened" is a claim about all 130 host
     * writes and not about the loop above.
     *
     * ⚠ IT IS NOT READ BACK THROUGH SDATA, and that is audio.md §16 item 33
     * rather than a shortcut: writing SPTR is specified to prefetch that entry
     * and nothing on the card does it, so the first read after a pointer write
     * returns the byte the PREVIOUS pointer named - and SDATA post-increments,
     * so a second read is of the next address, not a retry of this one. The
     * item is open; this testbench does not pretend otherwise. */
    srfd = $fopen(sram_path, "r");
    n = 0; got = 0;
    while ($fscanf(srfd, "%h", v) == 1) begin
      if (card.SRAM[n] !== v[7:0]) got++;
      n++;
    end
    $fclose(srfd);
    ok(got == 0,
       $sformatf("all %0d bytes are in the card's sample RAM, byte for byte (%0d wrong)",
                 n, got));

    // ---- 2. the module ---------------------------------------------------
    tick_now = 0;
    tick_line = 0;
    while ($fscanf(trfd, "%d %s %h", tick_line, rname, byte_v) == 3) begin
      // A new tick: wait for the card's own timer to say so.
      while (tick_line > tick_now) begin
        wait_firq(200000);
        tick_now++;
        ticks_played++;
      end
      n = reg_of(rname);
      if (n < 0) unknown_regs++;
      else begin
        wr(n, byte_v);
        writes_played++;
      end
      if (cc > run_cc) break;
    end
    $fclose(trfd);

    ok(unknown_regs == 0,
       $sformatf("every register name in the trace is one the card has (%0d unknown)",
                 unknown_regs));
    ok(firq_timeouts == 0,
       $sformatf("the card's own §8.2 timer produced every tick (%0d never came)",
                 firq_timeouts));

    ok(vol_bad == 0,
       $sformatf("16 item 41: every settled VOL byte reaches its own converter (%0d of %0d samples wrong%s)",
                 vol_bad, vol_checks,
                 vol_bad_ch < 0 ? "" : $sformatf(", first on channel %0d", vol_bad_ch)));
    ok(vol_checks > 100,
       $sformatf("and the volume path was sampled enough times to mean it (%0d)", vol_checks));

    // Run on to the requested length, so the tail of the last note is rendered.
    while (cc < run_cc) @(posedge SLOTCLK);

    if (dacfd != 0) begin
      dac_emit();                       // a final row, so the hold has an end
      $fclose(dacfd);
    end

    $display("");
    $display("      %0d colour clocks, %0d ticks, %0d register writes, %0d converter changes",
             cc, ticks_played, writes_played, dac_rows);
    $display("      worst ASTAT b6 poll: %0d reads", pw_wait_max);
    $display("");
    if (fails == 0) $display("modplay_tb OK - %0d claims", claims);
    else            $display("modplay_tb - %0d of %0d claims FAILED", fails, claims);
    $finish;
  end

  // The backstop. A hang is worse than a failure.
  initial begin
    #4000000000;
    $display("FAIL  modplay_tb: global timeout at colour clock %0d", cc);
    $display("modplay_tb - TIMED OUT");
    $finish;
  end

endmodule
