// GENERATED by hardware/gal/verilog/emit.ts from the term lists in
// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module pxsel (
    input  wire CLK,
    input  wire RESET,
    input  wire LDHS,
    input  wire LWHSL,
    input  wire D0,
    input  wire D1,
    input  wire PB0,
    input  wire PB1,
    output wire HS0,
    output wire HS1,
    output wire OEA0,
    output wire OEA1,
    output wire OEA2,
    output wire OEB0,
    output wire OEB1,
    output wire OEB2
);

  reg  r_HS0;
  reg  r_HS1;

  assign HS0 = r_HS0;
  assign HS1 = r_HS1;

  // EXTERNAL
  assign OEA0 =
         (HS0)
         | (HS1);
  // EXTERNAL
  assign OEA1 =
         (HS1);
  // EXTERNAL
  assign OEA2 =
         (HS1 & HS0);
  // EXTERNAL
  assign OEB0 =
         (~HS1 & ~HS0);
  // EXTERNAL
  assign OEB1 =
         (~HS1);
  // EXTERNAL
  assign OEB2 =
         (~HS1)
         | (~HS0);


  wire AR_ = (RESET);
  always @(posedge CLK or posedge AR_) begin
    if (AR_) begin
      r_HS0 <= 1'b0;
      r_HS1 <= 1'b0;
    end else begin
      r_HS0 <=
         (LDHS & D0)
         | (LWHSL & PB0)
         | (HS0 & ~LDHS & ~LWHSL);
      r_HS1 <=
         (LDHS & D1)
         | (LWHSL & PB1)
         | (HS1 & ~LDHS & ~LWHSL);
    end
  end

endmodule
`default_nettype wire
