// GENERATED by hardware/gal/verilog/emit.ts from the term lists in
// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module rfa (
    input  wire IOSEL,
    input  wire A5,
    input  wire A6,
    input  wire A0,
    input  wire A1,
    input  wire A2,
    input  wire A3,
    input  wire A4,
    input  wire RW,
    input  wire E,
    input  wire SPANBUSY,
    input  wire MASKBIT,
    input  wire RP0,
    input  wire RP1,
    output wire WSTB,
    output wire RA0,
    output wire RA1,
    output wire RA2,
    output wire RA3,
    output wire RA4,
    output wire WCTRL,
    output wire VSTATWR
);



  // EXTERNAL - E-qualified: a 6809 write is only valid data in the second half
  assign WSTB =
         (IOSEL & A6 & A5 & ~RW & E);
  // EXTERNAL - 7.4: the mask bit IS the register file's address bit 0, inverted
  assign RA0 =
         (IOSEL & A6 & A5 & ~SPANBUSY & A0)
         | (SPANBUSY & ~MASKBIT)
         | (~IOSEL & ~SPANBUSY & ~RP0 & ~RP1)
         | (~A6 & ~SPANBUSY & ~RP0 & ~RP1)
         | (~A5 & ~SPANBUSY & ~RP0 & ~RP1)
         | (~IOSEL & RP1)
         | (~A6 & RP1)
         | (~A5 & RP1);
  // EXTERNAL
  assign RA1 =
         (IOSEL & A6 & A5 & ~SPANBUSY & A1)
         | (SPANBUSY);
  // EXTERNAL
  assign RA2 =
         (IOSEL & A6 & A5 & ~SPANBUSY & A2)
         | (~IOSEL & ~RP0 & ~RP1)
         | (~A6 & ~RP0 & ~RP1)
         | (~A5 & ~RP0 & ~RP1)
         | (SPANBUSY & ~RP0 & ~RP1);
  // EXTERNAL
  assign RA3 =
         (IOSEL & A6 & A5 & ~SPANBUSY & A3)
         | (~IOSEL & RP0)
         | (~A6 & RP0)
         | (~A5 & RP0)
         | (~IOSEL & RP1)
         | (~A6 & RP1)
         | (~A5 & RP1);
  // EXTERNAL
  assign RA4 =
         (IOSEL & A6 & A5 & ~SPANBUSY & A4);
  // EXTERNAL
  assign WCTRL =
         (IOSEL & A6 & A5 & ~RW & E & ~A4 & ~A3 & ~A2 & ~A1 & ~A0);
  // EXTERNAL
  assign VSTATWR =
         (IOSEL & A6 & A5 & ~RW & E & A4 & ~A3 & ~A2 & A1 & A0);



endmodule
`default_nettype wire
