// GENERATED by hardware/gal/verilog/emit.ts from the term lists in
// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module sdbus (
    input  wire IOSEL,
    input  wire A6,
    input  wire A5,
    input  wire A4,
    input  wire A3,
    input  wire A2,
    input  wire A1,
    input  wire A0,
    input  wire RW,
    input  wire E,
    input  wire BUSY,
    input  wire CD,
    input  wire WP,
    input  wire TRIGP,
    output wire DATSTB,
    output wire RDST,
    output wire CTRLW,
    output wire OE595,
    output wire MOSICK,
    output wire SD0,
    output wire SD1,
    output wire SD2,
    output wire SD0_OE,
    output wire SD1_OE,
    output wire SD2_OE
);



  // EXTERNAL
  assign DATSTB =
         (IOSEL & A6 & ~A5 & A4 & A3 & ~A2 & ~A1 & ~A0 & E);
  // EXTERNAL
  assign RDST =
         (IOSEL & A6 & ~A5 & A4 & A3 & ~A2 & ~A1 & A0 & RW & E);
  // EXTERNAL
  assign CTRLW =
         (IOSEL & A6 & ~A5 & A4 & A3 & ~A2 & A1 & ~A0 & ~RW & E);
  // EXTERNAL
  assign OE595 =
         (IOSEL & A6 & ~A5 & A4 & A3 & ~A2 & ~A1 & ~A0 & RW & E);
  // EXTERNAL
  assign MOSICK =
         (IOSEL & A6 & ~A5 & A4 & A3 & ~A2 & ~A1 & ~A0 & ~RW & E)
         | (IOSEL & A6 & ~A5 & A4 & A3 & ~A2 & A1 & A0 & ~RW & E);
  // EXTERNAL
  assign SD0 =
         (BUSY)
         | (TRIGP);
  // EXTERNAL
  assign SD1 =
         (CD);
  // EXTERNAL
  assign SD2 =
         (WP);

  // SD0 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD0_OE =
         (RDST);
  // SD1 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD1_OE =
         (RDST);
  // SD2 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SD2_OE =
         (RDST);


endmodule
`default_nettype wire
