// GENERATED by hardware/gal/verilog/emit.ts from the term lists in
// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module u10 (
    input  wire CLK,
    input  wire DRAMSEL,
    input  wire A23,
    input  wire A22,
    input  wire C0,
    input  wire C1,
    input  wire C2,
    input  wire C3,
    input  wire RW,
    input  wire REFCLK,
    input  wire RESET,
    output wire RF0,
    output wire RF1,
    output wire REFQ,
    output wire RAS0,
    output wire RAS1,
    output wire RAS2,
    output wire RAS3,
    output wire CAS,
    output wire DWE
);

  reg  r_RF0;
  reg  r_RF1;
  reg  r_REFQ;

  assign RF0 = r_RF0;
  assign RF1 = r_RF1;
  assign REFQ = r_REFQ;

  // EXTERNAL
  assign RAS0 =
         (DRAMSEL & ~A23 & A22 & ~C3 & C2)
         | (DRAMSEL & ~A23 & A22 & C3 & ~C2 & ~C1)
         | (RF1);
  // EXTERNAL
  assign RAS1 =
         (DRAMSEL & A23 & ~A22 & ~C3 & C2)
         | (DRAMSEL & A23 & ~A22 & C3 & ~C2 & ~C1)
         | (RF1);
  // EXTERNAL
  assign RAS2 =
         (DRAMSEL & A23 & A22 & ~C3 & C2)
         | (DRAMSEL & A23 & A22 & C3 & ~C2 & ~C1)
         | (RF1);
  // EXTERNAL
  assign RAS3 =
         (DRAMSEL & ~A23 & ~A22 & ~C3 & C2)
         | (DRAMSEL & ~A23 & ~A22 & C3 & ~C2 & ~C1)
         | (RF1);
  // EXTERNAL
  assign CAS =
         (DRAMSEL & ~C3 & C2 & C1 & C0)
         | (DRAMSEL & C3 & ~C2 & ~C1)
         | (RF0)
         | (RF1);
  // EXTERNAL
  assign DWE =
         (DRAMSEL & ~RW & ~C3 & C2)
         | (DRAMSEL & ~RW & C3 & ~C2 & ~C1);


  wire AR_ = (RESET);
  always @(posedge CLK or posedge AR_) begin
    if (AR_) begin
      r_RF0 <= 1'b0;
      r_RF1 <= 1'b0;
      r_REFQ <= 1'b0;
    end else begin
      r_RF0 <=
         (~RF1 & ~RF0 & REFCLK & ~REFQ & ~DRAMSEL)
         | (~RF1 & ~RF0 & REFCLK & ~REFQ & C3 & ~C2 & C1)
         | (~RF1 & ~RF0 & ~REFCLK & REFQ & ~DRAMSEL)
         | (~RF1 & ~RF0 & ~REFCLK & REFQ & C3 & ~C2 & C1)
         | (RF1 & ~RF0);
      r_RF1 <=
         (~RF1 & RF0)
         | (RF1 & ~RF0);
      r_REFQ <=
         (REFQ & ~RF1)
         | (REFQ & ~RF0)
         | (REFCLK & RF1 & RF0);
    end
  end

endmodule
`default_nettype wire
