// GENERATED by hardware/gal/verilog/emit.ts from the term lists in
// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module u9 (
    input  wire A24,
    input  wire A23,
    input  wire A22,
    input  wire A21,
    input  wire A20,
    input  wire A19,
    input  wire IOPAGE,
    input  wire RUN,
    input  wire LA7,
    input  wire LA6,
    input  wire LA5,
    input  wire LA4,
    input  wire RW,
    output wire MAPCE_LO,
    output wire MAPCE_HI,
    output wire ROMCE0,
    output wire ROMCE1,
    output wire IOPAGE_BP,
    output wire DRAMSEL
);



  // EXTERNAL
  assign MAPCE_LO =
         (RUN & ~IOPAGE)
         | (IOPAGE & LA7 & ~LA6 & LA5 & ~LA4);
  // EXTERNAL
  assign MAPCE_HI =
         (RUN & ~IOPAGE)
         | (IOPAGE & LA7 & ~LA6 & ~LA5 & LA4);
  // EXTERNAL
  assign ROMCE0 =
         (~RUN & ~IOPAGE & ~A19 & RW)
         | (IOPAGE & LA7 & LA6 & ~A19 & RW)
         | (~IOPAGE & ~A24 & ~A23 & ~A22 & A21 & ~A20 & ~A19 & RW);
  // EXTERNAL
  assign ROMCE1 =
         (~RUN & ~IOPAGE & A19 & RW)
         | (IOPAGE & LA7 & LA6 & A19 & RW)
         | (~IOPAGE & ~A24 & ~A23 & ~A22 & A21 & ~A20 & A19 & RW);
  // EXTERNAL
  assign IOPAGE_BP =
         (IOPAGE)
         | (RUN & A24)
         | (RUN & A23)
         | (RUN & A22)
         | (RUN & A21);
  // EXTERNAL
  assign DRAMSEL =
         (~IOPAGE & RUN & ~A24 & ~A23 & A22)
         | (~IOPAGE & RUN & ~A24 & A23 & ~A22)
         | (~IOPAGE & RUN & ~A24 & A23 & A22)
         | (~IOPAGE & RUN & A24 & ~A23 & ~A22);



endmodule
`default_nettype wire
