// GENERATED by hardware/gal/verilog/emit.ts from the term lists in
// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module v3host (
    input  wire CLK25,
    input  wire RESET,
    input  wire IOSEL,
    input  wire IOPGH,
    input  wire A0,
    input  wire A1,
    input  wire A2,
    input  wire A3,
    input  wire A4,
    input  wire A5,
    input  wire A6,
    input  wire A19,
    input  wire A20,
    input  wire E,
    input  wire RW,
    input  wire WRCYC,
    input  wire SPANBUSY,
    input  wire CBUSY,
    input  wire VBLANK,
    input  wire HLOAD,
    input  wire RDCK,
    input  wire RETIRE,
    input  wire RSTART,
    input  wire IRQEN,
    output wire REGWR,
    output wire RA0,
    output wire RA1,
    output wire RA2,
    output wire RA3,
    output wire RA4,
    output wire LDPDATH,
    output wire LDIRQACK,
    output wire PPEND,
    output wire PS0,
    output wire PS1,
    output wire PS2,
    output wire PS3,
    output wire PALTURN,
    output wire PBUSY,
    output wire LUTWE,
    output wire PIDXCE,
    output wire VDSEL,
    output wire VPORT,
    output wire WSTBV,
    output wire WSTB,
    output wire RDVALID,
    output wire RDINV,
    output wire RDOE,
    output wire RDREQ,
    output wire WAITN,
    output wire IRQPEND,
    output wire VBLQ,
    output wire VBLRISE,
    output wire IRQACK,
    output wire IRQN,
    output wire VSTATOE,
    output wire RDBKOE,
    output wire WAITN_OE,
    output wire IRQN_OE
);

  reg  r_PPEND;
  reg  r_PS0;
  reg  r_PS1;
  reg  r_PS2;
  reg  r_PS3;
  reg  r_RDVALID;
  reg  r_IRQPEND;
  reg  r_VBLQ;

  assign PPEND = r_PPEND;
  assign PS0 = r_PS0;
  assign PS1 = r_PS1;
  assign PS2 = r_PS2;
  assign PS3 = r_PS3;
  assign RDVALID = r_RDVALID;
  assign IRQPEND = r_IRQPEND;
  assign VBLQ = r_VBLQ;

  // EXTERNAL
  assign REGWR =
         (IOSEL & A6 & A5 & WRCYC);
  // EXTERNAL
  assign RA0 =
         (A0);
  // EXTERNAL
  assign RA1 =
         (A1);
  // EXTERNAL
  assign RA2 =
         (A2);
  // EXTERNAL
  assign RA3 =
         (A3);
  // EXTERNAL
  assign RA4 =
         (A4);
  // buried
  assign LDPDATH =
         (IOSEL & A6 & A5 & WRCYC & A4 & ~A3 & ~A2 & ~A1 & A0);
  // buried
  assign LDIRQACK =
         (IOSEL & A6 & A5 & WRCYC & ~A4 & A3 & A2 & ~A1 & A0);
  // EXTERNAL
  assign PALTURN =
         (PS0)
         | (PS1)
         | (PS2);
  // EXTERNAL
  assign PBUSY =
         (PPEND)
         | (PS0)
         | (PS1)
         | (PS2)
         | (PS3);
  // EXTERNAL
  assign LUTWE =
         (PS1);
  // EXTERNAL
  assign PIDXCE =
         (PS3);
  // EXTERNAL
  assign VDSEL =
         (IOSEL & A6 & A5 & ~A4 & A3 & A2 & ~A1 & ~A0);
  // EXTERNAL
  assign VPORT =
         (~IOSEL & A19 & ~A20)
         | (VDSEL);
  // EXTERNAL
  assign WSTBV =
         (VPORT & ~RW & E);
  // EXTERNAL
  assign WSTB =
         (IOSEL & A6 & A5 & WRCYC);
  // buried
  assign RDINV =
         (WSTB)
         | (RETIRE)
         | (RSTART);
  // EXTERNAL
  assign RDOE =
         (VPORT & RW);
  // EXTERNAL
  assign RDREQ =
         (~RDVALID);
  // EXTERNAL
  assign WAITN =
         1'b0;
  // buried
  assign VBLRISE =
         (VBLANK & ~VBLQ);
  // buried
  assign IRQACK =
         (LDIRQACK);
  // EXTERNAL
  assign IRQN =
         1'b0;
  // EXTERNAL
  assign VSTATOE =
         (IOSEL & A6 & A5 & ~A4 & A3 & A2 & ~A1 & A0 & RW & E);
  // EXTERNAL
  assign RDBKOE =
         (IOSEL & A6 & A5 & RW & E & ~VDSEL);

  // WAITN is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign WAITN_OE =
         (VPORT & ~IOPGH & E & SPANBUSY | VPORT & ~IOPGH & E & RW & ~RDVALID);
  // IRQN is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign IRQN_OE =
         (IRQPEND & IRQEN);

  always @(posedge CLK25) begin
      r_PPEND <=
         (LDPDATH & ~VBLANK)
         | (PPEND & ~PS0);
      r_PS0 <=
         (PPEND & HLOAD)
         | (LDPDATH & VBLANK)
         | (PS0 & ~PS1);
      r_PS1 <=
         (PS0)
         | (PS1 & ~PS2);
      r_PS2 <=
         (PS1)
         | (PS2 & ~PS3);
      r_PS3 <=
         (PS2);
      r_RDVALID <=
         (RDCK)
         | (RDVALID & ~RDINV);
      r_IRQPEND <=
         (VBLRISE)
         | (IRQPEND & ~IRQACK);
      r_VBLQ <=
         (VBLANK);
  end

endmodule
`default_nettype wire
