// GENERATED by hardware/gal/verilog/emit.ts from the term lists in
// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module v3lane (
    input  wire LANE0,
    input  wire LANE1,
    input  wire CRDSEL,
    input  wire GRD,
    input  wire GCPY,
    input  wire GSPN,
    input  wire WM0,
    input  wire WM1,
    input  wire VWE,
    input  wire WSTBV,
    input  wire KEY,
    output wire LOE0,
    output wire LOE1,
    output wire LOE2,
    output wire LOE3,
    output wire LB0,
    output wire UB0,
    output wire LB1,
    output wire UB1,
    output wire PWOE,
    output wire RFOE
);



  // EXTERNAL
  assign LOE0 =
         (GRD & ~LANE1 & ~LANE0)
         | (GCPY & ~LANE1 & ~LANE0)
         | (GSPN & ~LANE1 & ~LANE0);
  // EXTERNAL
  assign LOE1 =
         (GRD & ~LANE1 & LANE0)
         | (GCPY & ~LANE1 & LANE0)
         | (GSPN & ~LANE1 & LANE0);
  // EXTERNAL
  assign LOE2 =
         (GRD & LANE1 & ~LANE0)
         | (GCPY & LANE1 & ~LANE0)
         | (GSPN & LANE1 & ~LANE0);
  // EXTERNAL
  assign LOE3 =
         (GRD & LANE1 & LANE0)
         | (GCPY & LANE1 & LANE0)
         | (GSPN & LANE1 & LANE0);
  // EXTERNAL
  assign LB0 =
         (~VWE & ~KEY)
         | (~VWE & ~WM1)
         | (~VWE & ~WM0)
         | (~VWE & ~GCPY)
         | (~LANE1 & ~LANE0 & ~KEY)
         | (~LANE1 & ~LANE0 & ~WM1)
         | (~LANE1 & ~LANE0 & ~WM0)
         | (~LANE1 & ~LANE0 & ~GCPY);
  // EXTERNAL
  assign UB0 =
         (~VWE & ~KEY)
         | (~VWE & ~WM1)
         | (~VWE & ~WM0)
         | (~VWE & ~GCPY)
         | (~LANE1 & LANE0 & ~KEY)
         | (~LANE1 & LANE0 & ~WM1)
         | (~LANE1 & LANE0 & ~WM0)
         | (~LANE1 & LANE0 & ~GCPY);
  // EXTERNAL
  assign LB1 =
         (~VWE & ~KEY)
         | (~VWE & ~WM1)
         | (~VWE & ~WM0)
         | (~VWE & ~GCPY)
         | (LANE1 & ~LANE0 & ~KEY)
         | (LANE1 & ~LANE0 & ~WM1)
         | (LANE1 & ~LANE0 & ~WM0)
         | (LANE1 & ~LANE0 & ~GCPY);
  // EXTERNAL
  assign UB1 =
         (~VWE & ~KEY)
         | (~VWE & ~WM1)
         | (~VWE & ~WM0)
         | (~VWE & ~GCPY)
         | (LANE1 & LANE0 & ~KEY)
         | (LANE1 & LANE0 & ~WM1)
         | (LANE1 & LANE0 & ~WM0)
         | (LANE1 & LANE0 & ~GCPY);
  // EXTERNAL
  assign PWOE =
         (GSPN & ~WM1 & ~WM0)
         | (GCPY & ~CRDSEL);
  // EXTERNAL
  assign RFOE =
         (~GRD & ~GCPY & ~WSTBV & ~GSPN)
         | (~GRD & ~GCPY & ~WSTBV & WM1)
         | (~GRD & ~GCPY & ~WSTBV & WM0);



endmodule
`default_nettype wire
