// GENERATED by hardware/gal/verilog/emit.ts from the term lists in
// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module v3ptr (
    input  wire CLK25,
    input  wire RESET,
    input  wire D0,
    input  wire D1,
    input  wire D2,
    input  wire D3,
    input  wire D4,
    input  wire D5,
    input  wire D6,
    input  wire D7,
    input  wire WSTBV,
    input  wire WSTART,
    input  wire WM0,
    input  wire WM1,
    input  wire DP0,
    input  wire RP1,
    input  wire RP2,
    input  wire RP3,
    input  wire RP4,
    input  wire WSTEP,
    input  wire CPURF,
    input  wire GSPN,
    input  wire CDONE,
    input  wire CSTEP,
    input  wire CROWADV,
    input  wire CWLOAD,
    input  wire CRDSEL,
    input  wire REGWR,
    input  wire RA0,
    input  wire RA1,
    input  wire RA2,
    input  wire RA3,
    input  wire RA4,
    input  wire FBOEPTR,
    output wire LDWP0,
    output wire LDWP1,
    output wire LDWP2,
    output wire LDWADV,
    output wire LDCP0,
    output wire LDCP1,
    output wire LDCP2,
    output wire LDCW,
    output wire LDCH,
    output wire LDCCTRL,
    output wire WC0,
    output wire WC1,
    output wire WC2,
    output wire WC3,
    output wire WC4,
    output wire WC5,
    output wire WC6,
    output wire WC7,
    output wire WC8,
    output wire WC9,
    output wire WR0,
    output wire WR1,
    output wire WR2,
    output wire WR3,
    output wire WR4,
    output wire WR5,
    output wire WR6,
    output wire WR7,
    output wire WR8,
    output wire CC0,
    output wire CC1,
    output wire CC2,
    output wire CC3,
    output wire CC4,
    output wire CC5,
    output wire CC6,
    output wire CC7,
    output wire CC8,
    output wire CC9,
    output wire CR0,
    output wire CR1,
    output wire CR2,
    output wire CR3,
    output wire CR4,
    output wire CR5,
    output wire CR6,
    output wire CR7,
    output wire CR8,
    output wire CW0,
    output wire CW1,
    output wire CW2,
    output wire CW3,
    output wire CW4,
    output wire CW5,
    output wire CW6,
    output wire CW7,
    output wire CW8,
    output wire CW9,
    output wire CWN0,
    output wire CWN1,
    output wire CWN2,
    output wire CWN3,
    output wire CWN4,
    output wire CWN5,
    output wire CWN6,
    output wire CWN7,
    output wire CWN8,
    output wire CWN9,
    output wire CH0,
    output wire CH1,
    output wire CH2,
    output wire CH3,
    output wire CH4,
    output wire CH5,
    output wire CH6,
    output wire CH7,
    output wire CH8,
    output wire CEOR,
    output wire CHLAST,
    output wire GOQ,
    output wire CBUSY,
    output wire MS0,
    output wire MS1,
    output wire MS2,
    output wire MS3,
    output wire MS4,
    output wire MS5,
    output wire MS6,
    output wire MS7,
    output wire MS8,
    output wire NSL0,
    output wire NSL1,
    output wire NSL2,
    output wire NSL3,
    output wire NSL4,
    output wire NSL5,
    output wire NSL6,
    output wire NSL7,
    output wire WADV0,
    output wire WADV1,
    output wire WADV2,
    output wire SPANBUSY,
    output wire RETIRE,
    output wire SPANEND,
    output wire VWE,
    output wire WINC,
    output wire WROWADV,
    output wire RFA0,
    output wire RIDLE,
    output wire FBA2,
    output wire FBA3,
    output wire FBA4,
    output wire FBA5,
    output wire FBA6,
    output wire FBA7,
    output wire FBA8,
    output wire FBA9,
    output wire FBA10,
    output wire FBA11,
    output wire FBA12,
    output wire FBA13,
    output wire FBA14,
    output wire FBA15,
    output wire FBA16,
    output wire FBA17,
    output wire FBA18,
    output wire LANE0,
    output wire LANE1,
    output wire FBA2_OE,
    output wire FBA3_OE,
    output wire FBA4_OE,
    output wire FBA5_OE,
    output wire FBA6_OE,
    output wire FBA7_OE,
    output wire FBA8_OE,
    output wire FBA9_OE,
    output wire FBA10_OE,
    output wire FBA11_OE,
    output wire FBA12_OE,
    output wire FBA13_OE,
    output wire FBA14_OE,
    output wire FBA15_OE,
    output wire FBA16_OE,
    output wire FBA17_OE,
    output wire FBA18_OE
);

  reg  r_WC0;
  reg  r_WC1;
  reg  r_WC2;
  reg  r_WC3;
  reg  r_WC4;
  reg  r_WC5;
  reg  r_WC6;
  reg  r_WC7;
  reg  r_WC8;
  reg  r_WC9;
  reg  r_WR0;
  reg  r_WR1;
  reg  r_WR2;
  reg  r_WR3;
  reg  r_WR4;
  reg  r_WR5;
  reg  r_WR6;
  reg  r_WR7;
  reg  r_WR8;
  reg  r_CC0;
  reg  r_CC1;
  reg  r_CC2;
  reg  r_CC3;
  reg  r_CC4;
  reg  r_CC5;
  reg  r_CC6;
  reg  r_CC7;
  reg  r_CC8;
  reg  r_CC9;
  reg  r_CR0;
  reg  r_CR1;
  reg  r_CR2;
  reg  r_CR3;
  reg  r_CR4;
  reg  r_CR5;
  reg  r_CR6;
  reg  r_CR7;
  reg  r_CR8;
  reg  r_CW0;
  reg  r_CW1;
  reg  r_CW2;
  reg  r_CW3;
  reg  r_CW4;
  reg  r_CW5;
  reg  r_CW6;
  reg  r_CW7;
  reg  r_CW8;
  reg  r_CW9;
  reg  r_CWN0;
  reg  r_CWN1;
  reg  r_CWN2;
  reg  r_CWN3;
  reg  r_CWN4;
  reg  r_CWN5;
  reg  r_CWN6;
  reg  r_CWN7;
  reg  r_CWN8;
  reg  r_CWN9;
  reg  r_CH0;
  reg  r_CH1;
  reg  r_CH2;
  reg  r_CH3;
  reg  r_CH4;
  reg  r_CH5;
  reg  r_CH6;
  reg  r_CH7;
  reg  r_CH8;
  reg  r_GOQ;
  reg  r_CBUSY;
  reg  r_MS0;
  reg  r_MS1;
  reg  r_MS2;
  reg  r_MS3;
  reg  r_MS4;
  reg  r_MS5;
  reg  r_MS6;
  reg  r_MS7;
  reg  r_MS8;
  reg  r_NSL0;
  reg  r_NSL1;
  reg  r_NSL2;
  reg  r_NSL3;
  reg  r_NSL4;
  reg  r_NSL5;
  reg  r_NSL6;
  reg  r_NSL7;
  reg  r_WADV0;
  reg  r_WADV1;
  reg  r_WADV2;
  reg  r_SPANBUSY;

  assign WC0 = r_WC0;
  assign WC1 = r_WC1;
  assign WC2 = r_WC2;
  assign WC3 = r_WC3;
  assign WC4 = r_WC4;
  assign WC5 = r_WC5;
  assign WC6 = r_WC6;
  assign WC7 = r_WC7;
  assign WC8 = r_WC8;
  assign WC9 = r_WC9;
  assign WR0 = r_WR0;
  assign WR1 = r_WR1;
  assign WR2 = r_WR2;
  assign WR3 = r_WR3;
  assign WR4 = r_WR4;
  assign WR5 = r_WR5;
  assign WR6 = r_WR6;
  assign WR7 = r_WR7;
  assign WR8 = r_WR8;
  assign CC0 = r_CC0;
  assign CC1 = r_CC1;
  assign CC2 = r_CC2;
  assign CC3 = r_CC3;
  assign CC4 = r_CC4;
  assign CC5 = r_CC5;
  assign CC6 = r_CC6;
  assign CC7 = r_CC7;
  assign CC8 = r_CC8;
  assign CC9 = r_CC9;
  assign CR0 = r_CR0;
  assign CR1 = r_CR1;
  assign CR2 = r_CR2;
  assign CR3 = r_CR3;
  assign CR4 = r_CR4;
  assign CR5 = r_CR5;
  assign CR6 = r_CR6;
  assign CR7 = r_CR7;
  assign CR8 = r_CR8;
  assign CW0 = r_CW0;
  assign CW1 = r_CW1;
  assign CW2 = r_CW2;
  assign CW3 = r_CW3;
  assign CW4 = r_CW4;
  assign CW5 = r_CW5;
  assign CW6 = r_CW6;
  assign CW7 = r_CW7;
  assign CW8 = r_CW8;
  assign CW9 = r_CW9;
  assign CWN0 = r_CWN0;
  assign CWN1 = r_CWN1;
  assign CWN2 = r_CWN2;
  assign CWN3 = r_CWN3;
  assign CWN4 = r_CWN4;
  assign CWN5 = r_CWN5;
  assign CWN6 = r_CWN6;
  assign CWN7 = r_CWN7;
  assign CWN8 = r_CWN8;
  assign CWN9 = r_CWN9;
  assign CH0 = r_CH0;
  assign CH1 = r_CH1;
  assign CH2 = r_CH2;
  assign CH3 = r_CH3;
  assign CH4 = r_CH4;
  assign CH5 = r_CH5;
  assign CH6 = r_CH6;
  assign CH7 = r_CH7;
  assign CH8 = r_CH8;
  assign GOQ = r_GOQ;
  assign CBUSY = r_CBUSY;
  assign MS0 = r_MS0;
  assign MS1 = r_MS1;
  assign MS2 = r_MS2;
  assign MS3 = r_MS3;
  assign MS4 = r_MS4;
  assign MS5 = r_MS5;
  assign MS6 = r_MS6;
  assign MS7 = r_MS7;
  assign MS8 = r_MS8;
  assign NSL0 = r_NSL0;
  assign NSL1 = r_NSL1;
  assign NSL2 = r_NSL2;
  assign NSL3 = r_NSL3;
  assign NSL4 = r_NSL4;
  assign NSL5 = r_NSL5;
  assign NSL6 = r_NSL6;
  assign NSL7 = r_NSL7;
  assign WADV0 = r_WADV0;
  assign WADV1 = r_WADV1;
  assign WADV2 = r_WADV2;
  assign SPANBUSY = r_SPANBUSY;

  // buried
  assign LDWP0 =
         (REGWR & ~RA4 & RA3 & ~RA2 & ~RA1 & ~RA0);
  // buried
  assign LDWP1 =
         (REGWR & ~RA4 & RA3 & ~RA2 & ~RA1 & RA0);
  // buried
  assign LDWP2 =
         (REGWR & ~RA4 & RA3 & ~RA2 & RA1 & ~RA0);
  // buried
  assign LDWADV =
         (REGWR & ~RA4 & RA3 & ~RA2 & RA1 & RA0);
  // buried
  assign LDCP0 =
         (REGWR & RA4 & ~RA3 & ~RA2 & RA1 & ~RA0);
  // buried
  assign LDCP1 =
         (REGWR & RA4 & ~RA3 & ~RA2 & RA1 & RA0);
  // buried
  assign LDCP2 =
         (REGWR & RA4 & ~RA3 & RA2 & ~RA1 & ~RA0);
  // buried
  assign LDCW =
         (REGWR & RA4 & ~RA3 & RA2 & ~RA1 & RA0);
  // buried
  assign LDCH =
         (REGWR & RA4 & ~RA3 & RA2 & RA1 & ~RA0);
  // buried
  assign LDCCTRL =
         (REGWR & RA4 & ~RA3 & RA2 & RA1 & RA0);
  // EXTERNAL - the last byte of a row - ~N + N - 1, one product term
  assign CEOR =
         (~CWN0 & CWN1 & CWN2 & CWN3 & CWN4 & CWN5 & CWN6 & CWN7 & CWN8 & CWN9);
  // EXTERNAL
  assign CHLAST =
         (~CH0 & CH1 & CH2 & CH3 & CH4 & CH5 & CH6 & CH7 & CH8);
  // EXTERNAL - one byte goes to VRAM: also WPTR's column step, the serialiser's shift and SPANLEN's count
  assign RETIRE =
         (SPANBUSY & GSPN & DP0);
  // buried
  assign SPANEND =
         (RETIRE & ~WM1 & ~WM0)
         | (RETIRE & WM0 & MS1 & ~MS2 & ~MS3 & ~MS4 & ~MS5 & ~MS6 & ~MS7 & ~MS8)
         | (RETIRE & WM1 & ~WM0 & NSL0 & NSL1 & NSL2 & NSL3 & NSL4 & NSL5 & NSL6 & NSL7);
  // EXTERNAL - a retire, except a transparent pixel in sprite mode; or a copy write
  assign VWE =
         (RETIRE & ~WM1)
         | (RETIRE & ~WM0)
         | (RETIRE & MS0)
         | (CSTEP);
  // buried
  assign WINC =
         (RETIRE)
         | (WSTEP);
  // EXTERNAL
  assign WROWADV =
         (SPANEND & WADV0)
         | (SPANEND & WADV1)
         | (CROWADV);
  // EXTERNAL - §5: the mask bit IS the register file's address bit 0, inverted
  assign RFA0 =
         (CPURF & RA0)
         | (SPANBUSY & RIDLE & ~MS0 & WM0)
         | (~CPURF & ~SPANBUSY & RIDLE)
         | (RP2)
         | (RP4);
  // buried
  assign RIDLE =
         (~RP1 & ~RP2 & ~RP3 & ~RP4);
  // EXTERNAL
  assign FBA2 =
         (~CRDSEL & WC2)
         | (CRDSEL & CC2);
  // EXTERNAL
  assign FBA3 =
         (~CRDSEL & WC3)
         | (CRDSEL & CC3);
  // EXTERNAL
  assign FBA4 =
         (~CRDSEL & WC4)
         | (CRDSEL & CC4);
  // EXTERNAL
  assign FBA5 =
         (~CRDSEL & WC5)
         | (CRDSEL & CC5);
  // EXTERNAL
  assign FBA6 =
         (~CRDSEL & WC6)
         | (CRDSEL & CC6);
  // EXTERNAL
  assign FBA7 =
         (~CRDSEL & WC7)
         | (CRDSEL & CC7);
  // EXTERNAL
  assign FBA8 =
         (~CRDSEL & WC8)
         | (CRDSEL & CC8);
  // EXTERNAL
  assign FBA9 =
         (~CRDSEL & WC9)
         | (CRDSEL & CC9);
  // EXTERNAL
  assign FBA10 =
         (~CRDSEL & WR0)
         | (CRDSEL & CR0);
  // EXTERNAL
  assign FBA11 =
         (~CRDSEL & WR1)
         | (CRDSEL & CR1);
  // EXTERNAL
  assign FBA12 =
         (~CRDSEL & WR2)
         | (CRDSEL & CR2);
  // EXTERNAL
  assign FBA13 =
         (~CRDSEL & WR3)
         | (CRDSEL & CR3);
  // EXTERNAL
  assign FBA14 =
         (~CRDSEL & WR4)
         | (CRDSEL & CR4);
  // EXTERNAL
  assign FBA15 =
         (~CRDSEL & WR5)
         | (CRDSEL & CR5);
  // EXTERNAL
  assign FBA16 =
         (~CRDSEL & WR6)
         | (CRDSEL & CR6);
  // EXTERNAL
  assign FBA17 =
         (~CRDSEL & WR7)
         | (CRDSEL & CR7);
  // EXTERNAL
  assign FBA18 =
         (~CRDSEL & WR8)
         | (CRDSEL & CR8);
  // EXTERNAL
  assign LANE0 =
         (~CRDSEL & WC0)
         | (CRDSEL & CC0);
  // EXTERNAL
  assign LANE1 =
         (~CRDSEL & WC1)
         | (CRDSEL & CC1);

  // FBA2 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA2_OE =
         (FBOEPTR);
  // FBA3 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA3_OE =
         (FBOEPTR);
  // FBA4 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA4_OE =
         (FBOEPTR);
  // FBA5 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA5_OE =
         (FBOEPTR);
  // FBA6 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA6_OE =
         (FBOEPTR);
  // FBA7 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA7_OE =
         (FBOEPTR);
  // FBA8 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA8_OE =
         (FBOEPTR);
  // FBA9 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA9_OE =
         (FBOEPTR);
  // FBA10 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA10_OE =
         (FBOEPTR);
  // FBA11 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA11_OE =
         (FBOEPTR);
  // FBA12 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA12_OE =
         (FBOEPTR);
  // FBA13 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA13_OE =
         (FBOEPTR);
  // FBA14 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA14_OE =
         (FBOEPTR);
  // FBA15 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA15_OE =
         (FBOEPTR);
  // FBA16 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA16_OE =
         (FBOEPTR);
  // FBA17 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA17_OE =
         (FBOEPTR);
  // FBA18 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA18_OE =
         (FBOEPTR);

  always @(posedge CLK25) begin
      r_WC0 <=
         (LDWP0 & D0)
         | (RP1 & D0)
         | (~LDWP0 & ~RP1 & WINC & ~WADV2 & ~WC0)
         | (~LDWP0 & ~RP1 & WINC & WADV2 & WC0)
         | (~LDWP0 & ~RP1 & ~WINC & WC0);
      r_WC1 <=
         (LDWP0 & D1)
         | (RP1 & D1)
         | (~LDWP0 & ~RP1 & WINC & WC1 & ~WADV2 & ~WC0)
         | (~LDWP0 & ~RP1 & WINC & ~WC1 & WADV2)
         | (~LDWP0 & ~RP1 & WINC & ~WC1 & WC0)
         | (~LDWP0 & ~RP1 & ~WINC & WC1);
      r_WC2 <=
         (LDWP0 & D2)
         | (RP1 & D2)
         | (~LDWP0 & ~RP1 & WINC & WC2 & ~WC1)
         | (~LDWP0 & ~RP1 & WINC & WC2 & ~WADV2 & ~WC0)
         | (~LDWP0 & ~RP1 & WINC & ~WC2 & WC1 & WADV2)
         | (~LDWP0 & ~RP1 & WINC & ~WC2 & WC1 & WC0)
         | (~LDWP0 & ~RP1 & ~WINC & WC2);
      r_WC3 <=
         (LDWP0 & D3)
         | (RP1 & D3)
         | (~LDWP0 & ~RP1 & WINC & WC3 & ~WC1)
         | (~LDWP0 & ~RP1 & WINC & WC3 & ~WC2)
         | (~LDWP0 & ~RP1 & WINC & WC3 & ~WADV2 & ~WC0)
         | (~LDWP0 & ~RP1 & WINC & ~WC3 & WC1 & WC2 & WADV2)
         | (~LDWP0 & ~RP1 & WINC & ~WC3 & WC1 & WC2 & WC0)
         | (~LDWP0 & ~RP1 & ~WINC & WC3);
      r_WC4 <=
         (LDWP0 & D4)
         | (RP1 & D4)
         | (~LDWP0 & ~RP1 & WINC & WC4 & ~WC1)
         | (~LDWP0 & ~RP1 & WINC & WC4 & ~WC2)
         | (~LDWP0 & ~RP1 & WINC & WC4 & ~WC3)
         | (~LDWP0 & ~RP1 & WINC & WC4 & ~WADV2 & ~WC0)
         | (~LDWP0 & ~RP1 & WINC & ~WC4 & WC1 & WC2 & WC3 & WADV2)
         | (~LDWP0 & ~RP1 & WINC & ~WC4 & WC1 & WC2 & WC3 & WC0)
         | (~LDWP0 & ~RP1 & ~WINC & WC4);
      r_WC5 <=
         (LDWP0 & D5)
         | (RP1 & D5)
         | (~LDWP0 & ~RP1 & WINC & WC5 & ~WC1)
         | (~LDWP0 & ~RP1 & WINC & WC5 & ~WC2)
         | (~LDWP0 & ~RP1 & WINC & WC5 & ~WC3)
         | (~LDWP0 & ~RP1 & WINC & WC5 & ~WC4)
         | (~LDWP0 & ~RP1 & WINC & WC5 & ~WADV2 & ~WC0)
         | (~LDWP0 & ~RP1 & WINC & ~WC5 & WC1 & WC2 & WC3 & WC4 & WADV2)
         | (~LDWP0 & ~RP1 & WINC & ~WC5 & WC1 & WC2 & WC3 & WC4 & WC0)
         | (~LDWP0 & ~RP1 & ~WINC & WC5);
      r_WC6 <=
         (LDWP0 & D6)
         | (RP1 & D6)
         | (~LDWP0 & ~RP1 & WINC & WC6 & ~WC1)
         | (~LDWP0 & ~RP1 & WINC & WC6 & ~WC2)
         | (~LDWP0 & ~RP1 & WINC & WC6 & ~WC3)
         | (~LDWP0 & ~RP1 & WINC & WC6 & ~WC4)
         | (~LDWP0 & ~RP1 & WINC & WC6 & ~WC5)
         | (~LDWP0 & ~RP1 & WINC & WC6 & ~WADV2 & ~WC0)
         | (~LDWP0 & ~RP1 & WINC & ~WC6 & WC1 & WC2 & WC3 & WC4 & WC5 & WADV2)
         | (~LDWP0 & ~RP1 & WINC & ~WC6 & WC1 & WC2 & WC3 & WC4 & WC5 & WC0)
         | (~LDWP0 & ~RP1 & ~WINC & WC6);
      r_WC7 <=
         (LDWP0 & D7)
         | (RP1 & D7)
         | (~LDWP0 & ~RP1 & WINC & WC7 & ~WC1)
         | (~LDWP0 & ~RP1 & WINC & WC7 & ~WC2)
         | (~LDWP0 & ~RP1 & WINC & WC7 & ~WC3)
         | (~LDWP0 & ~RP1 & WINC & WC7 & ~WC4)
         | (~LDWP0 & ~RP1 & WINC & WC7 & ~WC5)
         | (~LDWP0 & ~RP1 & WINC & WC7 & ~WC6)
         | (~LDWP0 & ~RP1 & WINC & WC7 & ~WADV2 & ~WC0)
         | (~LDWP0 & ~RP1 & WINC & ~WC7 & WC1 & WC2 & WC3 & WC4 & WC5 & WC6 & WADV2)
         | (~LDWP0 & ~RP1 & WINC & ~WC7 & WC1 & WC2 & WC3 & WC4 & WC5 & WC6 & WC0)
         | (~LDWP0 & ~RP1 & ~WINC & WC7);
      r_WC8 <=
         (LDWP1 & D0)
         | (RP2 & D0)
         | (~LDWP1 & ~RP2 & WINC & WC8 & ~WC1)
         | (~LDWP1 & ~RP2 & WINC & WC8 & ~WC2)
         | (~LDWP1 & ~RP2 & WINC & WC8 & ~WC3)
         | (~LDWP1 & ~RP2 & WINC & WC8 & ~WC4)
         | (~LDWP1 & ~RP2 & WINC & WC8 & ~WC5)
         | (~LDWP1 & ~RP2 & WINC & WC8 & ~WC6)
         | (~LDWP1 & ~RP2 & WINC & WC8 & ~WC7)
         | (~LDWP1 & ~RP2 & WINC & WC8 & ~WADV2 & ~WC0)
         | (~LDWP1 & ~RP2 & WINC & ~WC8 & WC1 & WC2 & WC3 & WC4 & WC5 & WC6 & WC7 & WADV2)
         | (~LDWP1 & ~RP2 & WINC & ~WC8 & WC1 & WC2 & WC3 & WC4 & WC5 & WC6 & WC7 & WC0)
         | (~LDWP1 & ~RP2 & ~WINC & WC8);
      r_WC9 <=
         (LDWP1 & D1)
         | (RP2 & D1)
         | (~LDWP1 & ~RP2 & WINC & WC9 & ~WC1)
         | (~LDWP1 & ~RP2 & WINC & WC9 & ~WC2)
         | (~LDWP1 & ~RP2 & WINC & WC9 & ~WC3)
         | (~LDWP1 & ~RP2 & WINC & WC9 & ~WC4)
         | (~LDWP1 & ~RP2 & WINC & WC9 & ~WC5)
         | (~LDWP1 & ~RP2 & WINC & WC9 & ~WC6)
         | (~LDWP1 & ~RP2 & WINC & WC9 & ~WC7)
         | (~LDWP1 & ~RP2 & WINC & WC9 & ~WC8)
         | (~LDWP1 & ~RP2 & WINC & WC9 & ~WADV2 & ~WC0)
         | (~LDWP1 & ~RP2 & WINC & ~WC9 & WC1 & WC2 & WC3 & WC4 & WC5 & WC6 & WC7 & WC8 & WADV2)
         | (~LDWP1 & ~RP2 & WINC & ~WC9 & WC1 & WC2 & WC3 & WC4 & WC5 & WC6 & WC7 & WC8 & WC0)
         | (~LDWP1 & ~RP2 & ~WINC & WC9);
      r_WR0 <=
         (LDWP1 & D2)
         | (~LDWP1 & WROWADV & ~WR0)
         | (~LDWP1 & ~WROWADV & WR0);
      r_WR1 <=
         (LDWP1 & D3)
         | (~LDWP1 & WROWADV & WR1 & ~WR0)
         | (~LDWP1 & WROWADV & ~WR1 & WR0)
         | (~LDWP1 & ~WROWADV & WR1);
      r_WR2 <=
         (LDWP1 & D4)
         | (~LDWP1 & WROWADV & WR2 & ~WR0)
         | (~LDWP1 & WROWADV & WR2 & ~WR1)
         | (~LDWP1 & WROWADV & ~WR2 & WR0 & WR1)
         | (~LDWP1 & ~WROWADV & WR2);
      r_WR3 <=
         (LDWP1 & D5)
         | (~LDWP1 & WROWADV & WR3 & ~WR0)
         | (~LDWP1 & WROWADV & WR3 & ~WR1)
         | (~LDWP1 & WROWADV & WR3 & ~WR2)
         | (~LDWP1 & WROWADV & ~WR3 & WR0 & WR1 & WR2)
         | (~LDWP1 & ~WROWADV & WR3);
      r_WR4 <=
         (LDWP1 & D6)
         | (~LDWP1 & WROWADV & WR4 & ~WR0)
         | (~LDWP1 & WROWADV & WR4 & ~WR1)
         | (~LDWP1 & WROWADV & WR4 & ~WR2)
         | (~LDWP1 & WROWADV & WR4 & ~WR3)
         | (~LDWP1 & WROWADV & ~WR4 & WR0 & WR1 & WR2 & WR3)
         | (~LDWP1 & ~WROWADV & WR4);
      r_WR5 <=
         (LDWP1 & D7)
         | (~LDWP1 & WROWADV & WR5 & ~WR0)
         | (~LDWP1 & WROWADV & WR5 & ~WR1)
         | (~LDWP1 & WROWADV & WR5 & ~WR2)
         | (~LDWP1 & WROWADV & WR5 & ~WR3)
         | (~LDWP1 & WROWADV & WR5 & ~WR4)
         | (~LDWP1 & WROWADV & ~WR5 & WR0 & WR1 & WR2 & WR3 & WR4)
         | (~LDWP1 & ~WROWADV & WR5);
      r_WR6 <=
         (LDWP2 & D0)
         | (~LDWP2 & WROWADV & WR6 & ~WR0)
         | (~LDWP2 & WROWADV & WR6 & ~WR1)
         | (~LDWP2 & WROWADV & WR6 & ~WR2)
         | (~LDWP2 & WROWADV & WR6 & ~WR3)
         | (~LDWP2 & WROWADV & WR6 & ~WR4)
         | (~LDWP2 & WROWADV & WR6 & ~WR5)
         | (~LDWP2 & WROWADV & ~WR6 & WR0 & WR1 & WR2 & WR3 & WR4 & WR5)
         | (~LDWP2 & ~WROWADV & WR6);
      r_WR7 <=
         (LDWP2 & D1)
         | (~LDWP2 & WROWADV & WR7 & ~WR0)
         | (~LDWP2 & WROWADV & WR7 & ~WR1)
         | (~LDWP2 & WROWADV & WR7 & ~WR2)
         | (~LDWP2 & WROWADV & WR7 & ~WR3)
         | (~LDWP2 & WROWADV & WR7 & ~WR4)
         | (~LDWP2 & WROWADV & WR7 & ~WR5)
         | (~LDWP2 & WROWADV & WR7 & ~WR6)
         | (~LDWP2 & WROWADV & ~WR7 & WR0 & WR1 & WR2 & WR3 & WR4 & WR5 & WR6)
         | (~LDWP2 & ~WROWADV & WR7);
      r_WR8 <=
         (LDWP2 & D2)
         | (~LDWP2 & WROWADV & WR8 & ~WR0)
         | (~LDWP2 & WROWADV & WR8 & ~WR1)
         | (~LDWP2 & WROWADV & WR8 & ~WR2)
         | (~LDWP2 & WROWADV & WR8 & ~WR3)
         | (~LDWP2 & WROWADV & WR8 & ~WR4)
         | (~LDWP2 & WROWADV & WR8 & ~WR5)
         | (~LDWP2 & WROWADV & WR8 & ~WR6)
         | (~LDWP2 & WROWADV & WR8 & ~WR7)
         | (~LDWP2 & WROWADV & ~WR8 & WR0 & WR1 & WR2 & WR3 & WR4 & WR5 & WR6 & WR7)
         | (~LDWP2 & ~WROWADV & WR8);
      r_CC0 <=
         (LDCP0 & D0)
         | (RP3 & D0)
         | (~LDCP0 & ~RP3 & CSTEP & ~CC0)
         | (~LDCP0 & ~RP3 & ~CSTEP & CC0);
      r_CC1 <=
         (LDCP0 & D1)
         | (RP3 & D1)
         | (~LDCP0 & ~RP3 & CSTEP & CC1 & ~CC0)
         | (~LDCP0 & ~RP3 & CSTEP & ~CC1 & CC0)
         | (~LDCP0 & ~RP3 & ~CSTEP & CC1);
      r_CC2 <=
         (LDCP0 & D2)
         | (RP3 & D2)
         | (~LDCP0 & ~RP3 & CSTEP & CC2 & ~CC0)
         | (~LDCP0 & ~RP3 & CSTEP & CC2 & ~CC1)
         | (~LDCP0 & ~RP3 & CSTEP & ~CC2 & CC0 & CC1)
         | (~LDCP0 & ~RP3 & ~CSTEP & CC2);
      r_CC3 <=
         (LDCP0 & D3)
         | (RP3 & D3)
         | (~LDCP0 & ~RP3 & CSTEP & CC3 & ~CC0)
         | (~LDCP0 & ~RP3 & CSTEP & CC3 & ~CC1)
         | (~LDCP0 & ~RP3 & CSTEP & CC3 & ~CC2)
         | (~LDCP0 & ~RP3 & CSTEP & ~CC3 & CC0 & CC1 & CC2)
         | (~LDCP0 & ~RP3 & ~CSTEP & CC3);
      r_CC4 <=
         (LDCP0 & D4)
         | (RP3 & D4)
         | (~LDCP0 & ~RP3 & CSTEP & CC4 & ~CC0)
         | (~LDCP0 & ~RP3 & CSTEP & CC4 & ~CC1)
         | (~LDCP0 & ~RP3 & CSTEP & CC4 & ~CC2)
         | (~LDCP0 & ~RP3 & CSTEP & CC4 & ~CC3)
         | (~LDCP0 & ~RP3 & CSTEP & ~CC4 & CC0 & CC1 & CC2 & CC3)
         | (~LDCP0 & ~RP3 & ~CSTEP & CC4);
      r_CC5 <=
         (LDCP0 & D5)
         | (RP3 & D5)
         | (~LDCP0 & ~RP3 & CSTEP & CC5 & ~CC0)
         | (~LDCP0 & ~RP3 & CSTEP & CC5 & ~CC1)
         | (~LDCP0 & ~RP3 & CSTEP & CC5 & ~CC2)
         | (~LDCP0 & ~RP3 & CSTEP & CC5 & ~CC3)
         | (~LDCP0 & ~RP3 & CSTEP & CC5 & ~CC4)
         | (~LDCP0 & ~RP3 & CSTEP & ~CC5 & CC0 & CC1 & CC2 & CC3 & CC4)
         | (~LDCP0 & ~RP3 & ~CSTEP & CC5);
      r_CC6 <=
         (LDCP0 & D6)
         | (RP3 & D6)
         | (~LDCP0 & ~RP3 & CSTEP & CC6 & ~CC0)
         | (~LDCP0 & ~RP3 & CSTEP & CC6 & ~CC1)
         | (~LDCP0 & ~RP3 & CSTEP & CC6 & ~CC2)
         | (~LDCP0 & ~RP3 & CSTEP & CC6 & ~CC3)
         | (~LDCP0 & ~RP3 & CSTEP & CC6 & ~CC4)
         | (~LDCP0 & ~RP3 & CSTEP & CC6 & ~CC5)
         | (~LDCP0 & ~RP3 & CSTEP & ~CC6 & CC0 & CC1 & CC2 & CC3 & CC4 & CC5)
         | (~LDCP0 & ~RP3 & ~CSTEP & CC6);
      r_CC7 <=
         (LDCP0 & D7)
         | (RP3 & D7)
         | (~LDCP0 & ~RP3 & CSTEP & CC7 & ~CC0)
         | (~LDCP0 & ~RP3 & CSTEP & CC7 & ~CC1)
         | (~LDCP0 & ~RP3 & CSTEP & CC7 & ~CC2)
         | (~LDCP0 & ~RP3 & CSTEP & CC7 & ~CC3)
         | (~LDCP0 & ~RP3 & CSTEP & CC7 & ~CC4)
         | (~LDCP0 & ~RP3 & CSTEP & CC7 & ~CC5)
         | (~LDCP0 & ~RP3 & CSTEP & CC7 & ~CC6)
         | (~LDCP0 & ~RP3 & CSTEP & ~CC7 & CC0 & CC1 & CC2 & CC3 & CC4 & CC5 & CC6)
         | (~LDCP0 & ~RP3 & ~CSTEP & CC7);
      r_CC8 <=
         (LDCP1 & D0)
         | (RP4 & D0)
         | (~LDCP1 & ~RP4 & CSTEP & CC8 & ~CC0)
         | (~LDCP1 & ~RP4 & CSTEP & CC8 & ~CC1)
         | (~LDCP1 & ~RP4 & CSTEP & CC8 & ~CC2)
         | (~LDCP1 & ~RP4 & CSTEP & CC8 & ~CC3)
         | (~LDCP1 & ~RP4 & CSTEP & CC8 & ~CC4)
         | (~LDCP1 & ~RP4 & CSTEP & CC8 & ~CC5)
         | (~LDCP1 & ~RP4 & CSTEP & CC8 & ~CC6)
         | (~LDCP1 & ~RP4 & CSTEP & CC8 & ~CC7)
         | (~LDCP1 & ~RP4 & CSTEP & ~CC8 & CC0 & CC1 & CC2 & CC3 & CC4 & CC5 & CC6 & CC7)
         | (~LDCP1 & ~RP4 & ~CSTEP & CC8);
      r_CC9 <=
         (LDCP1 & D1)
         | (RP4 & D1)
         | (~LDCP1 & ~RP4 & CSTEP & CC9 & ~CC0)
         | (~LDCP1 & ~RP4 & CSTEP & CC9 & ~CC1)
         | (~LDCP1 & ~RP4 & CSTEP & CC9 & ~CC2)
         | (~LDCP1 & ~RP4 & CSTEP & CC9 & ~CC3)
         | (~LDCP1 & ~RP4 & CSTEP & CC9 & ~CC4)
         | (~LDCP1 & ~RP4 & CSTEP & CC9 & ~CC5)
         | (~LDCP1 & ~RP4 & CSTEP & CC9 & ~CC6)
         | (~LDCP1 & ~RP4 & CSTEP & CC9 & ~CC7)
         | (~LDCP1 & ~RP4 & CSTEP & CC9 & ~CC8)
         | (~LDCP1 & ~RP4 & CSTEP & ~CC9 & CC0 & CC1 & CC2 & CC3 & CC4 & CC5 & CC6 & CC7 & CC8)
         | (~LDCP1 & ~RP4 & ~CSTEP & CC9);
      r_CR0 <=
         (LDCP1 & D2)
         | (~LDCP1 & CROWADV & ~CR0)
         | (~LDCP1 & ~CROWADV & CR0);
      r_CR1 <=
         (LDCP1 & D3)
         | (~LDCP1 & CROWADV & CR1 & ~CR0)
         | (~LDCP1 & CROWADV & ~CR1 & CR0)
         | (~LDCP1 & ~CROWADV & CR1);
      r_CR2 <=
         (LDCP1 & D4)
         | (~LDCP1 & CROWADV & CR2 & ~CR0)
         | (~LDCP1 & CROWADV & CR2 & ~CR1)
         | (~LDCP1 & CROWADV & ~CR2 & CR0 & CR1)
         | (~LDCP1 & ~CROWADV & CR2);
      r_CR3 <=
         (LDCP1 & D5)
         | (~LDCP1 & CROWADV & CR3 & ~CR0)
         | (~LDCP1 & CROWADV & CR3 & ~CR1)
         | (~LDCP1 & CROWADV & CR3 & ~CR2)
         | (~LDCP1 & CROWADV & ~CR3 & CR0 & CR1 & CR2)
         | (~LDCP1 & ~CROWADV & CR3);
      r_CR4 <=
         (LDCP1 & D6)
         | (~LDCP1 & CROWADV & CR4 & ~CR0)
         | (~LDCP1 & CROWADV & CR4 & ~CR1)
         | (~LDCP1 & CROWADV & CR4 & ~CR2)
         | (~LDCP1 & CROWADV & CR4 & ~CR3)
         | (~LDCP1 & CROWADV & ~CR4 & CR0 & CR1 & CR2 & CR3)
         | (~LDCP1 & ~CROWADV & CR4);
      r_CR5 <=
         (LDCP1 & D7)
         | (~LDCP1 & CROWADV & CR5 & ~CR0)
         | (~LDCP1 & CROWADV & CR5 & ~CR1)
         | (~LDCP1 & CROWADV & CR5 & ~CR2)
         | (~LDCP1 & CROWADV & CR5 & ~CR3)
         | (~LDCP1 & CROWADV & CR5 & ~CR4)
         | (~LDCP1 & CROWADV & ~CR5 & CR0 & CR1 & CR2 & CR3 & CR4)
         | (~LDCP1 & ~CROWADV & CR5);
      r_CR6 <=
         (LDCP2 & D0)
         | (~LDCP2 & CROWADV & CR6 & ~CR0)
         | (~LDCP2 & CROWADV & CR6 & ~CR1)
         | (~LDCP2 & CROWADV & CR6 & ~CR2)
         | (~LDCP2 & CROWADV & CR6 & ~CR3)
         | (~LDCP2 & CROWADV & CR6 & ~CR4)
         | (~LDCP2 & CROWADV & CR6 & ~CR5)
         | (~LDCP2 & CROWADV & ~CR6 & CR0 & CR1 & CR2 & CR3 & CR4 & CR5)
         | (~LDCP2 & ~CROWADV & CR6);
      r_CR7 <=
         (LDCP2 & D1)
         | (~LDCP2 & CROWADV & CR7 & ~CR0)
         | (~LDCP2 & CROWADV & CR7 & ~CR1)
         | (~LDCP2 & CROWADV & CR7 & ~CR2)
         | (~LDCP2 & CROWADV & CR7 & ~CR3)
         | (~LDCP2 & CROWADV & CR7 & ~CR4)
         | (~LDCP2 & CROWADV & CR7 & ~CR5)
         | (~LDCP2 & CROWADV & CR7 & ~CR6)
         | (~LDCP2 & CROWADV & ~CR7 & CR0 & CR1 & CR2 & CR3 & CR4 & CR5 & CR6)
         | (~LDCP2 & ~CROWADV & CR7);
      r_CR8 <=
         (LDCP2 & D2)
         | (~LDCP2 & CROWADV & CR8 & ~CR0)
         | (~LDCP2 & CROWADV & CR8 & ~CR1)
         | (~LDCP2 & CROWADV & CR8 & ~CR2)
         | (~LDCP2 & CROWADV & CR8 & ~CR3)
         | (~LDCP2 & CROWADV & CR8 & ~CR4)
         | (~LDCP2 & CROWADV & CR8 & ~CR5)
         | (~LDCP2 & CROWADV & CR8 & ~CR6)
         | (~LDCP2 & CROWADV & CR8 & ~CR7)
         | (~LDCP2 & CROWADV & ~CR8 & CR0 & CR1 & CR2 & CR3 & CR4 & CR5 & CR6 & CR7)
         | (~LDCP2 & ~CROWADV & CR8);
      r_CW0 <=
         (LDCW & D0)
         | (CW0 & ~LDCW);
      r_CW1 <=
         (LDCW & D1)
         | (CW1 & ~LDCW);
      r_CW2 <=
         (LDCW & D2)
         | (CW2 & ~LDCW);
      r_CW3 <=
         (LDCW & D3)
         | (CW3 & ~LDCW);
      r_CW4 <=
         (LDCW & D4)
         | (CW4 & ~LDCW);
      r_CW5 <=
         (LDCW & D5)
         | (CW5 & ~LDCW);
      r_CW6 <=
         (LDCW & D6)
         | (CW6 & ~LDCW);
      r_CW7 <=
         (LDCW & D7)
         | (CW7 & ~LDCW);
      r_CW8 <=
         (LDCCTRL & D3)
         | (CW8 & ~LDCCTRL);
      r_CW9 <=
         (LDCCTRL & D4)
         | (CW9 & ~LDCCTRL);
      r_CWN0 <=
         (CWLOAD & ~CW0)
         | (~CWLOAD & CSTEP & ~CWN0)
         | (~CWLOAD & ~CSTEP & CWN0);
      r_CWN1 <=
         (CWLOAD & ~CW1)
         | (~CWLOAD & CSTEP & CWN1 & ~CWN0)
         | (~CWLOAD & CSTEP & ~CWN1 & CWN0)
         | (~CWLOAD & ~CSTEP & CWN1);
      r_CWN2 <=
         (CWLOAD & ~CW2)
         | (~CWLOAD & CSTEP & CWN2 & ~CWN0)
         | (~CWLOAD & CSTEP & CWN2 & ~CWN1)
         | (~CWLOAD & CSTEP & ~CWN2 & CWN0 & CWN1)
         | (~CWLOAD & ~CSTEP & CWN2);
      r_CWN3 <=
         (CWLOAD & ~CW3)
         | (~CWLOAD & CSTEP & CWN3 & ~CWN0)
         | (~CWLOAD & CSTEP & CWN3 & ~CWN1)
         | (~CWLOAD & CSTEP & CWN3 & ~CWN2)
         | (~CWLOAD & CSTEP & ~CWN3 & CWN0 & CWN1 & CWN2)
         | (~CWLOAD & ~CSTEP & CWN3);
      r_CWN4 <=
         (CWLOAD & ~CW4)
         | (~CWLOAD & CSTEP & CWN4 & ~CWN0)
         | (~CWLOAD & CSTEP & CWN4 & ~CWN1)
         | (~CWLOAD & CSTEP & CWN4 & ~CWN2)
         | (~CWLOAD & CSTEP & CWN4 & ~CWN3)
         | (~CWLOAD & CSTEP & ~CWN4 & CWN0 & CWN1 & CWN2 & CWN3)
         | (~CWLOAD & ~CSTEP & CWN4);
      r_CWN5 <=
         (CWLOAD & ~CW5)
         | (~CWLOAD & CSTEP & CWN5 & ~CWN0)
         | (~CWLOAD & CSTEP & CWN5 & ~CWN1)
         | (~CWLOAD & CSTEP & CWN5 & ~CWN2)
         | (~CWLOAD & CSTEP & CWN5 & ~CWN3)
         | (~CWLOAD & CSTEP & CWN5 & ~CWN4)
         | (~CWLOAD & CSTEP & ~CWN5 & CWN0 & CWN1 & CWN2 & CWN3 & CWN4)
         | (~CWLOAD & ~CSTEP & CWN5);
      r_CWN6 <=
         (CWLOAD & ~CW6)
         | (~CWLOAD & CSTEP & CWN6 & ~CWN0)
         | (~CWLOAD & CSTEP & CWN6 & ~CWN1)
         | (~CWLOAD & CSTEP & CWN6 & ~CWN2)
         | (~CWLOAD & CSTEP & CWN6 & ~CWN3)
         | (~CWLOAD & CSTEP & CWN6 & ~CWN4)
         | (~CWLOAD & CSTEP & CWN6 & ~CWN5)
         | (~CWLOAD & CSTEP & ~CWN6 & CWN0 & CWN1 & CWN2 & CWN3 & CWN4 & CWN5)
         | (~CWLOAD & ~CSTEP & CWN6);
      r_CWN7 <=
         (CWLOAD & ~CW7)
         | (~CWLOAD & CSTEP & CWN7 & ~CWN0)
         | (~CWLOAD & CSTEP & CWN7 & ~CWN1)
         | (~CWLOAD & CSTEP & CWN7 & ~CWN2)
         | (~CWLOAD & CSTEP & CWN7 & ~CWN3)
         | (~CWLOAD & CSTEP & CWN7 & ~CWN4)
         | (~CWLOAD & CSTEP & CWN7 & ~CWN5)
         | (~CWLOAD & CSTEP & CWN7 & ~CWN6)
         | (~CWLOAD & CSTEP & ~CWN7 & CWN0 & CWN1 & CWN2 & CWN3 & CWN4 & CWN5 & CWN6)
         | (~CWLOAD & ~CSTEP & CWN7);
      r_CWN8 <=
         (CWLOAD & ~CW8)
         | (~CWLOAD & CSTEP & CWN8 & ~CWN0)
         | (~CWLOAD & CSTEP & CWN8 & ~CWN1)
         | (~CWLOAD & CSTEP & CWN8 & ~CWN2)
         | (~CWLOAD & CSTEP & CWN8 & ~CWN3)
         | (~CWLOAD & CSTEP & CWN8 & ~CWN4)
         | (~CWLOAD & CSTEP & CWN8 & ~CWN5)
         | (~CWLOAD & CSTEP & CWN8 & ~CWN6)
         | (~CWLOAD & CSTEP & CWN8 & ~CWN7)
         | (~CWLOAD & CSTEP & ~CWN8 & CWN0 & CWN1 & CWN2 & CWN3 & CWN4 & CWN5 & CWN6 & CWN7)
         | (~CWLOAD & ~CSTEP & CWN8);
      r_CWN9 <=
         (CWLOAD & ~CW9)
         | (~CWLOAD & CSTEP & CWN9 & ~CWN0)
         | (~CWLOAD & CSTEP & CWN9 & ~CWN1)
         | (~CWLOAD & CSTEP & CWN9 & ~CWN2)
         | (~CWLOAD & CSTEP & CWN9 & ~CWN3)
         | (~CWLOAD & CSTEP & CWN9 & ~CWN4)
         | (~CWLOAD & CSTEP & CWN9 & ~CWN5)
         | (~CWLOAD & CSTEP & CWN9 & ~CWN6)
         | (~CWLOAD & CSTEP & CWN9 & ~CWN7)
         | (~CWLOAD & CSTEP & CWN9 & ~CWN8)
         | (~CWLOAD & CSTEP & ~CWN9 & CWN0 & CWN1 & CWN2 & CWN3 & CWN4 & CWN5 & CWN6 & CWN7 & CWN8)
         | (~CWLOAD & ~CSTEP & CWN9);
      r_CH0 <=
         (LDCH & ~D0)
         | (~LDCH & CROWADV & ~CH0)
         | (~LDCH & ~CROWADV & CH0);
      r_CH1 <=
         (LDCH & ~D1)
         | (~LDCH & CROWADV & CH1 & ~CH0)
         | (~LDCH & CROWADV & ~CH1 & CH0)
         | (~LDCH & ~CROWADV & CH1);
      r_CH2 <=
         (LDCH & ~D2)
         | (~LDCH & CROWADV & CH2 & ~CH0)
         | (~LDCH & CROWADV & CH2 & ~CH1)
         | (~LDCH & CROWADV & ~CH2 & CH0 & CH1)
         | (~LDCH & ~CROWADV & CH2);
      r_CH3 <=
         (LDCH & ~D3)
         | (~LDCH & CROWADV & CH3 & ~CH0)
         | (~LDCH & CROWADV & CH3 & ~CH1)
         | (~LDCH & CROWADV & CH3 & ~CH2)
         | (~LDCH & CROWADV & ~CH3 & CH0 & CH1 & CH2)
         | (~LDCH & ~CROWADV & CH3);
      r_CH4 <=
         (LDCH & ~D4)
         | (~LDCH & CROWADV & CH4 & ~CH0)
         | (~LDCH & CROWADV & CH4 & ~CH1)
         | (~LDCH & CROWADV & CH4 & ~CH2)
         | (~LDCH & CROWADV & CH4 & ~CH3)
         | (~LDCH & CROWADV & ~CH4 & CH0 & CH1 & CH2 & CH3)
         | (~LDCH & ~CROWADV & CH4);
      r_CH5 <=
         (LDCH & ~D5)
         | (~LDCH & CROWADV & CH5 & ~CH0)
         | (~LDCH & CROWADV & CH5 & ~CH1)
         | (~LDCH & CROWADV & CH5 & ~CH2)
         | (~LDCH & CROWADV & CH5 & ~CH3)
         | (~LDCH & CROWADV & CH5 & ~CH4)
         | (~LDCH & CROWADV & ~CH5 & CH0 & CH1 & CH2 & CH3 & CH4)
         | (~LDCH & ~CROWADV & CH5);
      r_CH6 <=
         (LDCH & ~D6)
         | (~LDCH & CROWADV & CH6 & ~CH0)
         | (~LDCH & CROWADV & CH6 & ~CH1)
         | (~LDCH & CROWADV & CH6 & ~CH2)
         | (~LDCH & CROWADV & CH6 & ~CH3)
         | (~LDCH & CROWADV & CH6 & ~CH4)
         | (~LDCH & CROWADV & CH6 & ~CH5)
         | (~LDCH & CROWADV & ~CH6 & CH0 & CH1 & CH2 & CH3 & CH4 & CH5)
         | (~LDCH & ~CROWADV & CH6);
      r_CH7 <=
         (LDCH & ~D7)
         | (~LDCH & CROWADV & CH7 & ~CH0)
         | (~LDCH & CROWADV & CH7 & ~CH1)
         | (~LDCH & CROWADV & CH7 & ~CH2)
         | (~LDCH & CROWADV & CH7 & ~CH3)
         | (~LDCH & CROWADV & CH7 & ~CH4)
         | (~LDCH & CROWADV & CH7 & ~CH5)
         | (~LDCH & CROWADV & CH7 & ~CH6)
         | (~LDCH & CROWADV & ~CH7 & CH0 & CH1 & CH2 & CH3 & CH4 & CH5 & CH6)
         | (~LDCH & ~CROWADV & CH7);
      r_CH8 <=
         (LDCCTRL & ~D5)
         | (~LDCCTRL & CROWADV & CH8 & ~CH0)
         | (~LDCCTRL & CROWADV & CH8 & ~CH1)
         | (~LDCCTRL & CROWADV & CH8 & ~CH2)
         | (~LDCCTRL & CROWADV & CH8 & ~CH3)
         | (~LDCCTRL & CROWADV & CH8 & ~CH4)
         | (~LDCCTRL & CROWADV & CH8 & ~CH5)
         | (~LDCCTRL & CROWADV & CH8 & ~CH6)
         | (~LDCCTRL & CROWADV & CH8 & ~CH7)
         | (~LDCCTRL & CROWADV & ~CH8 & CH0 & CH1 & CH2 & CH3 & CH4 & CH5 & CH6 & CH7)
         | (~LDCCTRL & ~CROWADV & CH8);
      r_GOQ <=
         (LDCCTRL & D0);
      r_CBUSY <=
         (GOQ & ~LDCCTRL)
         | (CBUSY & ~CDONE);
      r_MS0 <=
         (WSTBV & D7)
         | (~WSTBV & RETIRE & MS1)
         | (~WSTBV & ~RETIRE & MS0);
      r_MS1 <=
         (WSTBV & D6)
         | (~WSTBV & RETIRE & MS2)
         | (~WSTBV & ~RETIRE & MS1);
      r_MS2 <=
         (WSTBV & D5)
         | (~WSTBV & RETIRE & MS3)
         | (~WSTBV & ~RETIRE & MS2);
      r_MS3 <=
         (WSTBV & D4)
         | (~WSTBV & RETIRE & MS4)
         | (~WSTBV & ~RETIRE & MS3);
      r_MS4 <=
         (WSTBV & D3)
         | (~WSTBV & RETIRE & MS5)
         | (~WSTBV & ~RETIRE & MS4);
      r_MS5 <=
         (WSTBV & D2)
         | (~WSTBV & RETIRE & MS6)
         | (~WSTBV & ~RETIRE & MS5);
      r_MS6 <=
         (WSTBV & D1)
         | (~WSTBV & RETIRE & MS7)
         | (~WSTBV & ~RETIRE & MS6);
      r_MS7 <=
         (WSTBV & D0)
         | (~WSTBV & RETIRE & MS8)
         | (~WSTBV & ~RETIRE & MS7);
      r_MS8 <=
         (WSTBV)
         | (~WSTBV & ~RETIRE & MS8);
      r_NSL0 <=
         (WSTART & ~D0)
         | (~WSTART & RETIRE & ~NSL0)
         | (~WSTART & ~RETIRE & NSL0);
      r_NSL1 <=
         (WSTART & ~D1)
         | (~WSTART & RETIRE & NSL1 & ~NSL0)
         | (~WSTART & RETIRE & ~NSL1 & NSL0)
         | (~WSTART & ~RETIRE & NSL1);
      r_NSL2 <=
         (WSTART & ~D2)
         | (~WSTART & RETIRE & NSL2 & ~NSL0)
         | (~WSTART & RETIRE & NSL2 & ~NSL1)
         | (~WSTART & RETIRE & ~NSL2 & NSL0 & NSL1)
         | (~WSTART & ~RETIRE & NSL2);
      r_NSL3 <=
         (WSTART & ~D3)
         | (~WSTART & RETIRE & NSL3 & ~NSL0)
         | (~WSTART & RETIRE & NSL3 & ~NSL1)
         | (~WSTART & RETIRE & NSL3 & ~NSL2)
         | (~WSTART & RETIRE & ~NSL3 & NSL0 & NSL1 & NSL2)
         | (~WSTART & ~RETIRE & NSL3);
      r_NSL4 <=
         (WSTART & ~D4)
         | (~WSTART & RETIRE & NSL4 & ~NSL0)
         | (~WSTART & RETIRE & NSL4 & ~NSL1)
         | (~WSTART & RETIRE & NSL4 & ~NSL2)
         | (~WSTART & RETIRE & NSL4 & ~NSL3)
         | (~WSTART & RETIRE & ~NSL4 & NSL0 & NSL1 & NSL2 & NSL3)
         | (~WSTART & ~RETIRE & NSL4);
      r_NSL5 <=
         (WSTART & ~D5)
         | (~WSTART & RETIRE & NSL5 & ~NSL0)
         | (~WSTART & RETIRE & NSL5 & ~NSL1)
         | (~WSTART & RETIRE & NSL5 & ~NSL2)
         | (~WSTART & RETIRE & NSL5 & ~NSL3)
         | (~WSTART & RETIRE & NSL5 & ~NSL4)
         | (~WSTART & RETIRE & ~NSL5 & NSL0 & NSL1 & NSL2 & NSL3 & NSL4)
         | (~WSTART & ~RETIRE & NSL5);
      r_NSL6 <=
         (WSTART & ~D6)
         | (~WSTART & RETIRE & NSL6 & ~NSL0)
         | (~WSTART & RETIRE & NSL6 & ~NSL1)
         | (~WSTART & RETIRE & NSL6 & ~NSL2)
         | (~WSTART & RETIRE & NSL6 & ~NSL3)
         | (~WSTART & RETIRE & NSL6 & ~NSL4)
         | (~WSTART & RETIRE & NSL6 & ~NSL5)
         | (~WSTART & RETIRE & ~NSL6 & NSL0 & NSL1 & NSL2 & NSL3 & NSL4 & NSL5)
         | (~WSTART & ~RETIRE & NSL6);
      r_NSL7 <=
         (WSTART & ~D7)
         | (~WSTART & RETIRE & NSL7 & ~NSL0)
         | (~WSTART & RETIRE & NSL7 & ~NSL1)
         | (~WSTART & RETIRE & NSL7 & ~NSL2)
         | (~WSTART & RETIRE & NSL7 & ~NSL3)
         | (~WSTART & RETIRE & NSL7 & ~NSL4)
         | (~WSTART & RETIRE & NSL7 & ~NSL5)
         | (~WSTART & RETIRE & NSL7 & ~NSL6)
         | (~WSTART & RETIRE & ~NSL7 & NSL0 & NSL1 & NSL2 & NSL3 & NSL4 & NSL5 & NSL6)
         | (~WSTART & ~RETIRE & NSL7);
      r_WADV0 <=
         (LDWADV & D0)
         | (WADV0 & ~LDWADV);
      r_WADV1 <=
         (LDWADV & D1)
         | (WADV1 & ~LDWADV);
      r_WADV2 <=
         (LDWADV & D2)
         | (WADV2 & ~LDWADV);
      r_SPANBUSY <=
         (WSTART)
         | (SPANBUSY & ~SPANEND);
  end

endmodule
`default_nettype wire
