// GENERATED by hardware/gal/verilog/emit.ts from the term lists in
// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module v3scan (
    input  wire CLK25,
    input  wire RESET,
    input  wire FETCH,
    input  wire HLOAD,
    input  wire VLOAD,
    input  wire ROWADV,
    input  wire MCADV,
    input  wire MAPLD,
    input  wire SRC0,
    input  wire SRC1,
    input  wire FBOE,
    input  wire D0,
    input  wire D1,
    input  wire D2,
    input  wire D3,
    input  wire D4,
    input  wire D5,
    input  wire D6,
    input  wire D7,
    input  wire PB0,
    input  wire PB1,
    input  wire PB2,
    input  wire PB3,
    input  wire PB4,
    input  wire PB5,
    input  wire PB6,
    input  wire PB7,
    input  wire PA0,
    input  wire PA1,
    input  wire PA2,
    input  wire PA3,
    input  wire PA4,
    input  wire PA5,
    input  wire PA6,
    input  wire PA7,
    input  wire REGWR,
    input  wire RA0,
    input  wire RA1,
    input  wire RA2,
    input  wire RA3,
    input  wire RA4,
    output wire LDHSL,
    output wire LDHSH,
    output wire LDVSL,
    output wire LDVSH,
    output wire LDTB,
    output wire LDMB,
    output wire HS2,
    output wire HS3,
    output wire HS4,
    output wire HS5,
    output wire HS6,
    output wire HS7,
    output wire HS8,
    output wire HS9,
    output wire VS0,
    output wire VS1,
    output wire VS2,
    output wire VS3,
    output wire VS4,
    output wire VS5,
    output wire VS6,
    output wire VS7,
    output wire VS8,
    output wire TB0,
    output wire TB1,
    output wire TB2,
    output wire TB3,
    output wire TB4,
    output wire MB0,
    output wire MB1,
    output wire MB2,
    output wire MAP0,
    output wire MAP1,
    output wire MAP2,
    output wire MAP3,
    output wire MAP4,
    output wire MAP5,
    output wire MAP6,
    output wire MAP7,
    output wire MAPA0,
    output wire MAPA1,
    output wire MAPA2,
    output wire MAPA3,
    output wire MAPA4,
    output wire MAPA5,
    output wire MAPA6,
    output wire MAPA7,
    output wire MAPQ0,
    output wire MAPQ1,
    output wire MAPQ2,
    output wire MAPQ3,
    output wire MAPQ4,
    output wire MAPQ5,
    output wire MAPQ6,
    output wire MAPQ7,
    output wire ATO0,
    output wire ATO1,
    output wire ATO2,
    output wire ATO3,
    output wire ATO4,
    output wire ATO5,
    output wire ATO6,
    output wire ATO7,
    output wire MC0,
    output wire MC1,
    output wire MC2,
    output wire MC3,
    output wire MC4,
    output wire MC5,
    output wire MC6,
    output wire SA2,
    output wire SA3,
    output wire SA4,
    output wire SA5,
    output wire SA6,
    output wire SA7,
    output wire SA8,
    output wire SA9,
    output wire SA10,
    output wire SA11,
    output wire SA12,
    output wire SA13,
    output wire SA14,
    output wire SA15,
    output wire SA16,
    output wire SA17,
    output wire SA18,
    output wire FBA2,
    output wire FBA3,
    output wire FBA4,
    output wire FBA5,
    output wire FBA6,
    output wire FBA7,
    output wire FBA8,
    output wire FBA9,
    output wire FBA10,
    output wire FBA11,
    output wire FBA12,
    output wire FBA13,
    output wire FBA14,
    output wire FBA15,
    output wire FBA16,
    output wire FBA17,
    output wire FBA18,
    output wire FBA2_OE,
    output wire FBA3_OE,
    output wire FBA4_OE,
    output wire FBA5_OE,
    output wire FBA6_OE,
    output wire FBA7_OE,
    output wire FBA8_OE,
    output wire FBA9_OE,
    output wire FBA10_OE,
    output wire FBA11_OE,
    output wire FBA12_OE,
    output wire FBA13_OE,
    output wire FBA14_OE,
    output wire FBA15_OE,
    output wire FBA16_OE,
    output wire FBA17_OE,
    output wire FBA18_OE
);

  reg  r_HS2;
  reg  r_HS3;
  reg  r_HS4;
  reg  r_HS5;
  reg  r_HS6;
  reg  r_HS7;
  reg  r_HS8;
  reg  r_HS9;
  reg  r_VS0;
  reg  r_VS1;
  reg  r_VS2;
  reg  r_VS3;
  reg  r_VS4;
  reg  r_VS5;
  reg  r_VS6;
  reg  r_VS7;
  reg  r_VS8;
  reg  r_TB0;
  reg  r_TB1;
  reg  r_TB2;
  reg  r_TB3;
  reg  r_TB4;
  reg  r_MB0;
  reg  r_MB1;
  reg  r_MB2;
  reg  r_MAP0;
  reg  r_MAP1;
  reg  r_MAP2;
  reg  r_MAP3;
  reg  r_MAP4;
  reg  r_MAP5;
  reg  r_MAP6;
  reg  r_MAP7;
  reg  r_MAPA0;
  reg  r_MAPA1;
  reg  r_MAPA2;
  reg  r_MAPA3;
  reg  r_MAPA4;
  reg  r_MAPA5;
  reg  r_MAPA6;
  reg  r_MAPA7;
  reg  r_MAPQ0;
  reg  r_MAPQ1;
  reg  r_MAPQ2;
  reg  r_MAPQ3;
  reg  r_MAPQ4;
  reg  r_MAPQ5;
  reg  r_MAPQ6;
  reg  r_MAPQ7;
  reg  r_ATO0;
  reg  r_ATO1;
  reg  r_ATO2;
  reg  r_ATO3;
  reg  r_ATO4;
  reg  r_ATO5;
  reg  r_ATO6;
  reg  r_ATO7;
  reg  r_MC0;
  reg  r_MC1;
  reg  r_MC2;
  reg  r_MC3;
  reg  r_MC4;
  reg  r_MC5;
  reg  r_MC6;
  reg  r_SA2;
  reg  r_SA3;
  reg  r_SA4;
  reg  r_SA5;
  reg  r_SA6;
  reg  r_SA7;
  reg  r_SA8;
  reg  r_SA9;
  reg  r_SA10;
  reg  r_SA11;
  reg  r_SA12;
  reg  r_SA13;
  reg  r_SA14;
  reg  r_SA15;
  reg  r_SA16;
  reg  r_SA17;
  reg  r_SA18;

  assign HS2 = r_HS2;
  assign HS3 = r_HS3;
  assign HS4 = r_HS4;
  assign HS5 = r_HS5;
  assign HS6 = r_HS6;
  assign HS7 = r_HS7;
  assign HS8 = r_HS8;
  assign HS9 = r_HS9;
  assign VS0 = r_VS0;
  assign VS1 = r_VS1;
  assign VS2 = r_VS2;
  assign VS3 = r_VS3;
  assign VS4 = r_VS4;
  assign VS5 = r_VS5;
  assign VS6 = r_VS6;
  assign VS7 = r_VS7;
  assign VS8 = r_VS8;
  assign TB0 = r_TB0;
  assign TB1 = r_TB1;
  assign TB2 = r_TB2;
  assign TB3 = r_TB3;
  assign TB4 = r_TB4;
  assign MB0 = r_MB0;
  assign MB1 = r_MB1;
  assign MB2 = r_MB2;
  assign MAP0 = r_MAP0;
  assign MAP1 = r_MAP1;
  assign MAP2 = r_MAP2;
  assign MAP3 = r_MAP3;
  assign MAP4 = r_MAP4;
  assign MAP5 = r_MAP5;
  assign MAP6 = r_MAP6;
  assign MAP7 = r_MAP7;
  assign MAPA0 = r_MAPA0;
  assign MAPA1 = r_MAPA1;
  assign MAPA2 = r_MAPA2;
  assign MAPA3 = r_MAPA3;
  assign MAPA4 = r_MAPA4;
  assign MAPA5 = r_MAPA5;
  assign MAPA6 = r_MAPA6;
  assign MAPA7 = r_MAPA7;
  assign MAPQ0 = r_MAPQ0;
  assign MAPQ1 = r_MAPQ1;
  assign MAPQ2 = r_MAPQ2;
  assign MAPQ3 = r_MAPQ3;
  assign MAPQ4 = r_MAPQ4;
  assign MAPQ5 = r_MAPQ5;
  assign MAPQ6 = r_MAPQ6;
  assign MAPQ7 = r_MAPQ7;
  assign ATO0 = r_ATO0;
  assign ATO1 = r_ATO1;
  assign ATO2 = r_ATO2;
  assign ATO3 = r_ATO3;
  assign ATO4 = r_ATO4;
  assign ATO5 = r_ATO5;
  assign ATO6 = r_ATO6;
  assign ATO7 = r_ATO7;
  assign MC0 = r_MC0;
  assign MC1 = r_MC1;
  assign MC2 = r_MC2;
  assign MC3 = r_MC3;
  assign MC4 = r_MC4;
  assign MC5 = r_MC5;
  assign MC6 = r_MC6;
  assign SA2 = r_SA2;
  assign SA3 = r_SA3;
  assign SA4 = r_SA4;
  assign SA5 = r_SA5;
  assign SA6 = r_SA6;
  assign SA7 = r_SA7;
  assign SA8 = r_SA8;
  assign SA9 = r_SA9;
  assign SA10 = r_SA10;
  assign SA11 = r_SA11;
  assign SA12 = r_SA12;
  assign SA13 = r_SA13;
  assign SA14 = r_SA14;
  assign SA15 = r_SA15;
  assign SA16 = r_SA16;
  assign SA17 = r_SA17;
  assign SA18 = r_SA18;

  // buried
  assign LDHSL =
         (REGWR & ~RA4 & ~RA3 & ~RA2 & RA1 & RA0);
  // buried
  assign LDHSH =
         (REGWR & ~RA4 & ~RA3 & RA2 & ~RA1 & ~RA0);
  // buried
  assign LDVSL =
         (REGWR & ~RA4 & ~RA3 & ~RA2 & ~RA1 & RA0);
  // buried
  assign LDVSH =
         (REGWR & ~RA4 & ~RA3 & ~RA2 & RA1 & ~RA0);
  // buried
  assign LDTB =
         (REGWR & RA4 & RA3 & ~RA2 & ~RA1 & ~RA0);
  // buried
  assign LDMB =
         (REGWR & RA4 & RA3 & ~RA2 & ~RA1 & RA0);
  // EXTERNAL
  assign FBA2 =
         (~SRC1 & ~SRC0 & SA2)
         | (~SRC1 & SRC0 & SA2)
         | (SRC1 & ~SRC0 & MC1);
  // EXTERNAL
  assign FBA3 =
         (~SRC1 & ~SRC0 & SA3)
         | (~SRC1 & SRC0 & SA10)
         | (SRC1 & ~SRC0 & MC2);
  // EXTERNAL
  assign FBA4 =
         (~SRC1 & ~SRC0 & SA4)
         | (~SRC1 & SRC0 & SA11)
         | (SRC1 & ~SRC0 & MC3);
  // EXTERNAL
  assign FBA5 =
         (~SRC1 & ~SRC0 & SA5)
         | (~SRC1 & SRC0 & SA12)
         | (SRC1 & ~SRC0 & MC4);
  // EXTERNAL
  assign FBA6 =
         (~SRC1 & ~SRC0 & SA6)
         | (~SRC1 & SRC0 & MAPQ0)
         | (SRC1 & ~SRC0 & MC5);
  // EXTERNAL
  assign FBA7 =
         (~SRC1 & ~SRC0 & SA7)
         | (~SRC1 & SRC0 & MAPQ1)
         | (SRC1 & ~SRC0 & MC6);
  // EXTERNAL
  assign FBA8 =
         (~SRC1 & ~SRC0 & SA8)
         | (~SRC1 & SRC0 & MAPQ2);
  // EXTERNAL
  assign FBA9 =
         (~SRC1 & ~SRC0 & SA9)
         | (~SRC1 & SRC0 & MAPQ3);
  // EXTERNAL
  assign FBA10 =
         (~SRC1 & ~SRC0 & SA10)
         | (~SRC1 & SRC0 & MAPQ4)
         | (SRC1 & ~SRC0 & SA13);
  // EXTERNAL
  assign FBA11 =
         (~SRC1 & ~SRC0 & SA11)
         | (~SRC1 & SRC0 & MAPQ5)
         | (SRC1 & ~SRC0 & SA14);
  // EXTERNAL
  assign FBA12 =
         (~SRC1 & ~SRC0 & SA12)
         | (~SRC1 & SRC0 & MAPQ6)
         | (SRC1 & ~SRC0 & SA15);
  // EXTERNAL
  assign FBA13 =
         (~SRC1 & ~SRC0 & SA13)
         | (~SRC1 & SRC0 & MAPQ7)
         | (SRC1 & ~SRC0 & SA16);
  // EXTERNAL
  assign FBA14 =
         (~SRC1 & ~SRC0 & SA14)
         | (~SRC1 & SRC0 & TB0)
         | (SRC1 & ~SRC0 & SA17);
  // EXTERNAL
  assign FBA15 =
         (~SRC1 & ~SRC0 & SA15)
         | (~SRC1 & SRC0 & TB1)
         | (SRC1 & ~SRC0 & SA18);
  // EXTERNAL
  assign FBA16 =
         (~SRC1 & ~SRC0 & SA16)
         | (~SRC1 & SRC0 & TB2)
         | (SRC1 & ~SRC0 & MB0);
  // EXTERNAL
  assign FBA17 =
         (~SRC1 & ~SRC0 & SA17)
         | (~SRC1 & SRC0 & TB3)
         | (SRC1 & ~SRC0 & MB1);
  // EXTERNAL
  assign FBA18 =
         (~SRC1 & ~SRC0 & SA18)
         | (~SRC1 & SRC0 & TB4)
         | (SRC1 & ~SRC0 & MB2);

  // FBA2 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA2_OE =
         (FBOE);
  // FBA3 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA3_OE =
         (FBOE);
  // FBA4 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA4_OE =
         (FBOE);
  // FBA5 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA5_OE =
         (FBOE);
  // FBA6 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA6_OE =
         (FBOE);
  // FBA7 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA7_OE =
         (FBOE);
  // FBA8 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA8_OE =
         (FBOE);
  // FBA9 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA9_OE =
         (FBOE);
  // FBA10 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA10_OE =
         (FBOE);
  // FBA11 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA11_OE =
         (FBOE);
  // FBA12 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA12_OE =
         (FBOE);
  // FBA13 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA13_OE =
         (FBOE);
  // FBA14 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA14_OE =
         (FBOE);
  // FBA15 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA15_OE =
         (FBOE);
  // FBA16 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA16_OE =
         (FBOE);
  // FBA17 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA17_OE =
         (FBOE);
  // FBA18 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA18_OE =
         (FBOE);

  always @(posedge CLK25) begin
      r_HS2 <=
         (LDHSL & D2)
         | (HS2 & ~LDHSL);
      r_HS3 <=
         (LDHSL & D3)
         | (HS3 & ~LDHSL);
      r_HS4 <=
         (LDHSL & D4)
         | (HS4 & ~LDHSL);
      r_HS5 <=
         (LDHSL & D5)
         | (HS5 & ~LDHSL);
      r_HS6 <=
         (LDHSL & D6)
         | (HS6 & ~LDHSL);
      r_HS7 <=
         (LDHSL & D7)
         | (HS7 & ~LDHSL);
      r_HS8 <=
         (LDHSH & D0)
         | (HS8 & ~LDHSH);
      r_HS9 <=
         (LDHSH & D1)
         | (HS9 & ~LDHSH);
      r_VS0 <=
         (LDVSL & D0)
         | (VS0 & ~LDVSL);
      r_VS1 <=
         (LDVSL & D1)
         | (VS1 & ~LDVSL);
      r_VS2 <=
         (LDVSL & D2)
         | (VS2 & ~LDVSL);
      r_VS3 <=
         (LDVSL & D3)
         | (VS3 & ~LDVSL);
      r_VS4 <=
         (LDVSL & D4)
         | (VS4 & ~LDVSL);
      r_VS5 <=
         (LDVSL & D5)
         | (VS5 & ~LDVSL);
      r_VS6 <=
         (LDVSL & D6)
         | (VS6 & ~LDVSL);
      r_VS7 <=
         (LDVSL & D7)
         | (VS7 & ~LDVSL);
      r_VS8 <=
         (LDVSH & D0)
         | (VS8 & ~LDVSH);
      r_TB0 <=
         (LDTB & D0)
         | (TB0 & ~LDTB);
      r_TB1 <=
         (LDTB & D1)
         | (TB1 & ~LDTB);
      r_TB2 <=
         (LDTB & D2)
         | (TB2 & ~LDTB);
      r_TB3 <=
         (LDTB & D3)
         | (TB3 & ~LDTB);
      r_TB4 <=
         (LDTB & D4)
         | (TB4 & ~LDTB);
      r_MB0 <=
         (LDMB & D0)
         | (MB0 & ~LDMB);
      r_MB1 <=
         (LDMB & D1)
         | (MB1 & ~LDMB);
      r_MB2 <=
         (LDMB & D2)
         | (MB2 & ~LDMB);
      r_MAP0 <=
         (MAPLD & PB0)
         | (MAP0 & ~MAPLD);
      r_MAP1 <=
         (MAPLD & PB1)
         | (MAP1 & ~MAPLD);
      r_MAP2 <=
         (MAPLD & PB2)
         | (MAP2 & ~MAPLD);
      r_MAP3 <=
         (MAPLD & PB3)
         | (MAP3 & ~MAPLD);
      r_MAP4 <=
         (MAPLD & PB4)
         | (MAP4 & ~MAPLD);
      r_MAP5 <=
         (MAPLD & PB5)
         | (MAP5 & ~MAPLD);
      r_MAP6 <=
         (MAPLD & PB6)
         | (MAP6 & ~MAPLD);
      r_MAP7 <=
         (MAPLD & PB7)
         | (MAP7 & ~MAPLD);
      r_MAPA0 <=
         (MAPLD & PA0)
         | (MAPA0 & ~MAPLD);
      r_MAPA1 <=
         (MAPLD & PA1)
         | (MAPA1 & ~MAPLD);
      r_MAPA2 <=
         (MAPLD & PA2)
         | (MAPA2 & ~MAPLD);
      r_MAPA3 <=
         (MAPLD & PA3)
         | (MAPA3 & ~MAPLD);
      r_MAPA4 <=
         (MAPLD & PA4)
         | (MAPA4 & ~MAPLD);
      r_MAPA5 <=
         (MAPLD & PA5)
         | (MAPA5 & ~MAPLD);
      r_MAPA6 <=
         (MAPLD & PA6)
         | (MAPA6 & ~MAPLD);
      r_MAPA7 <=
         (MAPLD & PA7)
         | (MAPA7 & ~MAPLD);
      r_MAPQ0 <=
         (MCADV & MAP0)
         | (MAPQ0 & ~MCADV);
      r_MAPQ1 <=
         (MCADV & MAP1)
         | (MAPQ1 & ~MCADV);
      r_MAPQ2 <=
         (MCADV & MAP2)
         | (MAPQ2 & ~MCADV);
      r_MAPQ3 <=
         (MCADV & MAP3)
         | (MAPQ3 & ~MCADV);
      r_MAPQ4 <=
         (MCADV & MAP4)
         | (MAPQ4 & ~MCADV);
      r_MAPQ5 <=
         (MCADV & MAP5)
         | (MAPQ5 & ~MCADV);
      r_MAPQ6 <=
         (MCADV & MAP6)
         | (MAPQ6 & ~MCADV);
      r_MAPQ7 <=
         (MCADV & MAP7)
         | (MAPQ7 & ~MCADV);
      r_ATO0 <=
         (MCADV & MAPA0)
         | (ATO0 & ~MCADV);
      r_ATO1 <=
         (MCADV & MAPA1)
         | (ATO1 & ~MCADV);
      r_ATO2 <=
         (MCADV & MAPA2)
         | (ATO2 & ~MCADV);
      r_ATO3 <=
         (MCADV & MAPA3)
         | (ATO3 & ~MCADV);
      r_ATO4 <=
         (MCADV & MAPA4)
         | (ATO4 & ~MCADV);
      r_ATO5 <=
         (MCADV & MAPA5)
         | (ATO5 & ~MCADV);
      r_ATO6 <=
         (MCADV & MAPA6)
         | (ATO6 & ~MCADV);
      r_ATO7 <=
         (MCADV & MAPA7)
         | (ATO7 & ~MCADV);
      r_MC0 <=
         (HLOAD & HS3)
         | (~HLOAD & MCADV & ~MC0)
         | (~HLOAD & ~MCADV & MC0);
      r_MC1 <=
         (HLOAD & HS4)
         | (~HLOAD & MCADV & MC1 & ~MC0)
         | (~HLOAD & MCADV & ~MC1 & MC0)
         | (~HLOAD & ~MCADV & MC1);
      r_MC2 <=
         (HLOAD & HS5)
         | (~HLOAD & MCADV & MC2 & ~MC0)
         | (~HLOAD & MCADV & MC2 & ~MC1)
         | (~HLOAD & MCADV & ~MC2 & MC0 & MC1)
         | (~HLOAD & ~MCADV & MC2);
      r_MC3 <=
         (HLOAD & HS6)
         | (~HLOAD & MCADV & MC3 & ~MC0)
         | (~HLOAD & MCADV & MC3 & ~MC1)
         | (~HLOAD & MCADV & MC3 & ~MC2)
         | (~HLOAD & MCADV & ~MC3 & MC0 & MC1 & MC2)
         | (~HLOAD & ~MCADV & MC3);
      r_MC4 <=
         (HLOAD & HS7)
         | (~HLOAD & MCADV & MC4 & ~MC0)
         | (~HLOAD & MCADV & MC4 & ~MC1)
         | (~HLOAD & MCADV & MC4 & ~MC2)
         | (~HLOAD & MCADV & MC4 & ~MC3)
         | (~HLOAD & MCADV & ~MC4 & MC0 & MC1 & MC2 & MC3)
         | (~HLOAD & ~MCADV & MC4);
      r_MC5 <=
         (HLOAD & HS8)
         | (~HLOAD & MCADV & MC5 & ~MC0)
         | (~HLOAD & MCADV & MC5 & ~MC1)
         | (~HLOAD & MCADV & MC5 & ~MC2)
         | (~HLOAD & MCADV & MC5 & ~MC3)
         | (~HLOAD & MCADV & MC5 & ~MC4)
         | (~HLOAD & MCADV & ~MC5 & MC0 & MC1 & MC2 & MC3 & MC4)
         | (~HLOAD & ~MCADV & MC5);
      r_MC6 <=
         (HLOAD & HS9)
         | (~HLOAD & MCADV & MC6 & ~MC0)
         | (~HLOAD & MCADV & MC6 & ~MC1)
         | (~HLOAD & MCADV & MC6 & ~MC2)
         | (~HLOAD & MCADV & MC6 & ~MC3)
         | (~HLOAD & MCADV & MC6 & ~MC4)
         | (~HLOAD & MCADV & MC6 & ~MC5)
         | (~HLOAD & MCADV & ~MC6 & MC0 & MC1 & MC2 & MC3 & MC4 & MC5)
         | (~HLOAD & ~MCADV & MC6);
      r_SA2 <=
         (HLOAD & HS2)
         | (~HLOAD & FETCH & ~SA2)
         | (~HLOAD & ~FETCH & SA2);
      r_SA3 <=
         (HLOAD & HS3)
         | (~HLOAD & FETCH & SA3 & ~SA2)
         | (~HLOAD & FETCH & ~SA3 & SA2)
         | (~HLOAD & ~FETCH & SA3);
      r_SA4 <=
         (HLOAD & HS4)
         | (~HLOAD & FETCH & SA4 & ~SA2)
         | (~HLOAD & FETCH & SA4 & ~SA3)
         | (~HLOAD & FETCH & ~SA4 & SA2 & SA3)
         | (~HLOAD & ~FETCH & SA4);
      r_SA5 <=
         (HLOAD & HS5)
         | (~HLOAD & FETCH & SA5 & ~SA2)
         | (~HLOAD & FETCH & SA5 & ~SA3)
         | (~HLOAD & FETCH & SA5 & ~SA4)
         | (~HLOAD & FETCH & ~SA5 & SA2 & SA3 & SA4)
         | (~HLOAD & ~FETCH & SA5);
      r_SA6 <=
         (HLOAD & HS6)
         | (~HLOAD & FETCH & SA6 & ~SA2)
         | (~HLOAD & FETCH & SA6 & ~SA3)
         | (~HLOAD & FETCH & SA6 & ~SA4)
         | (~HLOAD & FETCH & SA6 & ~SA5)
         | (~HLOAD & FETCH & ~SA6 & SA2 & SA3 & SA4 & SA5)
         | (~HLOAD & ~FETCH & SA6);
      r_SA7 <=
         (HLOAD & HS7)
         | (~HLOAD & FETCH & SA7 & ~SA2)
         | (~HLOAD & FETCH & SA7 & ~SA3)
         | (~HLOAD & FETCH & SA7 & ~SA4)
         | (~HLOAD & FETCH & SA7 & ~SA5)
         | (~HLOAD & FETCH & SA7 & ~SA6)
         | (~HLOAD & FETCH & ~SA7 & SA2 & SA3 & SA4 & SA5 & SA6)
         | (~HLOAD & ~FETCH & SA7);
      r_SA8 <=
         (HLOAD & HS8)
         | (~HLOAD & FETCH & SA8 & ~SA2)
         | (~HLOAD & FETCH & SA8 & ~SA3)
         | (~HLOAD & FETCH & SA8 & ~SA4)
         | (~HLOAD & FETCH & SA8 & ~SA5)
         | (~HLOAD & FETCH & SA8 & ~SA6)
         | (~HLOAD & FETCH & SA8 & ~SA7)
         | (~HLOAD & FETCH & ~SA8 & SA2 & SA3 & SA4 & SA5 & SA6 & SA7)
         | (~HLOAD & ~FETCH & SA8);
      r_SA9 <=
         (HLOAD & HS9)
         | (~HLOAD & FETCH & SA9 & ~SA2)
         | (~HLOAD & FETCH & SA9 & ~SA3)
         | (~HLOAD & FETCH & SA9 & ~SA4)
         | (~HLOAD & FETCH & SA9 & ~SA5)
         | (~HLOAD & FETCH & SA9 & ~SA6)
         | (~HLOAD & FETCH & SA9 & ~SA7)
         | (~HLOAD & FETCH & SA9 & ~SA8)
         | (~HLOAD & FETCH & ~SA9 & SA2 & SA3 & SA4 & SA5 & SA6 & SA7 & SA8)
         | (~HLOAD & ~FETCH & SA9);
      r_SA10 <=
         (VLOAD & VS0)
         | (~VLOAD & ROWADV & ~SA10)
         | (~VLOAD & ~ROWADV & SA10);
      r_SA11 <=
         (VLOAD & VS1)
         | (~VLOAD & ROWADV & SA11 & ~SA10)
         | (~VLOAD & ROWADV & ~SA11 & SA10)
         | (~VLOAD & ~ROWADV & SA11);
      r_SA12 <=
         (VLOAD & VS2)
         | (~VLOAD & ROWADV & SA12 & ~SA10)
         | (~VLOAD & ROWADV & SA12 & ~SA11)
         | (~VLOAD & ROWADV & ~SA12 & SA10 & SA11)
         | (~VLOAD & ~ROWADV & SA12);
      r_SA13 <=
         (VLOAD & VS3)
         | (~VLOAD & ROWADV & SA13 & ~SA10)
         | (~VLOAD & ROWADV & SA13 & ~SA11)
         | (~VLOAD & ROWADV & SA13 & ~SA12)
         | (~VLOAD & ROWADV & ~SA13 & SA10 & SA11 & SA12)
         | (~VLOAD & ~ROWADV & SA13);
      r_SA14 <=
         (VLOAD & VS4)
         | (~VLOAD & ROWADV & SA14 & ~SA10)
         | (~VLOAD & ROWADV & SA14 & ~SA11)
         | (~VLOAD & ROWADV & SA14 & ~SA12)
         | (~VLOAD & ROWADV & SA14 & ~SA13)
         | (~VLOAD & ROWADV & ~SA14 & SA10 & SA11 & SA12 & SA13)
         | (~VLOAD & ~ROWADV & SA14);
      r_SA15 <=
         (VLOAD & VS5)
         | (~VLOAD & ROWADV & SA15 & ~SA10)
         | (~VLOAD & ROWADV & SA15 & ~SA11)
         | (~VLOAD & ROWADV & SA15 & ~SA12)
         | (~VLOAD & ROWADV & SA15 & ~SA13)
         | (~VLOAD & ROWADV & SA15 & ~SA14)
         | (~VLOAD & ROWADV & ~SA15 & SA10 & SA11 & SA12 & SA13 & SA14)
         | (~VLOAD & ~ROWADV & SA15);
      r_SA16 <=
         (VLOAD & VS6)
         | (~VLOAD & ROWADV & SA16 & ~SA10)
         | (~VLOAD & ROWADV & SA16 & ~SA11)
         | (~VLOAD & ROWADV & SA16 & ~SA12)
         | (~VLOAD & ROWADV & SA16 & ~SA13)
         | (~VLOAD & ROWADV & SA16 & ~SA14)
         | (~VLOAD & ROWADV & SA16 & ~SA15)
         | (~VLOAD & ROWADV & ~SA16 & SA10 & SA11 & SA12 & SA13 & SA14 & SA15)
         | (~VLOAD & ~ROWADV & SA16);
      r_SA17 <=
         (VLOAD & VS7)
         | (~VLOAD & ROWADV & SA17 & ~SA10)
         | (~VLOAD & ROWADV & SA17 & ~SA11)
         | (~VLOAD & ROWADV & SA17 & ~SA12)
         | (~VLOAD & ROWADV & SA17 & ~SA13)
         | (~VLOAD & ROWADV & SA17 & ~SA14)
         | (~VLOAD & ROWADV & SA17 & ~SA15)
         | (~VLOAD & ROWADV & SA17 & ~SA16)
         | (~VLOAD & ROWADV & ~SA17 & SA10 & SA11 & SA12 & SA13 & SA14 & SA15 & SA16)
         | (~VLOAD & ~ROWADV & SA17);
      r_SA18 <=
         (VLOAD & VS8)
         | (~VLOAD & ROWADV & SA18 & ~SA10)
         | (~VLOAD & ROWADV & SA18 & ~SA11)
         | (~VLOAD & ROWADV & SA18 & ~SA12)
         | (~VLOAD & ROWADV & SA18 & ~SA13)
         | (~VLOAD & ROWADV & SA18 & ~SA14)
         | (~VLOAD & ROWADV & SA18 & ~SA15)
         | (~VLOAD & ROWADV & SA18 & ~SA16)
         | (~VLOAD & ROWADV & SA18 & ~SA17)
         | (~VLOAD & ROWADV & ~SA18 & SA10 & SA11 & SA12 & SA13 & SA14 & SA15 & SA16 & SA17)
         | (~VLOAD & ~ROWADV & SA18);
  end

endmodule
`default_nettype wire
