// GENERATED by hardware/gal/verilog/emit.ts from the term lists in
// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module vaddr (
    input  wire DOTCLK,
    input  wire FETCH,
    input  wire RESET,
    input  wire HLOAD,
    input  wire ROWADV,
    input  wire VBLANK,
    input  wire D0,
    input  wire D1,
    input  wire D2,
    input  wire D3,
    input  wire D4,
    input  wire D5,
    input  wire D6,
    input  wire D7,
    input  wire WROWADV,
    input  wire LWHSL,
    input  wire PB2,
    input  wire PB3,
    input  wire PB4,
    input  wire PB5,
    input  wire PB6,
    input  wire PB7,
    input  wire LWHSH,
    input  wire PB0,
    input  wire PB1,
    input  wire MAPLD,
    input  wire CELLTICK,
    input  wire MCADV,
    input  wire WSTB,
    input  wire RA4,
    input  wire RA3,
    input  wire RA2,
    input  wire RA1,
    input  wire RA0,
    input  wire RETIRE,
    input  wire LADV,
    input  wire SRC1,
    input  wire SRC0,
    output wire SA2,
    output wire SA3,
    output wire SA4,
    output wire SA5,
    output wire SA6,
    output wire SA7,
    output wire SA8,
    output wire SA9,
    output wire SA10,
    output wire SA11,
    output wire SA12,
    output wire SA13,
    output wire SA14,
    output wire SA15,
    output wire SA16,
    output wire SA17,
    output wire SA18,
    output wire WA0,
    output wire WA1,
    output wire WA2,
    output wire WA3,
    output wire WA4,
    output wire WA5,
    output wire WA6,
    output wire WA7,
    output wire WA8,
    output wire WA9,
    output wire WA10,
    output wire WA11,
    output wire WA12,
    output wire WA13,
    output wire WA14,
    output wire WA15,
    output wire WA16,
    output wire WA17,
    output wire WA18,
    output wire HS2,
    output wire HS3,
    output wire HS4,
    output wire HS5,
    output wire HS6,
    output wire HS7,
    output wire HS8,
    output wire HS9,
    output wire VS0,
    output wire VS1,
    output wire VS2,
    output wire VS3,
    output wire VS4,
    output wire VS5,
    output wire VS6,
    output wire VS7,
    output wire VS8,
    output wire TB0,
    output wire TB1,
    output wire TB2,
    output wire TB3,
    output wire TB4,
    output wire MB0,
    output wire MB1,
    output wire MB2,
    output wire MB3,
    output wire MB4,
    output wire MB5,
    output wire MB6,
    output wire MAP0,
    output wire MAP1,
    output wire MAP2,
    output wire MAP3,
    output wire MAP4,
    output wire MAP5,
    output wire MAP6,
    output wire MAP7,
    output wire MAPQ0,
    output wire MAPQ1,
    output wire MAPQ2,
    output wire MAPQ3,
    output wire MAPQ4,
    output wire MAPQ5,
    output wire MAPQ6,
    output wire MAPQ7,
    output wire MC0,
    output wire MC1,
    output wire MC2,
    output wire MC3,
    output wire MC4,
    output wire MC5,
    output wire MC6,
    output wire MAPA0,
    output wire MAPA1,
    output wire RP0,
    output wire RP1,
    output wire RLDA,
    output wire RLDB,
    output wire LDVSL,
    output wire LDVSH,
    output wire LDHS,
    output wire LDHSH,
    output wire LDADV,
    output wire LDA,
    output wire LDB,
    output wire LDC,
    output wire LDTB,
    output wire LDMB,
    output wire WINC,
    output wire FBA2,
    output wire FBA3,
    output wire FBA4,
    output wire FBA5,
    output wire FBA6,
    output wire FBA7,
    output wire FBA8,
    output wire FBA9,
    output wire FBA10,
    output wire FBA11,
    output wire FBA12,
    output wire FBA13,
    output wire FBA14,
    output wire FBA15,
    output wire FBA16,
    output wire FBA17,
    output wire FBA18
);

  reg  r_SA2;
  reg  r_SA3;
  reg  r_SA4;
  reg  r_SA5;
  reg  r_SA6;
  reg  r_SA7;
  reg  r_SA8;
  reg  r_SA9;
  reg  r_SA10;
  reg  r_SA11;
  reg  r_SA12;
  reg  r_SA13;
  reg  r_SA14;
  reg  r_SA15;
  reg  r_SA16;
  reg  r_SA17;
  reg  r_SA18;
  reg  r_WA0;
  reg  r_WA1;
  reg  r_WA2;
  reg  r_WA3;
  reg  r_WA4;
  reg  r_WA5;
  reg  r_WA6;
  reg  r_WA7;
  reg  r_WA8;
  reg  r_WA9;
  reg  r_WA10;
  reg  r_WA11;
  reg  r_WA12;
  reg  r_WA13;
  reg  r_WA14;
  reg  r_WA15;
  reg  r_WA16;
  reg  r_WA17;
  reg  r_WA18;
  reg  r_HS2;
  reg  r_HS3;
  reg  r_HS4;
  reg  r_HS5;
  reg  r_HS6;
  reg  r_HS7;
  reg  r_HS8;
  reg  r_HS9;
  reg  r_VS0;
  reg  r_VS1;
  reg  r_VS2;
  reg  r_VS3;
  reg  r_VS4;
  reg  r_VS5;
  reg  r_VS6;
  reg  r_VS7;
  reg  r_VS8;
  reg  r_TB0;
  reg  r_TB1;
  reg  r_TB2;
  reg  r_TB3;
  reg  r_TB4;
  reg  r_MB0;
  reg  r_MB1;
  reg  r_MB2;
  reg  r_MB3;
  reg  r_MB4;
  reg  r_MB5;
  reg  r_MB6;
  reg  r_MAP0;
  reg  r_MAP1;
  reg  r_MAP2;
  reg  r_MAP3;
  reg  r_MAP4;
  reg  r_MAP5;
  reg  r_MAP6;
  reg  r_MAP7;
  reg  r_MAPQ0;
  reg  r_MAPQ1;
  reg  r_MAPQ2;
  reg  r_MAPQ3;
  reg  r_MAPQ4;
  reg  r_MAPQ5;
  reg  r_MAPQ6;
  reg  r_MAPQ7;
  reg  r_MC0;
  reg  r_MC1;
  reg  r_MC2;
  reg  r_MC3;
  reg  r_MC4;
  reg  r_MC5;
  reg  r_MC6;
  reg  r_RP0;
  reg  r_RP1;

  assign SA2 = r_SA2;
  assign SA3 = r_SA3;
  assign SA4 = r_SA4;
  assign SA5 = r_SA5;
  assign SA6 = r_SA6;
  assign SA7 = r_SA7;
  assign SA8 = r_SA8;
  assign SA9 = r_SA9;
  assign SA10 = r_SA10;
  assign SA11 = r_SA11;
  assign SA12 = r_SA12;
  assign SA13 = r_SA13;
  assign SA14 = r_SA14;
  assign SA15 = r_SA15;
  assign SA16 = r_SA16;
  assign SA17 = r_SA17;
  assign SA18 = r_SA18;
  assign WA0 = r_WA0;
  assign WA1 = r_WA1;
  assign WA2 = r_WA2;
  assign WA3 = r_WA3;
  assign WA4 = r_WA4;
  assign WA5 = r_WA5;
  assign WA6 = r_WA6;
  assign WA7 = r_WA7;
  assign WA8 = r_WA8;
  assign WA9 = r_WA9;
  assign WA10 = r_WA10;
  assign WA11 = r_WA11;
  assign WA12 = r_WA12;
  assign WA13 = r_WA13;
  assign WA14 = r_WA14;
  assign WA15 = r_WA15;
  assign WA16 = r_WA16;
  assign WA17 = r_WA17;
  assign WA18 = r_WA18;
  assign HS2 = r_HS2;
  assign HS3 = r_HS3;
  assign HS4 = r_HS4;
  assign HS5 = r_HS5;
  assign HS6 = r_HS6;
  assign HS7 = r_HS7;
  assign HS8 = r_HS8;
  assign HS9 = r_HS9;
  assign VS0 = r_VS0;
  assign VS1 = r_VS1;
  assign VS2 = r_VS2;
  assign VS3 = r_VS3;
  assign VS4 = r_VS4;
  assign VS5 = r_VS5;
  assign VS6 = r_VS6;
  assign VS7 = r_VS7;
  assign VS8 = r_VS8;
  assign TB0 = r_TB0;
  assign TB1 = r_TB1;
  assign TB2 = r_TB2;
  assign TB3 = r_TB3;
  assign TB4 = r_TB4;
  assign MB0 = r_MB0;
  assign MB1 = r_MB1;
  assign MB2 = r_MB2;
  assign MB3 = r_MB3;
  assign MB4 = r_MB4;
  assign MB5 = r_MB5;
  assign MB6 = r_MB6;
  assign MAP0 = r_MAP0;
  assign MAP1 = r_MAP1;
  assign MAP2 = r_MAP2;
  assign MAP3 = r_MAP3;
  assign MAP4 = r_MAP4;
  assign MAP5 = r_MAP5;
  assign MAP6 = r_MAP6;
  assign MAP7 = r_MAP7;
  assign MAPQ0 = r_MAPQ0;
  assign MAPQ1 = r_MAPQ1;
  assign MAPQ2 = r_MAPQ2;
  assign MAPQ3 = r_MAPQ3;
  assign MAPQ4 = r_MAPQ4;
  assign MAPQ5 = r_MAPQ5;
  assign MAPQ6 = r_MAPQ6;
  assign MAPQ7 = r_MAPQ7;
  assign MC0 = r_MC0;
  assign MC1 = r_MC1;
  assign MC2 = r_MC2;
  assign MC3 = r_MC3;
  assign MC4 = r_MC4;
  assign MC5 = r_MC5;
  assign MC6 = r_MC6;
  assign RP0 = r_RP0;
  assign RP1 = r_RP1;

  // EXTERNAL
  assign MAPA0 =
         (MC0);
  // EXTERNAL
  assign MAPA1 =
         (MC1);
  // buried
  assign RLDA =
         (RP0 & ~RP1);
  // buried
  assign RLDB =
         (RP1 & ~RP0);
  // buried
  assign LDVSL =
         (WSTB & ~RA4 & ~RA3 & ~RA2 & ~RA1 & RA0);
  // buried
  assign LDVSH =
         (WSTB & ~RA4 & ~RA3 & ~RA2 & RA1 & ~RA0);
  // buried
  assign LDHS =
         (WSTB & ~RA4 & ~RA3 & ~RA2 & RA1 & RA0);
  // buried
  assign LDHSH =
         (WSTB & ~RA4 & ~RA3 & RA2 & ~RA1 & ~RA0);
  // buried - 13's +$14 - 7.2's next-row-same-column mode
  assign LDADV =
         (WSTB & RA4 & ~RA3 & RA2 & ~RA1 & ~RA0);
  // buried - WPTR's three bytes - item 23 offered a '138 for these
  assign LDA =
         (WSTB & ~RA4 & RA3 & ~RA2 & ~RA1 & ~RA0);
  // buried
  assign LDB =
         (WSTB & ~RA4 & RA3 & ~RA2 & ~RA1 & RA0);
  // buried
  assign LDC =
         (WSTB & ~RA4 & RA3 & ~RA2 & RA1 & ~RA0);
  // buried
  assign LDTB =
         (WSTB & RA4 & ~RA3 & RA2 & RA1 & RA0);
  // buried
  assign LDMB =
         (WSTB & RA4 & RA3 & ~RA2 & ~RA1 & RA0);
  // buried
  assign WINC =
         (RETIRE)
         | (LADV);
  // EXTERNAL
  assign FBA2 =
         (~SRC1 & ~SRC0 & SA2)
         | (~SRC1 & SRC0 & WA2)
         | (SRC1 & ~SRC0 & SA2)
         | (SRC1 & SRC0 & MC2);
  // EXTERNAL
  assign FBA3 =
         (~SRC1 & ~SRC0 & SA3)
         | (~SRC1 & SRC0 & WA3)
         | (SRC1 & ~SRC0 & SA10)
         | (SRC1 & SRC0 & MC3);
  // EXTERNAL
  assign FBA4 =
         (~SRC1 & ~SRC0 & SA4)
         | (~SRC1 & SRC0 & WA4)
         | (SRC1 & ~SRC0 & SA11)
         | (SRC1 & SRC0 & MC4);
  // EXTERNAL
  assign FBA5 =
         (~SRC1 & ~SRC0 & SA5)
         | (~SRC1 & SRC0 & WA5)
         | (SRC1 & ~SRC0 & SA12)
         | (SRC1 & SRC0 & MC5);
  // EXTERNAL
  assign FBA6 =
         (~SRC1 & ~SRC0 & SA6)
         | (~SRC1 & SRC0 & WA6)
         | (SRC1 & ~SRC0 & MAPQ0)
         | (SRC1 & SRC0 & MC6);
  // EXTERNAL
  assign FBA7 =
         (~SRC1 & ~SRC0 & SA7)
         | (~SRC1 & SRC0 & WA7)
         | (SRC1 & ~SRC0 & MAPQ1)
         | (SRC1 & SRC0 & SA13);
  // EXTERNAL
  assign FBA8 =
         (~SRC1 & ~SRC0 & SA8)
         | (~SRC1 & SRC0 & WA8)
         | (SRC1 & ~SRC0 & MAPQ2)
         | (SRC1 & SRC0 & SA14);
  // EXTERNAL
  assign FBA9 =
         (~SRC1 & ~SRC0 & SA9)
         | (~SRC1 & SRC0 & WA9)
         | (SRC1 & ~SRC0 & MAPQ3)
         | (SRC1 & SRC0 & SA15);
  // EXTERNAL
  assign FBA10 =
         (~SRC1 & ~SRC0 & SA10)
         | (~SRC1 & SRC0 & WA10)
         | (SRC1 & ~SRC0 & MAPQ4)
         | (SRC1 & SRC0 & SA16);
  // EXTERNAL
  assign FBA11 =
         (~SRC1 & ~SRC0 & SA11)
         | (~SRC1 & SRC0 & WA11)
         | (SRC1 & ~SRC0 & MAPQ5)
         | (SRC1 & SRC0 & SA17);
  // EXTERNAL
  assign FBA12 =
         (~SRC1 & ~SRC0 & SA12)
         | (~SRC1 & SRC0 & WA12)
         | (SRC1 & ~SRC0 & MAPQ6)
         | (SRC1 & SRC0 & MB0);
  // EXTERNAL
  assign FBA13 =
         (~SRC1 & ~SRC0 & SA13)
         | (~SRC1 & SRC0 & WA13)
         | (SRC1 & ~SRC0 & MAPQ7)
         | (SRC1 & SRC0 & MB1);
  // EXTERNAL
  assign FBA14 =
         (~SRC1 & ~SRC0 & SA14)
         | (~SRC1 & SRC0 & WA14)
         | (SRC1 & ~SRC0 & TB0)
         | (SRC1 & SRC0 & MB2);
  // EXTERNAL
  assign FBA15 =
         (~SRC1 & ~SRC0 & SA15)
         | (~SRC1 & SRC0 & WA15)
         | (SRC1 & ~SRC0 & TB1)
         | (SRC1 & SRC0 & MB3);
  // EXTERNAL
  assign FBA16 =
         (~SRC1 & ~SRC0 & SA16)
         | (~SRC1 & SRC0 & WA16)
         | (SRC1 & ~SRC0 & TB2)
         | (SRC1 & SRC0 & MB4);
  // EXTERNAL
  assign FBA17 =
         (~SRC1 & ~SRC0 & SA17)
         | (~SRC1 & SRC0 & WA17)
         | (SRC1 & ~SRC0 & TB3)
         | (SRC1 & SRC0 & MB5);
  // EXTERNAL
  assign FBA18 =
         (~SRC1 & ~SRC0 & SA18)
         | (~SRC1 & SRC0 & WA18)
         | (SRC1 & ~SRC0 & TB4)
         | (SRC1 & SRC0 & MB6);


  wire AR_ = (RESET);
  always @(posedge DOTCLK or posedge AR_) begin
    if (AR_) begin
      r_SA2 <= 1'b0;
      r_SA3 <= 1'b0;
      r_SA4 <= 1'b0;
      r_SA5 <= 1'b0;
      r_SA6 <= 1'b0;
      r_SA7 <= 1'b0;
      r_SA8 <= 1'b0;
      r_SA9 <= 1'b0;
      r_SA10 <= 1'b0;
      r_SA11 <= 1'b0;
      r_SA12 <= 1'b0;
      r_SA13 <= 1'b0;
      r_SA14 <= 1'b0;
      r_SA15 <= 1'b0;
      r_SA16 <= 1'b0;
      r_SA17 <= 1'b0;
      r_SA18 <= 1'b0;
      r_WA0 <= 1'b0;
      r_WA1 <= 1'b0;
      r_WA2 <= 1'b0;
      r_WA3 <= 1'b0;
      r_WA4 <= 1'b0;
      r_WA5 <= 1'b0;
      r_WA6 <= 1'b0;
      r_WA7 <= 1'b0;
      r_WA8 <= 1'b0;
      r_WA9 <= 1'b0;
      r_WA10 <= 1'b0;
      r_WA11 <= 1'b0;
      r_WA12 <= 1'b0;
      r_WA13 <= 1'b0;
      r_WA14 <= 1'b0;
      r_WA15 <= 1'b0;
      r_WA16 <= 1'b0;
      r_WA17 <= 1'b0;
      r_WA18 <= 1'b0;
      r_HS2 <= 1'b0;
      r_HS3 <= 1'b0;
      r_HS4 <= 1'b0;
      r_HS5 <= 1'b0;
      r_HS6 <= 1'b0;
      r_HS7 <= 1'b0;
      r_HS8 <= 1'b0;
      r_HS9 <= 1'b0;
      r_VS0 <= 1'b0;
      r_VS1 <= 1'b0;
      r_VS2 <= 1'b0;
      r_VS3 <= 1'b0;
      r_VS4 <= 1'b0;
      r_VS5 <= 1'b0;
      r_VS6 <= 1'b0;
      r_VS7 <= 1'b0;
      r_VS8 <= 1'b0;
      r_TB0 <= 1'b0;
      r_TB1 <= 1'b0;
      r_TB2 <= 1'b0;
      r_TB3 <= 1'b0;
      r_TB4 <= 1'b0;
      r_MB0 <= 1'b0;
      r_MB1 <= 1'b0;
      r_MB2 <= 1'b0;
      r_MB3 <= 1'b0;
      r_MB4 <= 1'b0;
      r_MB5 <= 1'b0;
      r_MB6 <= 1'b0;
      r_MAP0 <= 1'b0;
      r_MAP1 <= 1'b0;
      r_MAP2 <= 1'b0;
      r_MAP3 <= 1'b0;
      r_MAP4 <= 1'b0;
      r_MAP5 <= 1'b0;
      r_MAP6 <= 1'b0;
      r_MAP7 <= 1'b0;
      r_MAPQ0 <= 1'b0;
      r_MAPQ1 <= 1'b0;
      r_MAPQ2 <= 1'b0;
      r_MAPQ3 <= 1'b0;
      r_MAPQ4 <= 1'b0;
      r_MAPQ5 <= 1'b0;
      r_MAPQ6 <= 1'b0;
      r_MAPQ7 <= 1'b0;
      r_MC0 <= 1'b0;
      r_MC1 <= 1'b0;
      r_MC2 <= 1'b0;
      r_MC3 <= 1'b0;
      r_MC4 <= 1'b0;
      r_MC5 <= 1'b0;
      r_MC6 <= 1'b0;
      r_RP0 <= 1'b0;
      r_RP1 <= 1'b0;
    end else begin
      r_SA2 <=
         (HLOAD & HS2)
         | (~HLOAD & FETCH & ~SA2)
         | (~HLOAD & ~FETCH & SA2);
      r_SA3 <=
         (HLOAD & HS3)
         | (~HLOAD & FETCH & SA3 & ~SA2)
         | (~HLOAD & FETCH & ~SA3 & SA2)
         | (~HLOAD & ~FETCH & SA3);
      r_SA4 <=
         (HLOAD & HS4)
         | (~HLOAD & FETCH & SA4 & ~SA2)
         | (~HLOAD & FETCH & SA4 & ~SA3)
         | (~HLOAD & FETCH & ~SA4 & SA2 & SA3)
         | (~HLOAD & ~FETCH & SA4);
      r_SA5 <=
         (HLOAD & HS5)
         | (~HLOAD & FETCH & SA5 & ~SA2)
         | (~HLOAD & FETCH & SA5 & ~SA3)
         | (~HLOAD & FETCH & SA5 & ~SA4)
         | (~HLOAD & FETCH & ~SA5 & SA2 & SA3 & SA4)
         | (~HLOAD & ~FETCH & SA5);
      r_SA6 <=
         (HLOAD & HS6)
         | (~HLOAD & FETCH & SA6 & ~SA2)
         | (~HLOAD & FETCH & SA6 & ~SA3)
         | (~HLOAD & FETCH & SA6 & ~SA4)
         | (~HLOAD & FETCH & SA6 & ~SA5)
         | (~HLOAD & FETCH & ~SA6 & SA2 & SA3 & SA4 & SA5)
         | (~HLOAD & ~FETCH & SA6);
      r_SA7 <=
         (HLOAD & HS7)
         | (~HLOAD & FETCH & SA7 & ~SA2)
         | (~HLOAD & FETCH & SA7 & ~SA3)
         | (~HLOAD & FETCH & SA7 & ~SA4)
         | (~HLOAD & FETCH & SA7 & ~SA5)
         | (~HLOAD & FETCH & SA7 & ~SA6)
         | (~HLOAD & FETCH & ~SA7 & SA2 & SA3 & SA4 & SA5 & SA6)
         | (~HLOAD & ~FETCH & SA7);
      r_SA8 <=
         (HLOAD & HS8)
         | (~HLOAD & FETCH & SA8 & ~SA2)
         | (~HLOAD & FETCH & SA8 & ~SA3)
         | (~HLOAD & FETCH & SA8 & ~SA4)
         | (~HLOAD & FETCH & SA8 & ~SA5)
         | (~HLOAD & FETCH & SA8 & ~SA6)
         | (~HLOAD & FETCH & SA8 & ~SA7)
         | (~HLOAD & FETCH & ~SA8 & SA2 & SA3 & SA4 & SA5 & SA6 & SA7)
         | (~HLOAD & ~FETCH & SA8);
      r_SA9 <=
         (HLOAD & HS9)
         | (~HLOAD & FETCH & SA9 & ~SA2)
         | (~HLOAD & FETCH & SA9 & ~SA3)
         | (~HLOAD & FETCH & SA9 & ~SA4)
         | (~HLOAD & FETCH & SA9 & ~SA5)
         | (~HLOAD & FETCH & SA9 & ~SA6)
         | (~HLOAD & FETCH & SA9 & ~SA7)
         | (~HLOAD & FETCH & SA9 & ~SA8)
         | (~HLOAD & FETCH & ~SA9 & SA2 & SA3 & SA4 & SA5 & SA6 & SA7 & SA8)
         | (~HLOAD & ~FETCH & SA9);
      r_SA10 <=
         (VBLANK & VS0)
         | (~VBLANK & ROWADV & ~SA10)
         | (~VBLANK & ~ROWADV & SA10);
      r_SA11 <=
         (VBLANK & VS1)
         | (~VBLANK & ROWADV & SA11 & ~SA10)
         | (~VBLANK & ROWADV & ~SA11 & SA10)
         | (~VBLANK & ~ROWADV & SA11);
      r_SA12 <=
         (VBLANK & VS2)
         | (~VBLANK & ROWADV & SA12 & ~SA10)
         | (~VBLANK & ROWADV & SA12 & ~SA11)
         | (~VBLANK & ROWADV & ~SA12 & SA10 & SA11)
         | (~VBLANK & ~ROWADV & SA12);
      r_SA13 <=
         (VBLANK & VS3)
         | (~VBLANK & ROWADV & SA13 & ~SA10)
         | (~VBLANK & ROWADV & SA13 & ~SA11)
         | (~VBLANK & ROWADV & SA13 & ~SA12)
         | (~VBLANK & ROWADV & ~SA13 & SA10 & SA11 & SA12)
         | (~VBLANK & ~ROWADV & SA13);
      r_SA14 <=
         (VBLANK & VS4)
         | (~VBLANK & ROWADV & SA14 & ~SA10)
         | (~VBLANK & ROWADV & SA14 & ~SA11)
         | (~VBLANK & ROWADV & SA14 & ~SA12)
         | (~VBLANK & ROWADV & SA14 & ~SA13)
         | (~VBLANK & ROWADV & ~SA14 & SA10 & SA11 & SA12 & SA13)
         | (~VBLANK & ~ROWADV & SA14);
      r_SA15 <=
         (VBLANK & VS5)
         | (~VBLANK & ROWADV & SA15 & ~SA10)
         | (~VBLANK & ROWADV & SA15 & ~SA11)
         | (~VBLANK & ROWADV & SA15 & ~SA12)
         | (~VBLANK & ROWADV & SA15 & ~SA13)
         | (~VBLANK & ROWADV & SA15 & ~SA14)
         | (~VBLANK & ROWADV & ~SA15 & SA10 & SA11 & SA12 & SA13 & SA14)
         | (~VBLANK & ~ROWADV & SA15);
      r_SA16 <=
         (VBLANK & VS6)
         | (~VBLANK & ROWADV & SA16 & ~SA10)
         | (~VBLANK & ROWADV & SA16 & ~SA11)
         | (~VBLANK & ROWADV & SA16 & ~SA12)
         | (~VBLANK & ROWADV & SA16 & ~SA13)
         | (~VBLANK & ROWADV & SA16 & ~SA14)
         | (~VBLANK & ROWADV & SA16 & ~SA15)
         | (~VBLANK & ROWADV & ~SA16 & SA10 & SA11 & SA12 & SA13 & SA14 & SA15)
         | (~VBLANK & ~ROWADV & SA16);
      r_SA17 <=
         (VBLANK & VS7)
         | (~VBLANK & ROWADV & SA17 & ~SA10)
         | (~VBLANK & ROWADV & SA17 & ~SA11)
         | (~VBLANK & ROWADV & SA17 & ~SA12)
         | (~VBLANK & ROWADV & SA17 & ~SA13)
         | (~VBLANK & ROWADV & SA17 & ~SA14)
         | (~VBLANK & ROWADV & SA17 & ~SA15)
         | (~VBLANK & ROWADV & SA17 & ~SA16)
         | (~VBLANK & ROWADV & ~SA17 & SA10 & SA11 & SA12 & SA13 & SA14 & SA15 & SA16)
         | (~VBLANK & ~ROWADV & SA17);
      r_SA18 <=
         (VBLANK & VS8)
         | (~VBLANK & ROWADV & SA18 & ~SA10)
         | (~VBLANK & ROWADV & SA18 & ~SA11)
         | (~VBLANK & ROWADV & SA18 & ~SA12)
         | (~VBLANK & ROWADV & SA18 & ~SA13)
         | (~VBLANK & ROWADV & SA18 & ~SA14)
         | (~VBLANK & ROWADV & SA18 & ~SA15)
         | (~VBLANK & ROWADV & SA18 & ~SA16)
         | (~VBLANK & ROWADV & SA18 & ~SA17)
         | (~VBLANK & ROWADV & ~SA18 & SA10 & SA11 & SA12 & SA13 & SA14 & SA15 & SA16 & SA17)
         | (~VBLANK & ~ROWADV & SA18);
      r_WA0 <=
         (LDA & D0)
         | (RLDA & D0)
         | (~LDA & ~RLDA & WINC & ~WA0)
         | (~LDA & ~RLDA & ~WINC & WA0);
      r_WA1 <=
         (LDA & D1)
         | (RLDA & D1)
         | (~LDA & ~RLDA & WINC & WA1 & ~WA0)
         | (~LDA & ~RLDA & WINC & ~WA1 & WA0)
         | (~LDA & ~RLDA & ~WINC & WA1);
      r_WA2 <=
         (LDA & D2)
         | (RLDA & D2)
         | (~LDA & ~RLDA & WINC & WA2 & ~WA0)
         | (~LDA & ~RLDA & WINC & WA2 & ~WA1)
         | (~LDA & ~RLDA & WINC & ~WA2 & WA0 & WA1)
         | (~LDA & ~RLDA & ~WINC & WA2);
      r_WA3 <=
         (LDA & D3)
         | (RLDA & D3)
         | (~LDA & ~RLDA & WINC & WA3 & ~WA0)
         | (~LDA & ~RLDA & WINC & WA3 & ~WA1)
         | (~LDA & ~RLDA & WINC & WA3 & ~WA2)
         | (~LDA & ~RLDA & WINC & ~WA3 & WA0 & WA1 & WA2)
         | (~LDA & ~RLDA & ~WINC & WA3);
      r_WA4 <=
         (LDA & D4)
         | (RLDA & D4)
         | (~LDA & ~RLDA & WINC & WA4 & ~WA0)
         | (~LDA & ~RLDA & WINC & WA4 & ~WA1)
         | (~LDA & ~RLDA & WINC & WA4 & ~WA2)
         | (~LDA & ~RLDA & WINC & WA4 & ~WA3)
         | (~LDA & ~RLDA & WINC & ~WA4 & WA0 & WA1 & WA2 & WA3)
         | (~LDA & ~RLDA & ~WINC & WA4);
      r_WA5 <=
         (LDA & D5)
         | (RLDA & D5)
         | (~LDA & ~RLDA & WINC & WA5 & ~WA0)
         | (~LDA & ~RLDA & WINC & WA5 & ~WA1)
         | (~LDA & ~RLDA & WINC & WA5 & ~WA2)
         | (~LDA & ~RLDA & WINC & WA5 & ~WA3)
         | (~LDA & ~RLDA & WINC & WA5 & ~WA4)
         | (~LDA & ~RLDA & WINC & ~WA5 & WA0 & WA1 & WA2 & WA3 & WA4)
         | (~LDA & ~RLDA & ~WINC & WA5);
      r_WA6 <=
         (LDA & D6)
         | (RLDA & D6)
         | (~LDA & ~RLDA & WINC & WA6 & ~WA0)
         | (~LDA & ~RLDA & WINC & WA6 & ~WA1)
         | (~LDA & ~RLDA & WINC & WA6 & ~WA2)
         | (~LDA & ~RLDA & WINC & WA6 & ~WA3)
         | (~LDA & ~RLDA & WINC & WA6 & ~WA4)
         | (~LDA & ~RLDA & WINC & WA6 & ~WA5)
         | (~LDA & ~RLDA & WINC & ~WA6 & WA0 & WA1 & WA2 & WA3 & WA4 & WA5)
         | (~LDA & ~RLDA & ~WINC & WA6);
      r_WA7 <=
         (LDA & D7)
         | (RLDA & D7)
         | (~LDA & ~RLDA & WINC & WA7 & ~WA0)
         | (~LDA & ~RLDA & WINC & WA7 & ~WA1)
         | (~LDA & ~RLDA & WINC & WA7 & ~WA2)
         | (~LDA & ~RLDA & WINC & WA7 & ~WA3)
         | (~LDA & ~RLDA & WINC & WA7 & ~WA4)
         | (~LDA & ~RLDA & WINC & WA7 & ~WA5)
         | (~LDA & ~RLDA & WINC & WA7 & ~WA6)
         | (~LDA & ~RLDA & WINC & ~WA7 & WA0 & WA1 & WA2 & WA3 & WA4 & WA5 & WA6)
         | (~LDA & ~RLDA & ~WINC & WA7);
      r_WA8 <=
         (LDB & D0)
         | (RLDB & D0)
         | (~LDB & ~RLDB & WINC & WA8 & ~WA0)
         | (~LDB & ~RLDB & WINC & WA8 & ~WA1)
         | (~LDB & ~RLDB & WINC & WA8 & ~WA2)
         | (~LDB & ~RLDB & WINC & WA8 & ~WA3)
         | (~LDB & ~RLDB & WINC & WA8 & ~WA4)
         | (~LDB & ~RLDB & WINC & WA8 & ~WA5)
         | (~LDB & ~RLDB & WINC & WA8 & ~WA6)
         | (~LDB & ~RLDB & WINC & WA8 & ~WA7)
         | (~LDB & ~RLDB & WINC & ~WA8 & WA0 & WA1 & WA2 & WA3 & WA4 & WA5 & WA6 & WA7)
         | (~LDB & ~RLDB & ~WINC & WA8);
      r_WA9 <=
         (LDB & D1)
         | (RLDB & D1)
         | (~LDB & ~RLDB & WINC & WA9 & ~WA0)
         | (~LDB & ~RLDB & WINC & WA9 & ~WA1)
         | (~LDB & ~RLDB & WINC & WA9 & ~WA2)
         | (~LDB & ~RLDB & WINC & WA9 & ~WA3)
         | (~LDB & ~RLDB & WINC & WA9 & ~WA4)
         | (~LDB & ~RLDB & WINC & WA9 & ~WA5)
         | (~LDB & ~RLDB & WINC & WA9 & ~WA6)
         | (~LDB & ~RLDB & WINC & WA9 & ~WA7)
         | (~LDB & ~RLDB & WINC & WA9 & ~WA8)
         | (~LDB & ~RLDB & WINC & ~WA9 & WA0 & WA1 & WA2 & WA3 & WA4 & WA5 & WA6 & WA7 & WA8)
         | (~LDB & ~RLDB & ~WINC & WA9);
      r_WA10 <=
         (LDB & D2)
         | (~LDB & WROWADV & ~WA10)
         | (~LDB & ~WROWADV & WA10);
      r_WA11 <=
         (LDB & D3)
         | (~LDB & WROWADV & WA11 & ~WA10)
         | (~LDB & WROWADV & ~WA11 & WA10)
         | (~LDB & ~WROWADV & WA11);
      r_WA12 <=
         (LDB & D4)
         | (~LDB & WROWADV & WA12 & ~WA10)
         | (~LDB & WROWADV & WA12 & ~WA11)
         | (~LDB & WROWADV & ~WA12 & WA10 & WA11)
         | (~LDB & ~WROWADV & WA12);
      r_WA13 <=
         (LDB & D5)
         | (~LDB & WROWADV & WA13 & ~WA10)
         | (~LDB & WROWADV & WA13 & ~WA11)
         | (~LDB & WROWADV & WA13 & ~WA12)
         | (~LDB & WROWADV & ~WA13 & WA10 & WA11 & WA12)
         | (~LDB & ~WROWADV & WA13);
      r_WA14 <=
         (LDB & D6)
         | (~LDB & WROWADV & WA14 & ~WA10)
         | (~LDB & WROWADV & WA14 & ~WA11)
         | (~LDB & WROWADV & WA14 & ~WA12)
         | (~LDB & WROWADV & WA14 & ~WA13)
         | (~LDB & WROWADV & ~WA14 & WA10 & WA11 & WA12 & WA13)
         | (~LDB & ~WROWADV & WA14);
      r_WA15 <=
         (LDB & D7)
         | (~LDB & WROWADV & WA15 & ~WA10)
         | (~LDB & WROWADV & WA15 & ~WA11)
         | (~LDB & WROWADV & WA15 & ~WA12)
         | (~LDB & WROWADV & WA15 & ~WA13)
         | (~LDB & WROWADV & WA15 & ~WA14)
         | (~LDB & WROWADV & ~WA15 & WA10 & WA11 & WA12 & WA13 & WA14)
         | (~LDB & ~WROWADV & WA15);
      r_WA16 <=
         (LDC & D0)
         | (~LDC & WROWADV & WA16 & ~WA10)
         | (~LDC & WROWADV & WA16 & ~WA11)
         | (~LDC & WROWADV & WA16 & ~WA12)
         | (~LDC & WROWADV & WA16 & ~WA13)
         | (~LDC & WROWADV & WA16 & ~WA14)
         | (~LDC & WROWADV & WA16 & ~WA15)
         | (~LDC & WROWADV & ~WA16 & WA10 & WA11 & WA12 & WA13 & WA14 & WA15)
         | (~LDC & ~WROWADV & WA16);
      r_WA17 <=
         (LDC & D1)
         | (~LDC & WROWADV & WA17 & ~WA10)
         | (~LDC & WROWADV & WA17 & ~WA11)
         | (~LDC & WROWADV & WA17 & ~WA12)
         | (~LDC & WROWADV & WA17 & ~WA13)
         | (~LDC & WROWADV & WA17 & ~WA14)
         | (~LDC & WROWADV & WA17 & ~WA15)
         | (~LDC & WROWADV & WA17 & ~WA16)
         | (~LDC & WROWADV & ~WA17 & WA10 & WA11 & WA12 & WA13 & WA14 & WA15 & WA16)
         | (~LDC & ~WROWADV & WA17);
      r_WA18 <=
         (LDC & D2)
         | (~LDC & WROWADV & WA18 & ~WA10)
         | (~LDC & WROWADV & WA18 & ~WA11)
         | (~LDC & WROWADV & WA18 & ~WA12)
         | (~LDC & WROWADV & WA18 & ~WA13)
         | (~LDC & WROWADV & WA18 & ~WA14)
         | (~LDC & WROWADV & WA18 & ~WA15)
         | (~LDC & WROWADV & WA18 & ~WA16)
         | (~LDC & WROWADV & WA18 & ~WA17)
         | (~LDC & WROWADV & ~WA18 & WA10 & WA11 & WA12 & WA13 & WA14 & WA15 & WA16 & WA17)
         | (~LDC & ~WROWADV & WA18);
      r_HS2 <=
         (LDHS & D2)
         | (LWHSL & PB2)
         | (HS2 & ~LDHS & ~LWHSL);
      r_HS3 <=
         (LDHS & D3)
         | (LWHSL & PB3)
         | (HS3 & ~LDHS & ~LWHSL);
      r_HS4 <=
         (LDHS & D4)
         | (LWHSL & PB4)
         | (HS4 & ~LDHS & ~LWHSL);
      r_HS5 <=
         (LDHS & D5)
         | (LWHSL & PB5)
         | (HS5 & ~LDHS & ~LWHSL);
      r_HS6 <=
         (LDHS & D6)
         | (LWHSL & PB6)
         | (HS6 & ~LDHS & ~LWHSL);
      r_HS7 <=
         (LDHS & D7)
         | (LWHSL & PB7)
         | (HS7 & ~LDHS & ~LWHSL);
      r_HS8 <=
         (LDHSH & D0)
         | (LWHSH & PB0)
         | (HS8 & ~LDHSH & ~LWHSH);
      r_HS9 <=
         (LDHSH & D1)
         | (LWHSH & PB1)
         | (HS9 & ~LDHSH & ~LWHSH);
      r_VS0 <=
         (LDVSL & D0)
         | (VS0 & ~LDVSL);
      r_VS1 <=
         (LDVSL & D1)
         | (VS1 & ~LDVSL);
      r_VS2 <=
         (LDVSL & D2)
         | (VS2 & ~LDVSL);
      r_VS3 <=
         (LDVSL & D3)
         | (VS3 & ~LDVSL);
      r_VS4 <=
         (LDVSL & D4)
         | (VS4 & ~LDVSL);
      r_VS5 <=
         (LDVSL & D5)
         | (VS5 & ~LDVSL);
      r_VS6 <=
         (LDVSL & D6)
         | (VS6 & ~LDVSL);
      r_VS7 <=
         (LDVSL & D7)
         | (VS7 & ~LDVSL);
      r_VS8 <=
         (LDVSH & D0)
         | (VS8 & ~LDVSH);
      r_TB0 <=
         (LDTB & D0)
         | (TB0 & ~LDTB);
      r_TB1 <=
         (LDTB & D1)
         | (TB1 & ~LDTB);
      r_TB2 <=
         (LDTB & D2)
         | (TB2 & ~LDTB);
      r_TB3 <=
         (LDTB & D3)
         | (TB3 & ~LDTB);
      r_TB4 <=
         (LDTB & D4)
         | (TB4 & ~LDTB);
      r_MB0 <=
         (LDMB & D0)
         | (MB0 & ~LDMB);
      r_MB1 <=
         (LDMB & D1)
         | (MB1 & ~LDMB);
      r_MB2 <=
         (LDMB & D2)
         | (MB2 & ~LDMB);
      r_MB3 <=
         (LDMB & D3)
         | (MB3 & ~LDMB);
      r_MB4 <=
         (LDMB & D4)
         | (MB4 & ~LDMB);
      r_MB5 <=
         (LDMB & D5)
         | (MB5 & ~LDMB);
      r_MB6 <=
         (LDMB & D6)
         | (MB6 & ~LDMB);
      r_MAP0 <=
         (MAPLD & PB0)
         | (MAP0 & ~MAPLD);
      r_MAP1 <=
         (MAPLD & PB1)
         | (MAP1 & ~MAPLD);
      r_MAP2 <=
         (MAPLD & PB2)
         | (MAP2 & ~MAPLD);
      r_MAP3 <=
         (MAPLD & PB3)
         | (MAP3 & ~MAPLD);
      r_MAP4 <=
         (MAPLD & PB4)
         | (MAP4 & ~MAPLD);
      r_MAP5 <=
         (MAPLD & PB5)
         | (MAP5 & ~MAPLD);
      r_MAP6 <=
         (MAPLD & PB6)
         | (MAP6 & ~MAPLD);
      r_MAP7 <=
         (MAPLD & PB7)
         | (MAP7 & ~MAPLD);
      r_MAPQ0 <=
         (CELLTICK & MAP0)
         | (MAPQ0 & ~CELLTICK);
      r_MAPQ1 <=
         (CELLTICK & MAP1)
         | (MAPQ1 & ~CELLTICK);
      r_MAPQ2 <=
         (CELLTICK & MAP2)
         | (MAPQ2 & ~CELLTICK);
      r_MAPQ3 <=
         (CELLTICK & MAP3)
         | (MAPQ3 & ~CELLTICK);
      r_MAPQ4 <=
         (CELLTICK & MAP4)
         | (MAPQ4 & ~CELLTICK);
      r_MAPQ5 <=
         (CELLTICK & MAP5)
         | (MAPQ5 & ~CELLTICK);
      r_MAPQ6 <=
         (CELLTICK & MAP6)
         | (MAPQ6 & ~CELLTICK);
      r_MAPQ7 <=
         (CELLTICK & MAP7)
         | (MAPQ7 & ~CELLTICK);
      r_MC0 <=
         (HLOAD & HS3)
         | (~HLOAD & MCADV & ~MC0)
         | (~HLOAD & ~MCADV & MC0);
      r_MC1 <=
         (HLOAD & HS4)
         | (~HLOAD & MCADV & MC1 & ~MC0)
         | (~HLOAD & MCADV & ~MC1 & MC0)
         | (~HLOAD & ~MCADV & MC1);
      r_MC2 <=
         (HLOAD & HS5)
         | (~HLOAD & MCADV & MC2 & ~MC0)
         | (~HLOAD & MCADV & MC2 & ~MC1)
         | (~HLOAD & MCADV & ~MC2 & MC0 & MC1)
         | (~HLOAD & ~MCADV & MC2);
      r_MC3 <=
         (HLOAD & HS6)
         | (~HLOAD & MCADV & MC3 & ~MC0)
         | (~HLOAD & MCADV & MC3 & ~MC1)
         | (~HLOAD & MCADV & MC3 & ~MC2)
         | (~HLOAD & MCADV & ~MC3 & MC0 & MC1 & MC2)
         | (~HLOAD & ~MCADV & MC3);
      r_MC4 <=
         (HLOAD & HS7)
         | (~HLOAD & MCADV & MC4 & ~MC0)
         | (~HLOAD & MCADV & MC4 & ~MC1)
         | (~HLOAD & MCADV & MC4 & ~MC2)
         | (~HLOAD & MCADV & MC4 & ~MC3)
         | (~HLOAD & MCADV & ~MC4 & MC0 & MC1 & MC2 & MC3)
         | (~HLOAD & ~MCADV & MC4);
      r_MC5 <=
         (HLOAD & HS8)
         | (~HLOAD & MCADV & MC5 & ~MC0)
         | (~HLOAD & MCADV & MC5 & ~MC1)
         | (~HLOAD & MCADV & MC5 & ~MC2)
         | (~HLOAD & MCADV & MC5 & ~MC3)
         | (~HLOAD & MCADV & MC5 & ~MC4)
         | (~HLOAD & MCADV & ~MC5 & MC0 & MC1 & MC2 & MC3 & MC4)
         | (~HLOAD & ~MCADV & MC5);
      r_MC6 <=
         (HLOAD & HS9)
         | (~HLOAD & MCADV & MC6 & ~MC0)
         | (~HLOAD & MCADV & MC6 & ~MC1)
         | (~HLOAD & MCADV & MC6 & ~MC2)
         | (~HLOAD & MCADV & MC6 & ~MC3)
         | (~HLOAD & MCADV & MC6 & ~MC4)
         | (~HLOAD & MCADV & MC6 & ~MC5)
         | (~HLOAD & MCADV & ~MC6 & MC0 & MC1 & MC2 & MC3 & MC4 & MC5)
         | (~HLOAD & ~MCADV & MC6);
      r_RP0 <=
         (~RP1 & ~RP0 & WROWADV);
      r_RP1 <=
         (~RP1 & RP0);
    end
  end

endmodule
`default_nettype wire
