// GENERATED by hardware/gal/verilog/emit.ts from the term lists in
// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module vctrl (
    input  wire DOTCLK,
    input  wire RESET,
    input  wire VSTATWR,
    input  wire TC,
    input  wire IOPAGE,
    input  wire A0,
    input  wire A1,
    input  wire SPNA0,
    input  wire SPNA1,
    input  wire E,
    input  wire WCTRL,
    input  wire D0,
    input  wire D1,
    input  wire D3,
    input  wire D4,
    input  wire D5,
    input  wire D6,
    input  wire D7,
    input  wire RW,
    input  wire LDHS,
    input  wire LDADV,
    input  wire D2,
    input  wire LRUN,
    input  wire MAPA0,
    input  wire MAPA1,
    input  wire A19,
    input  wire A20,
    output wire H0,
    output wire H1,
    output wire H2,
    output wire H3,
    output wire H4,
    output wire H5,
    output wire H6,
    output wire H7,
    output wire HSYNC,
    output wire HBLANK,
    output wire V0,
    output wire V1,
    output wire V2,
    output wire V3,
    output wire V4,
    output wire V5,
    output wire V6,
    output wire V7,
    output wire V8,
    output wire V9,
    output wire VTC,
    output wire VSYNC,
    output wire VBLANK,
    output wire BLANK,
    output wire VSDLY,
    output wire VBLPEND,
    output wire IRQ,
    output wire PH0,
    output wire PH1,
    output wire SLOTTICK,
    output wire SPAREWIN,
    output wire FCLK0,
    output wire FCLK1,
    output wire FCLK2,
    output wire FCLK3,
    output wire MUXSEL0,
    output wire MUXSEL1,
    output wire SPANBUSY,
    output wire RETIRE,
    output wire MC0,
    output wire MC1,
    output wire MC2,
    output wire SPANEND,
    output wire WEN,
    output wire WROWADV,
    output wire ACPU0,
    output wire GSPN0,
    output wire ACPU1,
    output wire GSPN1,
    output wire ACPU2,
    output wire GSPN2,
    output wire ACPU3,
    output wire GSPN3,
    output wire SPNGRANT,
    output wire WAIT,
    output wire VMODE0,
    output wire VMODE1,
    output wire WM0,
    output wire WM1,
    output wire CELL,
    output wire IRQEN,
    output wire DISPEN,
    output wire M0,
    output wire HPOL,
    output wire TILEMODE,
    output wire WSTBV,
    output wire HS0,
    output wire HS1,
    output wire WADV0,
    output wire WADV1,
    output wire SR7,
    output wire SR6,
    output wire SR5,
    output wire SR4,
    output wire SR3,
    output wire SR2,
    output wire SR1,
    output wire SR0,
    output wire MASKBIT,
    output wire TFETCH,
    output wire MFETCH,
    output wire FETCH,
    output wire HLOAD,
    output wire HEND,
    output wire ROWADV,
    output wire MAPREQ,
    output wire MCADV,
    output wire MAPLD,
    output wire CELLTICK,
    output wire MAPSEL,
    output wire TILESEL,
    output wire LINEAR,
    output wire SRC0,
    output wire SRC1,
    output wire SPNREQG,
    output wire SPNREQ,
    output wire SPNTICK,
    output wire LGRANT,
    output wire GMAP0,
    output wire GMAP1,
    output wire GMAP2,
    output wire GMAP3,
    output wire GCPU0,
    output wire GCPU1,
    output wire GCPU2,
    output wire GCPU3,
    output wire MAPHOLD,
    output wire WAITSRC,
    output wire WAITRW,
    output wire VRAMSEL,
    output wire IRQ_OE,
    output wire WAIT_OE
);

  reg  r_H0;
  reg  r_H1;
  reg  r_H2;
  reg  r_H3;
  reg  r_H4;
  reg  r_H5;
  reg  r_H6;
  reg  r_H7;
  reg  r_V0;
  reg  r_V1;
  reg  r_V2;
  reg  r_V3;
  reg  r_V4;
  reg  r_V5;
  reg  r_V6;
  reg  r_V7;
  reg  r_V8;
  reg  r_V9;
  reg  r_VSDLY;
  reg  r_VBLPEND;
  reg  r_PH0;
  reg  r_PH1;
  reg  r_SPANBUSY;
  reg  r_MC0;
  reg  r_MC1;
  reg  r_MC2;
  reg  r_VMODE0;
  reg  r_VMODE1;
  reg  r_WM0;
  reg  r_WM1;
  reg  r_CELL;
  reg  r_IRQEN;
  reg  r_DISPEN;
  reg  r_HS0;
  reg  r_HS1;
  reg  r_WADV0;
  reg  r_WADV1;
  reg  r_SR7;
  reg  r_SR6;
  reg  r_SR5;
  reg  r_SR4;
  reg  r_SR3;
  reg  r_SR2;
  reg  r_SR1;
  reg  r_SR0;

  assign H0 = r_H0;
  assign H1 = r_H1;
  assign H2 = r_H2;
  assign H3 = r_H3;
  assign H4 = r_H4;
  assign H5 = r_H5;
  assign H6 = r_H6;
  assign H7 = r_H7;
  assign V0 = r_V0;
  assign V1 = r_V1;
  assign V2 = r_V2;
  assign V3 = r_V3;
  assign V4 = r_V4;
  assign V5 = r_V5;
  assign V6 = r_V6;
  assign V7 = r_V7;
  assign V8 = r_V8;
  assign V9 = r_V9;
  assign VSDLY = r_VSDLY;
  assign VBLPEND = r_VBLPEND;
  assign PH0 = r_PH0;
  assign PH1 = r_PH1;
  assign SPANBUSY = r_SPANBUSY;
  assign MC0 = r_MC0;
  assign MC1 = r_MC1;
  assign MC2 = r_MC2;
  assign VMODE0 = r_VMODE0;
  assign VMODE1 = r_VMODE1;
  assign WM0 = r_WM0;
  assign WM1 = r_WM1;
  assign CELL = r_CELL;
  assign IRQEN = r_IRQEN;
  assign DISPEN = r_DISPEN;
  assign HS0 = r_HS0;
  assign HS1 = r_HS1;
  assign WADV0 = r_WADV0;
  assign WADV1 = r_WADV1;
  assign SR7 = r_SR7;
  assign SR6 = r_SR6;
  assign SR5 = r_SR5;
  assign SR4 = r_SR4;
  assign SR3 = r_SR3;
  assign SR2 = r_SR2;
  assign SR1 = r_SR1;
  assign SR0 = r_SR0;

  // EXTERNAL - polarity carried as an input, not strapped in silicon
  assign HSYNC =
         (~H7 & ~H6 & ~H5 & ~H4 & ~HPOL)
         | (~H7 & ~H6 & ~H5 & ~H3 & ~HPOL)
         | (H4 & H3 & HPOL)
         | (H5 & HPOL)
         | (H6 & HPOL)
         | (H7 & HPOL);
  // EXTERNAL
  assign HBLANK =
         (~H7 & ~H6 & ~H5)
         | (~H7 & ~H6 & ~H4 & ~H3 & ~H2)
         | (H7 & H6 & H2);
  // buried
  assign VTC =
         (~M0 & V8 & V7 & V6 & ~V5 & ~V4 & ~V3 & ~V2 & ~V1 & ~V0)
         | (M0 & V9 & V3 & V2);
  // EXTERNAL - polarity is a function of VMODE[0] - graphics.md 6.2.1
  assign VSYNC =
         (~V9 & ~V8 & ~V7 & ~V6 & ~V5 & ~V4 & ~V3 & ~V2 & ~V1 & ~M0)
         | (V1 & M0)
         | (V2 & M0)
         | (V3 & M0)
         | (V4 & M0)
         | (V5 & M0)
         | (V6 & M0)
         | (V7 & M0)
         | (V8 & M0)
         | (V9 & M0);
  // EXTERNAL
  assign VBLANK =
         (~M0 & ~V9 & ~V8 & ~V7 & ~V6 & ~V5)
         | (~M0 & ~V8 & ~V7 & ~V6 & V5 & ~V4 & ~V3 & ~V2)
         | (~M0 & ~V8 & ~V7 & ~V6 & V5 & ~V4 & ~V3 & ~V1 & ~V0)
         | (~M0 & V8 & V7 & ~V6 & V5 & V4 & V2 & V0)
         | (~M0 & V8 & V7 & ~V6 & V5 & V4 & V2 & V1)
         | (~M0 & V8 & V7 & ~V6 & V5 & V4 & V3)
         | (~M0 & V8 & V7 & V6 & ~V5 & ~V4 & ~V3 & ~V2 & ~V1 & ~V0)
         | (M0 & ~V9 & ~V8 & ~V7 & ~V6 & ~V5)
         | (M0 & ~V8 & ~V7 & ~V6 & V5 & ~V4 & ~V3 & ~V2 & ~V1)
         | (M0 & ~V8 & ~V7 & ~V6 & V5 & ~V4 & ~V3 & ~V2 & ~V0)
         | (M0 & V9 & V1 & V0)
         | (M0 & V9 & V2)
         | (M0 & V9 & V3);
  // EXTERNAL
  assign BLANK =
         (VBLANK)
         | (HBLANK);
  // EXTERNAL - open-drain by the OE idiom - the one OE term is spent
  assign IRQ =
         1'b0;
  // buried
  assign SLOTTICK =
         (PH1 & PH0);
  // buried - 5.2.2 - spare first, which is +46.9 ns against video-first's -25.1
  assign SPAREWIN =
         (~PH1);
  // EXTERNAL
  assign FCLK0 =
         (PH1 & PH0 & ~HS0 & ~HS1)
         | (~PH1 & ~PH0 & HS0)
         | (~PH1 & ~PH0 & HS1);
  // EXTERNAL
  assign FCLK1 =
         (PH1 & PH0 & ~HS1)
         | (~PH1 & ~PH0 & HS1);
  // EXTERNAL
  assign FCLK2 =
         (~PH1 & ~PH0 & HS0 & HS1)
         | (PH1 & PH0 & ~HS1)
         | (PH1 & PH0 & ~HS0);
  // EXTERNAL - chip 3 is never after the wrap, so it is EARLY for every p
  assign FCLK3 =
         (PH1 & PH0);
  // EXTERNAL
  assign MUXSEL0 =
         (PH0 & ~HS0)
         | (~PH0 & HS0);
  // EXTERNAL
  assign MUXSEL1 =
         (PH1 & ~HS1 & ~PH0)
         | (PH1 & ~HS1 & ~HS0)
         | (~PH1 & HS1 & ~PH0)
         | (~PH1 & HS1 & ~HS0)
         | (PH1 & HS1 & PH0 & HS0)
         | (~PH1 & ~HS1 & PH0 & HS0);
  // EXTERNAL - also WPTR's WINC, the serialiser's shift and the length counter's enable
  assign RETIRE =
         (SPANBUSY & SPNGRANT & SPNTICK);
  // buried
  assign SPANEND =
         (RETIRE & ~WM1 & ~WM0)
         | (RETIRE & ~WM1 & WM0 & MC2 & MC1 & MC0)
         | (RETIRE & WM1 & ~WM0 & TC)
         | (RETIRE & WM1 & WM0 & MC2 & MC1 & MC0);
  // EXTERNAL - RETIRE, except a transparent pixel in sprite mode
  assign WEN =
         (RETIRE & ~WM1)
         | (RETIRE & ~WM0)
         | (RETIRE & MASKBIT);
  // EXTERNAL
  assign WROWADV =
         (SPANEND & WADV0)
         | (SPANEND & WADV1);
  // buried - SRCSEL[n] is this same pin - 5.2.1, not a second macrocell
  assign ACPU0 =
         (VRAMSEL & ~IOPAGE & ~A0 & ~A1);
  // EXTERNAL
  assign GSPN0 =
         (SPNREQG & ~SPNA0 & ~SPNA1 & ~VRAMSEL)
         | (SPNREQG & ~SPNA0 & ~SPNA1 & IOPAGE)
         | (SPNREQG & ~SPNA0 & ~SPNA1 & A0)
         | (SPNREQG & ~SPNA0 & ~SPNA1 & A1);
  // buried
  assign ACPU1 =
         (VRAMSEL & ~IOPAGE & A0 & ~A1);
  // EXTERNAL
  assign GSPN1 =
         (SPNREQG & SPNA0 & ~SPNA1 & ~VRAMSEL)
         | (SPNREQG & SPNA0 & ~SPNA1 & IOPAGE)
         | (SPNREQG & SPNA0 & ~SPNA1 & ~A0)
         | (SPNREQG & SPNA0 & ~SPNA1 & A1);
  // buried
  assign ACPU2 =
         (VRAMSEL & ~IOPAGE & ~A0 & A1);
  // EXTERNAL
  assign GSPN2 =
         (SPNREQG & ~SPNA0 & SPNA1 & ~VRAMSEL)
         | (SPNREQG & ~SPNA0 & SPNA1 & IOPAGE)
         | (SPNREQG & ~SPNA0 & SPNA1 & A0)
         | (SPNREQG & ~SPNA0 & SPNA1 & ~A1);
  // buried
  assign ACPU3 =
         (VRAMSEL & ~IOPAGE & A0 & A1);
  // EXTERNAL
  assign GSPN3 =
         (SPNREQG & SPNA0 & SPNA1 & ~VRAMSEL)
         | (SPNREQG & SPNA0 & SPNA1 & IOPAGE)
         | (SPNREQG & SPNA0 & SPNA1 & ~A0)
         | (SPNREQG & SPNA0 & SPNA1 & ~A1);
  // buried
  assign SPNGRANT =
         (SPNREQG & ~SPNA0 & A0)
         | (SPNREQG & SPNA0 & ~A0)
         | (SPNREQG & ~SPNA1 & A1)
         | (SPNREQG & SPNA1 & ~A1)
         | (SPNREQG & ~VRAMSEL)
         | (SPNREQG & IOPAGE);
  // EXTERNAL - open-drain by the OE idiom - SPANBUSY . VRAMSEL . /IOPAGE . E . /RW
  assign WAIT =
         1'b0;
  // buried
  assign M0 =
         (VMODE0);
  // buried
  assign HPOL =
         (VMODE0)
         | (~VMODE0);
  // buried
  assign TILEMODE =
         (CELL);
  // buried
  assign WSTBV =
         (VRAMSEL & ~RW & E);
  // EXTERNAL - the serialiser's top bit, except that span-solid is always WFG
  assign MASKBIT =
         (WM1 & ~WM0)
         | (SR7 & ~WM1)
         | (SR7 & WM0);
  // buried
  assign TFETCH =
         (H5 & H2)
         | (H5 & H3)
         | (H5 & H4)
         | (~H7 & H6)
         | (H7 & ~H6)
         | (H6 & ~H2);
  // buried
  assign MFETCH =
         (H5 & H1)
         | (H5 & H2)
         | (H5 & H3)
         | (H5 & H4)
         | (~H7 & H6)
         | (H7 & ~H6)
         | (H6 & ~H2 & ~H1);
  // EXTERNAL
  assign FETCH =
         (TFETCH & SLOTTICK);
  // EXTERNAL
  assign HLOAD =
         (~H7 & ~H6 & ~H5)
         | (~H7 & ~H6 & ~H4 & ~H3 & ~H2 & ~H1);
  // buried
  assign HEND =
         (H7 & H6 & H2 & H1 & H0);
  // EXTERNAL
  assign ROWADV =
         (~VBLANK & HEND & SLOTTICK & VMODE1)
         | (~VBLANK & HEND & SLOTTICK & ~V0);
  // buried
  assign MAPREQ =
         (TILEMODE & MFETCH & ~H0);
  // EXTERNAL
  assign MCADV =
         (TILEMODE & MFETCH & H0 & SLOTTICK);
  // EXTERNAL
  assign MAPLD =
         (MAPREQ & ~PH1 & PH0);
  // EXTERNAL
  assign CELLTICK =
         (TILEMODE & MFETCH & H0 & SLOTTICK);
  // buried
  assign MAPSEL =
         (MAPREQ & ~PH1);
  // buried
  assign TILESEL =
         (TILEMODE & PH1 & ~SPNGRANT);
  // buried
  assign LINEAR =
         (~TILEMODE & PH1 & ~SPNGRANT);
  // EXTERNAL
  assign SRC0 =
         (SPNGRANT)
         | (MAPSEL);
  // EXTERNAL
  assign SRC1 =
         (TILESEL)
         | (MAPSEL);
  // buried
  assign SPNREQG =
         (SPNREQ & ~MAPREQ);
  // buried
  assign SPNREQ =
         (SPANBUSY & SPAREWIN)
         | (LRUN & SPAREWIN);
  // buried
  assign SPNTICK =
         (~PH1 & PH0);
  // EXTERNAL
  assign LGRANT =
         (LRUN & ~SPANBUSY & SPNGRANT & SPNTICK);
  // buried
  assign GMAP0 =
         (MAPREQ & ~MAPA0 & ~MAPA1);
  // buried
  assign GMAP1 =
         (MAPREQ & MAPA0 & ~MAPA1);
  // buried
  assign GMAP2 =
         (MAPREQ & ~MAPA0 & MAPA1);
  // buried
  assign GMAP3 =
         (MAPREQ & MAPA0 & MAPA1);
  // EXTERNAL
  assign GCPU0 =
         (ACPU0 & ~GMAP0);
  // EXTERNAL
  assign GCPU1 =
         (ACPU1 & ~GMAP1);
  // EXTERNAL
  assign GCPU2 =
         (ACPU2 & ~GMAP2);
  // EXTERNAL
  assign GCPU3 =
         (ACPU3 & ~GMAP3);
  // buried
  assign MAPHOLD =
         (MAPREQ & ~MAPA0 & ~A0 & ~MAPA1 & ~A1)
         | (MAPREQ & MAPA0 & A0 & ~MAPA1 & ~A1)
         | (MAPREQ & ~MAPA0 & ~A0 & MAPA1 & A1)
         | (MAPREQ & MAPA0 & A0 & MAPA1 & A1);
  // buried
  assign WAITSRC =
         (SPANBUSY)
         | (MAPHOLD);
  // buried
  assign WAITRW =
         (RW & ~MAPHOLD);
  // EXTERNAL - 6.3.2 - A19 alone matches every I/O access, because the map SRAM keeps driving it. /A20 since 2026-09-08: the physical map is 32 MB (machine.md 5 item 1 D) and the ring is one 512 KB quadrant of it, not the top half of a 1 MB map
  assign VRAMSEL =
         (A19 & ~A20 & ~IOPAGE);

  // IRQ is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign IRQ_OE =
         (VBLPEND & IRQEN);
  // WAIT is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign WAIT_OE =
         (WAITSRC & VRAMSEL & ~IOPAGE & E & ~WAITRW);

  wire AR_ = (RESET);
  always @(posedge DOTCLK or posedge AR_) begin
    if (AR_) begin
      r_H0 <= 1'b0;
      r_H1 <= 1'b0;
      r_H2 <= 1'b0;
      r_H3 <= 1'b0;
      r_H4 <= 1'b0;
      r_H5 <= 1'b0;
      r_H6 <= 1'b0;
      r_H7 <= 1'b0;
      r_V0 <= 1'b0;
      r_V1 <= 1'b0;
      r_V2 <= 1'b0;
      r_V3 <= 1'b0;
      r_V4 <= 1'b0;
      r_V5 <= 1'b0;
      r_V6 <= 1'b0;
      r_V7 <= 1'b0;
      r_V8 <= 1'b0;
      r_V9 <= 1'b0;
      r_VSDLY <= 1'b0;
      r_VBLPEND <= 1'b0;
      r_PH0 <= 1'b0;
      r_PH1 <= 1'b0;
      r_SPANBUSY <= 1'b0;
      r_MC0 <= 1'b0;
      r_MC1 <= 1'b0;
      r_MC2 <= 1'b0;
      r_VMODE0 <= 1'b0;
      r_VMODE1 <= 1'b0;
      r_WM0 <= 1'b0;
      r_WM1 <= 1'b0;
      r_CELL <= 1'b0;
      r_IRQEN <= 1'b0;
      r_DISPEN <= 1'b0;
      r_HS0 <= 1'b0;
      r_HS1 <= 1'b0;
      r_WADV0 <= 1'b0;
      r_WADV1 <= 1'b0;
      r_SR7 <= 1'b0;
      r_SR6 <= 1'b0;
      r_SR5 <= 1'b0;
      r_SR4 <= 1'b0;
      r_SR3 <= 1'b0;
      r_SR2 <= 1'b0;
      r_SR1 <= 1'b0;
      r_SR0 <= 1'b0;
    end else begin
      r_H0 <=
         (SLOTTICK & ~H0)
         | (~SLOTTICK & H0);
      r_H1 <=
         (SLOTTICK & ~H0 & H1)
         | (SLOTTICK & ~H1 & H0)
         | (~SLOTTICK & H1);
      r_H2 <=
         (SLOTTICK & ~H0 & H2)
         | (SLOTTICK & ~H1 & H2)
         | (SLOTTICK & ~H2 & H0 & H1)
         | (~SLOTTICK & H2);
      r_H3 <=
         (SLOTTICK & ~H0 & H3)
         | (SLOTTICK & ~H1 & H3)
         | (SLOTTICK & ~H2 & H3)
         | (SLOTTICK & ~H7 & ~H3 & H0 & H1 & H2)
         | (SLOTTICK & ~H6 & ~H3 & H0 & H1 & H2)
         | (~SLOTTICK & H3);
      r_H4 <=
         (SLOTTICK & ~H0 & H4)
         | (SLOTTICK & ~H1 & H4)
         | (SLOTTICK & ~H2 & H4)
         | (SLOTTICK & ~H7 & H4 & ~H3)
         | (SLOTTICK & ~H6 & H4 & ~H3)
         | (SLOTTICK & ~H7 & ~H4 & H0 & H1 & H2 & H3)
         | (SLOTTICK & ~H6 & ~H4 & H0 & H1 & H2 & H3)
         | (~SLOTTICK & H4);
      r_H5 <=
         (SLOTTICK & ~H0 & H5)
         | (SLOTTICK & ~H1 & H5)
         | (SLOTTICK & ~H2 & H5)
         | (SLOTTICK & ~H7 & H5 & ~H3)
         | (SLOTTICK & ~H6 & H5 & ~H3)
         | (SLOTTICK & ~H7 & H5 & ~H4)
         | (SLOTTICK & ~H6 & H5 & ~H4)
         | (SLOTTICK & ~H7 & ~H5 & H0 & H1 & H2 & H3 & H4)
         | (SLOTTICK & ~H6 & ~H5 & H0 & H1 & H2 & H3 & H4)
         | (~SLOTTICK & H5);
      r_H6 <=
         (SLOTTICK & ~H0 & H6)
         | (SLOTTICK & ~H1 & H6)
         | (SLOTTICK & ~H2 & H6)
         | (SLOTTICK & ~H7 & H6 & ~H3)
         | (SLOTTICK & ~H7 & H6 & ~H4)
         | (SLOTTICK & ~H7 & H6 & ~H5)
         | (SLOTTICK & ~H6 & H0 & H1 & H2 & H3 & H4 & H5)
         | (~SLOTTICK & H6);
      r_H7 <=
         (SLOTTICK & ~H0 & H7)
         | (SLOTTICK & ~H1 & H7)
         | (SLOTTICK & ~H2 & H7)
         | (SLOTTICK & ~H6 & H7)
         | (SLOTTICK & ~H7 & H0 & H1 & H2 & H3 & H4 & H5 & H6)
         | (~SLOTTICK & H7);
      r_V0 <=
         (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & ~V0)
         | (~SLOTTICK & V0)
         | (~H7 & V0)
         | (~H6 & V0)
         | (~H2 & V0)
         | (~H1 & V0)
         | (~H0 & V0);
      r_V1 <=
         (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V1 & ~V0)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & ~V1 & V0)
         | (~SLOTTICK & V1)
         | (~H7 & V1)
         | (~H6 & V1)
         | (~H2 & V1)
         | (~H1 & V1)
         | (~H0 & V1);
      r_V2 <=
         (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V2 & ~V0)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V2 & ~V1)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & ~V2 & V0 & V1)
         | (~SLOTTICK & V2)
         | (~H7 & V2)
         | (~H6 & V2)
         | (~H2 & V2)
         | (~H1 & V2)
         | (~H0 & V2);
      r_V3 <=
         (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V3 & ~V0)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V3 & ~V1)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V3 & ~V2)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & ~V3 & V0 & V1 & V2)
         | (~SLOTTICK & V3)
         | (~H7 & V3)
         | (~H6 & V3)
         | (~H2 & V3)
         | (~H1 & V3)
         | (~H0 & V3);
      r_V4 <=
         (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V4 & ~V0)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V4 & ~V1)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V4 & ~V2)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V4 & ~V3)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & ~V4 & V0 & V1 & V2 & V3)
         | (~SLOTTICK & V4)
         | (~H7 & V4)
         | (~H6 & V4)
         | (~H2 & V4)
         | (~H1 & V4)
         | (~H0 & V4);
      r_V5 <=
         (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V5 & ~V0)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V5 & ~V1)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V5 & ~V2)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V5 & ~V3)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V5 & ~V4)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & ~V5 & V0 & V1 & V2 & V3 & V4)
         | (~SLOTTICK & V5)
         | (~H7 & V5)
         | (~H6 & V5)
         | (~H2 & V5)
         | (~H1 & V5)
         | (~H0 & V5);
      r_V6 <=
         (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V6 & ~V0)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V6 & ~V1)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V6 & ~V2)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V6 & ~V3)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V6 & ~V4)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V6 & ~V5)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & ~V6 & V0 & V1 & V2 & V3 & V4 & V5)
         | (~SLOTTICK & V6)
         | (~H7 & V6)
         | (~H6 & V6)
         | (~H2 & V6)
         | (~H1 & V6)
         | (~H0 & V6);
      r_V7 <=
         (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V7 & ~V0)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V7 & ~V1)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V7 & ~V2)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V7 & ~V3)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V7 & ~V4)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V7 & ~V5)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V7 & ~V6)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & ~V7 & V0 & V1 & V2 & V3 & V4 & V5 & V6)
         | (~SLOTTICK & V7)
         | (~H7 & V7)
         | (~H6 & V7)
         | (~H2 & V7)
         | (~H1 & V7)
         | (~H0 & V7);
      r_V8 <=
         (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V8 & ~V0)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V8 & ~V1)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V8 & ~V2)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V8 & ~V3)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V8 & ~V4)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V8 & ~V5)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V8 & ~V6)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V8 & ~V7)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & ~V8 & V0 & V1 & V2 & V3 & V4 & V5 & V6 & V7)
         | (~SLOTTICK & V8)
         | (~H7 & V8)
         | (~H6 & V8)
         | (~H2 & V8)
         | (~H1 & V8)
         | (~H0 & V8);
      r_V9 <=
         (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V9 & ~V0)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V9 & ~V1)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V9 & ~V2)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V9 & ~V3)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V9 & ~V4)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V9 & ~V5)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V9 & ~V6)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V9 & ~V7)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & V9 & ~V8)
         | (SLOTTICK & H7 & H6 & H2 & H1 & H0 & ~VTC & ~V9 & V0 & V1 & V2 & V3 & V4 & V5 & V6 & V7 & V8)
         | (~SLOTTICK & V9)
         | (~H7 & V9)
         | (~H6 & V9)
         | (~H2 & V9)
         | (~H1 & V9)
         | (~H0 & V9);
      r_VSDLY <=
         (~V9 & ~V8 & ~V7 & ~V6 & ~V5 & ~V4 & ~V3 & ~V2 & ~V1);
      r_VBLPEND <=
         (~V9 & ~V8 & ~V7 & ~V6 & ~V5 & ~V4 & ~V3 & ~V2 & ~V1 & ~VSDLY)
         | (VBLPEND & ~VSTATWR);
      r_PH0 <=
         (~PH0);
      r_PH1 <=
         (PH1 & ~PH0)
         | (~PH1 & PH0);
      r_SPANBUSY <=
         (WSTBV)
         | (SPANBUSY & ~SPANEND);
      r_MC0 <=
         (~WSTBV & RETIRE & ~MC0)
         | (~WSTBV & ~RETIRE & MC0);
      r_MC1 <=
         (~WSTBV & RETIRE & MC1 & ~MC0)
         | (~WSTBV & RETIRE & ~MC1 & MC0)
         | (~WSTBV & ~RETIRE & MC1);
      r_MC2 <=
         (~WSTBV & RETIRE & MC2 & ~MC0)
         | (~WSTBV & RETIRE & MC2 & ~MC1)
         | (~WSTBV & RETIRE & ~MC2 & MC0 & MC1)
         | (~WSTBV & ~RETIRE & MC2);
      r_VMODE0 <=
         (WCTRL & D0)
         | (VMODE0 & ~WCTRL);
      r_VMODE1 <=
         (WCTRL & D1)
         | (VMODE1 & ~WCTRL);
      r_WM0 <=
         (WCTRL & D3)
         | (WM0 & ~WCTRL);
      r_WM1 <=
         (WCTRL & D4)
         | (WM1 & ~WCTRL);
      r_CELL <=
         (WCTRL & D5)
         | (CELL & ~WCTRL);
      r_IRQEN <=
         (WCTRL & D6)
         | (IRQEN & ~WCTRL);
      r_DISPEN <=
         (WCTRL & D7)
         | (DISPEN & ~WCTRL);
      r_HS0 <=
         (LDHS & D0)
         | (HS0 & ~LDHS);
      r_HS1 <=
         (LDHS & D1)
         | (HS1 & ~LDHS);
      r_WADV0 <=
         (LDADV & D0)
         | (WADV0 & ~LDADV);
      r_WADV1 <=
         (LDADV & D1)
         | (WADV1 & ~LDADV);
      r_SR7 <=
         (WSTBV & D7)
         | (~WSTBV & RETIRE & SR6)
         | (~WSTBV & ~RETIRE & SR7);
      r_SR6 <=
         (WSTBV & D6)
         | (~WSTBV & RETIRE & SR5)
         | (~WSTBV & ~RETIRE & SR6);
      r_SR5 <=
         (WSTBV & D5)
         | (~WSTBV & RETIRE & SR4)
         | (~WSTBV & ~RETIRE & SR5);
      r_SR4 <=
         (WSTBV & D4)
         | (~WSTBV & RETIRE & SR3)
         | (~WSTBV & ~RETIRE & SR4);
      r_SR3 <=
         (WSTBV & D3)
         | (~WSTBV & RETIRE & SR2)
         | (~WSTBV & ~RETIRE & SR3);
      r_SR2 <=
         (WSTBV & D2)
         | (~WSTBV & RETIRE & SR1)
         | (~WSTBV & ~RETIRE & SR2);
      r_SR1 <=
         (WSTBV & D1)
         | (~WSTBV & RETIRE & SR0)
         | (~WSTBV & ~RETIRE & SR1);
      r_SR0 <=
         (WSTBV & D0)
         | (~WSTBV & ~RETIRE & SR0);
    end
  end

endmodule
`default_nettype wire
