// GENERATED by hardware/gal/verilog/emit.ts from the term lists in
// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module vlen (
    input  wire CLK,
    input  wire RD0,
    input  wire RD1,
    input  wire RD2,
    input  wire RD3,
    input  wire RD4,
    input  wire RD5,
    input  wire RD6,
    input  wire RD7,
    input  wire WSTBV,
    input  wire SPANBUSY,
    input  wire RETIRE,
    output wire LDLEN,
    output wire NSL0,
    output wire NSL1,
    output wire NSL2,
    output wire NSL3,
    output wire NSL4,
    output wire NSL5,
    output wire NSL6,
    output wire NSL7,
    output wire TC
);

  reg  r_NSL0;
  reg  r_NSL1;
  reg  r_NSL2;
  reg  r_NSL3;
  reg  r_NSL4;
  reg  r_NSL5;
  reg  r_NSL6;
  reg  r_NSL7;

  assign NSL0 = r_NSL0;
  assign NSL1 = r_NSL1;
  assign NSL2 = r_NSL2;
  assign NSL3 = r_NSL3;
  assign NSL4 = r_NSL4;
  assign NSL5 = r_NSL5;
  assign NSL6 = r_NSL6;
  assign NSL7 = r_NSL7;

  // EXTERNAL
  assign LDLEN =
         (WSTBV & ~SPANBUSY);
  // EXTERNAL - SPANLEN = 0 is ~SPANLEN = 255 - one eight-literal term, not eight terms
  assign TC =
         (NSL0 & NSL1 & NSL2 & NSL3 & NSL4 & NSL5 & NSL6 & NSL7);


  always @(posedge CLK) begin
      r_NSL0 <=
         (LDLEN & ~RD0)
         | (~LDLEN & RETIRE & ~NSL0)
         | (~LDLEN & ~RETIRE & NSL0);
      r_NSL1 <=
         (LDLEN & ~RD1)
         | (~LDLEN & RETIRE & NSL1 & ~NSL0)
         | (~LDLEN & RETIRE & ~NSL1 & NSL0)
         | (~LDLEN & ~RETIRE & NSL1);
      r_NSL2 <=
         (LDLEN & ~RD2)
         | (~LDLEN & RETIRE & NSL2 & ~NSL0)
         | (~LDLEN & RETIRE & NSL2 & ~NSL1)
         | (~LDLEN & RETIRE & ~NSL2 & NSL0 & NSL1)
         | (~LDLEN & ~RETIRE & NSL2);
      r_NSL3 <=
         (LDLEN & ~RD3)
         | (~LDLEN & RETIRE & NSL3 & ~NSL0)
         | (~LDLEN & RETIRE & NSL3 & ~NSL1)
         | (~LDLEN & RETIRE & NSL3 & ~NSL2)
         | (~LDLEN & RETIRE & ~NSL3 & NSL0 & NSL1 & NSL2)
         | (~LDLEN & ~RETIRE & NSL3);
      r_NSL4 <=
         (LDLEN & ~RD4)
         | (~LDLEN & RETIRE & NSL4 & ~NSL0)
         | (~LDLEN & RETIRE & NSL4 & ~NSL1)
         | (~LDLEN & RETIRE & NSL4 & ~NSL2)
         | (~LDLEN & RETIRE & NSL4 & ~NSL3)
         | (~LDLEN & RETIRE & ~NSL4 & NSL0 & NSL1 & NSL2 & NSL3)
         | (~LDLEN & ~RETIRE & NSL4);
      r_NSL5 <=
         (LDLEN & ~RD5)
         | (~LDLEN & RETIRE & NSL5 & ~NSL0)
         | (~LDLEN & RETIRE & NSL5 & ~NSL1)
         | (~LDLEN & RETIRE & NSL5 & ~NSL2)
         | (~LDLEN & RETIRE & NSL5 & ~NSL3)
         | (~LDLEN & RETIRE & NSL5 & ~NSL4)
         | (~LDLEN & RETIRE & ~NSL5 & NSL0 & NSL1 & NSL2 & NSL3 & NSL4)
         | (~LDLEN & ~RETIRE & NSL5);
      r_NSL6 <=
         (LDLEN & ~RD6)
         | (~LDLEN & RETIRE & NSL6 & ~NSL0)
         | (~LDLEN & RETIRE & NSL6 & ~NSL1)
         | (~LDLEN & RETIRE & NSL6 & ~NSL2)
         | (~LDLEN & RETIRE & NSL6 & ~NSL3)
         | (~LDLEN & RETIRE & NSL6 & ~NSL4)
         | (~LDLEN & RETIRE & NSL6 & ~NSL5)
         | (~LDLEN & RETIRE & ~NSL6 & NSL0 & NSL1 & NSL2 & NSL3 & NSL4 & NSL5)
         | (~LDLEN & ~RETIRE & NSL6);
      r_NSL7 <=
         (LDLEN & ~RD7)
         | (~LDLEN & RETIRE & NSL7 & ~NSL0)
         | (~LDLEN & RETIRE & NSL7 & ~NSL1)
         | (~LDLEN & RETIRE & NSL7 & ~NSL2)
         | (~LDLEN & RETIRE & NSL7 & ~NSL3)
         | (~LDLEN & RETIRE & NSL7 & ~NSL4)
         | (~LDLEN & RETIRE & NSL7 & ~NSL5)
         | (~LDLEN & RETIRE & NSL7 & ~NSL6)
         | (~LDLEN & RETIRE & ~NSL7 & NSL0 & NSL1 & NSL2 & NSL3 & NSL4 & NSL5 & NSL6)
         | (~LDLEN & ~RETIRE & NSL7);
  end

endmodule
`default_nettype wire
