// GENERATED by hardware/gal/verilog/emit.ts from the term lists in
// hardware/gal/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module vsup (
    input  wire DOTCLK,
    input  wire IOSEL,
    input  wire A5,
    input  wire A6,
    input  wire A0,
    input  wire A1,
    input  wire A2,
    input  wire A3,
    input  wire A4,
    input  wire RW,
    input  wire E,
    input  wire SPANBUSY,
    input  wire MASKBIT,
    input  wire RP0,
    input  wire RP1,
    input  wire WSTBV,
    input  wire RETIRE,
    input  wire RESET,
    input  wire D0,
    input  wire D1,
    input  wire D2,
    input  wire D3,
    input  wire D4,
    input  wire D5,
    input  wire D6,
    input  wire D7,
    input  wire LGRANT,
    input  wire HLOAD,
    output wire WSTB,
    output wire RA0,
    output wire RA1,
    output wire RA2,
    output wire RA3,
    output wire RA4,
    output wire WCTRL,
    output wire VSTATWR,
    output wire LDLEN,
    output wire NSL0,
    output wire NSL1,
    output wire NSL2,
    output wire NSL3,
    output wire NSL4,
    output wire NSL5,
    output wire NSL6,
    output wire NSL7,
    output wire TC,
    output wire HS0,
    output wire HS1,
    output wire OEA0,
    output wire OEA1,
    output wire OEA2,
    output wire OEB0,
    output wire OEB1,
    output wire OEB2,
    output wire LDHS,
    output wire WSPL,
    output wire WPIDX,
    output wire WPDL,
    output wire WPDH,
    output wire SL0,
    output wire SL1,
    output wire SL2,
    output wire SL3,
    output wire SL4,
    output wire SL5,
    output wire SL6,
    output wire SL7,
    output wire BCTRLGO,
    output wire LGO,
    output wire LRUN,
    output wire LSTOP,
    output wire LADV,
    output wire LFETCH,
    output wire LMOVE,
    output wire LPH,
    output wire LREL,
    output wire LWAIT,
    output wire LD0,
    output wire LD1,
    output wire LD2,
    output wire LD3,
    output wire LD4,
    output wire LD7,
    output wire LBYTE,
    output wire LDBOE,
    output wire RFOE,
    output wire LWHSL,
    output wire LWHSH,
    output wire LWPI,
    output wire LWPDL,
    output wire LWPDH,
    output wire PLOAD,
    output wire PDHW,
    output wire PS0,
    output wire PS1,
    output wire PS2,
    output wire PS3,
    output wire LDPDL,
    output wire LDPDH,
    output wire PILD,
    output wire PINC,
    output wire PDOE,
    output wire PIXOE,
    output wire PWE
);

  reg  r_NSL0;
  reg  r_NSL1;
  reg  r_NSL2;
  reg  r_NSL3;
  reg  r_NSL4;
  reg  r_NSL5;
  reg  r_NSL6;
  reg  r_NSL7;
  reg  r_HS0;
  reg  r_HS1;
  reg  r_SL0;
  reg  r_SL1;
  reg  r_SL2;
  reg  r_SL3;
  reg  r_SL4;
  reg  r_SL5;
  reg  r_SL6;
  reg  r_SL7;
  reg  r_LGO;
  reg  r_LRUN;
  reg  r_LPH;
  reg  r_LREL;
  reg  r_LWAIT;
  reg  r_LD0;
  reg  r_LD1;
  reg  r_LD2;
  reg  r_LD3;
  reg  r_LD4;
  reg  r_LD7;
  reg  r_PS0;
  reg  r_PS1;
  reg  r_PS2;
  reg  r_PS3;

  assign NSL0 = r_NSL0;
  assign NSL1 = r_NSL1;
  assign NSL2 = r_NSL2;
  assign NSL3 = r_NSL3;
  assign NSL4 = r_NSL4;
  assign NSL5 = r_NSL5;
  assign NSL6 = r_NSL6;
  assign NSL7 = r_NSL7;
  assign HS0 = r_HS0;
  assign HS1 = r_HS1;
  assign SL0 = r_SL0;
  assign SL1 = r_SL1;
  assign SL2 = r_SL2;
  assign SL3 = r_SL3;
  assign SL4 = r_SL4;
  assign SL5 = r_SL5;
  assign SL6 = r_SL6;
  assign SL7 = r_SL7;
  assign LGO = r_LGO;
  assign LRUN = r_LRUN;
  assign LPH = r_LPH;
  assign LREL = r_LREL;
  assign LWAIT = r_LWAIT;
  assign LD0 = r_LD0;
  assign LD1 = r_LD1;
  assign LD2 = r_LD2;
  assign LD3 = r_LD3;
  assign LD4 = r_LD4;
  assign LD7 = r_LD7;
  assign PS0 = r_PS0;
  assign PS1 = r_PS1;
  assign PS2 = r_PS2;
  assign PS3 = r_PS3;

  // EXTERNAL - E-qualified: a 6809 write is only valid data in the second half
  assign WSTB =
         (IOSEL & A6 & A5 & ~RW & E);
  // EXTERNAL - 7.4: the mask bit IS the register file's address bit 0, inverted
  assign RA0 =
         (IOSEL & A6 & A5 & ~SPANBUSY & A0)
         | (SPANBUSY & ~MASKBIT)
         | (~IOSEL & ~SPANBUSY & ~RP0 & ~RP1)
         | (~A6 & ~SPANBUSY & ~RP0 & ~RP1)
         | (~A5 & ~SPANBUSY & ~RP0 & ~RP1)
         | (~IOSEL & RP1)
         | (~A6 & RP1)
         | (~A5 & RP1);
  // EXTERNAL
  assign RA1 =
         (IOSEL & A6 & A5 & ~SPANBUSY & A1)
         | (SPANBUSY);
  // EXTERNAL
  assign RA2 =
         (IOSEL & A6 & A5 & ~SPANBUSY & A2)
         | (~IOSEL & ~RP0 & ~RP1)
         | (~A6 & ~RP0 & ~RP1)
         | (~A5 & ~RP0 & ~RP1)
         | (SPANBUSY & ~RP0 & ~RP1);
  // EXTERNAL
  assign RA3 =
         (IOSEL & A6 & A5 & ~SPANBUSY & A3)
         | (~IOSEL & RP0)
         | (~A6 & RP0)
         | (~A5 & RP0)
         | (~IOSEL & RP1)
         | (~A6 & RP1)
         | (~A5 & RP1);
  // EXTERNAL
  assign RA4 =
         (IOSEL & A6 & A5 & ~SPANBUSY & A4);
  // EXTERNAL
  assign WCTRL =
         (IOSEL & A6 & A5 & ~RW & E & ~A4 & ~A3 & ~A2 & ~A1 & ~A0);
  // EXTERNAL
  assign VSTATWR =
         (IOSEL & A6 & A5 & ~RW & E & A4 & ~A3 & ~A2 & A1 & A0);
  // buried
  assign LDLEN =
         (WSTBV & ~SPANBUSY);
  // EXTERNAL - SPANLEN = 0 is ~SPANLEN = 255 - one eight-literal term, not eight terms
  assign TC =
         (NSL0 & NSL1 & NSL2 & NSL3 & NSL4 & NSL5 & NSL6 & NSL7);
  // EXTERNAL
  assign OEA0 =
         (HS0)
         | (HS1);
  // EXTERNAL
  assign OEA1 =
         (HS1);
  // EXTERNAL
  assign OEA2 =
         (HS1 & HS0);
  // EXTERNAL
  assign OEB0 =
         (~HS1 & ~HS0);
  // EXTERNAL
  assign OEB1 =
         (~HS1);
  // EXTERNAL
  assign OEB2 =
         (~HS1)
         | (~HS0);
  // buried
  assign LDHS =
         (WSTB & ~RA4 & ~RA3 & ~RA2 & RA1 & RA0);
  // buried - 13's +$05 - and it had no strobe, because SPANLEN was only ever read
  assign WSPL =
         (WSTB & ~RA4 & ~RA3 & RA2 & ~RA1 & RA0);
  // buried - 13's +$10
  assign WPIDX =
         (WSTB & RA4 & ~RA3 & ~RA2 & ~RA1 & ~RA0);
  // buried - 13's +$11
  assign WPDL =
         (WSTB & RA4 & ~RA3 & ~RA2 & ~RA1 & RA0);
  // buried - 13's +$12 - the commit
  assign WPDH =
         (WSTB & RA4 & ~RA3 & ~RA2 & RA1 & ~RA0);
  // buried - 10.3.1's GO - a strobe, because LRUN is what holds
  assign BCTRLGO =
         (WSTB & ~RA4 & RA3 & RA2 & RA1 & ~RA0 & D0);
  // buried - END is any b7 byte with b4..b0 set - canonically $FF
  assign LSTOP =
         (LRUN & LD7 & LD4 & LD3 & LD2 & LD1 & LD0);
  // EXTERNAL - 10.3.2's consumption cycle - out to vaddr, which is where WPTR is
  assign LADV =
         (LRUN & LGRANT & ~LWAIT);
  // buried
  assign LFETCH =
         (LADV & ~LPH);
  // buried
  assign LMOVE =
         (LADV & LPH);
  // buried
  assign LBYTE =
         (LADV & ~WSTB);
  // EXTERNAL - 10.3.3's '244 /OE - the descriptor byte owns the bus
  assign LDBOE =
         (LBYTE);
  // EXTERNAL - the register file drives, except while 10.3.3's buffer does
  assign RFOE =
         (~LADV)
         | (WSTB);
  // EXTERNAL
  assign LWHSL =
         (LMOVE & ~LD4 & ~LD3 & ~LD2 & LD1 & LD0);
  // EXTERNAL
  assign LWHSH =
         (LMOVE & ~LD4 & ~LD3 & LD2 & ~LD1 & ~LD0);
  // buried
  assign LWPI =
         (LMOVE & LD4 & ~LD3 & ~LD2 & ~LD1 & ~LD0);
  // buried
  assign LWPDL =
         (LMOVE & LD4 & ~LD3 & ~LD2 & ~LD1 & LD0);
  // buried
  assign LWPDH =
         (LMOVE & LD4 & ~LD3 & ~LD2 & LD1 & ~LD0);
  // buried - 13's +$10, from either port
  assign PLOAD =
         (WPIDX)
         | (LWPI);
  // buried - 13's +$12, the commit, from either port
  assign PDHW =
         (WPDH)
         | (LWPDH);
  // EXTERNAL - 13's +$11, PDATL's '573 LE
  assign LDPDL =
         (WPDL)
         | (LWPDL);
  // EXTERNAL - 13's +$12, PDATH's '573 LE
  assign LDPDH =
         (PDHW);
  // EXTERNAL - the '163 pair's /LOAD - from the card's internal data bus, no turnaround
  assign PILD =
         (PLOAD);
  // EXTERNAL - 13: PIDX auto-increments after PDATH
  assign PINC =
         (PS3);
  // EXTERNAL - the index '244 drives the LUT's address and the '573 pair its data
  assign PDOE =
         (PS1)
         | (PS2)
         | (PS3);
  // EXTERNAL - the pixel-index '574 drives the LUT's address AND the LUT drives its data
  assign PIXOE =
         (~PDOE);
  // EXTERNAL - the LUT's /WE - one dot, inside PDOE at both ends
  assign PWE =
         (PS2);


  wire AR_ = (RESET);
  always @(posedge DOTCLK or posedge AR_) begin
    if (AR_) begin
      r_NSL0 <= 1'b0;
      r_NSL1 <= 1'b0;
      r_NSL2 <= 1'b0;
      r_NSL3 <= 1'b0;
      r_NSL4 <= 1'b0;
      r_NSL5 <= 1'b0;
      r_NSL6 <= 1'b0;
      r_NSL7 <= 1'b0;
      r_HS0 <= 1'b0;
      r_HS1 <= 1'b0;
      r_SL0 <= 1'b0;
      r_SL1 <= 1'b0;
      r_SL2 <= 1'b0;
      r_SL3 <= 1'b0;
      r_SL4 <= 1'b0;
      r_SL5 <= 1'b0;
      r_SL6 <= 1'b0;
      r_SL7 <= 1'b0;
      r_LGO <= 1'b0;
      r_LRUN <= 1'b0;
      r_LPH <= 1'b0;
      r_LREL <= 1'b0;
      r_LWAIT <= 1'b0;
      r_LD0 <= 1'b0;
      r_LD1 <= 1'b0;
      r_LD2 <= 1'b0;
      r_LD3 <= 1'b0;
      r_LD4 <= 1'b0;
      r_LD7 <= 1'b0;
      r_PS0 <= 1'b0;
      r_PS1 <= 1'b0;
      r_PS2 <= 1'b0;
      r_PS3 <= 1'b0;
    end else begin
      r_NSL0 <=
         (LDLEN & ~SL0)
         | (~LDLEN & RETIRE & ~NSL0)
         | (~LDLEN & ~RETIRE & NSL0);
      r_NSL1 <=
         (LDLEN & ~SL1)
         | (~LDLEN & RETIRE & NSL1 & ~NSL0)
         | (~LDLEN & RETIRE & ~NSL1 & NSL0)
         | (~LDLEN & ~RETIRE & NSL1);
      r_NSL2 <=
         (LDLEN & ~SL2)
         | (~LDLEN & RETIRE & NSL2 & ~NSL0)
         | (~LDLEN & RETIRE & NSL2 & ~NSL1)
         | (~LDLEN & RETIRE & ~NSL2 & NSL0 & NSL1)
         | (~LDLEN & ~RETIRE & NSL2);
      r_NSL3 <=
         (LDLEN & ~SL3)
         | (~LDLEN & RETIRE & NSL3 & ~NSL0)
         | (~LDLEN & RETIRE & NSL3 & ~NSL1)
         | (~LDLEN & RETIRE & NSL3 & ~NSL2)
         | (~LDLEN & RETIRE & ~NSL3 & NSL0 & NSL1 & NSL2)
         | (~LDLEN & ~RETIRE & NSL3);
      r_NSL4 <=
         (LDLEN & ~SL4)
         | (~LDLEN & RETIRE & NSL4 & ~NSL0)
         | (~LDLEN & RETIRE & NSL4 & ~NSL1)
         | (~LDLEN & RETIRE & NSL4 & ~NSL2)
         | (~LDLEN & RETIRE & NSL4 & ~NSL3)
         | (~LDLEN & RETIRE & ~NSL4 & NSL0 & NSL1 & NSL2 & NSL3)
         | (~LDLEN & ~RETIRE & NSL4);
      r_NSL5 <=
         (LDLEN & ~SL5)
         | (~LDLEN & RETIRE & NSL5 & ~NSL0)
         | (~LDLEN & RETIRE & NSL5 & ~NSL1)
         | (~LDLEN & RETIRE & NSL5 & ~NSL2)
         | (~LDLEN & RETIRE & NSL5 & ~NSL3)
         | (~LDLEN & RETIRE & NSL5 & ~NSL4)
         | (~LDLEN & RETIRE & ~NSL5 & NSL0 & NSL1 & NSL2 & NSL3 & NSL4)
         | (~LDLEN & ~RETIRE & NSL5);
      r_NSL6 <=
         (LDLEN & ~SL6)
         | (~LDLEN & RETIRE & NSL6 & ~NSL0)
         | (~LDLEN & RETIRE & NSL6 & ~NSL1)
         | (~LDLEN & RETIRE & NSL6 & ~NSL2)
         | (~LDLEN & RETIRE & NSL6 & ~NSL3)
         | (~LDLEN & RETIRE & NSL6 & ~NSL4)
         | (~LDLEN & RETIRE & NSL6 & ~NSL5)
         | (~LDLEN & RETIRE & ~NSL6 & NSL0 & NSL1 & NSL2 & NSL3 & NSL4 & NSL5)
         | (~LDLEN & ~RETIRE & NSL6);
      r_NSL7 <=
         (LDLEN & ~SL7)
         | (~LDLEN & RETIRE & NSL7 & ~NSL0)
         | (~LDLEN & RETIRE & NSL7 & ~NSL1)
         | (~LDLEN & RETIRE & NSL7 & ~NSL2)
         | (~LDLEN & RETIRE & NSL7 & ~NSL3)
         | (~LDLEN & RETIRE & NSL7 & ~NSL4)
         | (~LDLEN & RETIRE & NSL7 & ~NSL5)
         | (~LDLEN & RETIRE & NSL7 & ~NSL6)
         | (~LDLEN & RETIRE & ~NSL7 & NSL0 & NSL1 & NSL2 & NSL3 & NSL4 & NSL5 & NSL6)
         | (~LDLEN & ~RETIRE & NSL7);
      r_HS0 <=
         (LDHS & D0)
         | (LWHSL & D0)
         | (HS0 & ~LDHS & ~LWHSL);
      r_HS1 <=
         (LDHS & D1)
         | (LWHSL & D1)
         | (HS1 & ~LDHS & ~LWHSL);
      r_SL0 <=
         (WSPL & D0)
         | (SL0 & ~WSPL);
      r_SL1 <=
         (WSPL & D1)
         | (SL1 & ~WSPL);
      r_SL2 <=
         (WSPL & D2)
         | (SL2 & ~WSPL);
      r_SL3 <=
         (WSPL & D3)
         | (SL3 & ~WSPL);
      r_SL4 <=
         (WSPL & D4)
         | (SL4 & ~WSPL);
      r_SL5 <=
         (WSPL & D5)
         | (SL5 & ~WSPL);
      r_SL6 <=
         (WSPL & D6)
         | (SL6 & ~WSPL);
      r_SL7 <=
         (WSPL & D7)
         | (SL7 & ~WSPL);
      r_LGO <=
         (BCTRLGO)
         | (LGO & WSTB);
      r_LRUN <=
         (LGO & ~WSTB)
         | (LRUN & ~LSTOP);
      r_LPH <=
         (LFETCH & ~D7)
         | (LPH & ~LMOVE & ~LGO);
      r_LREL <=
         (~HLOAD)
         | (LREL & ~LADV);
      r_LWAIT <=
         (LFETCH & D7 & ~LSTOP)
         | (LWAIT & ~HLOAD & LRUN & ~LSTOP)
         | (LWAIT & ~LREL & LRUN & ~LSTOP);
      r_LD0 <=
         (LFETCH & D0)
         | (LD0 & ~LFETCH & ~LGO);
      r_LD1 <=
         (LFETCH & D1)
         | (LD1 & ~LFETCH & ~LGO);
      r_LD2 <=
         (LFETCH & D2)
         | (LD2 & ~LFETCH & ~LGO);
      r_LD3 <=
         (LFETCH & D3)
         | (LD3 & ~LFETCH & ~LGO);
      r_LD4 <=
         (LFETCH & D4)
         | (LD4 & ~LFETCH & ~LGO);
      r_LD7 <=
         (LFETCH & D7)
         | (LD7 & ~LFETCH & ~LGO);
      r_PS0 <=
         (PDHW);
      r_PS1 <=
         (PS0 & ~PDHW);
      r_PS2 <=
         (PS1);
      r_PS3 <=
         (PS2);
    end
  end

endmodule
`default_nettype wire
