/* Emit CUPL source from a Design, so the CPLD is compiled from the same term
 * lists the GAL checks exercise.
 *
 * The audio card's logic is verified as six GAL22V10 designs (audio.check.ts,
 * exhaustively where that is cheap). Retyping it as CUPL for the ATF1508AS
 * would make a second source that nothing compares against the first - which is
 * the exact failure mode that put two errors in the fuse map on 2026-09-07.
 * So it is generated instead: one origin, two devices.
 *
 * What this is NOT is a fitter. It emits equations; cupl.exe compiles them and
 * fit1508.exe places and routes them. jedec/README.md explains why that split
 * is where it is.
 */

import type { Cell, Design } from "./assemble"

export interface Merged {
  name: string
  /** the clock every register runs on. A GAL22V10 has one clock on pin 1 and
   *  CUPL infers it; an ATF1508AS has three global clocks and the fitter
   *  refuses a registered node without an explicit .ck. */
  clock?: string
  partNo: string
  location: string
  device: string
  /** signals that leave the part; everything else the fitter may bury */
  external: Set<string>
  inputs: { name: string; activeLow?: boolean }[]
  cells: Cell[]
  ar?: string
}

/** Rewrite a design's signal names. Two of the video card's fits call their
 *  outputs A2..A18 - the scan address and the write pointer - and they are
 *  different nets that collide the moment the parts merge. Renaming has to
 *  reach the term strings as well as the cell names, which is why it lives
 *  here rather than in each design. */
export const rename = (d: Design, map: Record<string, string>): Design => {
  const sub = (text: string) =>
    text.replace(/!?[A-Za-z_][A-Za-z0-9_]*/g, (tok) => {
      const neg = tok.startsWith("!")
      const bare = neg ? tok.slice(1) : tok
      return (neg ? "!" : "") + (map[bare] ?? bare)
    })
  return {
    ...d,
    cells: d.cells.map((c) => ({
      ...c, name: map[c.name] ?? c.name,
      terms: c.terms.map(sub), oe: c.oe ? sub(c.oe) : undefined,
    })),
    inputs: d.inputs.map((i) => ({ ...i, name: map[i.name] ?? i.name })),
    ar: d.ar ? sub(d.ar) : undefined,
  }
}

/** Fold several 22V10 designs into one part. Any signal produced by one and
 *  consumed by another stops being a pin and becomes an internal node - which
 *  is the whole reason for doing it. */
export const merge = (
  designs: Design[], extra: Cell[], meta: Omit<Merged, "inputs" | "cells" | "external">,
): Merged => {
  const cells = [...designs.flatMap((d) => d.cells), ...extra]
  const produced = new Set(cells.map((c) => c.name))
  const inputs = new Map<string, { name: string; activeLow?: boolean }>()
  for (const d of designs) {
    for (const i of d.inputs) {
      if (!produced.has(i.name)) inputs.set(i.name, { name: i.name, activeLow: i.activeLow })
    }
  }
  /* Every literal any equation reads must be produced or supplied. */
  for (const c of cells) {
    for (const t of [...c.terms, c.oe ?? ""].join(" & ").split("&")) {
      const n = t.trim().replace(/^!/, "")
      if (n && /^[A-Za-z_]/.test(n) && !produced.has(n) && !inputs.has(n)) {
        inputs.set(n, { name: n })
      }
    }
  }
  const ar = designs.map((d) => d.ar).find(Boolean)
  return { ...meta, inputs: [...inputs.values()], cells, ar }
}

const banner = (m: Merged) => [
  `Name       ${m.name} ;`,
  `PartNo     ${m.partNo} ;`,
  `Date       generated ;`,
  `Revision   01 ;`,
  `Designer   arm6309 ;`,
  `Company    - ;`,
  `Assembly   ${m.location} ;`,
  `Location   ${m.location} ;`,
  `Device     ${m.device} ;`,
].join("\n")

/* Split a name list so that no emitted line exceeds `width` characters of
 * payload. CUPL counts characters, not names. */
const wrap = (names: string[], width: number): string[][] => {
  const chunks: string[][] = [[]]
  let n = 0
  for (const name of names) {
    if (n > 0 && n + name.length + 1 > width) { chunks.push([]); n = 0 }
    chunks[chunks.length - 1].push(name)
    n += name.length + 1
  }
  return chunks
}

export const toCupl = (m: Merged): string => {
  const out: string[] = [banner(m), ""]
  out.push("/* GENERATED by hardware/gal/jedec/cupl.ts - do not edit.")
  out.push(" *")
  out.push(" * The equations below are the same term lists the card's GAL22V10 checks")
  out.push(" * exercise. Writing them twice would create a second source with nothing")
  out.push(" * checking it against the first, which is how two errors got into the 22V10")
  out.push(" * fuse map. One origin, two devices.")
  out.push(" *")
  out.push(" * Pins are left unassigned: the fitter places them. The card's datapath pinout")
  out.push(" * is not settled, so fixing")
  out.push(" * pins here would be inventing a constraint rather than recording one.")
  out.push(" */")
  out.push("")

  out.push("/* --- inputs ------------------------------------------------------- */")
  /* The clock is only named in a .ck statement, which nothing else scans, so
   * it has to be declared here or CUPL reports it as an intermediate variable
   * with no expression. */
  const named = new Set(m.inputs.map((i) => i.name))
  if (m.clock && !named.has(m.clock)) out.push(`PIN = ${m.clock} ;`)
  for (const i of m.inputs) out.push(`PIN = ${i.activeLow ? "!" : ""}${i.name} ;`)
  out.push("")

  const internal = m.cells.filter((c) => !m.external.has(c.name))
  const external = m.cells.filter((c) => m.external.has(c.name))
  out.push("/* --- outputs ------------------------------------------------------ */")
  for (const c of external) out.push(`PIN = ${c.assertedLow ? "!" : ""}${c.name} ;`)
  out.push("")
  /* Only REGISTERED internal signals need a node. A combinational one is an
   * ordinary CUPL intermediate variable: it is substituted into whatever reads
   * it and costs no macrocell and no pin. Declaring those as PINNODE is what
   * made the fitter count 91 I/Os for a design with 47. */
  const buriedRegs = internal.filter((c) => c.registered)
  const buriedComb = internal.filter((c) => !c.registered)
  out.push("/* --- buried registers: state that used to cross a package boundary - */")
  for (const c of buriedRegs) out.push(`PINNODE = ${c.assertedLow ? "!" : ""}${c.name} ;`)
  out.push("")
  out.push("/* Combinational internals are left undeclared - CUPL substitutes them:")
  out.push(` * ${buriedComb.map((c) => c.name).join(", ")} */`)
  out.push("")

  out.push("/* --- equations ---------------------------------------------------- */")
  for (const c of m.cells) {
    const lhs = `${c.name}${c.registered ? ".d" : ""}`
    /* An EMPTY term list is the open-drain idiom: the cell drives a constant
     * and the condition rides entirely on .oe, so the pin pulls to one rail or
     * floats and never drives the other.
     *
     * THE CONSTANT IS 'b'1 FOR AN ACTIVE-LOW CELL, NOT 'b'0, and getting that
     * backwards is how /WAIT acquired its third defect on 2026-09-08. The pin
     * is declared `PIN n = !WAIT`, so CUPL inverts: writing `WAIT = 'b'0`
     * makes the pin drive HIGH whenever the enable is true - which on a shared
     * open-drain line is not "no wait", it is this card fighting the
     * motherboard's 3.3k pull-up and every other card on the wire.
     *
     * jedec/cupl.check.ts caught it by disagreeing with Atmel's own compiler
     * over exactly one signal, which is the entire reason that file exists. */
    if (c.terms.length === 0) {
      out.push(`${lhs} = 'b'${c.assertedLow ? 1 : 0} ;`)
    } else {
      out.push(`${lhs} = ${c.terms.join("\n${pad}# ".replace("${pad}", " ".repeat(lhs.length + 3)))} ;`)
    }
    if (c.oe) out.push(`${c.name}.oe = ${c.oe} ;`)
  }
  const regs = m.cells.filter((c) => c.registered).map((c) => c.name)
  if (m.clock && regs.length) {
    out.push("")
    out.push("/* One clock for every register: the card is one slot-walked datapath")
    out.push(" * referred to its own oscillator (3.1), so there is only one. */")
    /* CUPL has a maximum source line length and a hundred-register list runs
     * past it - "line exceeds maximum length", after which it writes no .tt2
     * at all. Chunked, and deliberately not by a round number of names: the
     * bound is characters. */
    for (const chunk of wrap(regs, 60)) out.push(`[${chunk.join(",")}].ck = ${m.clock} ;`)
  }
  if (m.ar) {
    out.push("")
    out.push(`/* One asynchronous reset for every register, as on the GALs. */`)
    for (const chunk of wrap(regs, 60)) out.push(`[${chunk.join(",")}].ar = ${m.ar} ;`)
    /* No .sp. A GAL22V10 has a synchronous preset term shared by every
     * macrocell and mmu.pld ties it off explicitly; an ATF1508AS does not have
     * one, and the fitter says so - "Warning - .P extension unknown", once per
     * register, while counting each as another output it has to place. */
  }
  return out.join("\n") + "\n"
}
