/* Emit a GAL22V10 CUPL source from a Design, so that CUPL's minimiser can be
 * asked what it would have done with the same equations.
 *
 * This exists to answer one question: our flow does no real minimisation, no
 * output-polarity selection and no foldback, and the ATF1508 fitter does all
 * three. How much are we leaving on the table? CUPL is the same second
 * implementation that found the two fuse-map errors, used here for cost
 * rather than for correctness.
 */

import type { Design } from "./assemble"

const decl = (name: string, pin: number, low: boolean | undefined) =>
  `PIN ${pin} = ${low ? "!" : ""}${name} ;`

/* When `complement` is set every equation is emitted as !(...) with its pin
 * declared the other way round. The 22V10's S1 bit is an XOR on the way to the
 * output, so the two forms compute the same function at the pin - the array
 * simply holds whichever is cheaper. Nothing in our flow ever picks; this is
 * how to find out what picking would be worth.
 *
 * The complemented file is a COST PROBE AND NOT A DESIGN. References to a
 * flipped signal are left alone, which is wrong as logic and irrelevant as
 * arithmetic: renaming a literal cannot change how many terms an equation
 * needs, and per-equation term count is the only thing being measured. */
export const toGalPld = (d: Design, complement = false): string => {
  const out = [
    `Name       ${d.name} ;`,
    `PartNo     ${d.partNo} ;`,
    `Date       2026-09-07 ;`,
    `Revision   01 ;`,
    `Designer   arm6309 ;`,
    `Company    - ;`,
    `Assembly   - ;`,
    `Location   ${d.location} ;`,
    `Device     g22v10 ;`,
    "",
    "/* GENERATED by hardware/gal/jedec/galpld.ts - a cost probe, not a build",
    " * artefact. See gal/minimise.probe.ts. */",
    "",
  ]
  for (const s of d.inputs) out.push(decl(s.name, s.pin, s.activeLow))
  out.push("")
  for (const c of d.cells) out.push(decl(c.name, c.pin, complement ? !c.assertedLow : c.assertedLow))
  out.push("")
  for (const c of d.cells) {
    const lhs = c.registered ? `${c.name}.d` : c.name
    /* An EMPTY term list is the open-drain idiom, not an oversight: the cell
     * drives a constant and the condition rides entirely on .oe, so the pin
     * pulls to one rail or floats and never drives the other. CUPL will not
     * accept `WAIT = ;` for it - the constant has to be written out.
     *
     * THE CONSTANT IS 'b'1 FOR AN ACTIVE-LOW CELL, NOT 'b'0, and getting that
     * backwards is how /WAIT acquired its third defect on 2026-09-08. The pin
     * is declared `PIN n = !WAIT`, so CUPL inverts: writing `WAIT = 'b'0`
     * makes the pin drive HIGH whenever the enable is true - which on a shared
     * open-drain line is not "no wait", it is this card fighting the
     * motherboard's 3.3k pull-up and every other card on the wire.
     *
     * jedec/cupl.check.ts caught it by disagreeing with Atmel's own compiler
     * over exactly one signal, which is the entire reason that file exists.
     * This emitter went years without meeting the idiom because the only
     * design using it was merged into a CPLD. It came back out on 2026-09-08. */
    const sop = c.terms.length
      ? c.terms.join("\n" + " ".repeat(lhs.length + 5) + "# ")
      : `'b'${c.assertedLow ? 1 : 0}`
    out.push(complement || !c.terms.length ? `${lhs} = ${complement && c.terms.length ? `!( ${sop} )` : sop} ;`
                                           : `${lhs} = ${sop} ;`)
    if (c.oe) out.push(`${c.name}.oe = ${c.oe} ;`)
  }
  const regs = d.cells.filter((c) => c.registered).map((c) => c.name)
  if (regs.length) {
    out.push("")
    out.push(`[${regs.join(",")}].ar = ${d.ar ?? "'b'0"} ;`)
    out.push(`[${regs.join(",")}].sp = ${d.sp ?? "'b'0"} ;`)
  }
  return out.join("\n") + "\n"
}
