// GENERATED by hardware/tools/sim/emit.ts from the term lists in
// hardware/<card>/logic/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module sdeng (
    input  wire CLK,
    input  wire RESET,
    input  wire CTRLW,
    input  wire DATSTB,
    input  wire DIV2,
    input  wire DIV64,
    input  wire CNT8,
    input  wire D0,
    input  wire D1,
    input  wire D7,
    output wire CS,
    output wire FAST,
    output wire SPICLK,
    output wire SPQ,
    output wire DATQ,
    output wire TRIGP,
    output wire BUSY,
    output wire SCK,
    output wire SCKN,
    output wire RCLK
);

  reg  r_CS;
  reg  r_FAST;
  reg  r_SPQ;
  reg  r_DATQ;
  reg  r_TRIGP;
  reg  r_BUSY;

  assign CS = r_CS;
  assign FAST = r_FAST;
  assign SPQ = r_SPQ;
  assign DATQ = r_DATQ;
  assign TRIGP = r_TRIGP;
  assign BUSY = r_BUSY;

  // EXTERNAL
  assign SPICLK =
         (FAST & DIV2)
         | (~FAST & DIV64);
  // EXTERNAL
  assign SCK =
         (SPICLK & BUSY);
  // EXTERNAL
  assign SCKN =
         (SPICLK & BUSY);
  // EXTERNAL
  assign RCLK =
         (BUSY);


  wire AR_ = (RESET);
  always @(posedge CLK or posedge AR_) begin
    if (AR_) begin
      r_CS <= 1'b0;
      r_FAST <= 1'b0;
      r_SPQ <= 1'b0;
      r_DATQ <= 1'b0;
      r_TRIGP <= 1'b0;
      r_BUSY <= 1'b0;
    end else begin
      r_CS <=
         (CTRLW & D0)
         | (~CTRLW & CS);
      r_FAST <=
         (CTRLW & D1)
         | (~CTRLW & FAST);
      r_SPQ <=
         (SPICLK);
      r_DATQ <=
         (DATSTB);
      r_TRIGP <=
         (~DATSTB & DATQ)
         | (TRIGP & ~BUSY);
      r_BUSY <=
         (TRIGP & ~BUSY & ~SPICLK & SPQ & ~CTRLW)
         | (TRIGP & ~BUSY & ~SPICLK & SPQ & ~D7)
         | (BUSY & ~CNT8 & ~CTRLW)
         | (BUSY & ~CNT8 & ~D7)
         | (BUSY & SPICLK & ~CTRLW)
         | (BUSY & SPICLK & ~D7)
         | (BUSY & ~SPQ & ~CTRLW)
         | (BUSY & ~SPQ & ~D7);
    end
  end

endmodule
`default_nettype wire
