// GENERATED by hardware/tools/sim/emit.ts from the term lists in
// hardware/<card>/logic/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module v3dot (
    input  wire CLK25,
    input  wire RESET,
    input  wire D0,
    input  wire D1,
    input  wire D2,
    input  wire D3,
    input  wire D4,
    input  wire D5,
    input  wire D6,
    input  wire D7,
    input  wire REGWR,
    input  wire RA0,
    input  wire RA1,
    input  wire RA2,
    input  wire RA3,
    input  wire RA4,
    input  wire RDREQ,
    input  wire RCPY,
    input  wire SPANBUSY,
    input  wire PALTURN,
    input  wire SQ0,
    input  wire SQ1,
    output wire LDCTRL,
    output wire LDHSL,
    output wire LDSPRX,
    output wire LDSPRY,
    output wire LDSPRH,
    output wire LDPIDXL,
    output wire LDPIDXH,
    output wire LDPDATL,
    output wire LDPDATH,
    output wire DP0,
    output wire DP1,
    output wire HC0,
    output wire HC1,
    output wire HC2,
    output wire HC3,
    output wire HC4,
    output wire HC5,
    output wire HC6,
    output wire HC7,
    output wire VC0,
    output wire VC1,
    output wire VC2,
    output wire VC3,
    output wire VC4,
    output wire VC5,
    output wire VC6,
    output wire VC7,
    output wire VC8,
    output wire VC9,
    output wire M0,
    output wire CT0,
    output wire CT1,
    output wire CT2,
    output wire CT3,
    output wire CT4,
    output wire CT5,
    output wire CT7,
    output wire HS0,
    output wire HS1,
    output wire HS2,
    output wire SX0,
    output wire SX1,
    output wire SX2,
    output wire SX3,
    output wire SX4,
    output wire SX5,
    output wire SX6,
    output wire SX7,
    output wire SX8,
    output wire SX9,
    output wire SY0,
    output wire SY1,
    output wire SY2,
    output wire SY3,
    output wire SY4,
    output wire SY5,
    output wire SY6,
    output wire SY7,
    output wire SY8,
    output wire SPREN,
    output wire SHC0,
    output wire SHC1,
    output wire SHC2,
    output wire SHC3,
    output wire SHC4,
    output wire SHC5,
    output wire SHC6,
    output wire SHC7,
    output wire SHC8,
    output wire SHC9,
    output wire SVC0,
    output wire SVC1,
    output wire SVC2,
    output wire SVC3,
    output wire SVC4,
    output wire SVC5,
    output wire SVC6,
    output wire SVC7,
    output wire SVC8,
    output wire SHQ,
    output wire SVQ,
    output wire SR0,
    output wire SR1,
    output wire SR2,
    output wire SR3,
    output wire SR4,
    output wire SPRA0,
    output wire SPRA1,
    output wire SLOTTICK,
    output wire HBLANK,
    output wire HSYNC,
    output wire VSYNC,
    output wire VBLANK,
    output wire BLANK,
    output wire FRAMEEND,
    output wire LINETICK,
    output wire SPARE,
    output wire HLOAD,
    output wire VLOAD,
    output wire ROWADV,
    output wire DBLHOLD,
    output wire MWIN,
    output wire MRQ,
    output wire MAPREQ,
    output wire MUXSEL0,
    output wire MUXSEL1,
    output wire PIXOE,
    output wire ATOE,
    output wire PIDXOE,
    output wire SPRAOE,
    output wire BD1,
    output wire OMR,
    output wire OEA0,
    output wire OEB0,
    output wire OEA1,
    output wire OEB1,
    output wire OEA2,
    output wire OEB2,
    output wire SPRACT,
    output wire SPRSH,
    output wire SPRLD,
    output wire FBA2,
    output wire FBA3,
    output wire FBA4,
    output wire FBA5,
    output wire GMAP,
    output wire GRD,
    output wire GCPY,
    output wire GSPN,
    output wire FBOEPTR,
    output wire HLAST,
    output wire ACTIVE,
    output wire VACTIVE,
    output wire VBLANKRAW,
    output wire VTC,
    output wire SPRVHIT,
    output wire SPRHIT,
    output wire SPRROW,
    output wire VMODE0,
    output wire MODE0,
    output wire MODE1,
    output wire WM0,
    output wire WM1,
    output wire SPRA0_OE,
    output wire SPRA1_OE,
    output wire FBA2_OE,
    output wire FBA3_OE,
    output wire FBA4_OE,
    output wire FBA5_OE
);

  reg  r_DP0;
  reg  r_DP1;
  reg  r_HC0;
  reg  r_HC1;
  reg  r_HC2;
  reg  r_HC3;
  reg  r_HC4;
  reg  r_HC5;
  reg  r_HC6;
  reg  r_HC7;
  reg  r_VC0;
  reg  r_VC1;
  reg  r_VC2;
  reg  r_VC3;
  reg  r_VC4;
  reg  r_VC5;
  reg  r_VC6;
  reg  r_VC7;
  reg  r_VC8;
  reg  r_VC9;
  reg  r_M0;
  reg  r_CT0;
  reg  r_CT1;
  reg  r_CT2;
  reg  r_CT3;
  reg  r_CT4;
  reg  r_CT5;
  reg  r_CT7;
  reg  r_HS0;
  reg  r_HS1;
  reg  r_HS2;
  reg  r_SX0;
  reg  r_SX1;
  reg  r_SX2;
  reg  r_SX3;
  reg  r_SX4;
  reg  r_SX5;
  reg  r_SX6;
  reg  r_SX7;
  reg  r_SX8;
  reg  r_SX9;
  reg  r_SY0;
  reg  r_SY1;
  reg  r_SY2;
  reg  r_SY3;
  reg  r_SY4;
  reg  r_SY5;
  reg  r_SY6;
  reg  r_SY7;
  reg  r_SY8;
  reg  r_SPREN;
  reg  r_SHC0;
  reg  r_SHC1;
  reg  r_SHC2;
  reg  r_SHC3;
  reg  r_SHC4;
  reg  r_SHC5;
  reg  r_SHC6;
  reg  r_SHC7;
  reg  r_SHC8;
  reg  r_SHC9;
  reg  r_SVC0;
  reg  r_SVC1;
  reg  r_SVC2;
  reg  r_SVC3;
  reg  r_SVC4;
  reg  r_SVC5;
  reg  r_SVC6;
  reg  r_SVC7;
  reg  r_SVC8;
  reg  r_SHQ;
  reg  r_SVQ;
  reg  r_SR0;
  reg  r_SR1;
  reg  r_SR2;
  reg  r_SR3;
  reg  r_SR4;
  reg  r_SPRA0;
  reg  r_SPRA1;
  reg  r_DBLHOLD;
  reg  r_MWIN;
  reg  r_MRQ;
  reg  r_BD1;
  reg  r_OMR;
  reg  r_ACTIVE;

  assign DP0 = r_DP0;
  assign DP1 = r_DP1;
  assign HC0 = r_HC0;
  assign HC1 = r_HC1;
  assign HC2 = r_HC2;
  assign HC3 = r_HC3;
  assign HC4 = r_HC4;
  assign HC5 = r_HC5;
  assign HC6 = r_HC6;
  assign HC7 = r_HC7;
  assign VC0 = r_VC0;
  assign VC1 = r_VC1;
  assign VC2 = r_VC2;
  assign VC3 = r_VC3;
  assign VC4 = r_VC4;
  assign VC5 = r_VC5;
  assign VC6 = r_VC6;
  assign VC7 = r_VC7;
  assign VC8 = r_VC8;
  assign VC9 = r_VC9;
  assign M0 = r_M0;
  assign CT0 = r_CT0;
  assign CT1 = r_CT1;
  assign CT2 = r_CT2;
  assign CT3 = r_CT3;
  assign CT4 = r_CT4;
  assign CT5 = r_CT5;
  assign CT7 = r_CT7;
  assign HS0 = r_HS0;
  assign HS1 = r_HS1;
  assign HS2 = r_HS2;
  assign SX0 = r_SX0;
  assign SX1 = r_SX1;
  assign SX2 = r_SX2;
  assign SX3 = r_SX3;
  assign SX4 = r_SX4;
  assign SX5 = r_SX5;
  assign SX6 = r_SX6;
  assign SX7 = r_SX7;
  assign SX8 = r_SX8;
  assign SX9 = r_SX9;
  assign SY0 = r_SY0;
  assign SY1 = r_SY1;
  assign SY2 = r_SY2;
  assign SY3 = r_SY3;
  assign SY4 = r_SY4;
  assign SY5 = r_SY5;
  assign SY6 = r_SY6;
  assign SY7 = r_SY7;
  assign SY8 = r_SY8;
  assign SPREN = r_SPREN;
  assign SHC0 = r_SHC0;
  assign SHC1 = r_SHC1;
  assign SHC2 = r_SHC2;
  assign SHC3 = r_SHC3;
  assign SHC4 = r_SHC4;
  assign SHC5 = r_SHC5;
  assign SHC6 = r_SHC6;
  assign SHC7 = r_SHC7;
  assign SHC8 = r_SHC8;
  assign SHC9 = r_SHC9;
  assign SVC0 = r_SVC0;
  assign SVC1 = r_SVC1;
  assign SVC2 = r_SVC2;
  assign SVC3 = r_SVC3;
  assign SVC4 = r_SVC4;
  assign SVC5 = r_SVC5;
  assign SVC6 = r_SVC6;
  assign SVC7 = r_SVC7;
  assign SVC8 = r_SVC8;
  assign SHQ = r_SHQ;
  assign SVQ = r_SVQ;
  assign SR0 = r_SR0;
  assign SR1 = r_SR1;
  assign SR2 = r_SR2;
  assign SR3 = r_SR3;
  assign SR4 = r_SR4;
  assign SPRA0 = r_SPRA0;
  assign SPRA1 = r_SPRA1;
  assign DBLHOLD = r_DBLHOLD;
  assign MWIN = r_MWIN;
  assign MRQ = r_MRQ;
  assign BD1 = r_BD1;
  assign OMR = r_OMR;
  assign ACTIVE = r_ACTIVE;

  // buried
  assign LDCTRL =
         (REGWR & ~RA4 & ~RA3 & ~RA2 & ~RA1 & ~RA0);
  // buried
  assign LDHSL =
         (REGWR & ~RA4 & ~RA3 & ~RA2 & RA1 & RA0);
  // buried
  assign LDSPRX =
         (REGWR & RA4 & RA3 & ~RA2 & RA1 & ~RA0);
  // buried
  assign LDSPRY =
         (REGWR & RA4 & RA3 & ~RA2 & RA1 & RA0);
  // buried
  assign LDSPRH =
         (REGWR & RA4 & RA3 & RA2 & ~RA1 & ~RA0);
  // EXTERNAL
  assign LDPIDXL =
         (REGWR & ~RA4 & RA3 & RA2 & RA1 & ~RA0);
  // EXTERNAL
  assign LDPIDXH =
         (REGWR & ~RA4 & RA3 & RA2 & RA1 & RA0);
  // EXTERNAL
  assign LDPDATL =
         (REGWR & RA4 & ~RA3 & ~RA2 & ~RA1 & ~RA0);
  // EXTERNAL
  assign LDPDATH =
         (REGWR & RA4 & ~RA3 & ~RA2 & ~RA1 & RA0);
  // buried
  assign SLOTTICK =
         (DP1 & DP0);
  // EXTERNAL
  assign HBLANK =
         (~ACTIVE);
  // EXTERNAL
  assign HSYNC =
         (~HC7 & ~HC6 & ~HC5 & ~HC4)
         | (~HC7 & ~HC6 & ~HC5 & ~HC3);
  // EXTERNAL
  assign VSYNC =
         (~VC9 & ~VC8 & ~VC7 & ~VC6 & ~VC5 & ~VC4 & ~VC3 & ~VC2 & ~VC1);
  // EXTERNAL
  assign VBLANK =
         (VBLANKRAW);
  // EXTERNAL
  assign BLANK =
         (HBLANK)
         | (VBLANK)
         | (~CT7);
  // buried
  assign FRAMEEND =
         (SLOTTICK & HLAST & VTC);
  // buried
  assign LINETICK =
         (SLOTTICK & HLAST);
  // EXTERNAL
  assign SPARE =
         (~DP1);
  // EXTERNAL
  assign HLOAD =
         (~HC7 & ~HC6 & HC5 & ~HC4 & ~HC3 & ~HC2 & ~HC1)
         | (~HC7 & ~HC6 & ~HC5 & HC4 & HC3 & HC2 & HC1);
  // buried
  assign VLOAD =
         (VBLANK);
  // EXTERNAL
  assign ROWADV =
         (LINETICK & VACTIVE & ~DBLHOLD);
  // buried
  assign MAPREQ =
         (MRQ);
  // EXTERNAL
  assign MUXSEL0 =
         (DP0 & ~HS0)
         | (~DP0 & HS0 & ~MODE0)
         | (DP0 & MODE0);
  // EXTERNAL
  assign MUXSEL1 =
         (DP1 & ~HS1 & ~HS0)
         | (~DP1 & HS1 & ~HS0 & ~MODE0)
         | (DP1 & ~DP0 & ~HS1)
         | (~DP1 & DP0 & ~HS1 & HS0 & ~MODE0)
         | (~DP1 & ~DP0 & HS1 & ~MODE0)
         | (DP1 & DP0 & HS1 & HS0)
         | (DP1 & MODE0);
  // EXTERNAL
  assign PIXOE =
         (~PALTURN);
  // EXTERNAL
  assign ATOE =
         (~PALTURN & MODE0);
  // EXTERNAL
  assign PIDXOE =
         (PALTURN);
  // buried
  assign SPRAOE =
         (~PALTURN & ~MODE0);
  // EXTERNAL
  assign OEA0 =
         (HS1 & ~MODE0)
         | (HS0 & ~MODE0);
  // EXTERNAL
  assign OEB0 =
         (~HS1 & ~HS0)
         | (MODE0);
  // EXTERNAL
  assign OEA1 =
         (HS1 & ~MODE0);
  // EXTERNAL
  assign OEB1 =
         (~HS1)
         | (MODE0);
  // EXTERNAL
  assign OEA2 =
         (HS1 & HS0 & ~MODE0);
  // EXTERNAL
  assign OEB2 =
         (~HS0)
         | (~HS1)
         | (MODE0);
  // buried
  assign SPRACT =
         (SPREN & ~MODE1 & ~MODE0 & SPRROW & SPRHIT & ACTIVE);
  // EXTERNAL
  assign SPRSH =
         (SPRACT);
  // EXTERNAL
  assign SPRLD =
         (MRQ & ~DP1 & DP0 & ~MODE0 & ~MODE1);
  // EXTERNAL
  assign FBA2 =
         (SR0);
  // EXTERNAL
  assign FBA3 =
         (SR1);
  // EXTERNAL
  assign FBA4 =
         (SR2);
  // EXTERNAL
  assign FBA5 =
         (SR3);
  // buried
  assign GMAP =
         (SPARE & MAPREQ);
  // EXTERNAL
  assign GRD =
         (SPARE & ~MAPREQ & RDREQ);
  // EXTERNAL
  assign GCPY =
         (SPARE & ~MAPREQ & ~RDREQ & RCPY);
  // EXTERNAL
  assign GSPN =
         (SPARE & ~MAPREQ & ~RDREQ & ~RCPY & SPANBUSY);
  // EXTERNAL
  assign FBOEPTR =
         (GRD)
         | (GCPY)
         | (GSPN);
  // buried
  assign HLAST =
         (HC7 & HC6 & HC2 & HC1 & HC0);
  // buried
  assign VACTIVE =
         (~VBLANKRAW);
  // buried
  assign VBLANKRAW =
         (~VC9 & ~VC8 & ~VC7 & ~VC6 & ~VC5)
         | (VC9 & M0)
         | (VC8 & VC7 & VC6 & ~M0)
         | (VC8 & VC7 & VC5 & VC4 & ~M0);
  // buried
  assign VTC =
         (VC8 & VC7 & VC6 & ~M0)
         | (VC9 & VC3 & VC2 & M0);
  // buried
  assign SPRVHIT =
         (SVC0 & SVC1 & SVC2 & SVC3 & SVC4 & SVC5 & SVC6 & SVC7 & SVC8)
         | (SVQ);
  // buried
  assign SPRHIT =
         (SHC0 & SHC1 & SHC2 & SHC3 & SHC4 & SHC5 & SHC6 & SHC7 & SHC8 & SHC9)
         | (SHQ);
  // buried
  assign SPRROW =
         (SPRVHIT & ~SR4);
  // buried
  assign VMODE0 =
         (CT0);
  // EXTERNAL
  assign MODE0 =
         (CT2);
  // EXTERNAL
  assign MODE1 =
         (CT3);
  // EXTERNAL
  assign WM0 =
         (CT4);
  // EXTERNAL
  assign WM1 =
         (CT5);

  // SPRA0 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SPRA0_OE =
         (SPRAOE);
  // SPRA1 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign SPRA1_OE =
         (SPRAOE);
  // FBA2 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA2_OE =
         (MRQ & ~DP1 & ~MODE0 & ~MODE1);
  // FBA3 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA3_OE =
         (MRQ & ~DP1 & ~MODE0 & ~MODE1);
  // FBA4 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA4_OE =
         (MRQ & ~DP1 & ~MODE0 & ~MODE1);
  // FBA5 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign FBA5_OE =
         (MRQ & ~DP1 & ~MODE0 & ~MODE1);

  always @(posedge CLK25) begin
      r_DP0 <=
         (~DP0);
      r_DP1 <=
         (DP1 & ~DP0)
         | (~DP1 & DP0);
      r_HC0 <=
         (SLOTTICK & ~HC0)
         | (~SLOTTICK & HC0);
      r_HC1 <=
         (SLOTTICK & ~HC0 & HC1)
         | (SLOTTICK & ~HC1 & HC0)
         | (~SLOTTICK & HC1);
      r_HC2 <=
         (SLOTTICK & ~HC0 & HC2)
         | (SLOTTICK & ~HC1 & HC2)
         | (SLOTTICK & ~HC2 & HC0 & HC1)
         | (~SLOTTICK & HC2);
      r_HC3 <=
         (SLOTTICK & ~HC0 & HC3)
         | (SLOTTICK & ~HC1 & HC3)
         | (SLOTTICK & ~HC2 & HC3)
         | (SLOTTICK & ~HC7 & ~HC3 & HC0 & HC1 & HC2)
         | (SLOTTICK & ~HC6 & ~HC3 & HC0 & HC1 & HC2)
         | (~SLOTTICK & HC3);
      r_HC4 <=
         (SLOTTICK & ~HC0 & HC4)
         | (SLOTTICK & ~HC1 & HC4)
         | (SLOTTICK & ~HC2 & HC4)
         | (SLOTTICK & ~HC7 & HC4 & ~HC3)
         | (SLOTTICK & ~HC6 & HC4 & ~HC3)
         | (SLOTTICK & ~HC7 & ~HC4 & HC0 & HC1 & HC2 & HC3)
         | (SLOTTICK & ~HC6 & ~HC4 & HC0 & HC1 & HC2 & HC3)
         | (~SLOTTICK & HC4);
      r_HC5 <=
         (SLOTTICK & ~HC0 & HC5)
         | (SLOTTICK & ~HC1 & HC5)
         | (SLOTTICK & ~HC2 & HC5)
         | (SLOTTICK & ~HC7 & HC5 & ~HC3)
         | (SLOTTICK & ~HC6 & HC5 & ~HC3)
         | (SLOTTICK & ~HC7 & HC5 & ~HC4)
         | (SLOTTICK & ~HC6 & HC5 & ~HC4)
         | (SLOTTICK & ~HC7 & ~HC5 & HC0 & HC1 & HC2 & HC3 & HC4)
         | (SLOTTICK & ~HC6 & ~HC5 & HC0 & HC1 & HC2 & HC3 & HC4)
         | (~SLOTTICK & HC5);
      r_HC6 <=
         (SLOTTICK & ~HC0 & HC6)
         | (SLOTTICK & ~HC1 & HC6)
         | (SLOTTICK & ~HC2 & HC6)
         | (SLOTTICK & ~HC7 & HC6 & ~HC3)
         | (SLOTTICK & ~HC7 & HC6 & ~HC4)
         | (SLOTTICK & ~HC7 & HC6 & ~HC5)
         | (SLOTTICK & ~HC6 & HC0 & HC1 & HC2 & HC3 & HC4 & HC5)
         | (~SLOTTICK & HC6);
      r_HC7 <=
         (SLOTTICK & ~HC0 & HC7)
         | (SLOTTICK & ~HC1 & HC7)
         | (SLOTTICK & ~HC2 & HC7)
         | (SLOTTICK & ~HC6 & HC7)
         | (SLOTTICK & ~HC7 & HC0 & HC1 & HC2 & HC3 & HC4 & HC5 & HC6)
         | (~SLOTTICK & HC7);
      r_VC0 <=
         (LINETICK & ~VTC & ~VC0)
         | (~LINETICK & VC0);
      r_VC1 <=
         (LINETICK & ~VTC & VC1 & ~VC0)
         | (LINETICK & ~VTC & ~VC1 & VC0)
         | (~LINETICK & VC1);
      r_VC2 <=
         (LINETICK & ~VTC & VC2 & ~VC0)
         | (LINETICK & ~VTC & VC2 & ~VC1)
         | (LINETICK & ~VTC & ~VC2 & VC0 & VC1)
         | (~LINETICK & VC2);
      r_VC3 <=
         (LINETICK & ~VTC & VC3 & ~VC0)
         | (LINETICK & ~VTC & VC3 & ~VC1)
         | (LINETICK & ~VTC & VC3 & ~VC2)
         | (LINETICK & ~VTC & ~VC3 & VC0 & VC1 & VC2)
         | (~LINETICK & VC3);
      r_VC4 <=
         (LINETICK & ~VTC & VC4 & ~VC0)
         | (LINETICK & ~VTC & VC4 & ~VC1)
         | (LINETICK & ~VTC & VC4 & ~VC2)
         | (LINETICK & ~VTC & VC4 & ~VC3)
         | (LINETICK & ~VTC & ~VC4 & VC0 & VC1 & VC2 & VC3)
         | (~LINETICK & VC4);
      r_VC5 <=
         (LINETICK & ~VTC & VC5 & ~VC0)
         | (LINETICK & ~VTC & VC5 & ~VC1)
         | (LINETICK & ~VTC & VC5 & ~VC2)
         | (LINETICK & ~VTC & VC5 & ~VC3)
         | (LINETICK & ~VTC & VC5 & ~VC4)
         | (LINETICK & ~VTC & ~VC5 & VC0 & VC1 & VC2 & VC3 & VC4)
         | (~LINETICK & VC5);
      r_VC6 <=
         (LINETICK & ~VTC & VC6 & ~VC0)
         | (LINETICK & ~VTC & VC6 & ~VC1)
         | (LINETICK & ~VTC & VC6 & ~VC2)
         | (LINETICK & ~VTC & VC6 & ~VC3)
         | (LINETICK & ~VTC & VC6 & ~VC4)
         | (LINETICK & ~VTC & VC6 & ~VC5)
         | (LINETICK & ~VTC & ~VC6 & VC0 & VC1 & VC2 & VC3 & VC4 & VC5)
         | (~LINETICK & VC6);
      r_VC7 <=
         (LINETICK & ~VTC & VC7 & ~VC0)
         | (LINETICK & ~VTC & VC7 & ~VC1)
         | (LINETICK & ~VTC & VC7 & ~VC2)
         | (LINETICK & ~VTC & VC7 & ~VC3)
         | (LINETICK & ~VTC & VC7 & ~VC4)
         | (LINETICK & ~VTC & VC7 & ~VC5)
         | (LINETICK & ~VTC & VC7 & ~VC6)
         | (LINETICK & ~VTC & ~VC7 & VC0 & VC1 & VC2 & VC3 & VC4 & VC5 & VC6)
         | (~LINETICK & VC7);
      r_VC8 <=
         (LINETICK & ~VTC & VC8 & ~VC0)
         | (LINETICK & ~VTC & VC8 & ~VC1)
         | (LINETICK & ~VTC & VC8 & ~VC2)
         | (LINETICK & ~VTC & VC8 & ~VC3)
         | (LINETICK & ~VTC & VC8 & ~VC4)
         | (LINETICK & ~VTC & VC8 & ~VC5)
         | (LINETICK & ~VTC & VC8 & ~VC6)
         | (LINETICK & ~VTC & VC8 & ~VC7)
         | (LINETICK & ~VTC & ~VC8 & VC0 & VC1 & VC2 & VC3 & VC4 & VC5 & VC6 & VC7)
         | (~LINETICK & VC8);
      r_VC9 <=
         (LINETICK & ~VTC & VC9 & ~VC0)
         | (LINETICK & ~VTC & VC9 & ~VC1)
         | (LINETICK & ~VTC & VC9 & ~VC2)
         | (LINETICK & ~VTC & VC9 & ~VC3)
         | (LINETICK & ~VTC & VC9 & ~VC4)
         | (LINETICK & ~VTC & VC9 & ~VC5)
         | (LINETICK & ~VTC & VC9 & ~VC6)
         | (LINETICK & ~VTC & VC9 & ~VC7)
         | (LINETICK & ~VTC & VC9 & ~VC8)
         | (LINETICK & ~VTC & ~VC9 & VC0 & VC1 & VC2 & VC3 & VC4 & VC5 & VC6 & VC7 & VC8)
         | (~LINETICK & VC9);
      r_M0 <=
         (FRAMEEND & VMODE0)
         | (M0 & ~FRAMEEND);
      r_CT0 <=
         (LDCTRL & D0)
         | (CT0 & ~LDCTRL);
      r_CT1 <=
         (LDCTRL & D1)
         | (CT1 & ~LDCTRL);
      r_CT2 <=
         (LDCTRL & D2)
         | (CT2 & ~LDCTRL);
      r_CT3 <=
         (LDCTRL & D3)
         | (CT3 & ~LDCTRL);
      r_CT4 <=
         (LDCTRL & D4)
         | (CT4 & ~LDCTRL);
      r_CT5 <=
         (LDCTRL & D5)
         | (CT5 & ~LDCTRL);
      r_CT7 <=
         (LDCTRL & D7)
         | (CT7 & ~LDCTRL);
      r_HS0 <=
         (LDHSL & D0)
         | (HS0 & ~LDHSL);
      r_HS1 <=
         (LDHSL & D1)
         | (HS1 & ~LDHSL);
      r_HS2 <=
         (LDHSL & D2)
         | (HS2 & ~LDHSL);
      r_SX0 <=
         (LDSPRX & D0)
         | (SX0 & ~LDSPRX);
      r_SX1 <=
         (LDSPRX & D1)
         | (SX1 & ~LDSPRX);
      r_SX2 <=
         (LDSPRX & D2)
         | (SX2 & ~LDSPRX);
      r_SX3 <=
         (LDSPRX & D3)
         | (SX3 & ~LDSPRX);
      r_SX4 <=
         (LDSPRX & D4)
         | (SX4 & ~LDSPRX);
      r_SX5 <=
         (LDSPRX & D5)
         | (SX5 & ~LDSPRX);
      r_SX6 <=
         (LDSPRX & D6)
         | (SX6 & ~LDSPRX);
      r_SX7 <=
         (LDSPRX & D7)
         | (SX7 & ~LDSPRX);
      r_SX8 <=
         (LDSPRH & D0)
         | (SX8 & ~LDSPRH);
      r_SX9 <=
         (LDSPRH & D1)
         | (SX9 & ~LDSPRH);
      r_SY0 <=
         (LDSPRY & D0)
         | (SY0 & ~LDSPRY);
      r_SY1 <=
         (LDSPRY & D1)
         | (SY1 & ~LDSPRY);
      r_SY2 <=
         (LDSPRY & D2)
         | (SY2 & ~LDSPRY);
      r_SY3 <=
         (LDSPRY & D3)
         | (SY3 & ~LDSPRY);
      r_SY4 <=
         (LDSPRY & D4)
         | (SY4 & ~LDSPRY);
      r_SY5 <=
         (LDSPRY & D5)
         | (SY5 & ~LDSPRY);
      r_SY6 <=
         (LDSPRY & D6)
         | (SY6 & ~LDSPRY);
      r_SY7 <=
         (LDSPRY & D7)
         | (SY7 & ~LDSPRY);
      r_SY8 <=
         (LDSPRH & D2)
         | (SY8 & ~LDSPRH);
      r_SPREN <=
         (LDSPRH & D7)
         | (SPREN & ~LDSPRH);
      r_SHC0 <=
         (HLOAD & ~SX0)
         | (~HLOAD & ACTIVE & ~SHC0)
         | (~HLOAD & ~ACTIVE & SHC0);
      r_SHC1 <=
         (HLOAD & ~SX1)
         | (~HLOAD & ACTIVE & SHC1 & ~SHC0)
         | (~HLOAD & ACTIVE & ~SHC1 & SHC0)
         | (~HLOAD & ~ACTIVE & SHC1);
      r_SHC2 <=
         (HLOAD & ~SX2)
         | (~HLOAD & ACTIVE & SHC2 & ~SHC0)
         | (~HLOAD & ACTIVE & SHC2 & ~SHC1)
         | (~HLOAD & ACTIVE & ~SHC2 & SHC0 & SHC1)
         | (~HLOAD & ~ACTIVE & SHC2);
      r_SHC3 <=
         (HLOAD & ~SX3)
         | (~HLOAD & ACTIVE & SHC3 & ~SHC0)
         | (~HLOAD & ACTIVE & SHC3 & ~SHC1)
         | (~HLOAD & ACTIVE & SHC3 & ~SHC2)
         | (~HLOAD & ACTIVE & ~SHC3 & SHC0 & SHC1 & SHC2)
         | (~HLOAD & ~ACTIVE & SHC3);
      r_SHC4 <=
         (HLOAD & ~SX4)
         | (~HLOAD & ACTIVE & SHC4 & ~SHC0)
         | (~HLOAD & ACTIVE & SHC4 & ~SHC1)
         | (~HLOAD & ACTIVE & SHC4 & ~SHC2)
         | (~HLOAD & ACTIVE & SHC4 & ~SHC3)
         | (~HLOAD & ACTIVE & ~SHC4 & SHC0 & SHC1 & SHC2 & SHC3)
         | (~HLOAD & ~ACTIVE & SHC4);
      r_SHC5 <=
         (HLOAD & ~SX5)
         | (~HLOAD & ACTIVE & SHC5 & ~SHC0)
         | (~HLOAD & ACTIVE & SHC5 & ~SHC1)
         | (~HLOAD & ACTIVE & SHC5 & ~SHC2)
         | (~HLOAD & ACTIVE & SHC5 & ~SHC3)
         | (~HLOAD & ACTIVE & SHC5 & ~SHC4)
         | (~HLOAD & ACTIVE & ~SHC5 & SHC0 & SHC1 & SHC2 & SHC3 & SHC4)
         | (~HLOAD & ~ACTIVE & SHC5);
      r_SHC6 <=
         (HLOAD & ~SX6)
         | (~HLOAD & ACTIVE & SHC6 & ~SHC0)
         | (~HLOAD & ACTIVE & SHC6 & ~SHC1)
         | (~HLOAD & ACTIVE & SHC6 & ~SHC2)
         | (~HLOAD & ACTIVE & SHC6 & ~SHC3)
         | (~HLOAD & ACTIVE & SHC6 & ~SHC4)
         | (~HLOAD & ACTIVE & SHC6 & ~SHC5)
         | (~HLOAD & ACTIVE & ~SHC6 & SHC0 & SHC1 & SHC2 & SHC3 & SHC4 & SHC5)
         | (~HLOAD & ~ACTIVE & SHC6);
      r_SHC7 <=
         (HLOAD & ~SX7)
         | (~HLOAD & ACTIVE & SHC7 & ~SHC0)
         | (~HLOAD & ACTIVE & SHC7 & ~SHC1)
         | (~HLOAD & ACTIVE & SHC7 & ~SHC2)
         | (~HLOAD & ACTIVE & SHC7 & ~SHC3)
         | (~HLOAD & ACTIVE & SHC7 & ~SHC4)
         | (~HLOAD & ACTIVE & SHC7 & ~SHC5)
         | (~HLOAD & ACTIVE & SHC7 & ~SHC6)
         | (~HLOAD & ACTIVE & ~SHC7 & SHC0 & SHC1 & SHC2 & SHC3 & SHC4 & SHC5 & SHC6)
         | (~HLOAD & ~ACTIVE & SHC7);
      r_SHC8 <=
         (HLOAD & ~SX8)
         | (~HLOAD & ACTIVE & SHC8 & ~SHC0)
         | (~HLOAD & ACTIVE & SHC8 & ~SHC1)
         | (~HLOAD & ACTIVE & SHC8 & ~SHC2)
         | (~HLOAD & ACTIVE & SHC8 & ~SHC3)
         | (~HLOAD & ACTIVE & SHC8 & ~SHC4)
         | (~HLOAD & ACTIVE & SHC8 & ~SHC5)
         | (~HLOAD & ACTIVE & SHC8 & ~SHC6)
         | (~HLOAD & ACTIVE & SHC8 & ~SHC7)
         | (~HLOAD & ACTIVE & ~SHC8 & SHC0 & SHC1 & SHC2 & SHC3 & SHC4 & SHC5 & SHC6 & SHC7)
         | (~HLOAD & ~ACTIVE & SHC8);
      r_SHC9 <=
         (HLOAD & ~SX9)
         | (~HLOAD & ACTIVE & SHC9 & ~SHC0)
         | (~HLOAD & ACTIVE & SHC9 & ~SHC1)
         | (~HLOAD & ACTIVE & SHC9 & ~SHC2)
         | (~HLOAD & ACTIVE & SHC9 & ~SHC3)
         | (~HLOAD & ACTIVE & SHC9 & ~SHC4)
         | (~HLOAD & ACTIVE & SHC9 & ~SHC5)
         | (~HLOAD & ACTIVE & SHC9 & ~SHC6)
         | (~HLOAD & ACTIVE & SHC9 & ~SHC7)
         | (~HLOAD & ACTIVE & SHC9 & ~SHC8)
         | (~HLOAD & ACTIVE & ~SHC9 & SHC0 & SHC1 & SHC2 & SHC3 & SHC4 & SHC5 & SHC6 & SHC7 & SHC8)
         | (~HLOAD & ~ACTIVE & SHC9);
      r_SVC0 <=
         (VLOAD & ~SY0)
         | (~VLOAD & ROWADV & ~SVC0)
         | (~VLOAD & ~ROWADV & SVC0);
      r_SVC1 <=
         (VLOAD & ~SY1)
         | (~VLOAD & ROWADV & SVC1 & ~SVC0)
         | (~VLOAD & ROWADV & ~SVC1 & SVC0)
         | (~VLOAD & ~ROWADV & SVC1);
      r_SVC2 <=
         (VLOAD & ~SY2)
         | (~VLOAD & ROWADV & SVC2 & ~SVC0)
         | (~VLOAD & ROWADV & SVC2 & ~SVC1)
         | (~VLOAD & ROWADV & ~SVC2 & SVC0 & SVC1)
         | (~VLOAD & ~ROWADV & SVC2);
      r_SVC3 <=
         (VLOAD & ~SY3)
         | (~VLOAD & ROWADV & SVC3 & ~SVC0)
         | (~VLOAD & ROWADV & SVC3 & ~SVC1)
         | (~VLOAD & ROWADV & SVC3 & ~SVC2)
         | (~VLOAD & ROWADV & ~SVC3 & SVC0 & SVC1 & SVC2)
         | (~VLOAD & ~ROWADV & SVC3);
      r_SVC4 <=
         (VLOAD & ~SY4)
         | (~VLOAD & ROWADV & SVC4 & ~SVC0)
         | (~VLOAD & ROWADV & SVC4 & ~SVC1)
         | (~VLOAD & ROWADV & SVC4 & ~SVC2)
         | (~VLOAD & ROWADV & SVC4 & ~SVC3)
         | (~VLOAD & ROWADV & ~SVC4 & SVC0 & SVC1 & SVC2 & SVC3)
         | (~VLOAD & ~ROWADV & SVC4);
      r_SVC5 <=
         (VLOAD & ~SY5)
         | (~VLOAD & ROWADV & SVC5 & ~SVC0)
         | (~VLOAD & ROWADV & SVC5 & ~SVC1)
         | (~VLOAD & ROWADV & SVC5 & ~SVC2)
         | (~VLOAD & ROWADV & SVC5 & ~SVC3)
         | (~VLOAD & ROWADV & SVC5 & ~SVC4)
         | (~VLOAD & ROWADV & ~SVC5 & SVC0 & SVC1 & SVC2 & SVC3 & SVC4)
         | (~VLOAD & ~ROWADV & SVC5);
      r_SVC6 <=
         (VLOAD & ~SY6)
         | (~VLOAD & ROWADV & SVC6 & ~SVC0)
         | (~VLOAD & ROWADV & SVC6 & ~SVC1)
         | (~VLOAD & ROWADV & SVC6 & ~SVC2)
         | (~VLOAD & ROWADV & SVC6 & ~SVC3)
         | (~VLOAD & ROWADV & SVC6 & ~SVC4)
         | (~VLOAD & ROWADV & SVC6 & ~SVC5)
         | (~VLOAD & ROWADV & ~SVC6 & SVC0 & SVC1 & SVC2 & SVC3 & SVC4 & SVC5)
         | (~VLOAD & ~ROWADV & SVC6);
      r_SVC7 <=
         (VLOAD & ~SY7)
         | (~VLOAD & ROWADV & SVC7 & ~SVC0)
         | (~VLOAD & ROWADV & SVC7 & ~SVC1)
         | (~VLOAD & ROWADV & SVC7 & ~SVC2)
         | (~VLOAD & ROWADV & SVC7 & ~SVC3)
         | (~VLOAD & ROWADV & SVC7 & ~SVC4)
         | (~VLOAD & ROWADV & SVC7 & ~SVC5)
         | (~VLOAD & ROWADV & SVC7 & ~SVC6)
         | (~VLOAD & ROWADV & ~SVC7 & SVC0 & SVC1 & SVC2 & SVC3 & SVC4 & SVC5 & SVC6)
         | (~VLOAD & ~ROWADV & SVC7);
      r_SVC8 <=
         (VLOAD & ~SY8)
         | (~VLOAD & ROWADV & SVC8 & ~SVC0)
         | (~VLOAD & ROWADV & SVC8 & ~SVC1)
         | (~VLOAD & ROWADV & SVC8 & ~SVC2)
         | (~VLOAD & ROWADV & SVC8 & ~SVC3)
         | (~VLOAD & ROWADV & SVC8 & ~SVC4)
         | (~VLOAD & ROWADV & SVC8 & ~SVC5)
         | (~VLOAD & ROWADV & SVC8 & ~SVC6)
         | (~VLOAD & ROWADV & SVC8 & ~SVC7)
         | (~VLOAD & ROWADV & ~SVC8 & SVC0 & SVC1 & SVC2 & SVC3 & SVC4 & SVC5 & SVC6 & SVC7)
         | (~VLOAD & ~ROWADV & SVC8);
      r_SHQ <=
         (SHQ & ACTIVE)
         | (SHC0 & SHC1 & SHC2 & SHC3 & SHC4 & SHC5 & SHC6 & SHC7 & SHC8 & SHC9 & ACTIVE);
      r_SVQ <=
         (SVQ & ~VLOAD)
         | (SVC0 & SVC1 & SVC2 & SVC3 & SVC4 & SVC5 & SVC6 & SVC7 & SVC8 & ROWADV);
      r_SR0 <=
         (~VLOAD & ROWADV & SPRROW & ~SR0)
         | (~VLOAD & ~ROWADV & SR0)
         | (~VLOAD & ~SPRROW & SR0);
      r_SR1 <=
         (~VLOAD & ROWADV & SPRROW & SR1 & ~SR0)
         | (~VLOAD & ROWADV & SPRROW & ~SR1 & SR0)
         | (~VLOAD & ~ROWADV & SR1)
         | (~VLOAD & ~SPRROW & SR1);
      r_SR2 <=
         (~VLOAD & ROWADV & SPRROW & SR2 & ~SR0)
         | (~VLOAD & ROWADV & SPRROW & SR2 & ~SR1)
         | (~VLOAD & ROWADV & SPRROW & ~SR2 & SR0 & SR1)
         | (~VLOAD & ~ROWADV & SR2)
         | (~VLOAD & ~SPRROW & SR2);
      r_SR3 <=
         (~VLOAD & ROWADV & SPRROW & SR3 & ~SR0)
         | (~VLOAD & ROWADV & SPRROW & SR3 & ~SR1)
         | (~VLOAD & ROWADV & SPRROW & SR3 & ~SR2)
         | (~VLOAD & ROWADV & SPRROW & ~SR3 & SR0 & SR1 & SR2)
         | (~VLOAD & ~ROWADV & SR3)
         | (~VLOAD & ~SPRROW & SR3);
      r_SR4 <=
         (~VLOAD & ROWADV & SPRROW & SR4 & ~SR0)
         | (~VLOAD & ROWADV & SPRROW & SR4 & ~SR1)
         | (~VLOAD & ROWADV & SPRROW & SR4 & ~SR2)
         | (~VLOAD & ROWADV & SPRROW & SR4 & ~SR3)
         | (~VLOAD & ROWADV & SPRROW & ~SR4 & SR0 & SR1 & SR2 & SR3)
         | (~VLOAD & ~ROWADV & SR4)
         | (~VLOAD & ~SPRROW & SR4);
      r_SPRA0 <=
         (SQ0 & SPRACT);
      r_SPRA1 <=
         (SQ1 & SPRACT);
      r_DBLHOLD <=
         (VBLANK & ~CT1)
         | (LINETICK & ~DBLHOLD & ~CT1)
         | (DBLHOLD & ~LINETICK);
      r_MWIN <=
         (SLOTTICK & ~HC7 & ~HC6 & ~HC5 & HC4 & HC3 & HC2 & ~HC1 & HC0)
         | (MWIN & ~DP1)
         | (MWIN & ~DP0)
         | (MWIN & ~HC7)
         | (MWIN & ~HC6)
         | (MWIN & ~HC0);
      r_MRQ <=
         (SLOTTICK & MWIN & MODE0 & HC0)
         | (SLOTTICK & MWIN & MODE1 & HC0 & ~HS2)
         | (SLOTTICK & MWIN & MODE1 & ~HC0 & HS2)
         | (SLOTTICK & SPREN & ~MODE0 & ~MODE1 & SPRROW & ~HC7 & ~HC6 & ~HC5 & ~HC4 & ~HC3 & HC2 & HC1 & HC0)
         | (MRQ & ~DP1)
         | (MRQ & ~DP0);
      r_BD1 <=
         (BLANK);
      r_OMR <=
         (~BD1);
      r_ACTIVE <=
         (SLOTTICK & ~HC7 & ~HC6 & HC5 & ~HC4 & ~HC3 & ~HC2 & HC1 & HC0)
         | (ACTIVE & ~SLOTTICK)
         | (ACTIVE & ~HC7)
         | (ACTIVE & ~HC6)
         | (ACTIVE & ~HC1)
         | (ACTIVE & ~HC0);
  end

endmodule
`default_nettype wire
