// GENERATED by hardware/tools/sim/emit.ts from the term lists in
// hardware/<card>/logic/*.jedec.ts and video.parts.ts. Do not edit.
//
// Every cell is a port, buried ones included, so a testbench can watch the
// counters. The ones that really leave the package are marked EXTERNAL.
`default_nettype none

module v3walk (
    input  wire CLK25,
    input  wire RESET,
    input  wire SREGWR,
    input  wire SRA0,
    input  wire SRA1,
    input  wire SRA2,
    input  wire SRA3,
    input  wire SRA4,
    input  wire D0,
    input  wire D1,
    input  wire D2,
    input  wire D3,
    input  wire D4,
    input  wire D5,
    input  wire D6,
    input  wire D7,
    input  wire CBUSY,
    input  wire RP1,
    input  wire RP2,
    input  wire RP3,
    input  wire RP4,
    input  wire VBLANK,
    input  wire E,
    output wire LDSWDAT,
    output wire LDSWCMD,
    output wire CMDLD,
    output wire CMD0,
    output wire CMD1,
    output wire CMD2,
    output wire CMD3,
    output wire CMD4,
    output wire CMD5,
    output wire CMD6,
    output wire SELQ,
    output wire GOQ,
    output wire DATQ,
    output wire SELE,
    output wire ARM,
    output wire PEND,
    output wire RDY,
    output wire EQ,
    output wire START,
    output wire PT0,
    output wire PT1,
    output wire PT2,
    output wire PY0,
    output wire PY1,
    output wire PS0,
    output wire PS1,
    output wire PS2,
    output wire PS3,
    output wire LDIRQACK,
    output wire LDCTRL,
    output wire VBLQ,
    output wire IRQPEND,
    output wire IRQEN,
    output wire IRQN,
    output wire WALK,
    output wire NUL,
    output wire WNEXT,
    output wire STEPQ,
    output wire ENDQ,
    output wire W,
    output wire J0,
    output wire J1,
    output wire J2,
    output wire J3,
    output wire J4,
    output wire J5,
    output wire G0,
    output wire G1,
    output wire G2,
    output wire PASSR,
    output wire KD,
    output wire RF,
    output wire RDQ,
    output wire WS0,
    output wire WS1,
    output wire WS2,
    output wire WS3,
    output wire L0,
    output wire L1,
    output wire L2,
    output wire L3,
    output wire L4,
    output wire L5,
    output wire L6,
    output wire L7,
    output wire B0,
    output wire B1,
    output wire B2,
    output wire B3,
    output wire B4,
    output wire B5,
    output wire B6,
    output wire B7,
    output wire REGWR,
    output wire RA0,
    output wire RA1,
    output wire RA2,
    output wire RA3,
    output wire RA4,
    output wire WSTB,
    output wire CPURF,
    output wire RFA1,
    output wire RFA2,
    output wire RFA3,
    output wire RFA4,
    output wire RFA5,
    output wire RFA6,
    output wire RFA7,
    output wire RFA8,
    output wire RFA9,
    output wire RFA10,
    output wire RFA11,
    output wire RFA12,
    output wire RFA13,
    output wire WD0,
    output wire WD1,
    output wire WD2,
    output wire WD3,
    output wire WD4,
    output wire WD5,
    output wire WD6,
    output wire WD7,
    output wire WKEY,
    output wire IRQN_OE,
    output wire REGWR_OE,
    output wire RA0_OE,
    output wire RA1_OE,
    output wire RA2_OE,
    output wire RA3_OE,
    output wire RA4_OE,
    output wire WSTB_OE,
    output wire CPURF_OE,
    output wire RFA1_OE,
    output wire RFA2_OE,
    output wire RFA3_OE,
    output wire RFA4_OE,
    output wire WD0_OE,
    output wire WD1_OE,
    output wire WD2_OE,
    output wire WD3_OE,
    output wire WD4_OE,
    output wire WD5_OE,
    output wire WD6_OE,
    output wire WD7_OE
);

  reg  r_CMD0;
  reg  r_CMD1;
  reg  r_CMD2;
  reg  r_CMD3;
  reg  r_CMD4;
  reg  r_CMD5;
  reg  r_CMD6;
  reg  r_SELQ;
  reg  r_GOQ;
  reg  r_DATQ;
  reg  r_ARM;
  reg  r_PEND;
  reg  r_RDY;
  reg  r_EQ;
  reg  r_PT0;
  reg  r_PT1;
  reg  r_PT2;
  reg  r_PY0;
  reg  r_PY1;
  reg  r_PS0;
  reg  r_PS1;
  reg  r_PS2;
  reg  r_PS3;
  reg  r_VBLQ;
  reg  r_IRQPEND;
  reg  r_IRQEN;
  reg  r_WALK;
  reg  r_STEPQ;
  reg  r_ENDQ;
  reg  r_W;
  reg  r_J0;
  reg  r_J1;
  reg  r_J2;
  reg  r_J3;
  reg  r_J4;
  reg  r_J5;
  reg  r_G0;
  reg  r_G1;
  reg  r_G2;
  reg  r_PASSR;
  reg  r_KD;
  reg  r_RF;
  reg  r_RDQ;
  reg  r_WS0;
  reg  r_WS1;
  reg  r_WS2;
  reg  r_WS3;
  reg  r_L0;
  reg  r_L1;
  reg  r_L2;
  reg  r_L3;
  reg  r_L4;
  reg  r_L5;
  reg  r_L6;
  reg  r_L7;
  reg  r_B0;
  reg  r_B1;
  reg  r_B2;
  reg  r_B3;
  reg  r_B4;
  reg  r_B5;
  reg  r_B6;
  reg  r_B7;

  assign CMD0 = r_CMD0;
  assign CMD1 = r_CMD1;
  assign CMD2 = r_CMD2;
  assign CMD3 = r_CMD3;
  assign CMD4 = r_CMD4;
  assign CMD5 = r_CMD5;
  assign CMD6 = r_CMD6;
  assign SELQ = r_SELQ;
  assign GOQ = r_GOQ;
  assign DATQ = r_DATQ;
  assign ARM = r_ARM;
  assign PEND = r_PEND;
  assign RDY = r_RDY;
  assign EQ = r_EQ;
  assign PT0 = r_PT0;
  assign PT1 = r_PT1;
  assign PT2 = r_PT2;
  assign PY0 = r_PY0;
  assign PY1 = r_PY1;
  assign PS0 = r_PS0;
  assign PS1 = r_PS1;
  assign PS2 = r_PS2;
  assign PS3 = r_PS3;
  assign VBLQ = r_VBLQ;
  assign IRQPEND = r_IRQPEND;
  assign IRQEN = r_IRQEN;
  assign WALK = r_WALK;
  assign STEPQ = r_STEPQ;
  assign ENDQ = r_ENDQ;
  assign W = r_W;
  assign J0 = r_J0;
  assign J1 = r_J1;
  assign J2 = r_J2;
  assign J3 = r_J3;
  assign J4 = r_J4;
  assign J5 = r_J5;
  assign G0 = r_G0;
  assign G1 = r_G1;
  assign G2 = r_G2;
  assign PASSR = r_PASSR;
  assign KD = r_KD;
  assign RF = r_RF;
  assign RDQ = r_RDQ;
  assign WS0 = r_WS0;
  assign WS1 = r_WS1;
  assign WS2 = r_WS2;
  assign WS3 = r_WS3;
  assign L0 = r_L0;
  assign L1 = r_L1;
  assign L2 = r_L2;
  assign L3 = r_L3;
  assign L4 = r_L4;
  assign L5 = r_L5;
  assign L6 = r_L6;
  assign L7 = r_L7;
  assign B0 = r_B0;
  assign B1 = r_B1;
  assign B2 = r_B2;
  assign B3 = r_B3;
  assign B4 = r_B4;
  assign B5 = r_B5;
  assign B6 = r_B6;
  assign B7 = r_B7;

  // buried
  assign LDSWDAT =
         (SREGWR & SRA4 & SRA3 & SRA2 & ~SRA1 & SRA0 & ~WALK);
  // buried
  assign LDSWCMD =
         (SREGWR & SRA4 & SRA3 & SRA2 & SRA1 & ~SRA0 & ~WALK);
  // buried
  assign CMDLD =
         (SREGWR & ~WALK & ~PEND);
  // buried
  assign SELE =
         (SELQ & ~SREGWR);
  // buried
  assign START =
         (GOQ & ~SREGWR & ~ARM)
         | (RDY & EQ & ~E);
  // buried
  assign LDIRQACK =
         (SREGWR & ~SRA4 & SRA3 & SRA2 & ~SRA1 & SRA0);
  // buried
  assign LDCTRL =
         (SREGWR & ~SRA4 & ~SRA3 & ~SRA2 & ~SRA1 & ~SRA0);
  // EXTERNAL
  assign IRQN =
         1'b0;
  // buried
  assign NUL =
         (WALK & J1 & RF & B3 & B4 & B5 & B6 & B7);
  // buried
  assign WNEXT =
         (W & J2 & ~CBUSY & ~RP1 & ~RP2 & ~RP3 & ~RP4)
         | (NUL);
  // EXTERNAL
  assign REGWR =
         (WALK & ~W & ~RDQ);
  // EXTERNAL
  assign RA0 =
         (~G2 & J3 & ~RF)
         | (~G2 & J2 & RF)
         | (G2 & J1)
         | (G2 & J5);
  // EXTERNAL
  assign RA1 =
         (G0 & ~RF & J5)
         | (G0 & RF & J3)
         | (G1 & ~RF & ~J5)
         | (G1 & RF & ~J3)
         | (G2 & ~J1);
  // EXTERNAL
  assign RA2 =
         (G1 & ~RF & J5)
         | (G1 & RF & J3)
         | (G2);
  // EXTERNAL
  assign RA3 =
         (G0);
  // EXTERNAL
  assign RA4 =
         (G1)
         | (G2);
  // EXTERNAL
  assign WSTB =
         (WALK & ~W & ~RDQ);
  // EXTERNAL
  assign CPURF =
         (WALK & ~W & ~RDQ);
  // EXTERNAL
  assign RFA1 =
         (~RDQ & G0 & ~RF & J5)
         | (~RDQ & G0 & RF & J3)
         | (~RDQ & G1 & ~RF & ~J5)
         | (~RDQ & G1 & RF & ~J3)
         | (~RDQ & G2 & ~J1);
  // EXTERNAL
  assign RFA2 =
         (RDQ)
         | (G1 & ~RF & J5)
         | (G1 & RF & J3)
         | (G2);
  // EXTERNAL
  assign RFA3 =
         (RDQ)
         | (G0);
  // EXTERNAL
  assign RFA4 =
         (RDQ)
         | (G1)
         | (G2);
  // EXTERNAL
  assign RFA5 =
         (LDSWDAT & PY0)
         | (RDQ & J2 & ~RF)
         | (RDQ & J1 & RF);
  // EXTERNAL
  assign RFA6 =
         (LDSWDAT & PY1)
         | (RDQ & J4 & ~RF)
         | (RDQ & J0 & RF);
  // EXTERNAL
  assign RFA7 =
         (LDSWDAT & PS0)
         | (RDQ & KD & G1 & B3)
         | (RDQ & ~G1 & WS0)
         | (RDQ & ~KD & WS0);
  // EXTERNAL
  assign RFA8 =
         (LDSWDAT & PS1)
         | (RDQ & KD & G1 & B4)
         | (RDQ & ~G1 & WS1)
         | (RDQ & ~KD & WS1);
  // EXTERNAL
  assign RFA9 =
         (LDSWDAT & PS2)
         | (RDQ & KD & G1 & B5)
         | (RDQ & ~G1 & WS2)
         | (RDQ & ~KD & WS2);
  // EXTERNAL
  assign RFA10 =
         (LDSWDAT & PS3)
         | (RDQ & KD & G1 & B6)
         | (RDQ & ~G1 & WS3)
         | (RDQ & ~KD & WS3);
  // EXTERNAL
  assign RFA11 =
         (LDSWDAT & PT0)
         | (RDQ & RF & PASSR & CMD6)
         | (RDQ & RF & ~PASSR & ~CMD6)
         | (RDQ & G2)
         | (RDQ & KD & G1 & ~B7);
  // EXTERNAL
  assign RFA12 =
         (LDSWDAT & PT1)
         | (RDQ & RF & PASSR & ~CMD6)
         | (RDQ & RF & ~PASSR & CMD6)
         | (RDQ & G2)
         | (RDQ & KD & G1 & B7);
  // EXTERNAL
  assign RFA13 =
         (LDSWDAT & PT2)
         | (RDQ & ~RF & G0)
         | (RDQ & ~RF & G1);
  // EXTERNAL
  assign WD0 =
         (J1 & L0)
         | (J5 & L0)
         | (J3 & ~RF & L0)
         | (J3 & RF & L6)
         | (J2 & B1)
         | (G2 & J5);
  // EXTERNAL
  assign WD1 =
         (J1 & L1)
         | (J5 & L1)
         | (J3 & ~RF & L1)
         | (J3 & RF & L7)
         | (J2 & B2);
  // EXTERNAL
  assign WD2 =
         (J1 & L2)
         | (J5 & L2)
         | (J3 & ~RF & L2)
         | (J3 & RF & B0)
         | (J2 & L0);
  // EXTERNAL
  assign WD3 =
         (J1 & L3)
         | (J5 & L3)
         | (J3 & ~RF & L3)
         | (J2 & L1);
  // EXTERNAL
  assign WD4 =
         (J1 & L4)
         | (J5 & L4)
         | (J3 & ~RF & L4)
         | (J2 & L2);
  // EXTERNAL
  assign WD5 =
         (J1 & L5)
         | (J5 & L5)
         | (J3 & ~RF & L5)
         | (J2 & L3);
  // EXTERNAL
  assign WD6 =
         (J1 & L6)
         | (J5 & L6)
         | (J3 & ~RF & L6)
         | (J2 & L4);
  // EXTERNAL
  assign WD7 =
         (J1 & L7)
         | (J5 & L7)
         | (J3 & ~RF & L7)
         | (J2 & L5);
  // EXTERNAL
  assign WKEY =
         (WALK & KD);

  // IRQN is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign IRQN_OE =
         (IRQPEND & IRQEN);
  // REGWR is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign REGWR_OE =
         (WALK);
  // RA0 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign RA0_OE =
         (WALK);
  // RA1 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign RA1_OE =
         (WALK);
  // RA2 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign RA2_OE =
         (WALK);
  // RA3 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign RA3_OE =
         (WALK);
  // RA4 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign RA4_OE =
         (WALK);
  // WSTB is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign WSTB_OE =
         (WALK);
  // CPURF is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign CPURF_OE =
         (WALK);
  // RFA1 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign RFA1_OE =
         (WALK & ~RP1 & ~RP2 & ~RP3 & ~RP4);
  // RFA2 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign RFA2_OE =
         (WALK & ~RP1 & ~RP2 & ~RP3 & ~RP4);
  // RFA3 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign RFA3_OE =
         (WALK & ~RP1 & ~RP2 & ~RP3 & ~RP4);
  // RFA4 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign RFA4_OE =
         (WALK & ~RP1 & ~RP2 & ~RP3 & ~RP4);
  // WD0 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign WD0_OE =
         (WALK & ~W & ~RDQ);
  // WD1 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign WD1_OE =
         (WALK & ~W & ~RDQ);
  // WD2 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign WD2_OE =
         (WALK & ~W & ~RDQ);
  // WD3 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign WD3_OE =
         (WALK & ~W & ~RDQ);
  // WD4 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign WD4_OE =
         (WALK & ~W & ~RDQ);
  // WD5 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign WD5_OE =
         (WALK & ~W & ~RDQ);
  // WD6 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign WD6_OE =
         (WALK & ~W & ~RDQ);
  // WD7 is open drain: the data is a constant and the
  // condition rides on the output enable (graphics.md 12.1).
  assign WD7_OE =
         (WALK & ~W & ~RDQ);

  always @(posedge CLK25) begin
      r_CMD0 <=
         (CMDLD & D0)
         | (~CMDLD & WALK & STEPQ & ~PASSR & KD & ~CMD0)
         | (~CMDLD & ~KD & CMD0)
         | (~CMDLD & ~STEPQ & CMD0)
         | (~CMDLD & ~WALK & CMD0)
         | (~CMDLD & PASSR & CMD0);
      r_CMD1 <=
         (CMDLD & D1)
         | (~CMDLD & WALK & STEPQ & ~PASSR & KD & ~CMD0 & ~CMD1)
         | (~CMDLD & ~KD & CMD1)
         | (~CMDLD & ~STEPQ & CMD1)
         | (~CMDLD & ~WALK & CMD1)
         | (~CMDLD & PASSR & CMD1)
         | (~CMDLD & CMD0 & CMD1);
      r_CMD2 <=
         (CMDLD & D2)
         | (~CMDLD & WALK & STEPQ & ~PASSR & KD & ~CMD0 & ~CMD1 & ~CMD2)
         | (~CMDLD & ~KD & CMD2)
         | (~CMDLD & ~STEPQ & CMD2)
         | (~CMDLD & ~WALK & CMD2)
         | (~CMDLD & PASSR & CMD2)
         | (~CMDLD & CMD0 & CMD2)
         | (~CMDLD & CMD1 & CMD2);
      r_CMD3 <=
         (CMDLD & D3)
         | (~CMDLD & WALK & STEPQ & ~PASSR & KD & ~CMD0 & ~CMD1 & ~CMD2 & ~CMD3)
         | (~CMDLD & ~KD & CMD3)
         | (~CMDLD & ~STEPQ & CMD3)
         | (~CMDLD & ~WALK & CMD3)
         | (~CMDLD & PASSR & CMD3)
         | (~CMDLD & CMD0 & CMD3)
         | (~CMDLD & CMD1 & CMD3)
         | (~CMDLD & CMD2 & CMD3);
      r_CMD4 <=
         (CMDLD & D4)
         | (~CMDLD & CMD4);
      r_CMD5 <=
         (CMDLD & D5)
         | (~CMDLD & CMD5);
      r_CMD6 <=
         (CMDLD & D6)
         | (~CMDLD & CMD6);
      r_SELQ <=
         (LDSWCMD & D7);
      r_GOQ <=
         (LDSWCMD & ~D7);
      r_DATQ <=
         (LDSWDAT);
      r_ARM <=
         (SELE & CMD0 & CMD1 & CMD2 & ~RESET)
         | (ARM & ~GOQ & ~RESET)
         | (ARM & SREGWR & ~RESET);
      r_PEND <=
         (GOQ & ~SREGWR & ARM & ~RESET)
         | (PEND & ~RDY & ~RESET)
         | (PEND & E & ~RESET)
         | (PEND & ~EQ & ~RESET);
      r_RDY <=
         (PEND & VBLANK & ~VBLQ & ~RESET)
         | (RDY & PEND & ~RESET);
      r_EQ <=
         (E);
      r_PT0 <=
         (SELE & CMD0)
         | (PT0 & ~SELQ)
         | (PT0 & SREGWR);
      r_PT1 <=
         (SELE & CMD1)
         | (PT1 & ~SELQ)
         | (PT1 & SREGWR);
      r_PT2 <=
         (SELE & CMD2)
         | (PT2 & ~SELQ)
         | (PT2 & SREGWR);
      r_PY0 <=
         (~SELQ & DATQ & ~SREGWR & ~PY0 & ~PY1)
         | (~SELQ & ~DATQ & PY0)
         | (SREGWR & PY0);
      r_PY1 <=
         (~SELQ & DATQ & ~SREGWR & PY0 & ~PY1)
         | (~SELQ & ~DATQ & PY1)
         | (SREGWR & PY1);
      r_PS0 <=
         (SELQ & ~SREGWR & CMD3)
         | (~SELQ & DATQ & ~SREGWR & PY1 & ~PS0)
         | (~SELQ & ~PY1 & PS0)
         | (SREGWR & PS0)
         | (~SELQ & ~DATQ & PS0);
      r_PS1 <=
         (SELQ & ~SREGWR & CMD4)
         | (~SELQ & DATQ & ~SREGWR & PY1 & PS0 & ~PS1)
         | (SREGWR & PS1)
         | (~SELQ & ~PS0 & PS1)
         | (~SELQ & ~PY1 & PS1)
         | (~SELQ & ~DATQ & PS1);
      r_PS2 <=
         (SELQ & ~SREGWR & CMD5)
         | (~SELQ & DATQ & ~SREGWR & PY1 & PS0 & PS1 & ~PS2)
         | (SREGWR & PS2)
         | (~SELQ & ~PS1 & PS2)
         | (~SELQ & ~PS0 & PS2)
         | (~SELQ & ~PY1 & PS2)
         | (~SELQ & ~DATQ & PS2);
      r_PS3 <=
         (SELQ & ~SREGWR & CMD6)
         | (~SELQ & DATQ & ~SREGWR & PY1 & PS0 & PS1 & PS2 & ~PS3)
         | (SREGWR & PS3)
         | (~SELQ & ~PS2 & PS3)
         | (~SELQ & ~PS1 & PS3)
         | (~SELQ & ~PS0 & PS3)
         | (~SELQ & ~PY1 & PS3)
         | (~SELQ & ~DATQ & PS3);
      r_VBLQ <=
         (VBLANK);
      r_IRQPEND <=
         (VBLANK & ~VBLQ)
         | (IRQPEND & ~LDIRQACK);
      r_IRQEN <=
         (LDCTRL & D6)
         | (IRQEN & ~LDCTRL);
      r_WALK <=
         (START & ~RESET)
         | (WALK & ~ENDQ & ~RESET);
      r_STEPQ <=
         (WNEXT);
      r_ENDQ <=
         (WNEXT & PASSR & ~WS0 & ~WS1 & ~WS2 & ~WS3 & CMD5)
         | (WNEXT & ~PASSR & KD & ~CMD0 & ~CMD1 & ~CMD2 & ~CMD3);
      r_W <=
         (G2 & J5)
         | (W & ~STEPQ)
         | (NUL);
      r_J0 <=
         (START)
         | (STEPQ & ~ENDQ)
         | (J5);
      r_J1 <=
         (J0);
      r_J2 <=
         (J1 & ~NUL)
         | (W & J2 & CBUSY)
         | (W & J2 & RP1)
         | (W & J2 & RP2)
         | (W & J2 & RP3)
         | (W & J2 & RP4);
      r_J3 <=
         (J2 & ~W);
      r_J4 <=
         (J3);
      r_J5 <=
         (J4);
      r_G0 <=
         (START)
         | (STEPQ & ~ENDQ)
         | (G0 & ~J5 & ~STEPQ);
      r_G1 <=
         (G0 & J5)
         | (G1 & ~J5 & ~STEPQ);
      r_G2 <=
         (G1 & J5)
         | (G2 & ~J5);
      r_PASSR <=
         (START & ~CMD4)
         | (WALK & PASSR & ~STEPQ)
         | (WALK & PASSR & WS0)
         | (WALK & PASSR & WS1)
         | (WALK & PASSR & WS2)
         | (WALK & PASSR & WS3);
      r_KD <=
         (WALK & KD & ~STEPQ)
         | (STEPQ & ~PASSR & ~KD);
      r_RF <=
         (START & ~CMD4)
         | (G0 & J5 & ~PASSR & ~KD)
         | (STEPQ & PASSR & WS0)
         | (STEPQ & PASSR & WS1)
         | (STEPQ & PASSR & WS2)
         | (STEPQ & PASSR & WS3)
         | (STEPQ & ~PASSR & ~KD)
         | (WALK & RF & ~J5 & ~STEPQ);
      r_RDQ <=
         (START)
         | (STEPQ & ~ENDQ)
         | (J5 & ~G2)
         | (J0 & ~W & RF)
         | (J1 & ~W & ~RF)
         | (J3);
      r_WS0 <=
         (START & ~CMD4 & CMD0)
         | (~START & STEPQ & ~PASSR & KD & ~WS0)
         | (~START & ~PASSR & ~KD & WS0)
         | (~START & ~STEPQ & WS0)
         | (~START & STEPQ & PASSR & ~WS0 & WS1)
         | (~START & STEPQ & PASSR & ~WS0 & WS2)
         | (~START & STEPQ & PASSR & ~WS0 & WS3);
      r_WS1 <=
         (START & ~CMD4 & CMD1)
         | (~START & STEPQ & ~PASSR & KD & WS0 & ~WS1)
         | (~START & ~STEPQ & WS1)
         | (~START & ~PASSR & ~WS0 & WS1)
         | (~START & PASSR & WS0 & WS1)
         | (~START & STEPQ & PASSR & ~WS0 & ~WS1 & WS2)
         | (~START & STEPQ & PASSR & ~WS0 & ~WS1 & WS3)
         | (~START & ~PASSR & ~KD & WS1);
      r_WS2 <=
         (START & ~CMD4 & CMD2)
         | (~START & STEPQ & ~PASSR & KD & WS0 & WS1 & ~WS2)
         | (~START & ~STEPQ & WS2)
         | (~START & STEPQ & PASSR & ~WS0 & ~WS1 & ~WS2 & WS3)
         | (~START & ~PASSR & ~WS1 & WS2)
         | (~START & PASSR & WS0 & WS2)
         | (~START & ~WS0 & WS1 & WS2)
         | (~START & ~PASSR & ~KD & WS2);
      r_WS3 <=
         (START & ~CMD4 & CMD3)
         | (~START & STEPQ & ~PASSR & KD & WS0 & WS1 & WS2 & ~WS3)
         | (~START & ~STEPQ & WS3)
         | (~START & ~PASSR & ~WS2 & WS3)
         | (~START & PASSR & WS0 & WS3)
         | (~START & ~WS0 & WS2 & WS3)
         | (~START & ~PASSR & ~WS1 & WS3)
         | (~START & WS1 & ~WS2 & WS3)
         | (~START & ~PASSR & ~KD & WS3);
      r_L0 <=
         (RDQ & D0)
         | (~RDQ & L0);
      r_L1 <=
         (RDQ & D1)
         | (~RDQ & L1);
      r_L2 <=
         (RDQ & D2)
         | (~RDQ & L2);
      r_L3 <=
         (RDQ & D3)
         | (~RDQ & L3);
      r_L4 <=
         (RDQ & D4)
         | (~RDQ & L4);
      r_L5 <=
         (RDQ & D5)
         | (~RDQ & L5);
      r_L6 <=
         (RDQ & D6)
         | (~RDQ & L6);
      r_L7 <=
         (RDQ & D7)
         | (~RDQ & L7);
      r_B0 <=
         (RDQ & J0 & RF & D0)
         | (B0 & ~J0)
         | (B0 & ~RF)
         | (B0 & ~RDQ);
      r_B1 <=
         (RDQ & J0 & RF & D1)
         | (B1 & ~J0)
         | (B1 & ~RF)
         | (B1 & ~RDQ);
      r_B2 <=
         (RDQ & J0 & RF & D2)
         | (B2 & ~J0)
         | (B2 & ~RF)
         | (B2 & ~RDQ);
      r_B3 <=
         (RDQ & J0 & RF & D3)
         | (B3 & ~J0)
         | (B3 & ~RF)
         | (B3 & ~RDQ);
      r_B4 <=
         (RDQ & J0 & RF & D4)
         | (B4 & ~J0)
         | (B4 & ~RF)
         | (B4 & ~RDQ);
      r_B5 <=
         (RDQ & J0 & RF & D5)
         | (B5 & ~J0)
         | (B5 & ~RF)
         | (B5 & ~RDQ);
      r_B6 <=
         (RDQ & J0 & RF & D6)
         | (B6 & ~J0)
         | (B6 & ~RF)
         | (B6 & ~RDQ);
      r_B7 <=
         (RDQ & J0 & RF & D7)
         | (B7 & ~J0)
         | (B7 & ~RF)
         | (B7 & ~RDQ);
  end

endmodule
`default_nettype wire
