/* GENERATED by test/mk6309tab.py from hd6309.tab - do not edit.
 *
 * Which (page, opcode) pairs exist on an HD6309 and NOT on a 6809.
 * A 6809 model must REFUSE these rather than decode them: $01 is OIM
 * on a 6309 and a ghost of NEG on a 6809, so "execute it as the
 * neighbour" turns a block operation into an arithmetic one and runs
 * on. armio.asm:513 records what that cost once - a TFM that
 * "assembled, linked, booted - and copied NOTHING".
 */
#ifndef HD6309OPS_H
#define HD6309OPS_H
#include <stdint.h>

#define HD6309_ONLY_COUNT 168

static const uint8_t hd6309_only[3][32] = {
    {0x26,0x08,0x10,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x26,0x08,0x26,0x08,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x20,0x00,0x00,0x00,0x00,0x00,0x00},
    {0x00,0x00,0x00,0x00,0x00,0x00,0xFF,0x0F,0xD9,0xB7,0x58,0xB6,0x00,0x00,0x00,0x00,0x77,0x0F,0xF7,0x0F,0xF7,0x0F,0xF7,0x0F,0x00,0x00,0x00,0x30,0x00,0x30,0x00,0x30},
    {0x00,0x00,0x00,0x00,0x00,0x00,0xFF,0x3F,0x08,0xB4,0x08,0xB4,0x00,0x00,0x00,0x00,0x43,0xE8,0xC3,0xE8,0xC3,0xE8,0xC3,0xE8,0x43,0x08,0xC3,0x08,0xC3,0x08,0xC3,0x08},
};

/* 1 if this (page, op) is a 6309-only encoding. */
static inline int hd6309_is_only(int page, uint8_t op)
{
    return page >= 0 && page < 3 &&
           (hd6309_only[page][op >> 3] >> (op & 7)) & 1;
}

/* native-mode cycle delta (NM - EM), 0 where the book's column
 * is state-dependent (>=N, N/M, N+kW) and a delta would lie. */
static const signed char hd6309_nm_delta[3][256] = {
    {-1,0,0,-1,-1,0,-1,-1,-1,-1,-1,0,-1,-2,-1,-1,0,0,-1,0,-1,0,-1,-2,0,-1,-1,0,0,-1,-3,-2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-1,0,-1,-2,0,0,-1,0,2,-1,0,0,-1,-1,0,-1,-1,-1,-1,-1,0,-1,-1,0,-1,-1,0,0,-1,-1,0,-1,-1,-1,-1,-1,0,-1,-1,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,-1,0,0,-1,-1,0,-1,-1,-1,-1,-1,0,-1,-2,-1,-1,0,0,0,-1,0,0,0,0,0,0,0,0,-1,-1,0,0,-1,-1,-1,-2,-1,-1,-1,-1,-1,-1,-1,-1,-2,-1,-1,-1,0,0,0,-1,0,0,0,0,0,0,0,0,-1,-1,0,0,-1,-1,-1,-2,-1,-1,-1,-1,-1,-1,-1,-1,-2,-1,-1,-1,0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,-1,0,0,-1,-1,0,-1,-1,-1,-1,-1,0,-1,-1,0,-1,0,0,0,-1,-1,0,-1,0,0,-1,-1,0,-1,-1,0,-2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-1,-1,-1,0,0,-1,-1,-1,-1,-1,0,0,0,-2,-2,-2,-2,-2,-2,-1,-1,-2,-2,-2,-2,-2,0,-1,-1,-1,-1,-1,-1,-1,-1,0,0,-1,-1,-1,-1,-1,0,0,0,-2,-2,-2,-2,-2,-2,-1,-1,-2,-2,-2,-2,-2,0,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-1},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,0,-1,0,0,0,-1,-1,0,-2,0,0,-1,-1,0,0,0,-1,-2,-1,-1,-1,0,0,0,-1,0,0,0,0,0,0,0,0,-1,0,0,0,-1,-1,0,-2,0,0,-1,-1,0,0,0,-1,-2,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,0,0,0,0,-1,-1,0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,0,0,0,0,-1,-1,0,0,0,-1,0,0,0,0},
};

/* 1 if this (page, op) is defined on an HD6309 (shared or not). */
static const uint8_t hd6309_def[3][32] = {
    {0xFF,0xFF,0xDC,0xF6,0xFF,0xFF,0xFF,0xBE,0xD9,0xB7,0xD9,0xB7,0xFF,0xFF,0xFF,0xFF,0x7F,0x7F,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF,0x7F,0x7F,0xFF,0xFF,0xFF,0xFF,0xFF,0xFF},
    {0x00,0x00,0x00,0x00,0xFE,0xFF,0xFF,0x8F,0xD9,0xB7,0x58,0xB6,0x00,0x00,0x00,0x00,0x7F,0x5F,0xFF,0xDF,0xFF,0xDF,0xFF,0xDF,0x00,0x40,0x00,0xF0,0x00,0xF0,0x00,0xF0},
    {0x00,0x00,0x00,0x00,0x00,0x00,0xFF,0xBF,0x08,0xB4,0x08,0xB4,0x00,0x00,0x00,0x00,0x4B,0xF8,0xCB,0xF8,0xCB,0xF8,0xCB,0xF8,0x43,0x08,0xC3,0x08,0xC3,0x08,0xC3,0x08},
};

static inline int hd6309_is_defined(int page, uint8_t op)
{
    return page >= 0 && page < 3 &&
           (hd6309_def[page][op >> 3] >> (op & 7)) & 1;
}

enum { HM_INH, HM_IMM, HM_DIR, HM_IDX, HM_EXT, HM_REL, HM_RTOR, HM_BITOP,
       HM_NONE = 255 };
static const uint8_t hd6309_mode[3][256] = {
    {2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,255,255,0,0,0,255,5,5,255,0,1,255,1,0,6,6,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,3,3,3,3,1,1,1,1,255,0,0,0,0,0,255,0,0,255,255,0,0,255,0,0,0,0,0,255,0,0,255,0,0,255,255,0,0,255,0,0,0,0,0,255,0,0,255,0,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,1,1,1,1,1,1,1,255,1,1,1,1,1,5,1,255,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,1,1,1,1,1,1,1,255,1,1,1,1,1,1,1,255,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4,4},
    {255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,5,5,5,5,5,5,5,5,5,5,5,5,5,5,5,6,6,6,6,6,6,6,6,0,0,0,0,255,255,255,0,0,255,255,0,0,255,0,0,0,0,0,255,0,0,255,0,255,255,255,0,0,255,0,255,255,0,0,255,0,0,255,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,1,1,1,1,1,1,1,255,1,1,1,1,1,255,1,255,2,2,2,2,2,2,2,2,2,2,2,2,2,255,2,2,3,3,3,3,3,3,3,3,3,3,3,3,3,255,3,3,4,4,4,4,4,4,4,4,4,4,4,4,4,255,4,4,255,255,255,255,255,255,255,255,255,255,255,255,255,255,1,255,255,255,255,255,255,255,255,255,255,255,255,255,2,2,2,2,255,255,255,255,255,255,255,255,255,255,255,255,3,3,3,3,255,255,255,255,255,255,255,255,255,255,255,255,4,4,4,4},
    {255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,7,7,7,7,7,7,7,7,6,6,6,6,1,1,255,0,255,255,255,0,255,255,255,255,255,255,0,255,0,0,255,0,255,255,255,0,255,255,255,255,255,255,0,255,0,0,255,0,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,1,1,255,1,255,255,1,255,255,255,255,1,1,1,1,1,2,2,255,2,255,255,2,2,255,255,255,2,2,2,2,2,3,3,255,3,255,255,3,3,255,255,255,3,3,3,3,3,4,4,255,4,255,255,4,4,255,255,255,4,4,4,4,4,1,1,255,255,255,255,1,255,255,255,255,1,255,255,255,255,2,2,255,255,255,255,2,2,255,255,255,2,255,255,255,255,3,3,255,255,255,255,3,3,255,255,255,3,255,255,255,255,4,4,255,255,255,255,4,4,255,255,255,4,255,255,255,255},
};

/* base cycles, [page][op][0 emulation, 1 native] - the book's column's
 * LEADING number; 0 where the 6309 does not define the encoding. */
static const uint8_t hd6309_cyc[3][256][2] = {
    {{6,5},{6,6},{6,6},{6,5},{6,5},{6,6},{6,5},{6,5},{6,5},{6,5},{6,5},{4,4},{6,5},{6,4},{3,2},{6,5},{0,0},{0,0},{2,1},{4,3},{4,4},{0,0},{5,4},{9,7},{0,0},{2,1},{3,3},{0,0},{3,3},{2,1},{8,5},{6,4},{3,3},{3,3},{3,3},{3,3},{3,3},{3,3},{3,3},{3,3},{3,3},{3,3},{3,3},{3,3},{3,3},{3,3},{3,3},{3,3},{4,4},{4,4},{4,4},{4,4},{5,4},{5,4},{5,4},{5,4},{0,0},{5,4},{3,1},{6,6},{20,22},{11,10},{0,0},{19,21},{2,1},{0,0},{0,0},{2,1},{2,1},{0,0},{2,1},{2,1},{2,1},{2,1},{2,1},{0,0},{2,1},{2,1},{0,0},{2,1},{2,1},{0,0},{0,0},{2,1},{2,1},{0,0},{2,1},{2,1},{2,1},{2,1},{2,1},{0,0},{2,1},{2,1},{0,0},{2,1},{6,6},{7,7},{7,7},{6,6},{6,6},{7,7},{6,6},{6,6},{6,6},{6,6},{6,6},{5,5},{6,6},{6,5},{3,3},{6,6},{7,6},{7,7},{7,7},{7,6},{7,6},{7,7},{7,6},{7,6},{7,6},{7,6},{7,6},{5,5},{7,6},{7,5},{4,3},{7,6},{2,2},{2,2},{2,2},{4,3},{2,2},{2,2},{2,2},{0,0},{2,2},{2,2},{2,2},{2,2},{4,3},{7,6},{3,3},{0,0},{4,3},{4,3},{4,3},{6,4},{4,3},{4,3},{4,3},{4,3},{4,3},{4,3},{4,3},{4,3},{6,4},{7,6},{5,4},{5,4},{4,4},{4,4},{4,4},{6,5},{4,4},{4,4},{4,4},{4,4},{4,4},{4,4},{4,4},{4,4},{6,5},{7,6},{5,5},{5,5},{5,4},{5,4},{5,4},{7,5},{5,4},{5,4},{5,4},{5,4},{5,4},{5,4},{5,4},{5,4},{7,5},{8,7},{6,5},{6,5},{2,2},{2,2},{2,2},{4,3},{2,2},{2,2},{2,2},{0,0},{2,2},{2,2},{2,2},{2,2},{3,3},{5,5},{3,3},{0,0},{4,3},{4,3},{4,3},{6,4},{4,3},{4,3},{4,3},{4,3},{4,3},{4,3},{4,3},{4,3},{5,4},{5,4},{5,4},{5,4},{4,4},{4,4},{4,4},{6,5},{4,4},{4,4},{4,4},{4,4},{4,4},{4,4},{4,4},{4,4},{5,5},{5,5},{5,5},{5,5},{5,4},{5,4},{5,4},{7,5},{5,4},{5,4},{5,4},{5,4},{5,4},{5,4},{5,4},{5,4},{6,5},{6,5},{6,5},{6,5}},
    {{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{5,5},{5,5},{5,5},{5,5},{5,5},{5,5},{5,5},{5,5},{5,5},{5,5},{5,5},{5,5},{5,5},{5,5},{5,5},{4,4},{4,4},{4,4},{4,4},{4,4},{4,4},{4,4},{4,4},{6,6},{6,6},{6,6},{6,6},{0,0},{0,0},{0,0},{20,22},{3,2},{0,0},{0,0},{3,2},{3,2},{0,0},{3,2},{3,2},{3,2},{3,2},{3,2},{0,0},{3,2},{3,2},{0,0},{3,2},{0,0},{0,0},{0,0},{3,2},{3,2},{0,0},{3,2},{0,0},{0,0},{3,2},{3,2},{0,0},{3,2},{3,2},{0,0},{3,2},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{5,4},{5,4},{5,4},{5,4},{5,4},{5,4},{4,4},{0,0},{5,4},{5,4},{5,4},{5,4},{5,4},{0,0},{4,4},{0,0},{7,5},{7,5},{7,5},{7,5},{7,5},{7,5},{6,5},{6,5},{7,5},{7,5},{7,5},{7,5},{7,5},{0,0},{6,5},{6,5},{7,6},{7,6},{7,6},{7,6},{7,6},{7,6},{6,6},{6,6},{7,6},{7,6},{7,6},{7,6},{7,6},{0,0},{6,6},{6,6},{8,6},{8,6},{8,6},{8,6},{8,6},{8,6},{7,6},{7,6},{8,6},{8,6},{8,6},{8,6},{8,6},{0,0},{7,6},{7,6},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{4,4},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{8,7},{8,7},{6,5},{6,5},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{8,8},{8,8},{6,6},{6,6},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{9,8},{9,8},{7,6},{7,6}},
    {{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{7,6},{7,6},{7,6},{7,6},{7,6},{7,6},{7,6},{8,7},{6,6},{6,6},{6,6},{6,6},{4,4},{5,5},{0,0},{20,22},{0,0},{0,0},{0,0},{3,2},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{3,2},{0,0},{3,2},{3,2},{0,0},{3,2},{0,0},{0,0},{0,0},{3,2},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{3,2},{0,0},{3,2},{3,2},{0,0},{3,2},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{0,0},{3,3},{3,3},{0,0},{5,4},{0,0},{0,0},{3,3},{0,0},{0,0},{0,0},{0,0},{3,3},{5,4},{25,25},{34,34},{28,28},{5,4},{5,4},{0,0},{7,5},{0,0},{0,0},{5,4},{5,4},{0,0},{0,0},{0,0},{5,4},{7,5},{27,26},{36,35},{30,29},{5,5},{5,5},{0,0},{7,6},{0,0},{0,0},{5,5},{5,5},{0,0},{0,0},{0,0},{5,5},{7,6},{27,27},{36,36},{30,30},{6,5},{6,5},{0,0},{8,6},{0,0},{0,0},{6,5},{6,5},{0,0},{0,0},{0,0},{6,5},{8,6},{28,27},{37,36},{31,30},{3,3},{3,3},{0,0},{0,0},{0,0},{0,0},{3,3},{0,0},{0,0},{0,0},{0,0},{3,3},{0,0},{0,0},{0,0},{0,0},{5,4},{5,4},{0,0},{0,0},{0,0},{0,0},{5,4},{5,4},{0,0},{0,0},{0,0},{5,4},{0,0},{0,0},{0,0},{0,0},{5,5},{5,5},{0,0},{0,0},{0,0},{0,0},{5,5},{5,5},{0,0},{0,0},{0,0},{5,5},{0,0},{0,0},{0,0},{0,0},{6,5},{6,5},{0,0},{0,0},{0,0},{0,0},{6,5},{6,5},{0,0},{0,0},{0,0},{6,5},{0,0},{0,0},{0,0},{0,0}},
};

static inline const char *hd6309_name(int page, uint8_t op)
{
    switch ((page << 8) | op) {
    case 0x000: return "NEG";
    case 0x001: return "OIM";
    case 0x002: return "AIM";
    case 0x003: return "COM";
    case 0x004: return "LSR";
    case 0x005: return "EIM";
    case 0x006: return "ROR";
    case 0x007: return "ASR";
    case 0x008: return "ASL/LSL";
    case 0x009: return "ROL";
    case 0x00A: return "DEC";
    case 0x00B: return "TIM";
    case 0x00C: return "INC";
    case 0x00D: return "TST";
    case 0x00E: return "JMP";
    case 0x00F: return "CLR";
    case 0x012: return "NOP";
    case 0x013: return "SYNC";
    case 0x014: return "SEXW";
    case 0x016: return "LBRA";
    case 0x017: return "LBSR";
    case 0x019: return "DAA";
    case 0x01A: return "ORCC";
    case 0x01C: return "ANDCC";
    case 0x01D: return "SEX";
    case 0x01E: return "EXG";
    case 0x01F: return "TFR";
    case 0x020: return "BRA";
    case 0x021: return "BRN";
    case 0x022: return "BHI";
    case 0x023: return "BLS";
    case 0x024: return "BHS/BCC";
    case 0x025: return "BLO/BCS";
    case 0x026: return "BNE";
    case 0x027: return "BEQ";
    case 0x028: return "BVC";
    case 0x029: return "BVS";
    case 0x02A: return "BPL";
    case 0x02B: return "BMI";
    case 0x02C: return "BGE";
    case 0x02D: return "BLT";
    case 0x02E: return "BGT";
    case 0x02F: return "BLE";
    case 0x030: return "LEAX";
    case 0x031: return "LEAY";
    case 0x032: return "LEAS";
    case 0x033: return "LEAU";
    case 0x034: return "PSHS";
    case 0x035: return "PULS";
    case 0x036: return "PSHU";
    case 0x037: return "PULU";
    case 0x039: return "RTS";
    case 0x03A: return "ABX";
    case 0x03B: return "RTI";
    case 0x03C: return "CWAI";
    case 0x03D: return "MUL";
    case 0x03F: return "SWI";
    case 0x040: return "NEGA";
    case 0x043: return "COMA";
    case 0x044: return "LSRA";
    case 0x046: return "RORA";
    case 0x047: return "ASRA";
    case 0x048: return "ASLA/LSLA";
    case 0x049: return "ROLA";
    case 0x04A: return "DECA";
    case 0x04C: return "INCA";
    case 0x04D: return "TSTA";
    case 0x04F: return "CLRA";
    case 0x050: return "NEGB";
    case 0x053: return "COMB";
    case 0x054: return "LSRB";
    case 0x056: return "RORB";
    case 0x057: return "ASRB";
    case 0x058: return "ASLB/LSLB";
    case 0x059: return "ROLB";
    case 0x05A: return "DECB";
    case 0x05C: return "INCB";
    case 0x05D: return "TSTB";
    case 0x05F: return "CLRB";
    case 0x060: return "NEG";
    case 0x061: return "OIM";
    case 0x062: return "AIM";
    case 0x063: return "COM";
    case 0x064: return "LSR";
    case 0x065: return "EIM";
    case 0x066: return "ROR";
    case 0x067: return "ASR";
    case 0x068: return "ASL/LSL";
    case 0x069: return "ROL";
    case 0x06A: return "DEC";
    case 0x06B: return "TIM";
    case 0x06C: return "INC";
    case 0x06D: return "TST";
    case 0x06E: return "JMP";
    case 0x06F: return "CLR";
    case 0x070: return "NEG";
    case 0x071: return "OIM";
    case 0x072: return "AIM";
    case 0x073: return "COM";
    case 0x074: return "LSR";
    case 0x075: return "EIM";
    case 0x076: return "ROR";
    case 0x077: return "ASR";
    case 0x078: return "ASL/LSL";
    case 0x079: return "ROL";
    case 0x07A: return "DEC";
    case 0x07B: return "TIM";
    case 0x07C: return "INC";
    case 0x07D: return "TST";
    case 0x07E: return "JMP";
    case 0x07F: return "CLR";
    case 0x080: return "SUBA";
    case 0x081: return "CMPA";
    case 0x082: return "SBCA";
    case 0x083: return "SUBD";
    case 0x084: return "ANDA";
    case 0x085: return "BITA";
    case 0x086: return "LDA";
    case 0x088: return "EORA";
    case 0x089: return "ADCA";
    case 0x08A: return "ORA";
    case 0x08B: return "ADDA";
    case 0x08C: return "CMPX";
    case 0x08D: return "BSR";
    case 0x08E: return "LDX";
    case 0x090: return "SUBA";
    case 0x091: return "CMPA";
    case 0x092: return "SBCA";
    case 0x093: return "SUBD";
    case 0x094: return "ANDA";
    case 0x095: return "BITA";
    case 0x096: return "LDA";
    case 0x097: return "STA";
    case 0x098: return "EORA";
    case 0x099: return "ADCA";
    case 0x09A: return "ORA";
    case 0x09B: return "ADDA";
    case 0x09C: return "CMPX";
    case 0x09D: return "JSR";
    case 0x09E: return "LDX";
    case 0x09F: return "STX";
    case 0x0A0: return "SUBA";
    case 0x0A1: return "CMPA";
    case 0x0A2: return "SBCA";
    case 0x0A3: return "SUBD";
    case 0x0A4: return "ANDA";
    case 0x0A5: return "BITA";
    case 0x0A6: return "LDA";
    case 0x0A7: return "STA";
    case 0x0A8: return "EORA";
    case 0x0A9: return "ADCA";
    case 0x0AA: return "ORA";
    case 0x0AB: return "ADDA";
    case 0x0AC: return "CMPX";
    case 0x0AD: return "JSR";
    case 0x0AE: return "LDX";
    case 0x0AF: return "STX";
    case 0x0B0: return "SUBA";
    case 0x0B1: return "CMPA";
    case 0x0B2: return "SBCA";
    case 0x0B3: return "SUBD";
    case 0x0B4: return "ANDA";
    case 0x0B5: return "BITA";
    case 0x0B6: return "LDA";
    case 0x0B7: return "STA";
    case 0x0B8: return "EORA";
    case 0x0B9: return "ADCA";
    case 0x0BA: return "ORA";
    case 0x0BB: return "ADDA";
    case 0x0BC: return "CMPX";
    case 0x0BD: return "JSR";
    case 0x0BE: return "LDX";
    case 0x0BF: return "STX";
    case 0x0C0: return "SUBB";
    case 0x0C1: return "CMPB";
    case 0x0C2: return "SBCB";
    case 0x0C3: return "ADDD";
    case 0x0C4: return "ANDB";
    case 0x0C5: return "BITB";
    case 0x0C6: return "LDB";
    case 0x0C8: return "EORB";
    case 0x0C9: return "ADCB";
    case 0x0CA: return "ORB";
    case 0x0CB: return "ADDB";
    case 0x0CC: return "LDD";
    case 0x0CD: return "LDQ";
    case 0x0CE: return "LDU";
    case 0x0D0: return "SUBB";
    case 0x0D1: return "CMPB";
    case 0x0D2: return "SBCB";
    case 0x0D3: return "ADDD";
    case 0x0D4: return "ANDB";
    case 0x0D5: return "BITB";
    case 0x0D6: return "LDB";
    case 0x0D7: return "STB";
    case 0x0D8: return "EORB";
    case 0x0D9: return "ADCB";
    case 0x0DA: return "ORB";
    case 0x0DB: return "ADDB";
    case 0x0DC: return "LDD";
    case 0x0DD: return "STD";
    case 0x0DE: return "LDU";
    case 0x0DF: return "STU";
    case 0x0E0: return "SUBB";
    case 0x0E1: return "CMPB";
    case 0x0E2: return "SBCB";
    case 0x0E3: return "ADDD";
    case 0x0E4: return "ANDB";
    case 0x0E5: return "BITB";
    case 0x0E6: return "LDB";
    case 0x0E7: return "STB";
    case 0x0E8: return "EORB";
    case 0x0E9: return "ADCB";
    case 0x0EA: return "ORB";
    case 0x0EB: return "ADDB";
    case 0x0EC: return "LDD";
    case 0x0ED: return "STD";
    case 0x0EE: return "LDU";
    case 0x0EF: return "STU";
    case 0x0F0: return "SUBB";
    case 0x0F1: return "CMPB";
    case 0x0F2: return "SBCB";
    case 0x0F3: return "ADDD";
    case 0x0F4: return "ANDB";
    case 0x0F5: return "BITB";
    case 0x0F6: return "LDB";
    case 0x0F7: return "STB";
    case 0x0F8: return "EORB";
    case 0x0F9: return "ADCB";
    case 0x0FA: return "ORB";
    case 0x0FB: return "ADDB";
    case 0x0FC: return "LDD";
    case 0x0FD: return "STD";
    case 0x0FE: return "LDU";
    case 0x0FF: return "STU";
    case 0x121: return "LBRN";
    case 0x122: return "LBHI";
    case 0x123: return "LBLS";
    case 0x124: return "LBHS/LBCC";
    case 0x125: return "LBLO/LBCS";
    case 0x126: return "LBNE";
    case 0x127: return "LBEQ";
    case 0x128: return "LBVC";
    case 0x129: return "LBVS";
    case 0x12A: return "LBPL";
    case 0x12B: return "LBMI";
    case 0x12C: return "LBGE";
    case 0x12D: return "LBLT";
    case 0x12E: return "LBGT";
    case 0x12F: return "LBLE";
    case 0x130: return "ADDR";
    case 0x131: return "ADCR";
    case 0x132: return "SUBR";
    case 0x133: return "SBCR";
    case 0x134: return "ANDR";
    case 0x135: return "ORR";
    case 0x136: return "EORR";
    case 0x137: return "CMPR";
    case 0x138: return "PSHSW";
    case 0x139: return "PULSW";
    case 0x13A: return "PSHUW";
    case 0x13B: return "PULUW";
    case 0x13F: return "SWI2";
    case 0x140: return "NEGD";
    case 0x143: return "COMD";
    case 0x144: return "LSRD";
    case 0x146: return "RORD";
    case 0x147: return "ASRD";
    case 0x148: return "ASLD/LSLD";
    case 0x149: return "ROLD";
    case 0x14A: return "DECD";
    case 0x14C: return "INCD";
    case 0x14D: return "TSTD";
    case 0x14F: return "CLRD";
    case 0x153: return "COMW";
    case 0x154: return "LSRW";
    case 0x156: return "RORW";
    case 0x159: return "ROLW";
    case 0x15A: return "DECW";
    case 0x15C: return "INCW";
    case 0x15D: return "TSTW";
    case 0x15F: return "CLRW";
    case 0x180: return "SUBW";
    case 0x181: return "CMPW";
    case 0x182: return "SBCD";
    case 0x183: return "CMPD";
    case 0x184: return "ANDD";
    case 0x185: return "BITD";
    case 0x186: return "LDW";
    case 0x188: return "EORD";
    case 0x189: return "ADCD";
    case 0x18A: return "ORD";
    case 0x18B: return "ADDW";
    case 0x18C: return "CMPY";
    case 0x18E: return "LDY";
    case 0x190: return "SUBW";
    case 0x191: return "CMPW";
    case 0x192: return "SBCD";
    case 0x193: return "CMPD";
    case 0x194: return "ANDD";
    case 0x195: return "BITD";
    case 0x196: return "LDW";
    case 0x197: return "STW";
    case 0x198: return "EORD";
    case 0x199: return "ADCD";
    case 0x19A: return "ORD";
    case 0x19B: return "ADDW";
    case 0x19C: return "CMPY";
    case 0x19E: return "LDY";
    case 0x19F: return "STY";
    case 0x1A0: return "SUBW";
    case 0x1A1: return "CMPW";
    case 0x1A2: return "SBCD";
    case 0x1A3: return "CMPD";
    case 0x1A4: return "ANDD";
    case 0x1A5: return "BITD";
    case 0x1A6: return "LDW";
    case 0x1A7: return "STW";
    case 0x1A8: return "EORD";
    case 0x1A9: return "ADCD";
    case 0x1AA: return "ORD";
    case 0x1AB: return "ADDW";
    case 0x1AC: return "CMPY";
    case 0x1AE: return "LDY";
    case 0x1AF: return "STY";
    case 0x1B0: return "SUBW";
    case 0x1B1: return "CMPW";
    case 0x1B2: return "SBCD";
    case 0x1B3: return "CMPD";
    case 0x1B4: return "ANDD";
    case 0x1B5: return "BITD";
    case 0x1B6: return "LDW";
    case 0x1B7: return "STW";
    case 0x1B8: return "EORD";
    case 0x1B9: return "ADCD";
    case 0x1BA: return "ORD";
    case 0x1BB: return "ADDW";
    case 0x1BC: return "CMPY";
    case 0x1BE: return "LDY";
    case 0x1BF: return "STY";
    case 0x1CE: return "LDS";
    case 0x1DC: return "LDQ";
    case 0x1DD: return "STQ";
    case 0x1DE: return "LDS";
    case 0x1DF: return "STS";
    case 0x1EC: return "LDQ";
    case 0x1ED: return "STQ";
    case 0x1EE: return "LDS";
    case 0x1EF: return "STS";
    case 0x1FC: return "LDQ";
    case 0x1FD: return "STQ";
    case 0x1FE: return "LDS";
    case 0x1FF: return "STS";
    case 0x230: return "BAND";
    case 0x231: return "BIAND";
    case 0x232: return "BOR";
    case 0x233: return "BIOR";
    case 0x234: return "BEOR";
    case 0x235: return "BIEOR";
    case 0x236: return "LDBT";
    case 0x237: return "STBT";
    case 0x238: return "TFM";
    case 0x239: return "TFM";
    case 0x23A: return "TFM";
    case 0x23B: return "TFM";
    case 0x23C: return "BITMD";
    case 0x23D: return "LDMD";
    case 0x23F: return "SWI3";
    case 0x243: return "COME";
    case 0x24A: return "DECE";
    case 0x24C: return "INCE";
    case 0x24D: return "TSTE";
    case 0x24F: return "CLRE";
    case 0x253: return "COMF";
    case 0x25A: return "DECF";
    case 0x25C: return "INCF";
    case 0x25D: return "TSTF";
    case 0x25F: return "CLRF";
    case 0x280: return "SUBE";
    case 0x281: return "CMPE";
    case 0x283: return "CMPU";
    case 0x286: return "LDE";
    case 0x28B: return "ADDE";
    case 0x28C: return "CMPS";
    case 0x28D: return "DIVD";
    case 0x28E: return "DIVQ";
    case 0x28F: return "MULD";
    case 0x290: return "SUBE";
    case 0x291: return "CMPE";
    case 0x293: return "CMPU";
    case 0x296: return "LDE";
    case 0x297: return "STE";
    case 0x29B: return "ADDE";
    case 0x29C: return "CMPS";
    case 0x29D: return "DIVD";
    case 0x29E: return "DIVQ";
    case 0x29F: return "MULD";
    case 0x2A0: return "SUBE";
    case 0x2A1: return "CMPE";
    case 0x2A3: return "CMPU";
    case 0x2A6: return "LDE";
    case 0x2A7: return "STE";
    case 0x2AB: return "ADDE";
    case 0x2AC: return "CMPS";
    case 0x2AD: return "DIVD";
    case 0x2AE: return "DIVQ";
    case 0x2AF: return "MULD";
    case 0x2B0: return "SUBE";
    case 0x2B1: return "CMPE";
    case 0x2B3: return "CMPU";
    case 0x2B6: return "LDE";
    case 0x2B7: return "STE";
    case 0x2BB: return "ADDE";
    case 0x2BC: return "CMPS";
    case 0x2BD: return "DIVD";
    case 0x2BE: return "DIVQ";
    case 0x2BF: return "MULD";
    case 0x2C0: return "SUBF";
    case 0x2C1: return "CMPF";
    case 0x2C6: return "LDF";
    case 0x2CB: return "ADDF";
    case 0x2D0: return "SUBF";
    case 0x2D1: return "CMPF";
    case 0x2D6: return "LDF";
    case 0x2D7: return "STF";
    case 0x2DB: return "ADDF";
    case 0x2E0: return "SUBF";
    case 0x2E1: return "CMPF";
    case 0x2E6: return "LDF";
    case 0x2E7: return "STF";
    case 0x2EB: return "ADDF";
    case 0x2F0: return "SUBF";
    case 0x2F1: return "CMPF";
    case 0x2F6: return "LDF";
    case 0x2F7: return "STF";
    case 0x2FB: return "ADDF";
    default: return "?";
    }
}

#endif
