#!/usr/bin/env python3
"""Write hardware/video3/bench/v3char.asm and v3char.json - the character-mode exerciser.

hardware/video3/docs/plan.md §2.2 and §3.  The ROM and tools/v3model.py share the JSON
- the DATA - and nothing else: the model renders from the plan's rules, not
from the ROM's code, which is the discipline software/nitros9/tools/vtmodel.py
already keeps.
"""
import json, sys

TILEBASE, MAPBASE = 1, 2            # VRAM 16,384 and 131,072
COLS, ROWS_N = 80, 64               # the whole six-bit cell row (plan §2.5)

# ⭐ every geometry video3 claims.  VMODE 10 and 11 - 80x50 and 80x60 - are the
# ones `video` cannot reach in cell mode at all (graphics.md §6.4.1's five-bit
# cell row), so they are the reason this card exists.
# (marker, active lines, doubling, the VMODE written to CTRL, title).  The
# marker and the CTRL VMODE differ only in the last entry, which is ⭐ the
# NEGATIVE half of plan §7's "bitmap mode only": the same SPRH write that puts
# a sprite on screen in bench/v3sprite - 36 positions, the positive control -
# must do nothing here.
VMODES = [(0, 400, 2, 0, "80x25, 449-line, doubled"),
          (1, 480, 2, 1, "80x30, 525-line, doubled"),
          (2, 400, 1, 2, "80x50, 449-line, progressive"),
          (3, 480, 1, 3, "80x60, 525-line, progressive"),
          (4, 400, 2, 0, "80x25 with the SPRITE ENABLED - it must not appear")]
SPR_X, SPR_Y = 32, 8                # cell (1, 4), whose attribute is $2A
# ⭐ plan §2.5: a cell is FOUR bytes and the card reads the EVEN two - the code
# at +0 and the attribute at +2, the two memory parts' low bytes.  +1 and +3
# are never read.  The ROM fills those two with a code and an attribute that
# are neither the cell's, so a card that reads the wrong lanes or the wrong
# stride paints the wrong glyph in the wrong colour.
PAD1, PAD3 = 0xB0, 0x77
# plan §7: the sprite shape is the top 64 bytes of MAPBASE's 64 KB region.
# Character mode never shows it; the negative phase writes it there anyway.
SHAPE_AT = MAPBASE * 65536 + 0xFFC0

GLYPHS = {                          # code -> eight 1bpp rows, MSB leftmost
    0x20: [0x00] * 8,
    0x41: [0x18, 0x24, 0x42, 0x7E, 0x42, 0x42, 0x42, 0x00],
    0x42: [0x7C, 0x42, 0x7C, 0x42, 0x42, 0x42, 0x7C, 0x00],
    0xB0: [0x88, 0x22, 0x88, 0x22, 0x88, 0x22, 0x88, 0x22],
    0xB1: [0xAA, 0x55, 0xAA, 0x55, 0xAA, 0x55, 0xAA, 0x55],
    0xDB: [0xFF] * 8,
    0xDC: [0x00, 0x00, 0x00, 0x00, 0xFF, 0xFF, 0xFF, 0xFF],
    0xDF: [0xFF, 0xFF, 0xFF, 0xFF, 0x00, 0x00, 0x00, 0x00],
}
CODES = sorted(GLYPHS)

def cell(r, c):
    """The (code, attr) at a cell.  Chosen so that a WRONG ATTR PATH is visible:
    row 0 walks the attribute with one glyph, row 1 walks the glyph with one
    attribute, and the rest mixes both."""
    if r == 0:  return (0xDB, c & 0xFF)                  # attribute sweep
    if r == 1:  return (CODES[c % len(CODES)], 0x2A)     # glyph sweep
    if r == 2:  return (0xB1, (c * 7) & 0xFF)
    if r == 3:  return (CODES[(c + r) % len(CODES)], (c * 13 + r) & 0xFF)
    return (CODES[(c + r) % len(CODES)], (c ^ (r * 5)) & 0xFF)

def subpal(a):
    """Entry 0 is the background and entry 1 the foreground.  Distinct per
    attribute, so a cell rendered through the wrong sub-palette is obvious."""
    return (a * 0x0101) & 0xFFFF, (0xFFFF - a * 0x0101) & 0xFFFF

data = {"tilebase": TILEBASE, "mapbase": MAPBASE, "cols": COLS, "rows": ROWS_N,
        "vmodes": [list(v) for v in VMODES],
        "glyphs": {str(k): v for k, v in GLYPHS.items()},
        "map": [[list(cell(r, c)) for c in range(COLS)] for r in range(ROWS_N)],
        "pal": [list(subpal(a)) for a in range(256)]}
json.dump(data, open(sys.argv[2], "w"))

def tbl(name, by, per=16):
    out = [f"{name}"]
    for i in range(0, len(by), per):
        out.append("        FCB     " + ",".join(f"${b:02X}" for b in by[i:i + per]))
    return "\n".join(out) + "\n"

paltab = bytearray()
for a in range(256):
    bg, fg = subpal(a)
    paltab += bytes([bg & 0xFF, bg >> 8, fg & 0xFF, fg >> 8])

glyphtab = bytearray()
for code in CODES:                        # code, then 64 bytes of one-per-pixel
    glyphtab.append(code)
    for row in GLYPHS[code]:
        for b in range(8):
            glyphtab.append(1 if row & (0x80 >> b) else 0)

maptab = bytearray()
for r in range(ROWS_N):
    for c in range(COLS):
        code, attr = cell(r, c)
        maptab += bytes([code, attr])

src = f"""*******************************************************************************
* v3char.asm -- video3's character mode on the host emulator.  GENERATED by
* bench/mkv3char.py; edit the generator.
*
*   sh hardware/video3/bench/run-v3char.sh
*
* plan 2.2 and 3: the map is FOUR bytes a cell - the code at +0, the attribute
* at +2, and +1/+3 never read - and the attribute is the HIGH
* eight bits of the LUT address, so a cell's colours are a sub-palette rather
* than a bank.  A wrong ATTR path renders the right shapes in the wrong
* colours - which a pixel-exact model catches and a register trace does not.
*
* The map goes in with WADV b2 set, the card's step-by-two write (plan 2.5),
* which is what makes a cell TWO VDATA writes rather than four.
*******************************************************************************

VCTRL   EQU     $FF60
WPTR0   EQU     $FF68
WPTR1   EQU     $FF69
WPTR2   EQU     $FF6A
WADV    EQU     $FF6B
VDATA   EQU     $FF6C
PIDXL   EQU     $FF6E
PIDXH   EQU     $FF6F
PDATL   EQU     $FF70
PDATH   EQU     $FF71
TILEBAS EQU     $FF78
MAPBAS  EQU     $FF79
SIMPORT EQU     $FF2F
VSTAT   EQU     $FF6D
SPRX    EQU     $FF7A
SPRY    EQU     $FF7B
SPRH    EQU     $FF7C
MKV     EQU     $C20A           machine.c records this with every frame

NGLYPH  EQU     {len(CODES)}
NROWS   EQU     {ROWS_N}
TBASE   EQU     {TILEBASE * 16384}

        ORG     $8000
        FCC     "6309"
        JMP     start

        SETDP   $FF
start   orcc    #$50
        lds     #$E000
        lda     #$FF
        tfr     a,dp
        clr     <VCTRL          display off, bitmap, WMODE 00 direct
        clr     <WADV
        lda     #{TILEBASE}
        sta     <TILEBAS
        lda     #{MAPBASE}
        sta     <MAPBAS

* --- 256 sub-palettes, entries 0 and 1.  PIDX is 16 bits and increments
*     after PDATH, so one index write covers a pair.
        ldx     #paltab
        clrb
pal1    stb     <PIDXH
        clr     <PIDXL
        lda     ,x+
        sta     <PDATL
        lda     ,x+
        sta     <PDATH
        lda     ,x+
        sta     <PDATL
        lda     ,x+
        sta     <PDATH
        incb
        bne     pal1

* --- the glyph bank: one byte a pixel, at TBASE + code * 64
        ldx     #glyphtab
        ldb     #NGLYPH
gl1     pshs    b
        lda     ,x+
        clrb
        lsra
        rorb
        lsra
        rorb                    D = code * 64
        addd    #TBASE
        stb     <WPTR0
        sta     <WPTR1
        clr     <WPTR2
        ldb     #64
gl2     lda     ,x+
        sta     <VDATA
        decb
        bne     gl2
        puls    b
        decb
        bne     gl1

* --- the map: four bytes a cell, one VRAM row a cell row, in TWO PASSES and
*     both of them with WADV b2 set - the card's step-by-two write (plan 2.5).
*     ⭐ Pass one starts at an ODD address, so stepping by two fills +1 and +3
*     of every cell with a decoy code and a decoy attribute the card must
*     never read.  Pass two starts at the even one and writes the cell itself:
*     the code into lane 0, the attribute into lane 2, two stores a character.
*     A card that reads the odd lanes, or a pointer that steps by one, paints
*     the decoy instead of the cell.
        lda     #$04
        sta     <WADV           b2: step by two
        ldx     #maptab
        clra
        ldb     #NROWS
mr1     pshs    a,b
        lda     #{MAPBASE}
        sta     <WPTR2
        lda     ,s
        lsla
        lsla                    row * 4 -> WPTR1, a 1024-byte stride
        sta     <WPTR1
        lda     #1
        sta     <WPTR0          the ODD lane of cell 0
        ldy     #{COLS}
mr0     lda     #${PAD1:02X}
        sta     <VDATA          lane 1: a decoy code
        lda     #${PAD3:02X}
        sta     <VDATA          lane 3: a decoy attribute
        leay    -1,y
        bne     mr0
        lda     ,s
        lsla
        lsla
        sta     <WPTR1
        clr     <WPTR0          and back to the even lane of cell 0
        ldy     #{COLS}
mr2     lda     ,x+
        sta     <VDATA          lane 0: the code
        lda     ,x+
        sta     <VDATA          lane 2: the attribute
        leay    -1,y
        bne     mr2
        puls    a,b
        inca
        decb
        bne     mr1
        clr     <WADV           ⛔ b2 off: everything below steps by one

* --- character mode, every VMODE in turn.  Each is set, allowed to settle -
*     graphics.md 6.2 latches the family at FRAME END - and only then marked at
*     $C20A, so no frame is judged against a geometry it was not drawn in.
        lda     #$A0
        sta     SIMPORT
        ldd     #$FFFF
        std     MKV
        lda     #$84          display on, MODE 01, VMODE 00 - 80x25, 449-line, doubled
        sta     <VCTRL
        lbsr    wait3
        ldd     #0
        std     MKV
        lbsr    wait3
        ldd     #$FFFF
        std     MKV
        lda     #$85          display on, MODE 01, VMODE 01 - 80x30, 525-line, doubled
        sta     <VCTRL
        lbsr    wait3
        ldd     #1
        std     MKV
        lbsr    wait3
        ldd     #$FFFF
        std     MKV
        lda     #$86          display on, MODE 01, VMODE 10 - 80x50, 449-line, progressive
        sta     <VCTRL
        lbsr    wait3
        ldd     #2
        std     MKV
        lbsr    wait3
        ldd     #$FFFF
        std     MKV
        lda     #$87          display on, MODE 01, VMODE 11 - 80x60, 525-line, progressive
        sta     <VCTRL
        lbsr    wait3
        ldd     #3
        std     MKV
        lbsr    wait3
        ldd     #$FFFF
        std     MKV
* --- ⭐ plan 7's negative half.  Arm the sprite, PROVE the register took the
*     enable - otherwise the test asserts nothing - and require that character
*     mode shows no trace of it.  bench/v3sprite is the positive control.
*     The shape is in VRAM at MAPBASE's top 64 bytes (plan 7), written with
*     ordinary VDATA writes: eight rows of $FF,0,0,0 - columns 0-7 opaque in
*     sub-palette 1, an 8 x 8 - and the other eight rows left zero.
        lda     #${SHAPE_AT >> 16:02X}
        sta     <WPTR2
        lda     #${(SHAPE_AT >> 8) & 0xFF:02X}
        sta     <WPTR1
        lda     #${SHAPE_AT & 0xFF:02X}
        sta     <WPTR0
        ldb     #8
sp1     lda     #$FF
        sta     <VDATA          low plane, columns 0-7
        clr     <VDATA
        clr     <VDATA
        clr     <VDATA
        decb
        bne     sp1
        ldb     #32
sp0     clr     <VDATA          rows 8-15 transparent
        decb
        bne     sp0
        lda     #$20
        sta     <SPRX           x = 32
        lda     #$08
        sta     <SPRY           y = 8, so cell (1,4) - its attribute is $2A
        lda     #$80
        sta     <SPRH           b7 enable
        lda     <SPRH
        cmpa    #$80
        beq     sp2
        lda     #$E1            the register refused the enable: fail loudly
        sta     SIMPORT
sp2     lda     #$84            display on, MODE 01, VMODE 00, sprite ARMED
        sta     <VCTRL
        lbsr    wait3
        ldd     #4
        std     MKV
        lbsr    wait3
        ldd     #$FFFF
        std     MKV
        lda     #$AF
        sta     SIMPORT
done    bra     done

wait3   pshs    a,b
        ldb     #3
w1      lda     <VSTAT
        bita    #$40
        bne     w1
w2      lda     <VSTAT
        bita    #$40
        beq     w2
        decb
        bne     w1
        puls    a,b,pc

{tbl("paltab", paltab)}
{tbl("glyphtab", glyphtab)}
{tbl("maptab", maptab)}
        END
"""
open(sys.argv[1], "w").write(src)
print(f"wrote {sys.argv[1]} ({len(src)} bytes) and {sys.argv[2]}")
