/* Write the CPLD sources from the same term lists everything else uses.
 *
 * The .pld files were generated by hand-invoking toCupl() and were the one
 * link in the chain with no script behind it, which is how archive/video/logic/vctrl.pld and
 * video.cpld.ts drifted apart. Now:
 *
 *   *.jedec.ts / video.parts.ts  ->  cpld.gen.ts  ->  <card>/logic/*.pld
 *                                ->  prjbureau/fit1508.sh  ->  cpld/*.fit
 *                                ->  verilog/gen.ts  ->  verilog/*.v
 *
 * One origin, three devices. `npm run gen:pld`.
 */

import { writeFileSync } from "fs"
import { dirname, join } from "path"
import { fileURLToPath } from "url"
import { vaddrSource, vctrlSource } from "../../archive/video/logic/video.cpld"
import { vsupSource } from "../../archive/video/logic/vsup.cpld"
import { audioCuplSource } from "../../audio/logic/audio.cpld"
import { aseqCuplSource } from "../../audio/logic/aseq.cpld"

const here = dirname(fileURLToPath(import.meta.url))
/* each .pld is written beside the term list it comes from */
const CARD: Record<string, string> = {
  vaddr: "archive/video", vctrl: "archive/video", vsup: "archive/video",
  audio: "audio", aseq: "audio",
}
const write = (name: string, text: string) => {
  writeFileSync(join(here, "..", "..", CARD[name], "logic", `${name}.pld`), text)
  console.log(`ok    ${name}.pld  ${text.split("\n").length} lines`)
}

write("vaddr", vaddrSource())
write("vctrl", vctrlSource())
write("vsup", vsupSource())
write("audio", audioCuplSource())
/* U2, the audio card's sequencer - audio.md 10.2. */
write("aseq", aseqCuplSource())
