/* GENERATED by test/mk6309tab.py from hd6309.tab - do not edit.
 *
 * Which (page, opcode) pairs exist on an HD6309 and NOT on a 6809.
 * A 6809 model must REFUSE these rather than decode them: $01 is OIM
 * on a 6309 and a ghost of NEG on a 6809, so "execute it as the
 * neighbour" turns a block operation into an arithmetic one and runs
 * on. armio.asm:513 records what that cost once - a TFM that
 * "assembled, linked, booted - and copied NOTHING".
 */
#ifndef HD6309OPS_H
#define HD6309OPS_H
#include <stdint.h>

#define HD6309_ONLY_COUNT 168

static const uint8_t hd6309_only[3][32] = {
    {0x26,0x08,0x10,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x26,0x08,0x26,0x08,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x20,0x00,0x00,0x00,0x00,0x00,0x00},
    {0x00,0x00,0x00,0x00,0x00,0x00,0xFF,0x0F,0xD9,0xB7,0x58,0xB6,0x00,0x00,0x00,0x00,0x77,0x0F,0xF7,0x0F,0xF7,0x0F,0xF7,0x0F,0x00,0x00,0x00,0x30,0x00,0x30,0x00,0x30},
    {0x00,0x00,0x00,0x00,0x00,0x00,0xFF,0x3F,0x08,0xB4,0x08,0xB4,0x00,0x00,0x00,0x00,0x43,0xE8,0xC3,0xE8,0xC3,0xE8,0xC3,0xE8,0x43,0x08,0xC3,0x08,0xC3,0x08,0xC3,0x08},
};

/* 1 if this (page, op) is a 6309-only encoding. */
static inline int hd6309_is_only(int page, uint8_t op)
{
    return page >= 0 && page < 3 &&
           (hd6309_only[page][op >> 3] >> (op & 7)) & 1;
}

/* native-mode cycle delta (NM - EM), 0 where the book's column
 * is state-dependent (>=N, N/M, N+kW) and a delta would lie. */
static const signed char hd6309_nm_delta[3][256] = {
    {-1,0,0,-1,-1,0,-1,-1,-1,-1,-1,0,-1,-2,-1,-1,0,0,-1,0,-1,0,-1,-2,0,-1,-1,0,0,-1,-3,-2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-1,0,-1,-2,0,0,-1,0,2,-1,0,0,-1,-1,0,-1,-1,-1,-1,-1,0,-1,-1,0,-1,-1,0,0,-1,-1,0,-1,-1,-1,-1,-1,0,-1,-1,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,-1,0,0,-1,-1,0,-1,-1,-1,-1,-1,0,-1,-2,-1,-1,0,0,0,-1,0,0,0,0,0,0,0,0,-1,-1,0,0,-1,-1,-1,-2,-1,-1,-1,-1,-1,-1,-1,-1,-2,-1,-1,-1,0,0,0,-1,0,0,0,0,0,0,0,0,-1,-1,0,0,-1,-1,-1,-2,-1,-1,-1,-1,-1,-1,-1,-1,-2,-1,-1,-1,0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-2,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,-1,0,0,-1,-1,0,-1,-1,-1,-1,-1,0,-1,-1,0,-1,0,0,0,-1,-1,0,-1,0,0,-1,-1,0,-1,-1,0,-2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-1,-1,-1,0,0,-1,-1,-1,-1,-1,0,0,0,-2,-2,-2,-2,-2,-2,-1,-1,-2,-2,-2,-2,-2,0,-1,-1,-1,-1,-1,-1,-1,-1,0,0,-1,-1,-1,-1,-1,0,0,0,-2,-2,-2,-2,-2,-2,-1,-1,-2,-2,-2,-2,-2,0,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-1},
    {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,-1,-1,-1,-1,-1,-1,0,0,0,0,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,0,0,0,0,0,0,0,0,-1,0,0,0,-1,-1,0,-2,0,0,-1,-1,0,0,0,-1,-2,-1,-1,-1,0,0,0,-1,0,0,0,0,0,0,0,0,-1,0,0,0,-1,-1,0,-2,0,0,-1,-1,0,0,0,-1,-2,-1,-1,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,0,0,0,0,-1,-1,0,0,0,-1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,-1,-1,0,0,0,0,-1,-1,0,0,0,-1,0,0,0,0},
};

static inline const char *hd6309_name(int page, uint8_t op)
{
    switch ((page << 8) | op) {
    case 0x001: return "OIM";
    case 0x002: return "AIM";
    case 0x005: return "EIM";
    case 0x00B: return "TIM";
    case 0x014: return "SEXW";
    case 0x061: return "OIM";
    case 0x062: return "AIM";
    case 0x065: return "EIM";
    case 0x06B: return "TIM";
    case 0x071: return "OIM";
    case 0x072: return "AIM";
    case 0x075: return "EIM";
    case 0x07B: return "TIM";
    case 0x0CD: return "LDQ";
    case 0x130: return "ADDR";
    case 0x131: return "ADCR";
    case 0x132: return "SUBR";
    case 0x133: return "SBCR";
    case 0x134: return "ANDR";
    case 0x135: return "ORR";
    case 0x136: return "EORR";
    case 0x137: return "CMPR";
    case 0x138: return "PSHSW";
    case 0x139: return "PULSW";
    case 0x13A: return "PSHUW";
    case 0x13B: return "PULUW";
    case 0x140: return "NEGD";
    case 0x143: return "COMD";
    case 0x144: return "LSRD";
    case 0x146: return "RORD";
    case 0x147: return "ASRD";
    case 0x148: return "ASLD/LSLD";
    case 0x149: return "ROLD";
    case 0x14A: return "DECD";
    case 0x14C: return "INCD";
    case 0x14D: return "TSTD";
    case 0x14F: return "CLRD";
    case 0x153: return "COMW";
    case 0x154: return "LSRW";
    case 0x156: return "RORW";
    case 0x159: return "ROLW";
    case 0x15A: return "DECW";
    case 0x15C: return "INCW";
    case 0x15D: return "TSTW";
    case 0x15F: return "CLRW";
    case 0x180: return "SUBW";
    case 0x181: return "CMPW";
    case 0x182: return "SBCD";
    case 0x184: return "ANDD";
    case 0x185: return "BITD";
    case 0x186: return "LDW";
    case 0x188: return "EORD";
    case 0x189: return "ADCD";
    case 0x18A: return "ORD";
    case 0x18B: return "ADDW";
    case 0x190: return "SUBW";
    case 0x191: return "CMPW";
    case 0x192: return "SBCD";
    case 0x194: return "ANDD";
    case 0x195: return "BITD";
    case 0x196: return "LDW";
    case 0x197: return "STW";
    case 0x198: return "EORD";
    case 0x199: return "ADCD";
    case 0x19A: return "ORD";
    case 0x19B: return "ADDW";
    case 0x1A0: return "SUBW";
    case 0x1A1: return "CMPW";
    case 0x1A2: return "SBCD";
    case 0x1A4: return "ANDD";
    case 0x1A5: return "BITD";
    case 0x1A6: return "LDW";
    case 0x1A7: return "STW";
    case 0x1A8: return "EORD";
    case 0x1A9: return "ADCD";
    case 0x1AA: return "ORD";
    case 0x1AB: return "ADDW";
    case 0x1B0: return "SUBW";
    case 0x1B1: return "CMPW";
    case 0x1B2: return "SBCD";
    case 0x1B4: return "ANDD";
    case 0x1B5: return "BITD";
    case 0x1B6: return "LDW";
    case 0x1B7: return "STW";
    case 0x1B8: return "EORD";
    case 0x1B9: return "ADCD";
    case 0x1BA: return "ORD";
    case 0x1BB: return "ADDW";
    case 0x1DC: return "LDQ";
    case 0x1DD: return "STQ";
    case 0x1EC: return "LDQ";
    case 0x1ED: return "STQ";
    case 0x1FC: return "LDQ";
    case 0x1FD: return "STQ";
    case 0x230: return "BAND";
    case 0x231: return "BIAND";
    case 0x232: return "BOR";
    case 0x233: return "BIOR";
    case 0x234: return "BEOR";
    case 0x235: return "BIEOR";
    case 0x236: return "LDBT";
    case 0x237: return "STBT";
    case 0x238: return "TFM";
    case 0x239: return "TFM";
    case 0x23A: return "TFM";
    case 0x23B: return "TFM";
    case 0x23C: return "BITMD";
    case 0x23D: return "LDMD";
    case 0x243: return "COME";
    case 0x24A: return "DECE";
    case 0x24C: return "INCE";
    case 0x24D: return "TSTE";
    case 0x24F: return "CLRE";
    case 0x253: return "COMF";
    case 0x25A: return "DECF";
    case 0x25C: return "INCF";
    case 0x25D: return "TSTF";
    case 0x25F: return "CLRF";
    case 0x280: return "SUBE";
    case 0x281: return "CMPE";
    case 0x286: return "LDE";
    case 0x28B: return "ADDE";
    case 0x28D: return "DIVD";
    case 0x28E: return "DIVQ";
    case 0x28F: return "MULD";
    case 0x290: return "SUBE";
    case 0x291: return "CMPE";
    case 0x296: return "LDE";
    case 0x297: return "STE";
    case 0x29B: return "ADDE";
    case 0x29D: return "DIVD";
    case 0x29E: return "DIVQ";
    case 0x29F: return "MULD";
    case 0x2A0: return "SUBE";
    case 0x2A1: return "CMPE";
    case 0x2A6: return "LDE";
    case 0x2A7: return "STE";
    case 0x2AB: return "ADDE";
    case 0x2AD: return "DIVD";
    case 0x2AE: return "DIVQ";
    case 0x2AF: return "MULD";
    case 0x2B0: return "SUBE";
    case 0x2B1: return "CMPE";
    case 0x2B6: return "LDE";
    case 0x2B7: return "STE";
    case 0x2BB: return "ADDE";
    case 0x2BD: return "DIVD";
    case 0x2BE: return "DIVQ";
    case 0x2BF: return "MULD";
    case 0x2C0: return "SUBF";
    case 0x2C1: return "CMPF";
    case 0x2C6: return "LDF";
    case 0x2CB: return "ADDF";
    case 0x2D0: return "SUBF";
    case 0x2D1: return "CMPF";
    case 0x2D6: return "LDF";
    case 0x2D7: return "STF";
    case 0x2DB: return "ADDF";
    case 0x2E0: return "SUBF";
    case 0x2E1: return "CMPF";
    case 0x2E6: return "LDF";
    case 0x2E7: return "STF";
    case 0x2EB: return "ADDF";
    case 0x2F0: return "SUBF";
    case 0x2F1: return "CMPF";
    case 0x2F6: return "LDF";
    case 0x2F7: return "STF";
    case 0x2FB: return "ADDF";
    default: return "?";
    }
}

#endif
