#!/usr/bin/env python3
"""Lay out the demo's 1 MB ROM, and write what the assembler and the simulation load.

    mkdemorom.py layout BUILD      -> BUILD/assets.inc, BUILD/tables.inc
    mkdemorom.py image  BUILD      -> BUILD/rom.bin, BUILD/rom.hex

docs/machine.md 7.2: the boot ROM is two SST39SF040 at physical 2.0-3.0 MB, and
"the remaining ~1016 KB" after page 0 is what a program lives in. The map names
it in 8 KB pages: map entry high byte $01, low byte = page.

    page 0        software/boot/boot.bin - the boot ROM, unchanged
    pages 1-2     demo.bin, ORG $8000 - boot.asm maps them at blocks 4 and 5
                  and jumps to $8004 if $8000 holds the signature
    page 3 ...    the assets, each starting on a page boundary

Everything the 6809 needs to find an asset is an EQU in assets.inc: its first
page and its length. The two passes exist because the assembler needs the
layout and the image needs the assembler's output; the asset pages do not move
with the code, so the order is always layout, assemble, image.
"""
import os, re, sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", "..", ".."))
PAGE = 8192
ROMSIZE = 1 << 20
FIRST_ASSET_PAGE = 3

# (EQU prefix, file in BUILD, required)
ASSETS = [
    ("MOD", "demo.mod"),        # the module, verbatim - the loader parses it
    ("SCR", "script.bin"),      # the show's bytecode - tools/show.py
    ("GFX", "gfx.bin"),         # the 8x16 and 8x8 fonts
    ("ICN", "icons.bin"),       # the icons, a (page, offset) table first
    ("IMG", "image.bin"),       # parrot.img, 640 x 345, the desktop palette
    ("TIL", "tiles.bin"),       # 256 x 64 bytes: the tile set
    ("WLD", "world.bin"),       # world cell codes, 256-cell row stride
    ("SPR", "sprites.bin"),     # Link's frames, 32 x 16 bytes each
    ("FRM", "frames.bin"),      # the camera and Link, one record per frame
]


def layout(build):
    page = FIRST_ASSET_PAGE
    lines = ["* GENERATED by software/archive/demo/tools/mkdemorom.py layout - do not edit",
             "* Each asset starts on an 8 KB ROM page; map low byte = page, high = $01."]
    placed = []
    for tag, name in ASSETS:
        path = os.path.join(build, name)
        size = os.path.getsize(path)
        pages = (size + PAGE - 1) // PAGE
        lines.append(f"{tag}PAGE  EQU     {page}")
        lines.append(f"{tag}LEN2  EQU     {size >> 16}")
        lines.append(f"{tag}LEN   EQU     ${size & 0xFFFF:04X}           {size} bytes, {pages} pages")
        placed.append((tag, name, page, size))
        page += pages
    if page * PAGE > ROMSIZE:
        sys.exit(f"FAIL  the assets need {page} pages and the ROM has {ROMSIZE // PAGE}")
    open(os.path.join(build, "assets.inc"), "w").write("\n".join(lines) + "\n")
    open(os.path.join(build, "layout.txt"), "w").write(
        "".join(f"{t} {n} {p} {s}\n" for t, n, p, s in placed))
    tables(build)
    print(f"ok    {len(placed)} assets in pages {FIRST_ASSET_PAGE}..{page - 1}")


def tables(build):
    """ProTracker's period table, copied out of hardware/audio/refplayer/period_table.c
    rather than typed a second time - modplayer.md 5.4 says it is copied, never
    computed, and the same rule applies to copying it twice. And the tempo
    reload for every BPM, because 1773447 / bpm is a 24-by-8 division the FIRQ
    path has no business doing."""
    src = open(os.path.join(ROOT, "hardware/audio/refplayer/period_table.c")).read()
    body = src[src.index("mod_protracker_period_table"):]
    body = body[body.index("{") + 1:]
    body = re.sub(r"/\*.*?\*/", "", body, flags=re.S)   # "/* finetune +1 */" is not an entry
    nums = [int(v) for v in re.findall(r"\b\d+\b", body[:body.index("};")])]
    if len(nums) != 16 * 36:
        sys.exit(f"FAIL  period_table.c gave {len(nums)} numbers, want 576")
    out = ["* GENERATED by mkdemorom.py from hardware/audio/refplayer/period_table.c - do not edit"]
    out.append("ptab")
    for r in range(16):
        row = nums[r * 36:(r + 1) * 36]
        for k in range(0, 36, 12):
            out.append("        FDB     " + ",".join(str(v) for v in row[k:k + 12]))
    out.append("* TIMER reload = 1773447 / BPM (audio.md 8.2), BPM 0 read as 125 like mod_replay.c")
    out.append("tempotab")
    vals = [1773447 // (b if b else 125) for b in range(256)]
    vals = [v & 0xFFFF for v in vals]
    for k in range(0, 256, 8):
        out.append("        FDB     " + ",".join(f"${v:04X}" for v in vals[k:k + 8]))
    open(os.path.join(build, "tables.inc"), "w").write("\n".join(out) + "\n")


def image(build, code="demo.bin", out="rom"):
    rom = bytearray(b"\xFF" * ROMSIZE)
    boot = open(os.path.join(ROOT, "software/boot/boot.bin"), "rb").read()
    if len(boot) != PAGE:
        sys.exit(f"FAIL  boot.bin is {len(boot)} bytes, want {PAGE}")
    rom[0:PAGE] = boot
    demo = open(os.path.join(build, code), "rb").read()
    if len(demo) > 2 * PAGE:
        sys.exit(f"FAIL  demo.bin is {len(demo)} bytes; pages 1-2 hold {2 * PAGE}")
    rom[PAGE:PAGE + len(demo)] = demo
    for line in open(os.path.join(build, "layout.txt")):
        tag, name, page, size = line.split()
        data = open(os.path.join(build, name), "rb").read()
        if len(data) != int(size):
            sys.exit(f"FAIL  {name} changed size since layout ({len(data)} != {size}) - run layout again")
        rom[int(page) * PAGE:int(page) * PAGE + len(data)] = data
    open(os.path.join(build, out + ".bin"), "wb").write(rom)
    with open(os.path.join(build, out + ".hex"), "w") as f:
        for b in rom:
            f.write(f"{b:02x}\n")
    print(f"ok    {out}.bin: boot page 0, {code} {len(demo)} bytes in pages 1-2, assets from page {FIRST_ASSET_PAGE}")


if __name__ == "__main__":
    {"layout": layout, "image": image}[sys.argv[1]](*sys.argv[2:])
