#!/usr/bin/env python3
"""mklegs.py A CX B CY [emit] - v3drag's figure-8, as runs of equal steps.

    STEP=8 python3 video3/bench/mklegs.py 186 194 175 195 emit

⭐ EIGHT-WAY, NOT FOUR.  The copy engine moves a rectangle from anywhere to
anywhere - CP.DX and CP.DY are independent - so a diagonal step is one copy
exactly like an axis-aligned one, and there was never a reason for the path
to climb in stairs.  Each run is `count, dx, dy` with dx and dy signed and in
{-STEP, 0, +STEP}.

⚠ What a diagonal step costs is in Vacate, not in the move: the region the
window no longer covers is an L rather than a strip, so it is two rectangles
instead of one (plus the tab's own edge, which is the same story again).
"""
import math
import os
import sys

STEP = int(os.environ.get("STEP", 8))
WINW, WINH = 250, 99
HOME = (96, 373)


def path(A, CX, B, CY, n=2000):
    """The lemniscate, from the window's home and back to it."""
    return ([HOME] +
            [(CX + A * math.sin(2 * math.pi * i / n),
              CY + B * math.sin(4 * math.pi * i / n)) for i in range(n + 1)] +
            [HOME])


def runs(pts):
    """Quantise to the STEP grid and gather equal (dx, dy) steps into runs.
    ⭐ A step moves in BOTH axes when the curve does, which is what makes the
    figure-8 smooth instead of a staircase."""
    q = lambda v: round(v / STEP) * STEP
    cur = (q(pts[0][0]), q(pts[0][1]))
    out, xs, ys = [], [cur[0]], [cur[1]]
    for x, y in pts[1:]:
        gx, gy = q(x), q(y)
        while cur != (gx, gy):
            dx = STEP if gx > cur[0] else -STEP if gx < cur[0] else 0
            dy = STEP if gy > cur[1] else -STEP if gy < cur[1] else 0
            cur = (cur[0] + dx, cur[1] + dy)
            if out and out[-1][0] == (dx, dy) and out[-1][1] < 255:
                out[-1][1] += 1
            else:
                out.append([(dx, dy), 1])
            xs.append(cur[0])
            ys.append(cur[1])
    return out, xs, ys


def main():
    A, CX, B, CY = (int(v) for v in sys.argv[1:5])
    r, xs, ys = runs(path(A, CX, B, CY))
    n = sum(k for _, k in r)
    diag = sum(k for (dx, dy), k in r if dx and dy)
    sys.stderr.write("A=%d CX=%d B=%d CY=%d -> %d steps (%d diagonal, %d%%), %d runs\n"
                     % (A, CX, B, CY, n, diag, 100 * diag // n, len(r)))
    sys.stderr.write("   x %d..%d (right edge %d)   y %d..%d (bottom %d)\n"
                     % (min(xs), max(xs), max(xs) + WINW,
                        min(ys), max(ys), max(ys) + WINH))
    if len(sys.argv) <= 5:
        return
    print("* ⭐ A FIGURE-8, as runs of equal steps: count, dx, dy - EIGHT-WAY,")
    print("* so the window moves diagonally where the curve does instead of")
    print("* climbing in stairs.  x = %d + %d sin t, y = %d + %d sin 2t on a"
          % (CX, A, CY, B))
    print("* %d-pixel grid, from the window's home at (%d, %d) and back."
          % (STEP, HOME[0], HOME[1]))
    print("* %d steps, %d of them diagonal.  Generated by video3/bench/mklegs.py."
          % (n, diag))
    print("*")
    print("* ⚠ x reaches %d, so the right edge reaches %d and the window stays ON"
          % (max(xs), max(xs) + WINW))
    print("* SCREEN - which is what leaves the off-screen margin free for the")
    print("* backing store (SWX, SBX).  They cannot both have it.")
    print("* ⚠ y reaches %d, so the bottom reaches %d, clear of the staging rows"
          % (max(ys), max(ys) + WINH))
    print("* vidcpy3.asm uses from 480.")
    print("Legs                equ       *")
    for (dx, dy), k in r:
        print("                    fcb       %d,%d,%d" % (k, dx & 255, dy & 255))
    print("                    fcb       0         the end: a count of none")


if __name__ == "__main__":
    main()
