import math, sys
STEP=int(__import__("os").environ.get("STEP",8)); WINW,WINH=250,99
A,CX,B,CY = int(sys.argv[1]),int(sys.argv[2]),int(sys.argv[3]),int(sys.argv[4])
HOME=(96,373)
pts=[HOME]+[(CX+A*math.sin(2*math.pi*i/2000), CY+B*math.sin(4*math.pi*i/2000))
            for i in range(2001)]+[HOME]
cur=(round(pts[0][0]/STEP)*STEP, round(pts[0][1]/STEP)*STEP)
runs=[]; xs=[];ys=[]
for x,y in pts[1:]:
    gx,gy=round(x/STEP)*STEP, round(y/STEP)*STEP
    while cur!=(gx,gy):
        dx,dy=gx-cur[0], gy-cur[1]
        if abs(dx)>=abs(dy) and dx!=0:
            d=0 if dx>0 else 2; cur=(cur[0]+(STEP if dx>0 else -STEP), cur[1])
        else:
            d=1 if dy>0 else 3; cur=(cur[0], cur[1]+(STEP if dy>0 else -STEP))
        if runs and runs[-1][0]==d and runs[-1][1]<255: runs[-1][1]+=1
        else: runs.append([d,1])
        xs.append(cur[0]); ys.append(cur[1])
n=sum(k for _,k in runs)
sys.stderr.write("A=%d CX=%d B=%d CY=%d -> %d steps ~%.0f s  x %d..%d (edge %d) y %d..%d (bottom %d)\n"
                 % (A,CX,B,CY,n,n*0.082,min(xs),max(xs),max(xs)+WINW,min(ys),max(ys),max(ys)+WINH))
if len(sys.argv)>5:
    print("* ⭐ A FIGURE-8, as runs of single-axis steps: count, direction.")
    print("* x = %d + %d sin t, y = %d + %d sin 2t, quantised to %d-pixel steps," % (CX,A,CY,B,STEP))
    print("* with a run to it from the window's home at (%d, %d) and a run back." % HOME)
    print("* %d steps.  Generated by video3/bench/mklegs.py." % n)
    print("*")
    print("* ⚠ x reaches %d, so the window's right edge reaches %d - %d columns" % (max(xs),max(xs)+WINW,max(xs)+WINW-640))
    print("* PAST THE DISPLAY, into the off-screen margin (plan.md §4), and it comes")
    print("* back with its pixels intact.  CP.DX + CP.W must stay under 1024: %d." % (max(xs)+WINW))
    print("* ⚠ y reaches %d, so the bottom reaches %d, clear of the staging rows" % (max(ys),max(ys)+WINH))
    print("* vidcpy3.asm uses from 480.")
    print("Legs                equ       *")
    for d,k in runs: print("                    fcb       %d,%d" % (k,d))
    print("                    fcb       $FF")
