#!/usr/bin/env python3
"""mkpcs.py - generate `pcs`'s data from Bill Budge's original sources.

    python3 video3/bench/mkpcs.py [CMDSDIR]

Writes, beside this script:

    pcs.pal      512 bytes, big-endian RGB565 (kept as a file so the palette
                 can be eyeballed; pcsdat.asm also carries it inline)
    pcs.png      a 1:1 preview of the artwork and the screen layout
    pcsdat.asm   -> CMDSDIR (default ../nitros9/level2/arm6309/cmds)

⭐ THE POINT OF THIS SCRIPT IS THAT IT INVENTS ALMOST NOTHING.  The port claims
to *be* Pinball Construction Set, not to resemble it, and the whole of that
claim rests on the artwork, the 43 part templates, the four World tuning
tables, the seven cosine tables, the slope quantiser, the scoring tables, the
sound effects and the proportional font all coming out of `reference/pcs/`
rather than out of somebody's judgement.  What this script does add is:

  - the PALETTE (pcspal.py), because the original had two colours;
  - the 2x DOUBLING, because the screen is 640x480 and the original 320x192;
  - the 160 x 240 world, 48 rows taller than the Atari's 160 x 192, which is
    the one gameplay-visible decision in the port (video3/docs/pcs.md 3).

Everything else is transcription, and `pcsasm.py`/`pcsparts.py` check their own
transcription against a second statement of the same fact wherever the sources
make one.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import pcsasm as A                                             # noqa: E402
import pcsparts as P                                           # noqa: E402
import pcsobj as O                                            # noqa: E402
import pcspal                                                  # noqa: E402

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))

# ---------------------------------------------------------------- geometry --
# ⭐ THE WORLD IS THE ORIGINAL'S, AND ONLY THE RENDERER IS DOUBLED.  Every
# coordinate in the database, the file format and the simulator is a single
# byte in these units, exactly as on the Atari; SCALE applies on the way to the
# card and nowhere else.  video3/docs/pcs.md 1 is why.
SCALE = 2

TW, TH = 160, 240       # the table.  ⚠ 240 and not the Atari's 192 - see below
KW, KH = 160, 192       # the kit panel, unchanged

# The screen, in card pixels: VMODE 11, 640 x 480, 8bpp, 1024-byte stride.
SCRW, SCRH = 640, 480
TABLE_X, TABLE_Y = 0, 0                     # 320 x 480
KIT_X, KIT_Y = TW * SCALE, 0                # 320 x 384
STATUS_Y = KH * SCALE                       # 320 x 96, under the kit panel

# ⚠ 240 ROWS IS THE PORT'S ONE GAMEPLAY CHANGE, and it is the user's.  At 2x a
# 160 x 240 table is exactly 320 x 480 - the full screen height - and the kit
# panel's own 192 rows double to 384, leaving 96 rows beneath it for a
# permanent score strip.  The Atari had no status area in the editor at all and
# had to BLANK THE PARTS BIN during play to print BONUS/PLAYER into it
# (RUN.s:1958-1985).  So the taller table costs nothing and fixes that.
#
# ⛔ What it touches: PBDX[], PTLO/PTHI[] and the scanline tables grow from 192
# to 240 entries, and the drain test LASTY moves.  Nothing widens - y is still
# one byte.  A table authored for a 192-row world loads into the top of a
# 240-row one, which is what the file's version byte is for.
ATARI_TH = 192


def dbl_bits(b):
    """One byte of 1bpp art -> two bytes, every bit doubled.

    ⭐ This is the whole of the 2x renderer's cost, and it is paid once here at
    build time.  On the card a doubled byte is one `WM.Mask` or `WM.Sprite`
    store = 16 pixels, at any x, with no shifting - which is why the original's
    XOFFDRAW, MASKS and the 6,144-byte GPAK.OBJ table all delete (pcs.md 4)."""
    hi = lo = 0
    for k in range(4):
        if b & (0x80 >> k):
            hi |= 0xC0 >> (2 * k)
        if b & (0x08 >> k):
            lo |= 0xC0 >> (2 * k)
    return hi, lo


def double(bits, h, w):
    """An h x w 1bpp bitmap -> 2h x 2w, each row emitted twice."""
    out = bytearray()
    for r in range(h):
        row = bytearray()
        for c in range(w):
            row += bytes(dbl_bits(bits[r * w + c]))
        out += row
        out += row
    return bytes(out), h * 2, w * 2


# ------------------------------------------------------------------- tables --
def physics_tables():
    """Every constant the simulator runs on, verbatim from RUN.s and PPAK.s.

    ⛔ Nothing here is recomputed.  The seven cosine tables could be generated
    from `round(v * 4 * cos a)` and they are NOT, because the gate in
    checkpcs.py compares the 6809's ball trajectory against a Python model of
    the same arithmetic: a table regenerated by one and read by the other is
    the check answering its own question (CLAUDE.md's HOSTMAP trap)."""
    t = {}
    for name in ('C05625', 'C1125', 'C225', 'C45', 'C675', 'C7875', 'C84375'):
        t[name] = A.block('RUN.s', name)
    for name in ('GRAVTBL', 'TIMETBL', 'KICKTBL', 'ELASTLO', 'ELASTHI',
                 'SCORETBL', 'SOUNDTBL', 'BONUSTBL', 'FTTA', 'FLPVCTR',
                 'FXDVERT', 'FXHEIGHT', 'FXLEN', 'FDDVERT', 'FHEIGHT',
                 'DHITTBL', 'EFFECTS', 'NOTES'):
        t[name] = A.block('RUN.s', name)
    for name in ('DXCODESA', 'DXCODESB'):
        t[name] = A.block('PPAK.s', name)
    return t


def check_tables(t):
    """Cross-checks that cost nothing and would have caught a misread."""
    bad = []
    for n in ('C05625', 'C1125', 'C225', 'C45', 'C675', 'C7875', 'C84375'):
        if len(t[n]) != 64:
            bad.append('%s is %d bytes, not 64' % (n, len(t[n])))
    for n in ('GRAVTBL', 'TIMETBL', 'KICKTBL', 'ELASTLO', 'ELASTHI'):
        if len(t[n]) != 8:
            bad.append('%s is %d bytes, not 8 (one per World slider position)'
                       % (n, len(t[n])))
    for n in ('DXCODESA', 'DXCODESB'):
        if len(t[n]) != 16:
            bad.append('%s is %d bytes, not 16' % (n, len(t[n])))
    # ⭐ EFFECTS and NOTES appear in BOTH RUN.s and WIRE.s.  They must agree --
    # a free check that the block reader is not running past a table's end.
    for n in ('EFFECTS', 'NOTES'):
        if t[n] != A.block('WIRE.s', n):
            bad.append('%s differs between RUN.s and WIRE.s' % n)
    # ⭐ ELASTLO/ELASTHI are ADDRESSES of cosine tables, and every one must be a
    # table this script also carries -- which is what proves the elasticity
    # curve is the cosine curve and not an eighth table nobody noticed.
    syms = A.equs('RUN.s')
    cos = {}
    for n in ('C05625', 'C1125', 'C225', 'C45', 'C675', 'C7875', 'C84375'):
        if n in syms:
            cos[syms[n]] = n
    if cos:
        for i, (lo, hi) in enumerate(zip(t['ELASTLO'], t['ELASTHI'])):
            addr = lo | (hi << 8)
            if addr not in cos:
                bad.append('ELAST[%d] = $%04X is not the base of any cosine table'
                           % (i, addr))
    return bad


def rects():
    """The screen rects, decoded.  GETRECT (CDRAW.s:276) reads six bytes:
    TOP, LFTDIV8, LFTMOD8, height, width/8, width mod 8 -- so a rect covers
    x in [ld*8+lm, +w] and y in [top, top+h], both inclusive.

    ⚠ The bin-box labels COLLIDE with the bitmap names: EDIT.s's LAUNCHERB is a
    rectangle and RUN.s's LAUNCHERB is artwork.  Different files, and this
    reads each from the right one."""
    out = {}
    for name in ('TABLEB', 'KITB', 'TOOLB'):
        b = A.block('EDIT.s', name)
        top, ld, lm, h, wd, wm = b[:6]
        out[name] = (ld * 8 + lm, top, wd * 8 + wm, h)
    return out


def bin_boxes():
    """The 43 parts-bin rectangles, in part order, as (x, y, w, h) in the
    ORIGINAL's screen coordinates (x 160..319)."""
    names = [s.lstrip('<>') for s in A.block_syms('EDIT.s', 'BOXLO')]
    hi = [s.lstrip('<>') for s in A.block_syms('EDIT.s', 'BOXHI')]
    if names != hi:
        raise ValueError('BOXLO and BOXHI disagree')
    out = []
    for n in names:
        b = A.block('EDIT.s', n)
        top, ld, lm, h, wd, wm = b[:6]
        out.append((ld * 8 + lm, top, wd * 8 + wm, h))
    return out


def font():
    """The 36-glyph proportional mini-font, doubled.

    CDRAW.s:853 -- 7 rows x 1 byte a glyph, stride 7 (`PRCHAR` computes
    c*8 - c); codes 0-9 are '0'-'9', 10-35 'A'-'Z', 36 space.  CWIDTH gives a
    per-glyph advance of 4-7 pixels, so it is genuinely proportional.
    ⭐ Through `WM.Mask` a doubled glyph is 2 stores a row, 28 stores a glyph --
    against the ROM toolbox's 13.58 ms floor for ONE Text call
    (docs/proportional-font.md 1.3), which is why pcs carries its own."""
    f = A.block('CDRAW.s', 'FONT')
    w = A.block('CDRAW.s', 'CWIDTH')
    if len(f) != 36 * 7:
        raise ValueError('FONT is %d bytes, not 36 glyphs of 7 rows' % len(f))
    if len(w) != 37:
        raise ValueError('CWIDTH is %d bytes, not 37' % len(w))
    glyphs = []
    for g in range(36):
        bits, h, bw = double(f[g * 7:g * 7 + 7], 7, 1)
        glyphs.append(bits)
    return glyphs, [x * SCALE for x in w]


# ---------------------------------------------------------------- the art --
def art():
    """Every library part's every frame, doubled, packed into one blob.

    Returns (blob, frames, index) where `frames` is one (off, h, w, dy) tuple
    per frame in part order and `index` is one (first, count) per part.
    ⚠ Sizes and dy are in CARD PIXELS (already doubled); the database stays in
    the original's units.
    """
    blob = bytearray()
    frames, index = [], []
    for p in P.parts():
        if not p.lib:
            index.append((0, 0))
            continue
        first = len(frames)
        for (h, w, bits, dy) in p.frames():
            db, dh, dw = double(bits, h, w)
            frames.append((len(blob), dh, dw, dy * SCALE))
            blob += db
        index.append((first, len(frames) - first))
    return bytes(blob), frames, index


# --------------------------------------------------------- the test table --
def place(name, tx, ty, fillcolor=None):
    """⭐ ONE OF BUDGE'S 43 TEMPLATES, MOVED FROM THE PARTS BIN ONTO THE TABLE.

    The record is the template's own - the same bytes EDIT.s's ADDOBJ copies -
    translated so its bounding box's top-left corner lands at (tx, ty).
    ⚠ L[2] and L[3], where the ART sits, move with the vertices because they
    are the same coordinate system; that is why the port keeps one `px` where
    the Atari had HDIV8 and HMOD8 (pcs.md 4).

    ⛔ AND L[10] IS A PART TYPE ID WHERE THE 6502 HAD THREE ADDRESSES.  A saved
    table cannot carry 6502 vectors across a change of machine, so the type is
    stored and the vectors are rebuilt on load (pcs.md 5b).
    """
    import pcsobj
    import pcsparts as T
    tm = None
    for t in T.parts():
        if t.name == name:
            tm = t
            break
    if tm is None:
        raise KeyError('no template named %s' % name)
    kind = pcsobj.kind_of(tm)
    if kind is None:
        raise KeyError('%s\'s procs are step 3b-ii' % name)

    dx, dy = tx - min(tm.x), ty - min(tm.y)
    xs = [v + dx for v in tm.x]
    ys = [v + dy for v in tm.y]
    if min(xs) < 0 or max(xs) >= TW or min(ys) < 0 or max(ys) >= TH:
        raise ValueError('%s at (%d, %d) does not fit the table' % (name, tx, ty))

    L = bytearray(pcsobj.LREC)
    L[pcsobj.L_VERT] = tm.vert + dy
    L[pcsobj.L_PX] = tm.px + dx
    L[pcsobj.L_HEIGHT] = tm.height
    L[pcsobj.L_WIDTH] = tm.width
    L[pcsobj.L_STATE] = tm.time                 # lifted into TIME[] by PLAY
    L[pcsobj.L_SCORE] = tm.score_snd
    L[pcsobj.L_TYPE] = pcsobj.TYPEID[kind]

    import pcspak as K
    o = K.Obj(K.LIBOBJ, tm.fillcolor if fillcolor is None else fillcolor,
              xs, ys, L)
    if not o.align():
        raise ValueError('%s is degenerate' % name)
    return o


def test_table():
    """⭐ THE TABLE STEP 2's GATE IS BUILT ON, defined ONCE and used twice.

    `pcs` mode 0 copies the serialised form below into its database and runs
    the scan converter over it; `checkpcs.py` builds the same objects through
    pcspak.py and compares.  Defining it here rather than in either of them is
    what stops the two drifting - the same reason checkscroll.py imports
    mkscroll rather than restating the world.

    Four objects, chosen so that every arm of the converter is exercised:

      0  the backdrop      a B-POLYGON, so the complement path and the
                           "records are the open area" rule
      1  a wide sloped bar both edges sloping, so DIVIDE and the midpoint
                           rounding
      2  a concave U       two spans a scanline, and horizontal edges, which
                           is what PROCESSVERTEX's skip is for
      3  an unfilled wall  fillcolor 0: solid, and drawn as nothing
    """
    import pcspak as K
    objs = [
        K.Obj(K.BPOLY, PALTABLE, [6, 154, 154, 6], [4, 4, 232, 232]),
        K.Obj(K.POLY, PALBAR, [20, 140, 120, 40], [30, 46, 70, 54]),
        K.Obj(K.POLY, PALU, [30, 60, 60, 100, 100, 130, 130, 30],
              [96, 96, 150, 150, 96, 96, 178, 178]),
        K.Obj(K.POLY, 0, [70, 96, 96, 70], [190, 190, 214, 214]),
        # ⭐ 4  A SLIVER, and it is here for one line of the converter.  Both
        # edges leave the apex at the SAME x, so the active list's tie-break
        # fires - and their slopes differ only BELOW THE POINT, so an insert
        # that compares the integer parts alone orders them wrongly and the
        # span's two ends are swapped for as long as they run together.  The
        # Apple II source made that visible: ADDSTARTS6 subtracts ADXFRACT
        # before ADXCOEFF and guards the sign test with BVC.
        K.Obj(K.POLY, PALSLIV, [100, 59, 62], [60, 100, 100]),
    ]
    # ⭐⭐ AND SEVEN OF BUDGE'S OWN PARTS, which is what makes this a gate on
    # the SIMULATOR and not only on the converter.  Each is here for a
    # different arm of the object system, and between them they reach every
    # proc step 3b implements:
    #
    #   SPIN    the spinner      - a HIT that scores and does NOT deflect, and
    #                              a RUN proc that re-arms itself off L[16]
    #   ROLL1   a rollover       - PUTSP2: score with the carry CLEAR
    #   GATE1   the one-way gate - the BMOVE read that is the whole part
    #   TARG1   a target         - FLASHRUN, and a bounce that scores
    #   KICK1   a knocker        - ⛔ not a surface at all: it SETS BDY
    #   BMP3    the bumper       - TSET, the kick with NO elasticity, and
    #                              BUMPRUN's two-frame animation
    #   BALL    the ball         - ⭐ an object like any other, which is what
    #                              makes multiball a matter of cloning 23 bytes
    #
    # ⛔ AND THE BALL'S OWN HOME POLYGON IS IN THE DATABASE AND IS NOT SOLID.
    # That is what NULLBOUNCE is FOR: a five-pixel square sits wherever the
    # editor left the ball part, the collision walker finds it like any other
    # span, and its HIT proc answers `CLC / RTS`.  A port that quietly dropped
    # the ball from the display list would pass every picture test and change
    # the object numbering underneath the saved tables.
    #
    # ⚠ THE POSITIONS ARE CHOSEN, NOT ARBITRARY.  They are a channel down the
    # right of the table, because a ball dropped anywhere else lands on the
    # sloped bar and rolls for six hundred frames without meeting anything; and
    # the knocker sits BESIDE the bumper because the ball never gets below
    # them.  ⚠ No scanline may carry more than four spans - PPAK.s:568's limit
    # is part of what the construction set IS (pcs.md 5), so the bench's own
    # table has to live inside it.
    objs += [
        place('SPIN', 144, 105),
        place('ROLL1', 146, 125),
        place('GATE1', 144, 150),
        place('TARG1', 146, 175),
        place('KICK1', 139, 196),
        place('BMP3', 145, 196),
        place('BALL', BALL[0], BALL[1]),
    ]
    for o in objs:
        if not o.align():
            raise ValueError('a test object is degenerate')
    return objs


PALTABLE = pcspal.UI_TABLE
PALBAR = pcspal.PAINT0 + 3          # red
PALU = pcspal.PAINT0 + 5            # yellow
PALSLIV = pcspal.PAINT0 + 7         # cyan

# ⭐ The ball the bench serves, and the World it serves it into.  Defined once
# and used twice: `pcs 4` starts from these and checkpcs.py's model does too.
# ⭐ The ball's HOME, which is all it is now: INITBALL (RUN.s:626) puts the
# ball on its own template's top-left vertex with BDX 0 and BDY $FF, so the
# only thing the bench chooses is WHERE the part was placed.  ⚠ 145 is in the
# right-hand channel, clear of the sloped bar.
BALL = (145, 10)                    # x, y
WSET = (5, 3, 3, 4)                 # gravity, speed, kick, elasticity


def serialise(objs):
    """The objects as `pbdata` holds them: the count, the record lengths, then
    the records.  ⭐ pbdata[0] doubles as the count AND as the offset from
    pbdata+1 to the first record, which is why GETOBJ needs no index."""
    recs = []
    for o in objs:
        recs.append(bytes([o.objid, o.fillcolor, o.n]) + bytes(o.x) + bytes(o.y)
                    + bytes(o.L))
    out = bytearray([len(recs)])
    out += bytes(len(r) for r in recs)
    for r in recs:
        out += r
    return bytes(out)


# ------------------------------------------------------------ the emitter --
def _fcb(out, data, per=16, indent=' ' * 20):
    for i in range(0, len(data), per):
        out.append('%sfcb       %s' % (indent, ','.join('$%02X' % b for b in data[i:i + per])))


def emit(path):
    t = physics_tables()
    bad = check_tables(t) + P.check()
    if bad:
        for b in bad:
            print('FAIL', b)
        sys.exit(1)

    blob, frames, index = art()
    glyphs, cw = font()
    boxes = bin_boxes()
    r = rects()
    parts = P.parts()

    o = []
    w = o.append
    w('* pcsdat.asm - GENERATED by arm6309 video3/bench/mkpcs.py.  Do not edit.')
    w('*')
    w('* The artwork, the part templates and every physics constant of Bill')
    w("* Budge's Pinball Construction Set (Atari 800, 1983), read out of")
    w('* reference/pcs/ - which carries his MIT licence and this notice:')
    w('*')
    w('*   Copyright (C) 1982 Bill Budge.  Permission is hereby granted, free')
    w('*   of charge, to any person obtaining a copy of this software and')
    w('*   associated documentation files (the "Software"), to deal in the')
    w('*   Software without restriction...  The above copyright notice and')
    w('*   this permission notice shall be included in all copies or')
    w('*   substantial portions of the Software.')
    w('*')
    w('* ⚠ THE DATA IS FIRST, as pinball\'s and stardew\'s are and for the same')
    w('* reason: the geometry below is used in 8-bit immediates and a forward')
    w('* reference is a phasing error waiting to happen.')
    w('')
    w('* ══════════════════ GEOMETRY ══════════════════════════════════════')
    w('* ⭐ THE WORLD IS THE ORIGINAL\'S; ONLY THE RENDERER IS DOUBLED.  Every')
    w('* coordinate in the database and the file format is one byte in these')
    w('* units, exactly as on the Atari (video3/docs/pcs.md 1).')
    w('PC.Scale            equ       %d         card pixels per world unit' % SCALE)
    w('PC.TW               equ       %d       the table, in world units' % TW)
    w('PC.TH               equ       %d       ⚠ 240, not the Atari\'s %d' % (TH, ATARI_TH))
    w('PC.ATH              equ       %d       ...which is what a v1 file holds' % ATARI_TH)
    w('PC.KW               equ       %d       the kit panel, unchanged' % KW)
    w('PC.KH               equ       %d' % KH)
    w('')
    w('PC.ScrW             equ       %d       VMODE 11, 8bpp, 1024-byte stride' % SCRW)
    w('PC.ScrH             equ       %d' % SCRH)
    w('PC.TabX             equ       %d' % (TABLE_X * 1))
    w('PC.TabY             equ       %d' % TABLE_Y)
    w('PC.KitX             equ       %d       the kit panel, in card pixels' % KIT_X)
    w('PC.KitY             equ       %d' % KIT_Y)
    w('PC.StatY            equ       %d       the score strip the Atari had no room for' % STATUS_Y)
    w('')
    w('* The original\'s own rects (EDIT.s), in ITS coordinates - x 0..319.')
    for k, (x, y, ww, hh) in sorted(r.items()):
        w('* %-8s x %3d..%3d  y %3d..%3d' % (k, x, x + ww, y, y + hh))
    w('')
    w('* ══════════════════ THE BALL THE BENCH RUNS ═══════════════════════')
    w("* ⭐ Where the ball PART is placed, which is all the bench chooses:")
    w('* INITBALL (RUN.s:626) puts the ball on its own template\'s top-left')
    w('* vertex with BDX 0 and BDY $FF.  Defined here so checkpcs.py starts its')
    w('* model from exactly the same bytes.')
    w('PC.BallX            equ       %d' % BALL[0])
    w('PC.BallY            equ       %d' % BALL[1])
    w('PC.WGrav            equ       %d         the World sliders' % WSET[0])
    w('PC.WTime            equ       %d' % WSET[1])
    w('PC.WKick            equ       %d' % WSET[2])
    w('PC.WElast           equ       %d' % WSET[3])
    w('')
    w('* ══════════════════ LIMITS ════════════════════════════════════════')
    w('* ⚠ THE ORIGINAL\'S, KEPT.  They are part of what the construction set')
    w('* IS - raising them would change which tables exist.')
    w('PC.MaxObj           equ       127       PBDATA[0], EDIT.s ADDOBJ')
    w('PC.MaxVtx           equ       63        EDIT.s PASTEPOINT')
    w('PC.MinVtx           equ       3         EDIT.s CUTPOINT')
    w('PC.MaxEdge          equ       8         PPAK.s:568 - 4 spans a scanline')
    w('PC.SpanHead         equ       32        bytes of span-DB headroom, or roll back')
    w('PC.Gates            equ       6         LOGIC[24], 6 x 4')
    w('')
    w('* ══════════════════ THE LIBRARY TAIL ═════════════════════════════')
    w('* ⭐ L, the sixteen bytes after the two vertex arrays (GETINFO,')
    w('* PPAK.s:209).  ⚠ THE OFFSETS ARE THE ORIGINAL\'S and stay so: every')
    w('* part proc indexes them with a literal, and the ball\'s record is')
    w('* L[0..22] entire.')
    for nm, off in (('Frame', O.L_FRAME), ('Vert', O.L_VERT), ('PX', O.L_PX),
                    ('Hgt', O.L_HEIGHT), ('Wid', O.L_WIDTH),
                    ('Strid', O.L_STRIDE), ('State', O.L_STATE),
                    ('Score', O.L_SCORE), ('Type', O.L_TYPE),
                    ('BStat', O.L_BSTAT), ('X1', O.L_X1), ('Y1', O.L_Y1),
                    ('BDX', O.L_BDX), ('BDY', O.L_BDY),
                    ('BXAcc', O.L_BXACC), ('BYAcc', O.L_BYACC)):
        w('LB.%-16s equ       %d' % (nm, off))
    w('LB.Size             equ       %d' % O.LREC)
    w('')
    w('* ⛔ THE PART TYPE, WHERE THE 6502 HAD THREE ADDRESSES.  A saved table')
    w('* cannot carry 6502 vectors across a change of machine, so L[10] is a')
    w('* type id and the vectors are rebuilt on load (pcs.md 5b).')
    w('* ⛔ THE LIST IS APPEND-ONLY: inserting a type renumbers every table ever')
    w('* written, which is mktbox.py\'s ICON_NAMES rule for the same reason.')
    for i, nm in enumerate(O.TYPES):
        w('PT.%-16s equ       %d' % (nm.capitalize(), i))
    w('PT.Count            equ       %d' % len(O.TYPES))
    w('')
    w('* ⚠ SCORETBL, SOUNDTBL, EFFECTS and NOTES ARE EMITTED BY physics_tables()')
    w('* BELOW, as PCSCORETBL, PCSOUNDTBL, PCEFFECTS and PCNOTES.  They were')
    w('* briefly emitted here as well, and lwasm - which is case-insensitive -')
    w('* caught the collision: two copies of a generated table is the same')
    w('* defect as a constant agreed by number rather than by symbol.')
    w('')
    w('* Object kinds (PPAK.s), unchanged.')
    w('PC.Poly             equ       1')
    w('PC.BPoly            equ       2         the complement fill - ALWAYS object 0')
    w('PC.LibObj           equ       3')
    w('')
    w('* ══════════════════ PALETTE ═══════════════════════════════════════')
    w('* ⛔ INDEX 0 IS UNFILLED, AND UNFILLED IS NOT INVISIBLE: the polygon')
    w('* still collides (PPAK.s:269-271).  It is also video3\'s transparent')
    w('* key, so the two meanings agree instead of fighting.')
    for name, idx in sorted(pcspal.NAMES.items(), key=lambda kv: kv[1]):
        w('PCC.%-15s equ       %d' % (name.capitalize(), idx))
    w('PCC.Paint0          equ       %d         the brush strip, %d entries'
      % (pcspal.PAINT0, pcspal.NPAINT))
    w('PCC.NPaint          equ       %d' % pcspal.NPAINT)
    w('')
    w('* The Atari stored FILLCOLOR as a DITHER MASK; this is the translation')
    w('* for a table imported from a .PB file.  ($00 unfilled, $FF white,')
    w('* $55 green, $AA violet - the Apple II hi-res patterns.)')
    for k, v in sorted(pcspal.FROM_ATARI.items()):
        w('*   $%02X -> %d' % (k, v))
    w('')
    w('PCPal               equ       *         512 bytes, big-endian RGB565')
    _fcb(o, pcspal.blob())
    w('')
    w('* ══════════════════ THE FONT ══════════════════════════════════════')
    w('* CDRAW.s:853 - 36 glyphs, 7 rows x 1 byte, proportional (CWIDTH).')
    w('* Doubled: %d rows x %d bytes a glyph, %d pixels wide.'
      % (7 * SCALE, SCALE, 8 * SCALE))
    w('PC.Glyphs           equ       36')
    w('PC.GlyphH           equ       %d' % (7 * SCALE))
    w('PC.GlyphW           equ       %d         bytes a row' % SCALE)
    w('PC.GlyphSz          equ       %d' % (7 * SCALE * SCALE))
    w('')
    w('PCFntW              equ       *         advance in card pixels, 37 entries')
    _fcb(o, cw)
    w('')
    w('PCFont              equ       *')
    for g, bits in enumerate(glyphs):
        ch = '0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ'[g]
        w('* %s' % ch)
        _fcb(o, bits)
    w('')
    w('* ══════════════════ THE ARTWORK ═══════════════════════════════════')
    w('* BITMAPS.OBJ, cut by the EQU chain at RUN.s:100-118, with every XOR')
    w('* animation accumulated back into standalone pictures and doubled.')
    w('* ⛔ The frames ARE deltas in the original; a machine with no')
    w('* read-modify-write needs pictures (pcsparts.py says how).')
    w('PC.NPart            equ       %d' % len(parts))
    w('PC.NFrame           equ       %d' % len(frames))
    w('')
    w('* One (first frame, count) a part, in the parts-bin order.')
    w('PCPIdx              equ       *')
    for i, (first, n) in enumerate(index):
        w('                    fcb       %-4d,%-3d    %2d %s'
          % (first, n, i, parts[i].name))
    w('')
    w('* One (offset, height, width, dy) a frame.  dy is the flipper\'s moving')
    w('* top edge (FXDVERT), in card pixels; 0 for everything else.')
    w('PCFrm               equ       *')
    fi = 0
    for i, p in enumerate(parts):
        if not p.lib:
            continue
        for k in range(index[i][1]):
            off, h, ww, dy = frames[fi]
            w('                    fdb       %-6d' % off +
              '\n                    fcb       %d,%d,%d' % (h, ww, dy & 0xFF) +
              ('        %s frame %d' % (p.name, k) if k == 0 else ''))
            fi += 1
    w('')
    w('PCArt               equ       *         %d bytes' % len(blob))
    _fcb(o, blob)
    w('')
    w('* ══════════════════ THE 43 TEMPLATES ══════════════════════════════')
    w('* ADDOBJ (EDIT.s:703) places a part by copying its template into the')
    w('* database, so a template is laid out exactly like an object record.')
    w('* ⛔ The original\'s L+0/L+10/L+12/L+14 hold ATARI ADDRESSES - the')
    w('* bitmap and the RUN/INIT/HIT procs.  Here they are the part INDEX, and')
    w('* the port dispatches on it; a saved table therefore carries no address.')
    w('* ⚠ OBJLEN >= the template: the surplus is uninitialised runtime state')
    w('* the Atari copied from whatever followed in ROM.  Zeroed here.')
    w('PCTmpl              equ       *')
    for p in parts:
        w('* %2d %-13s %s' % (p.index, p.name,
                              'poly %d-gon' % p.nvertex if not p.lib else
                              '%dx%d x%d %s  TIME $%02X' %
                              (p.width * 8, p.height, p.nframes, p.anim, p.time)))
        w('                    fcb       %d,%d,%d' % (p.objid, p.fillcolor, p.nvertex))
        w('                    fcb       %s' % ','.join(str(v) for v in p.x))
        w('                    fcb       %s' % ','.join(str(v) for v in p.y))
        if p.lib:
            w('                    fcb       %d,%d,%d,%d,%d,%d'
              % (p.index, p.vert, p.px, p.height * SCALE, p.width * SCALE, p.time))
            w('                    fcb       $%02X,%d       score/sound, state bytes'
              % (p.score_snd, p.statebytes))
    w('')
    w('PCTLen              equ       *         OBJLEN, EDIT.s:1282')
    _fcb(o, bytes(p.objlen for p in parts))
    w('')
    w('* The parts bin, in the ORIGINAL\'s screen coordinates (x 160..319).')
    w('PCBox               equ       *         x, y, w, h a part')
    for i, (x, y, ww, hh) in enumerate(boxes):
        w('                    fcb       %-3d,%-3d,%-3d,%-3d   %2d %s'
          % (x, y, ww, hh, i, parts[i].name))
    w('')
    w('* ══════════════════ THE TEST TABLE ════════════════════════════════')
    w("* ⭐ Step 2's gate: `pcs 0` copies this into its database, runs the scan")
    w('* converter over it and paints the result; checkpcs.py builds the same')
    w('* four objects through pcspak.py and compares.  Defined in mkpcs.py so')
    w('* the program and the checker cannot drift.')
    tt = serialise(test_table())
    w('PCTestN             equ       %d' % len(tt))
    w('PCTest              equ       *')
    _fcb(o, tt)
    w('')
    w('* ══════════════════ PHYSICS ═══════════════════════════════════════')
    w('* ⛔ EVERY BYTE VERBATIM FROM RUN.s AND PPAK.s.  Nothing here is')
    w('* recomputed - checkpcs.py compares the 6809 against a Python model of')
    w('* the same arithmetic, and a table regenerated by one and read by the')
    w('* other is the check answering its own question.')
    w('*')
    w('* The World sliders, 8 positions each (INITWORLD, RUN.s:2169):')
    w('*   GRAVTBL  a MASK - apply -1 to BDY when (tick & mask) == 0')
    w('*   TIMETBL  the frame delay')
    w('*   KICKTBL  bumper kick, in 1/32 px/frame')
    w('*   ELASTLO/HI  eight ENTRY POINTS into the cosine tables, which is how')
    w('*               one curve gives eight restitutions')
    for name in ('GRAVTBL', 'TIMETBL', 'KICKTBL', 'ELASTLO', 'ELASTHI',
                 'SCORETBL', 'SOUNDTBL', 'BONUSTBL', 'DXCODESA', 'DXCODESB',
                 'FTTA', 'FLPVCTR', 'FXDVERT', 'FXHEIGHT', 'FXLEN',
                 'FDDVERT', 'FHEIGHT', 'DHITTBL', 'EFFECTS', 'NOTES'):
        w('')
        w('PC%-16s equ       *         %d bytes' % (name[:16], len(t[name])))
        _fcb(o, t[name])
    w('')
    # ⭐ THE ELASTICITY SLIDER AS AN INDEX, NOT AN ADDRESS.  ELASTLO/ELASTHI
    # are the ADDRESSES of cosine tables on the Atari, which say nothing on a
    # 6809 - and a position-independent NitrOS-9 module cannot carry an address
    # table anyway.  Decoded here into "which of the seven", so the port
    # multiplies by 64 and adds.
    base = 0x8200
    order = ['C05625', 'C1125', 'C225', 'C45', 'C675', 'C7875', 'C84375']
    idx = []
    for lo, hi in zip(t['ELASTLO'], t['ELASTHI']):
        k = ((lo | (hi << 8)) - base) // 64
        if not 0 <= k < len(order):
            print('FAIL  ELAST entry $%04X is not a cosine table' % (lo | (hi << 8)))
            sys.exit(1)
        idx.append(k)
    w('')
    w('* ⭐ Which cosine table each elasticity setting uses, 0..6 into the seven')
    w('* below.  ⚠ Settings 2 and 3 name the SAME table in the original and')
    w('* therefore behave identically; reproduced, not fixed.')
    w('PCELASTI            equ       *         %s' % idx)
    _fcb(o, bytes(idx))
    w('')
    w('* The seven cosine tables (RUN.s:129-190): cos[v] = round(v * 4 * cos a),')
    w('* v in 0..63.  ROTATE picks a pair - cos(SUB[s]) and cos(90-SUB[s]) - so')
    w('* these seven cover both roles, and they are the elasticity curve too.')
    w('* SUB[0..7] = 0, 5.625, 11.25, 22.5, 45, 67.5, 78.75, 84.375 degrees.')
    for name in ('C05625', 'C1125', 'C225', 'C45', 'C675', 'C7875', 'C84375'):
        w('')
        w('PC%-16s equ       *' % name)
        _fcb(o, t[name])
    w('')

    text = '\n'.join(o) + '\n'
    with open(path, 'w', encoding='utf-8') as f:
        f.write(text)
    return text, blob, frames


def preview(path):
    """pcs.png - the artwork and the screen layout, at the size the card draws
    them.

    ⭐ THIS IS THE REVIEW GATE, and it comes before any 6809 is written.  The
    repository's rule is that a pass is reviewed from a contact sheet before a
    full-motion file is worth making (`software/nitros9/video/run-desk.sh`);
    the same rule applied to a port says the ARTWORK is reviewed before the
    code that draws it exists.  It is also CLAUDE.md's other rule -- look at
    the data when the symptom would be a wrong answer of the right shape --
    and it is what caught the flipper animation being accumulated against the
    wrong row (pcsparts._flipper_frames).
    """
    from PIL import Image, ImageDraw

    pal = pcspal.palette()
    parts = P.parts()
    lib = [p for p in parts if p.lib]

    GAP, PAD, LBL = 10, 12, 13
    rows = []
    for p in lib:
        fr = [(h * SCALE, w * SCALE, double(b, h, w)[0], dy * SCALE)
              for (h, w, b, dy) in p.frames()]
        lo = min(f[3] for f in fr)
        hi = max(f[3] + f[0] for f in fr)
        rows.append((p, fr, sum(f[1] * 8 for f in fr) + GAP * (len(fr) - 1), hi - lo, lo))

    NC = 3
    COLW = max(r[2] for r in rows) + PAD * 2 + 100
    CELLH = max(r[3] for r in rows) + PAD + LBL
    NR = (len(rows) + NC - 1) // NC
    HEAD = 96

    im = Image.new('RGB', (max(COLW * NC, SCRW + 2 * PAD), HEAD + CELLH * NR), (16, 16, 22))
    d = ImageDraw.Draw(im)
    px = im.load()

    # the palette strip, 8 px a swatch
    d.text((PAD, 6), 'pcs palette - 0 is unfilled AND the transparent key', fill=(150, 160, 190))
    for i in range(256):
        x = PAD + (i % 64) * 9
        y = 20 + (i // 64) * 10
        d.rectangle([x, y, x + 7, y + 8], fill=pal[i])
    d.text((PAD, 62), 'table %d x %d world -> %d x %d   kit panel at x %d   score strip at y %d'
           % (TW, TH, TW * SCALE, TH * SCALE, KIT_X, STATUS_Y), fill=(150, 160, 190))
    d.text((PAD, 76), '%d parts, %d frames, %d bytes of doubled 1bpp art'
           % (len(parts), sum(len(p.frames()) for p in lib), len(art()[0])), fill=(150, 160, 190))

    ink = pal[pcspal.PAINT0]          # paint 1, white - the original's $FF
    for i, (p, fr, w_, h_, lo) in enumerate(rows):
        ox = (i % NC) * COLW + PAD
        oy = HEAD + (i // NC) * CELLH + LBL
        d.text((ox, oy - LBL + 1), '%d %s %dx%d x%d'
               % (p.index, p.name, p.width * 8 * SCALE, p.height * SCALE, len(fr)),
               fill=(150, 160, 190))
        x = ox + 96
        for (fh, fw, bits, dy) in fr:
            for yy in range(fh):
                for xb in range(fw):
                    b = bits[yy * fw + xb]
                    for k in range(8):
                        if (b >> (7 - k)) & 1:
                            X, Y = x + xb * 8 + k, oy + (dy - lo) + yy
                            if 0 <= X < im.width and 0 <= Y < im.height:
                                px[X, Y] = ink
            x += fw * 8 + GAP
    im.save(path)
    return im.size


def main():
    cmds = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        os.path.dirname(ROOT), 'nitros9', 'level2', 'arm6309', 'cmds')

    with open(os.path.join(HERE, 'pcs.pal'), 'wb') as f:
        f.write(pcspal.blob())
    size = preview(os.path.join(HERE, 'pcs.png'))

    out = os.path.join(cmds, 'pcsdat.asm')
    if not os.path.isdir(cmds):
        out = os.path.join(HERE, 'pcsdat.asm')
        print('⚠ %s is not a directory; writing pcsdat.asm here instead' % cmds)
    text, blob, frames = emit(out)

    print('pcs.pal      512 bytes')
    print('pcs.png      %d x %d' % size)
    print('pcsdat.asm   %s' % out)
    print('             %d lines, %d bytes of source' % (text.count('\n'), len(text)))
    print('             %d parts, %d frames, %d bytes of doubled art'
          % (len(P.parts()), len(frames), len(blob)))
    print('             world %d x %d, screen %d x %d at %dx'
          % (TW, TH, SCRW, SCRH, SCALE))


if __name__ == '__main__':
    main()
