#!/usr/bin/env python3
"""Write video3/bench/v3sprite.asm and v3sprite.json - the sprite exerciser.

video3/docs/plan.md §7.  One frame shows one sprite position, so the ROM steps
through positions and writes each to $C208/$C20A - the two words machine.c
records with EVERY frame (m->mk_camk / m->mk_herok, the mechanism `overworld`
uses for its camera).  The checker then renders each frame at the position that
frame reports, so one run covers every X phase.
"""
import json, sys

# 2 bits a pixel: bit from shape[row*2] is the low bit, shape[row*2+1] the high.
#   0 transparent, 1 sub-palette 1 (fill), 2 sub-palette 2 (outline)
ARROW = [
    "2.......", "22......", "212.....", "2112....",
    "21112...", "211112..", "2222222.", "..222...",
]
def shape_bytes():
    out = []
    for r in ARROW:
        lo = hi = 0
        for i, ch in enumerate(r):
            v = 0 if ch == "." else int(ch)
            lo |= (v & 1) << (7 - i)
            hi |= ((v >> 1) & 1) << (7 - i)
        out += [lo, hi]
    return out

# every X phase mod 8, both 4-byte phases, the left and right edges, and two
# rows that straddle the line-doubling boundary
# (x, y, vmode).  VMODE 00 and 01 are line-doubled and 10 and 11 progressive,
# so the sprite covers eight PICTURE rows either way - sixteen scanlines in the
# first pair and eight in the second, which is the thing to check.
POS = ([(x, 40, 0) for x in range(16)] + [(320 + x, 80, 0) for x in (0, 1, 2, 3)]
       + [(634, 100, 0), (638, 120, 0), (0, 0, 0), (632, 192, 0)]
       + [(100, y, 0) for y in (0, 1, 7, 8, 191, 192)]
       + [(50, 30, 1), (600, 236, 1)]          # 640x240, doubled
       + [(7, 300, 2), (300, 396, 2)]          # 640x400, progressive
       + [(9, 470, 3), (632, 476, 3)])         # 640x480, progressive

json.dump({"shape": shape_bytes(), "pos": POS, "arrow": ARROW}, open(sys.argv[2], "w"))

sb = shape_bytes()
steps = "".join(f"""        ldd     #$FFFF
        std     MKX
        lda     #${0x80 | v:02X}          display on, MODE 00 bitmap, VMODE {v:02b}
        sta     <VCTRL
        lda     #${x & 0xFF:02X}
        sta     <SPRX
        lda     #${y & 0xFF:02X}
        sta     <SPRY
        lda     #${0x80 | ((x >> 8) & 3) | (((y >> 8) & 1) << 2):02X}
        sta     <SPRH
        lbsr    wait3           let the family latch take the VMODE
        ldd     #{x}
        std     MKX
        ldd     #{y | (v << 12)}
        std     MKY             the high nibble carries the VMODE
        lbsr    wait3
""" for x, y, v in POS)

src = f"""*******************************************************************************
* v3sprite.asm -- video3's 8x8 sprite on the host emulator.  GENERATED by
* bench/mkv3sprite.py; edit the generator.
*
*   sh video3/bench/run-v3sprite.sh
*
* plan 7.  The sprite's two bits per pixel are the LUT's ATTR in bitmap mode:
* 0 is transparent, 1 and 2 select sub-palettes 1 and 2.  The ROM steps through
* every X phase and writes the position to $C208/$C20A, which machine.c records
* with every frame - so one run covers all of them.
*******************************************************************************

VCTRL   EQU     $FF60
VSCROLL EQU     $FF61
WPTR0   EQU     $FF68
WPTR1   EQU     $FF69
WPTR2   EQU     $FF6A
WADV    EQU     $FF6B
VDATA   EQU     $FF6C
VSTAT   EQU     $FF6D
VCTRL2  EQU     $FF60
PIDXL   EQU     $FF6E
PIDXH   EQU     $FF6F
PDATL   EQU     $FF70
PDATH   EQU     $FF71
SPRX    EQU     $FF7A
SPRY    EQU     $FF7B
SPRH    EQU     $FF7C
SPRIDX  EQU     $FF7D
SPRDAT  EQU     $FF7E
SIMPORT EQU     $FF2F

MKX     EQU     $C208           machine.c records these with every frame
MKY     EQU     $C20A
row     EQU     $C100
seed    EQU     $C102

        ORG     $8000
        FCC     "6309"
        JMP     start

        SETDP   $FF
start   orcc    #$50
        lds     #$E000
        lda     #$FF
        tfr     a,dp
        clr     <VCTRL
        clr     <WADV
        clr     <VSCROLL
        clr     <VSCROLL+1
        clr     <SPRH           the sprite is off while the screen is built
        ldd     #$FFFF          ... and the frames recorded meanwhile carry a
        std     MKX             position no test uses, so the checker skips them
        std     MKY

* --- sub-palette 0: entry i = i * $0101.  Sub-palettes 1 and 2 are the two
*     cursor colours, ALL 256 entries each (plan 7): $F800 and $001F.
        clr     <PIDXH
        clr     <PIDXL
        clrb
p0      stb     <PDATL
        stb     <PDATH
        incb
        bne     p0
        lda     #1
        sta     <PIDXH
        clr     <PIDXL
        clrb
p1      clr     <PDATL
        lda     #$F8
        sta     <PDATH
        incb
        bne     p1
        lda     #2
        sta     <PIDXH
        clr     <PIDXL
        clrb
p2      lda     #$1F
        sta     <PDATL
        clr     <PDATH
        incb
        bne     p2

* --- the background: VRAM[r][c] = (r * 7 + c * 3) & $FF, as v3copy uses
        clr     row
        clr     row+1
fr1     ldd     row
        lslb
        rola
        lslb
        rola
        clr     <WPTR0
        stb     <WPTR1
        sta     <WPTR2
        ldb     row+1
        lda     #7
        mul
        stb     seed
        ldy     #640
fc1     lda     seed
        sta     <VDATA
        adda    #3
        sta     seed
        leay    -1,y
        bne     fc1
        ldd     row
        addd    #1
        std     row
        cmpd    #200
        blo     fr1

* --- the shape: 16 bytes through SPRIDX/SPRDAT, which auto-increments
        clr     <SPRIDX
        ldx     #shape
        ldb     #16
sh1     lda     ,x+
        sta     <SPRDAT
        decb
        bne     sh1

        lda     #$A0
        sta     SIMPORT

{steps}        lda     #$AF
        sta     SIMPORT
done    bra     done

* wait3 - three whole frames at this position, so the recording has one
wait3   pshs    a,b
        ldb     #3
w1      lda     <VSTAT          out of the blank first
        bita    #$40
        bne     w1
w2      lda     <VSTAT          then into the next one
        bita    #$40
        beq     w2
        decb
        bne     w1
        puls    a,b,pc

shape   FCB     {",".join(f"${b:02X}" for b in sb)}
        END
"""
open(sys.argv[1], "w").write(src)
print(f"wrote {sys.argv[1]} and {sys.argv[2]} ({len(POS)} positions)")
