#!/usr/bin/env python3
"""Write video3/bench/v3tile.asm and v3tile.json - the tile-mode exerciser.

video3/docs/plan.md §2.4 (graphics.md §6.4.2's Variant A) and §8.1.  What only
this can catch: the ONE-byte map, 8bpp tiles with no per-cell colour limit,
both scroll axes one pixel at a time including their ring wraps, the six-bit cell
row - and ⭐ that ATTR is ZERO in tile mode, which the palette is loaded to
prove.

⚠ THE TILE BANK IS A FORMULA IN BOTH PLACES.  16 KB of tiles plus 8 KB of map
does not fit the two ROM pages, so the map is a table the JSON also carries and
the bank is computed from TILE_A/TILE_B at each end.  That is a duplication;
it is small, it is here, and the map - the part that actually addresses - is
declared rather than computed.
"""
import json, sys

TILEBASE, MAPBASE = 1, 2            # VRAM 16,384 and 131,072
CELL_ROWS, CELL_COLS = 64, 128      # plan §2.5: six-bit cell row, 128 columns
TILE_A, TILE_B = 7, 1               # tile t, pixel p -> (t * TILE_A + p * TILE_B) & 255
MARK = 0x07E0                       # bright green: any sub-palette but 0

def code(r, c):
    return (r * 13 + c * 5) & 0xFF

# (hscroll, vscroll): every sub-cell phase in both axes, both ring wraps, and a
# vscroll that puts the six-bit cell row at 63 and rolls it to 0
# (hscroll, vscroll, vmode).  The progressive families show twice as many
# picture rows, so a vertical ring wrap is a different test there.
POS = [(0, 0, 0), (1, 0, 0), (3, 0, 0), (7, 0, 0), (8, 0, 0), (9, 0, 0), (17, 0, 0),
       (0, 1, 0), (0, 3, 0), (0, 7, 0), (0, 8, 0), (0, 9, 0),
       (5, 5, 0), (100, 50, 0), (640, 0, 0), (1020, 0, 0), (0, 504, 0), (1021, 509, 0),
       (3, 7, 1), (1022, 500, 1),          # 640x240, doubled
       (5, 9, 2), (1019, 300, 2),          # 640x400, progressive
       (11, 13, 3), (1023, 440, 3)]        # 640x480, progressive - 480 rows of ring

mapdata = bytearray(code(r, c) for r in range(CELL_ROWS) for c in range(CELL_COLS))
json.dump({"tilebase": TILEBASE, "mapbase": MAPBASE, "cell_rows": CELL_ROWS,
           "cell_cols": CELL_COLS, "tile_a": TILE_A, "tile_b": TILE_B,
           "mark": MARK, "pos": POS, "map": list(mapdata)}, open(sys.argv[2], "w"))

def tbl(name, by, per=16):
    out = [name]
    for i in range(0, len(by), per):
        out.append("        FCB     " + ",".join(f"${b:02X}" for b in by[i:i + per]))
    return "\n".join(out) + "\n"

steps = "".join(f"""        ldd     #$FFFF
        std     MKH
        std     MKV
        lda     #${0x88 | vm:02X}          display on, MODE 10 tile, VMODE {vm:02b}
        sta     <VCTRL
        lda     #${h & 0xFF:02X}
        sta     <HSCROLL
        lda     #${(h >> 8) & 3:02X}
        sta     <HSCROLH
        lda     #${vs & 0xFF:02X}
        sta     <VSCROLL
        lda     #${(vs >> 8) & 1:02X}
        sta     <VSCROLH
        lbsr    wait3           let the frame-start latch take it
        ldd     #{h}
        std     MKH
        ldd     #{vs | (vm << 12)}
        std     MKV             the high nibble carries the VMODE
        lbsr    wait3
""" for h, vs, vm in POS)

src = f"""*******************************************************************************
* v3tile.asm -- video3's tile mode on the host emulator.  GENERATED by
* bench/mkv3tile.py; edit the generator.
*
*   sh video3/bench/run-v3tile.sh
*
* plan 2.4 and 8.1.  A ONE-byte map, 8bpp tiles with no per-cell colour limit,
* HSCROLL and VSCROLL one pixel at a time with their ring wraps, and a six-bit cell
* row.  The palette is loaded so that ANY sub-palette but 0 is bright green -
* so if the attribute path leaks into tile mode, the screen says so.
*
* Each scroll is set, allowed to settle, and only THEN marked at $C208/$C20A,
* so no frame is judged against a scroll the frame-start latch had not taken.
*******************************************************************************

VCTRL   EQU     $FF60
VSCROLL EQU     $FF61
VSCROLH EQU     $FF62
HSCROLL EQU     $FF63
HSCROLH EQU     $FF64
WPTR0   EQU     $FF68
WPTR1   EQU     $FF69
WPTR2   EQU     $FF6A
WADV    EQU     $FF6B
VDATA   EQU     $FF6C
VSTAT   EQU     $FF6D
PIDXL   EQU     $FF6E
PIDXH   EQU     $FF6F
PDATL   EQU     $FF70
PDATH   EQU     $FF71
TILEBAS EQU     $FF78
MAPBAS  EQU     $FF79
SIMPORT EQU     $FF2F

MKH     EQU     $C208
MKV     EQU     $C20A
tno     EQU     $C100
row     EQU     $C102

        ORG     $8000
        FCC     "6309"
        JMP     start

        SETDP   $FF
start   orcc    #$50
        lds     #$E000
        lda     #$FF
        tfr     a,dp
        clr     <VCTRL          display off, bitmap, WMODE 00
        clr     <WADV
        ldd     #$FFFF
        std     MKH
        std     MKV
        lda     #{TILEBASE}
        sta     <TILEBAS
        lda     #{MAPBASE}
        sta     <MAPBAS

* --- ⭐ EVERY sub-palette is the marker, then sub-palette 0 is the identity.
*     Tile mode drives ATTR to zero (plan 3), so nothing green may appear.
        clr     <PIDXL
        clr     <PIDXH
        ldx     #0
pm1     lda     #${MARK & 0xFF:02X}
        sta     <PDATL
        lda     #${MARK >> 8:02X}
        sta     <PDATH
        leax    1,x
        cmpx    #0
        bne     pm1
        clr     <PIDXL
        clr     <PIDXH
        clrb
p01     stb     <PDATL
        stb     <PDATH
        incb
        bne     p01

* --- the bank: 256 tiles of 64 bytes, tile t pixel p = (t*{TILE_A} + p*{TILE_B}) & $FF
        clr     tno
tl1     lda     tno
        clrb
        lsra
        rorb
        lsra
        rorb                    D = t * 64
        addd    #{TILEBASE * 16384}
        stb     <WPTR0
        sta     <WPTR1
        clr     <WPTR2
        lda     tno
        ldb     #{TILE_A}
        mul                     B = t * {TILE_A}, low byte
        stb     row             the running pixel value
        ldb     #64
tl2     lda     row
        sta     <VDATA
        adda    #{TILE_B}
        sta     row
        decb
        bne     tl2
        inc     tno
        bne     tl1

* --- the map: one byte a cell, one VRAM row a cell row (plan 2.5)
        ldx     #maptab
        clra
        ldb     #{CELL_ROWS}
mr1     pshs    a,b
        lda     #{MAPBASE}
        sta     <WPTR2
        lda     ,s
        lsla
        lsla
        sta     <WPTR1
        clr     <WPTR0
        ldy     #{CELL_COLS}
mr2     lda     ,x+
        sta     <VDATA
        leay    -1,y
        bne     mr2
        puls    a,b
        inca
        decb
        bne     mr1

* --- tile mode; each step sets its own VMODE
        lda     #$A0
        sta     SIMPORT

{steps}        lda     #$AF
        sta     SIMPORT
done    bra     done

wait3   pshs    a,b
        ldb     #3
w1      lda     <VSTAT
        bita    #$40
        bne     w1
w2      lda     <VSTAT
        bita    #$40
        beq     w2
        decb
        bne     w1
        puls    a,b,pc

{tbl("maptab", mapdata)}
        END
"""
open(sys.argv[1], "w").write(src)
print(f"wrote {sys.argv[1]} and {sys.argv[2]} ({len(POS)} scroll positions)")
